Repository antvis/G2Plot, pull requests merged in 2019-11, with the labels that each got.

#166 Add examples
  examples/basic/API.en.md
  examples/basic/API.zh.md
  examples/basic/demo/area.js
  examples/basic/demo/meta.json
  examples/basic/design.en.md
  examples/basic/design.zh.md
  examples/basic/index.en.md
  examples/basic/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  tsconfig.json
Labels: PR: reviewed-changes-requested

#164 fix(theme): fix API export
  src/index.ts
Labels: PR: unreviewed

#163 label配置项透传，支持autoRotate配置
  __tests__/unit/pie-spec.js
  src/components/label/parser.ts
  src/plots/pie/layer.ts
Labels: PR: unreviewed

#169 fix(description): 图表描述莫名换行bug
  __tests__/bugs/issue-112-spec.js
  src/components/description.ts
Labels: PR: reviewed-changes-requested, PR: unreviewed, bug

#170 雷达图radiusAxis默认以0值为起点
  src/plots/radar/layer.ts
Labels: PR: reviewed-changes-requested

#172 fix: export path error
  src/base/layer.ts
  src/base/plot.ts
  src/index.ts
  src/plots/area/layer.ts
Labels: PR: unreviewed, bug

#171 docs: support fetch json and categroy in examples
  docs/manual/introduction.zh.md
  examples/basic/demo/area.js
  examples/data/fireworks-sales.json
  examples/data/income.json
  examples/data/oil.json
  examples/data/sales.json
  examples/data/subsales.json
  examples/line/basic/API.en.md
  examples/line/basic/API.zh.md
  examples/line/basic/demo/area.js
  examples/line/basic/demo/meta.json
  examples/line/basic/design.en.md
  examples/line/basic/design.zh.md
  examples/line/basic/index.en.md
  examples/line/basic/index.zh.md
  examples/pie/basic/API.en.md
  examples/pie/basic/API.zh.md
  examples/pie/basic/demo/area.js
  examples/pie/basic/demo/meta.json
  examples/pie/basic/design.en.md
  examples/pie/basic/design.zh.md
  examples/pie/basic/index.en.md
  examples/pie/basic/index.zh.md
  gatsby-config.js
  package.json
Labels: PR: unreviewed, documentation

#174 docs: Upgrade theme config
  docs/manual/introduction.zh.md
  examples/line/basic/index.en.md
  examples/line/basic/index.zh.md
  gatsby-config.js
  package.json
Labels: PR: reviewed-approved, documentation

#175 feat: 为所有图表增加getDefaultProps静态方法
  src/base/view-layer.ts
  src/plots/area/index.ts
  src/plots/area/layer.ts
  src/plots/bar/index.ts
  src/plots/bar/layer.ts
  src/plots/column/index.ts
  src/plots/column/layer.ts
  src/plots/density/index.ts
  src/plots/group-bar/index.ts
  src/plots/group-column/index.ts
  src/plots/histogram/index.ts
  src/plots/line/index.ts
  src/plots/line/layer.ts
  src/plots/percentage-stack-area/index.ts
  src/plots/percentage-stack-bar/index.ts
  src/plots/percentage-stack-column/index.ts
  src/plots/pie/index.ts
  src/plots/pie/layer.ts
  src/plots/radar/index.ts
  src/plots/radar/layer.ts
  src/plots/ring/index.ts
  src/plots/ring/layer.ts
  src/plots/stack-area/index.ts
  src/plots/stack-area/layer.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-bar/layer.ts
  src/plots/stack-column/layer.ts
  src/tiny-plots/progress/index.ts
  src/tiny-plots/ring-progress/index.ts
  src/tiny-plots/tiny-area/index.ts
  src/tiny-plots/tiny-column/index.ts
  src/tiny-plots/tiny-layer.ts
  src/tiny-plots/tiny-line/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#176 feat: 允许自定义Tooltip的样式等选项
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, enhancement

#177 docs: fix example data url
  examples/line/basic/demo/area.js
  examples/pie/basic/demo/area.js
Labels: PR: reviewed-changes-requested, documentation

#181 feat: 增加图片比较功能
  demos/assets/common.css
  package.json
  scripts/compare.js
Labels: PR: reviewed-changes-requested, enhancement

#182 fix update config error
  src/base/plot.ts
  src/geoms/line/main.ts
Labels: PR: reviewed-changes-requested

#183 getDefaultProps => getDefaultOptions
  src/plots/area/index.ts
  src/plots/bar/index.ts
  src/plots/column/index.ts
  src/plots/density/index.ts
  src/plots/gauge/index.ts
  src/plots/group-bar/index.ts
  src/plots/group-column/index.ts
  src/plots/histogram/index.ts
  src/plots/line/index.ts
  src/plots/liquid/index.ts
  src/plots/percentage-stack-area/index.ts
  src/plots/percentage-stack-bar/index.ts
  src/plots/percentage-stack-column/index.ts
  src/plots/pie/index.ts
  src/plots/radar/index.ts
  src/plots/ring/index.ts
  src/plots/stack-area/index.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-column/index.ts
  src/tiny-plots/progress/index.ts
  src/tiny-plots/ring-progress/index.ts
  src/tiny-plots/tiny-area/index.ts
  src/tiny-plots/tiny-column/index.ts
  src/tiny-plots/tiny-line/index.ts
Labels: PR: reviewed-changes-requested

#179 添加气泡图
  demos/bubble-basic.html
  src/geoms/point/circle.ts
  src/geoms/point/index.ts
  src/index.ts
  src/plots/bubble/component/label/bubble-label.ts
  src/plots/bubble/event.ts
  src/plots/bubble/index.ts
  src/plots/bubble/layer.ts
Labels: PR: reviewed-approved, WIP

#186 fix canvas properties setting & events Closes#185
  src/base/controller/canvas.ts
  src/base/layer.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/util/event.ts
Labels: PR: unreviewed

#190 fix: 修复Layer/Plot相关的TS定义
  __tests__/unit/area-spec.js
  src/base/controller/theme.ts
  src/base/layer.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/index.ts
  src/interface/config.ts
  src/plots/area/index.ts
  src/plots/area/layer.ts
  src/plots/bar/index.ts
  src/plots/bar/layer.ts
  src/plots/bubble/index.ts
  src/plots/bubble/layer.ts
  src/plots/column/index.ts
  src/plots/column/layer.ts
  src/plots/density/index.ts
  src/plots/density/layer.ts
  src/plots/gauge/index.ts
  src/plots/gauge/layer.ts
  src/plots/group-bar/index.ts
  src/plots/group-bar/layer.ts
  src/plots/group-column/index.ts
  src/plots/group-column/layer.ts
  src/plots/histogram/index.ts
  src/plots/histogram/layer.ts
  src/plots/line/index.ts
  src/plots/line/layer.ts
  src/plots/liquid/index.ts
  src/plots/liquid/layer.ts
  src/plots/percentage-stack-area/index.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/index.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/index.ts
  src/plots/percentage-stack-column/layer.ts
  src/plots/pie/index.ts
  src/plots/pie/layer.ts
  src/plots/radar/index.ts
  src/plots/radar/layer.ts
  src/plots/ring/index.ts
  src/plots/ring/layer.ts
  src/plots/stack-area/index.ts
  src/plots/stack-area/layer.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-bar/layer.ts
  src/plots/stack-column/index.ts
  src/plots/stack-column/layer.ts
  src/tiny-plots/progress/index.ts
  src/tiny-plots/progress/layer.ts
  src/tiny-plots/ring-progress/index.ts
  src/tiny-plots/ring-progress/layer.ts
  src/tiny-plots/tiny-area/index.ts
  src/tiny-plots/tiny-area/layer.ts
  src/tiny-plots/tiny-column/index.ts
  src/tiny-plots/tiny-column/layer.ts
  src/tiny-plots/tiny-layer.ts
  src/tiny-plots/tiny-line/index.ts
  src/tiny-plots/tiny-line/layer.ts
  src/tiny-plots/tiny-plot.ts
Labels: PR: unreviewed, bug

#193 fix update plot size error
  src/base/plot.ts
  src/base/view-layer.ts
  src/plots/stack-area/layer.ts
Labels: PR: unreviewed

#196 feat(pie): di饼图开放innerRadius配置
  src/plots/pie/layer.ts
Labels: PR: unreviewed, enhancement

#198 Pie 默认配置项
  __tests__/unit/pie-spec.js
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested

#201 add home page
  package.json
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#204 feat(default-cfg): update defaultCfg of area & stack-area & line
  __tests__/unit/area-spec.js
  __tests__/unit/groupColumn-spec.js
  __tests__/unit/line-spec.js
  src/base/global.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/plots/area/layer.ts
  src/plots/line/index.ts
  src/plots/line/layer.ts
  src/plots/liquid/layer.ts
Labels: PR: reviewed-approved, enhancement

#203 Title desc rerender
  __tests__/unit/title-desc-spec.ts
  demos/area-basic.ts
  demos/tsconfig.json
  package.json
  scripts/demo-route.js
  src/base/controller/padding.ts
  src/base/view-layer.ts
  tsconfig.json
Labels: PR: unreviewed

#208 chore: 使用jest-electron替代torch & 使用TS编写单侧
  .github/workflows/ci.yml
  __tests__/bugs/issue-112-spec.ts
  __tests__/data/baby-names.ts
  __tests__/data/basement.ts
  __tests__/data/fireworks-sales.ts
  __tests__/data/global-oil-new.ts
  __tests__/data/income.ts
  __tests__/data/nintendo.ts
  __tests__/data/partySupport.ts
  __tests__/data/radar.js-
  __tests__/data/radar.ts
  __tests__/unit/area-spec.ts
  __tests__/unit/areaLabel-spec.ts
  __tests__/unit/bar-spec.ts
  __tests__/unit/column-spec.ts
  __tests__/unit/connectedArea-spec.ts
  __tests__/unit/density-spec.ts
  __tests__/unit/gauge-spec.ts
  __tests__/unit/genTheme.ts
  __tests__/unit/groupBar-spec.ts
  __tests__/unit/groupColumn-spec.ts
  __tests__/unit/histogram-spec.ts
  __tests__/unit/index-spec.js
  __tests__/unit/index-spec.ts
  __tests__/unit/line-spec.ts
  __tests__/unit/lineLabel-spec.ts
  __tests__/unit/liquid-spec.ts
  __tests__/unit/miniLineShape-spec.ts
  __tests__/unit/pie-spec.ts
  __tests__/unit/radar-spec.ts
  __tests__/unit/responsive-bar-spec.ts
  __tests__/unit/responsiveColumn-spec.ts
  __tests__/unit/responsiveColumnLabel-spec.ts
  __tests__/unit/responsiveLine-spec.ts
  __tests__/unit/responsiveRing-spec.ts
  __tests__/unit/ring-spec.ts
  __tests__/unit/stackArea-spec.ts
  __tests__/unit/stackBar-spec.ts
  __tests__/unit/stackColumn-spec.ts
  __tests__/unit/state-spec.ts
  __tests__/unit/stateManager-spec.ts
  __tests__/unit/theme/index-spec.js
  __tests__/unit/theme/index-spec.ts
  __tests__/unit/tinyPlot/progress-spec.ts
  __tests__/unit/tinyPlot/ringProgress-spec.ts
  __tests__/unit/tinyPlot/tinyArea-spec.ts
  __tests__/unit/tinyPlot/tinyColumn-spec.ts
  __tests__/unit/tinyPlot/tinyLine-spec.ts
  __tests__/unit/title-desc-spec.ts
  global.d.ts
  package.json
  src/base/view-layer.ts
Labels: PR: reviewed-approved, chore

#209 fix: title/desc 可能出现死循环
  src/components/description.ts
Labels: PR: reviewed-changes-requested, bug

#210 fix lint error
  src/components/description.ts
Labels: PR: reviewed-changes-requested

#202 feat: 更新柱条系列图形默认配置项
  src/base/view-layer.ts
  src/plots/bar/layer.ts
  src/plots/column/component/label/column-label.ts
  src/plots/column/layer.ts
  src/plots/group-bar/layer.ts
  src/plots/group-column/layer.ts
  src/plots/stack-bar/layer.ts
  src/plots/stack-column/layer.ts
Labels: PR: unreviewed, enhancement

#212 docs: update typo for README
  README.md
  __tests__/unit/groupColumn-spec.ts
  src/base/layer.ts
  src/geoms/area/main.ts
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/radar/layer.ts
  src/theme/default.ts
Labels: PR: unreviewed, documentation

#215 fix: updateConfig还是先按原来init流程
  __tests__/unit/title-desc-spec.ts
  src/base/controller/canvas.ts
  src/base/controller/padding.ts
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, bug

#222 fix: 修改plot为非泛型
  src/plots/area/index.ts
  src/plots/bar/index.ts
  src/plots/bubble/index.ts
  src/plots/column/index.ts
  src/plots/column/layer.ts
  src/plots/density/index.ts
  src/plots/gauge/index.ts
  src/plots/group-bar/index.ts
  src/plots/group-column/index.ts
  src/plots/histogram/index.ts
  src/plots/line/index.ts
  src/plots/liquid/index.ts
  src/plots/pie/index.ts
  src/plots/radar/index.ts
  src/plots/ring/index.ts
  src/plots/stack-area/index.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-column/index.ts
  src/theme/default.ts
  src/tiny-plots/progress/index.ts
  src/tiny-plots/ring-progress/index.ts
  src/tiny-plots/tiny-area/index.ts
  src/tiny-plots/tiny-column/index.ts
  src/tiny-plots/tiny-line/index.ts
Labels: PR: reviewed-changes-requested, bug

#223 fix: updateConfig size 更新修复
  src/base/layer.ts
  src/base/view-layer.ts
Labels: PR: unreviewed, bug

#218 修复axis，以及title/ desc的bug
  __tests__/unit/utils-spec.ts
  src/base/controller/padding.ts
  src/base/controller/theme.ts
  src/base/view-layer.ts
  src/components/axis/parser.ts
  src/components/description.ts
  src/components/factory.ts
  src/interface/config.ts
  src/plots/area/layer.ts
  src/plots/bar/layer.ts
  src/theme/default.ts
  src/theme/utils.ts
  src/util/common.ts
Labels: PR: unreviewed

#220 fix: title and description wrap bug
  __tests__/unit/title-desc-spec.ts
  src/components/description.ts
Labels: PR: unreviewed, bug

#226 fix: 修复标题和description换行的bug
  __tests__/unit/title-desc-spec.ts
  src/components/description.ts
Labels: PR: reviewed-changes-requested, bug

#229 饼图&环图 demo和默认配置项修改
  examples/pie/basic/demo/basic.js
  examples/pie/basic/demo/basic2.js
  examples/pie/basic/demo/inner-label.js
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/outer-label.js
  examples/pie/basic/demo/spider-label.js
  examples/pie/ring/demo/meta.json
  examples/pie/ring/demo/ring-basic.js
  examples/pie/ring/demo/ring-central-text.js
  examples/pie/ring/demo/ring-radius.js
  src/plots/pie/component/label/spider-label.ts
  src/plots/ring/layer.ts
Labels: PR: unreviewed

#228 Fix demo line
  examples/area/stack/demo/area-large-data.js
  examples/area/stack/demo/meta.json
  examples/data/emissions.json
  examples/line/multiple/demo/line-label.js
  examples/line/multiple/demo/line-large-data.js
  examples/line/multiple/demo/meta.json
Labels: PR: unreviewed

#233 markdown format
  CONTRIBUTING.md
  CONTRIBUTING.zh-CN.md
  docs/manual/advanced/responsive.zh.md
  docs/manual/advanced/state-and-charts-connetion.zh.md
  docs/manual/general-config.zh.md
  docs/manual/getting-started.zh.md
  docs/manual/introduction.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/group-bar.zh.md
  docs/manual/plots/group-column.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.zh.md
  docs/manual/plots/stack-bar.zh.md
  docs/manual/plots/stack-column.zh.md
  docs/manual/plots/tinyPlot-area.zh.md
  docs/manual/plots/tinyPlot-column.zh.md
  docs/manual/plots/tinyPlot-line.zh.md
  docs/manual/plots/tinyPlot-progress.zh.md
  docs/manual/plots/tinyPlot-ring-progress.zh.md
Labels: PR: unreviewed

#234 docs: 文档修复
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.zh.md
  docs/manual/plots/tinyPlot-area.zh.md
  docs/manual/plots/tinyPlot-column.zh.md
  docs/manual/plots/tinyPlot-line.zh.md
Labels: PR: unreviewed, documentation

#235 fix: bar column 使用主题蓝色
  __tests__/unit/title-desc-spec.ts
  src/geoms/factory.ts
  src/geoms/interval/main.ts
Labels: PR: reviewed-approved, bug

#236 docs: line & area
  docs/manual/getting-started.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/group-bar.zh.md
  docs/manual/plots/group-column.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.zh.md
  docs/manual/plots/stack-bar.zh.md
  docs/manual/plots/stack-column.zh.md
  docs/manual/plots/tinyPlot-progress.zh.md
  docs/manual/plots/tinyPlot-ring-progress.zh.md
Labels: PR: reviewed-changes-requested, documentation

#239 fix: 柱形图&条形图系列DEMO优化
  examples/bar/basic/demo/basic.js
  examples/bar/basic/demo/label-adjustColor.js
  examples/bar/basic/demo/label-position.js
  examples/bar/group/demo/basic.js
  examples/bar/stack/demo/adjust-label-display.js
  examples/bar/stack/demo/basic.js
  examples/column/basic/demo/column-colorMapping.js
  examples/column/basic/demo/column-label-color-adjust.js
  examples/column/basic/demo/column-scrollbar.js
  examples/column/basic/demo/column-slider.js
  examples/column/basic/demo/meta.json
  examples/column/group/demo/group-column-slider.js
  examples/column/group/demo/group-column.js
  examples/column/stack/demo/label-auto-hide.js
  src/components/axis/parser.ts
  src/interaction/scrollbar.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/group-bar/layer.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/layer.ts
Labels: PR: reviewed-changes-requested, bug

#242 docs: fix wrong link in document
  docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved, documentation

#240 fix: 在g2plot里设置widthRatio
  src/geoms/base.ts
  src/interface/config.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: PR: unreviewed, bug

#238 feat(mini): add mini chart demo table
  examples/mini/multiple/API.en.md
  examples/mini/multiple/API.zh.md
  examples/mini/multiple/demo/meta.json
  examples/mini/multiple/demo/mini-multiple1.js
  examples/mini/multiple/demo/mini-multiple2.js
  examples/mini/multiple/design.en.md
  examples/mini/multiple/design.zh.md
  examples/mini/multiple/index.en.md
  examples/mini/multiple/index.zh.md
  gatsby-config.js
  site/pages/index.zh.tsx
  src/geoms/area/main.ts
  src/geoms/area/mini.ts
  src/tiny-plots/progress/layer.ts
  src/tiny-plots/ring-progress/layer.ts
Labels: PR: unreviewed, enhancement

#243 Fix line point animation
  src/plots/area/layer.ts
  src/plots/line/layer.ts
  src/plots/radar/layer.ts
Labels: PR: unreviewed

#246 add advanced demos
  examples/advanced/connection/API.en.md
  examples/advanced/connection/API.zh.md
  examples/advanced/connection/demo/charts-connection.js
  examples/advanced/connection/demo/meta.json
  examples/advanced/connection/design.en.md
  examples/advanced/connection/design.zh.md
  examples/advanced/connection/index.en.md
  examples/advanced/connection/index.zh.md
  examples/advanced/responsive/API.en.md
  examples/advanced/responsive/API.zh.md
  examples/advanced/responsive/demo/meta.json
  examples/advanced/responsive/demo/responsive-axis.js
  examples/advanced/responsive/demo/responsive-label.js
  examples/advanced/responsive/design.en.md
  examples/advanced/responsive/design.zh.md
  examples/advanced/responsive/index.en.md
  examples/advanced/responsive/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  src/base/controller/state.ts
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested

#247 bug fix
  examples/general/padding/demo/set-padding.js
  examples/general/title-description/index.zh.md
  examples/mini/multiple/demo/mini-multiple1.js
  examples/mini/multiple/demo/mini-multiple2.js
  package.json
  src/base/controller/canvas.ts
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/description.ts
  src/plots/pie/component/label/spider-label.ts
  src/theme/default.ts
Labels: PR: unreviewed

#248 fix docs
  docs/manual/advanced/responsive.zh.md
  docs/manual/general-config.zh.md
  docs/manual/getting-started.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/group-bar.zh.md
  docs/manual/plots/group-column.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.zh.md
  docs/manual/plots/stack-bar.zh.md
  docs/manual/plots/stack-column.zh.md
Labels: PR: reviewed-changes-requested

#250 feat(ring-center-text): 环图中心文本默认显示总计 & 数值大小为32px
  src/plots/ring/component/annotation/central-text-template.ts
  src/plots/ring/layer.ts
Labels: PR: reviewed-approved, enhancement

#251 feat(radar-style): 调整radar样式
  src/plots/radar/layer.ts
Labels: PR: reviewed-changes-requested, enhancement

#252 line、area 诸多问题修复
  .torch.compile.opts.js
  examples/line/multiple/demo/line-label.js
  examples/line/multiple/demo/line-large-data.js
  examples/line/multiple/demo/line-multiple.js
  src/base/controller/canvas.ts
  src/plots/area/layer.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-approved

#255 fix: 柱条demo优化
  examples/bar/group/demo/basic.js
  examples/column/basic/demo/column-label-color-adjust.js
  examples/column/basic/demo/column-label-position.js
  examples/column/basic/demo/column-label.js
  examples/column/basic/demo/column-scrollbar.js
  examples/column/basic/demo/column.js
  src/base/view-layer.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/theme/default.ts
Labels: PR: reviewed-changes-requested, bug

#256 fix: axis中配置的scale type优先于meta中的配置
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, bug

#257 Fix pie label bug
  src/components/label/parser.ts
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested

#259 水波图样式更新
  examples/liquid/basic/demo/basic.js
  src/plots/liquid/geometry/shape/liquid.ts
  src/plots/liquid/layer.ts
  src/plots/liquid/theme.ts
Labels: PR: unreviewed

#260 fix: 修复column的数据标签默认的offset
  examples/column/basic/demo/column-scrollbar.js
  src/plots/column/layer.ts
Labels: PR: unreviewed, bug

#261 fix: 修复axis grid的callback配置方式
  src/components/axis/parser.ts
  src/interface/config.ts
Labels: PR: reviewed-changes-requested, bug

#264 sync to tnpm when publishing a new version
  package.json
Labels: PR: reviewed-approved

#265 Fix line area x date
  examples/area/basic/demo/slider.js
  examples/line/basic/demo/line-point-style.js
  examples/line/basic/demo/line-slider.js
  examples/line/basic/demo/line.js
  src/plots/stack-column/layer.ts
  src/theme/default.ts
Labels: PR: reviewed-approved

#266 fix: 默认主题中axis label调整 & tooltip 样式 & column widthRation调整
  src/geoms/base.ts
  src/plots/bar/layer.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: PR: reviewed-changes-requested, bug

#267 👹👺👹👺👹👺
  src/components/axis/parser.ts
  src/components/connected-area.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/percentage-stack-column/layer.ts
  src/plots/ring/component/annotation/central-text-template.ts
  src/plots/ring/layer.ts
  src/plots/stack-area/layer.ts
  src/plots/stack-bar/layer.ts
  src/plots/stack-column/layer.ts
Labels: PR: reviewed-approved

#268 add design principle
  examples/area/basic/design.zh.md
  examples/area/percentageArea/design.zh.md
  examples/area/stack/design.zh.md
  examples/bar/basic/design.zh.md
  examples/bar/group/design.zh.md
  examples/bar/percentageStack/design.zh.md
  examples/bar/stack/design.zh.md
  examples/column/basic/design.zh.md
  examples/column/group/design.zh.md
  examples/column/percentageStack/design.zh.md
  examples/column/stack/design.zh.md
  examples/general/axis/design.zh.md
  examples/line/basic/design.zh.md
  examples/line/multiple/design.zh.md
  package.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#269 remove unnecessary column responsive rule
  src/plots/column/apply-responsive/geometry.ts
  src/plots/column/apply-responsive/index.ts
  src/plots/column/apply-responsive/theme.ts
Labels: PR: reviewed-changes-requested

#270 the stranger things
  src/plots/ring/layer.ts
  src/theme/default.ts
Labels: PR: unreviewed

#272 Revert line area slider demo
  examples/area/basic/demo/slider.js
  examples/line/basic/demo/line-slider.js
Labels: PR: reviewed-changes-requested

#271 the stranger things s2
  examples/gauge/basic/demo/basic.js
  examples/gauge/basic/demo/half.js
  examples/gauge/basic/demo/style.js
  examples/liquid/basic/demo/basic.js
  examples/liquid/basic/demo/percent.js
  examples/pie/basic/demo/basic.js
  examples/pie/ring/demo/meta.json
  examples/pie/ring/demo/ring-basic.js
  examples/pie/ring/demo/ring-statistic.js
  package.json
  src/plots/gauge/layer.ts
  src/plots/liquid/layer.ts
  src/plots/pie/layer.ts
  src/plots/radar/layer.ts
  src/plots/ring/component/statistic-template.ts
  src/plots/ring/layer.ts
Labels: PR: unreviewed

#258 fix: 修复 Interface error
  src/plots/area/layer.ts
  src/plots/line/layer.ts
  src/plots/pie/layer.ts
  src/plots/radar/layer.ts
Labels: PR: reviewed-approved, bug

#278 feat: dark theme加一个demo
  examples/general/axis/index.en.md
  examples/general/axis/index.zh.md
  examples/general/label/index.en.md
  examples/general/label/index.zh.md
  examples/general/legend/index.en.md
  examples/general/legend/index.zh.md
  examples/general/padding/index.en.md
  examples/general/padding/index.zh.md
  examples/general/state/index.en.md
  examples/general/state/index.zh.md
  examples/general/theme/API.en.md
  examples/general/theme/API.zh.md
  examples/general/theme/demo/meta.json
  examples/general/theme/demo/set-dark-theme.js
  examples/general/theme/design.en.md
  examples/general/theme/design.zh.md
  examples/general/theme/index.en.md
  examples/general/theme/index.zh.md
Labels: PR: reviewed-approved, enhancement

#275 Upgrade pie
  package.json
  site/locale.json
  src/plots/pie/component/label/upgrade-label/index.ts
  src/plots/pie/component/label/utils.ts
Labels: PR: unreviewed

#280 Update docs
  docs/manual/general-config.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/group-bar.zh.md
  docs/manual/plots/group-column.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.zh.md
  docs/manual/plots/stack-bar.zh.md
  docs/manual/plots/stack-column.zh.md
  examples/general/axis/API.zh.md
  examples/pie/basic/design.zh.md
  examples/pie/ring/design.zh.md
  src/plots/pie/component/label/upgrade-label/index.ts
Labels: PR: unreviewed

#281 test-cases: 增加测试用例
  __tests__/unit/pie-upgradeLabel-spec.ts
  __tests__/unit/pie-utils-spec.ts
  src/plots/pie/component/label/upgrade-label/index.ts
  src/plots/pie/component/label/utils.ts
Labels: PR: reviewed-approved, cases

#276 build(*): upgrade dependence version
  package.json
Labels: PR: reviewed-approved, build

#283 feat(changelog): add commit-msg and changelog generator
  .commitlintrc.js
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, enhancement

#277 🚀 g2plot.antv.vision
  gatsby-config.js
  package.json
Labels: PR: unreviewed

#286 Readme cn
  README-en.md
  README.md
  package.json
Labels: PR: unreviewed

#287 chore: add design principles for components
  examples/general/axis/design.zh.md
  examples/general/label/design.zh.md
  examples/general/legend/design.zh.md
  examples/general/title-description/design.zh.md
Labels: PR: reviewed-changes-requested, chore

#288 docs: Update README.md
  README.md
Labels: PR: reviewed-changes-requested, documentation

#289 chore: update site & readme
  .prettierrc
  README.md
  examples/area/basic/index.zh.md
  examples/area/percentageArea/index.zh.md
  examples/area/stack/index.zh.md
  examples/bar/basic/design.zh.md
  examples/bar/basic/index.zh.md
  examples/bar/group/design.zh.md
  examples/bar/group/index.zh.md
  examples/bar/percentageStack/design.zh.md
  examples/bar/percentageStack/index.zh.md
  examples/bar/stack/design.zh.md
  examples/bar/stack/index.zh.md
  examples/column/basic/design.zh.md
  examples/column/basic/index.zh.md
  examples/column/group/design.zh.md
  examples/column/group/index.zh.md
  examples/column/histogram/index.zh.md
  examples/column/percentageStack/design.zh.md
  examples/column/percentageStack/index.zh.md
  examples/column/stack/design.zh.md
  examples/column/stack/index.zh.md
  examples/gauge/basic/index.zh.md
  examples/general/axis/design.zh.md
  examples/general/label/design.zh.md
  examples/general/legend/design.zh.md
  examples/general/padding/demo/set-padding.js
  examples/general/padding/index.zh.md
  examples/general/title-description/design.zh.md
  examples/line/basic/design.zh.md
  examples/line/basic/index.zh.md
  examples/line/multiple/design.zh.md
  examples/line/multiple/index.zh.md
  examples/mini/multiple/index.zh.md
  examples/pie/basic/design.zh.md
  examples/pie/basic/index.zh.md
  examples/pie/ring/index.zh.md
  examples/radar/basic/index.zh.md
  package.json
Labels: PR: reviewed-changes-requested, chore

#285 gh-pages build with remote action
  .github/workflows/gh-pages.yml
Labels: PR: unreviewed

#290 fix: support line label formatter config
  src/plots/line/layer.ts
Labels: PR: reviewed-changes-requested, bug

#291 docs: remove wrong title and description
  package.json
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, documentation

#297 feat: 隐藏bar 和 percentagestackbar x轴的tickline
  src/plots/bar/layer.ts
  src/plots/percentage-stack-bar/layer.ts
Labels: PR: reviewed-changes-requested, enhancement

#298 chore: 优化文档样式
  examples/area/basic/index.zh.md
  examples/area/percentageArea/index.zh.md
  examples/area/stack/index.zh.md
  examples/bar/basic/design.zh.md
  examples/bar/basic/index.zh.md
  examples/bar/group/design.zh.md
  examples/bar/group/index.zh.md
  examples/bar/percentageStack/design.zh.md
  examples/bar/percentageStack/index.zh.md
  examples/bar/stack/design.zh.md
  examples/bar/stack/index.zh.md
  examples/column/basic/design.zh.md
  examples/column/basic/index.zh.md
  examples/column/group/design.zh.md
  examples/column/group/index.zh.md
  examples/column/histogram/index.zh.md
  examples/column/percentageStack/design.zh.md
  examples/column/percentageStack/index.zh.md
  examples/column/stack/design.zh.md
  examples/column/stack/index.zh.md
  examples/gauge/basic/index.zh.md
  examples/general/axis/design.zh.md
  examples/general/label/design.zh.md
  examples/general/legend/design.zh.md
  examples/line/basic/design.zh.md
  examples/line/basic/index.zh.md
  examples/line/multiple/design.zh.md
  examples/line/multiple/index.zh.md
  examples/mini/multiple/index.zh.md
  examples/pie/basic/design.zh.md
  examples/pie/basic/index.zh.md
  examples/pie/ring/index.zh.md
  examples/radar/basic/index.zh.md
  src/plots/line/layer.ts
Labels: PR: unreviewed, chore

#299 fix: axisLine style won't work in responsive plots
  src/util/responsive/apply/axis.ts
Labels: PR: unreviewed, bug

#302 chore: update g2 and component version
  package.json
Labels: PR: unreviewed, chore

#301 fix: position is not supported for axisLabel
  src/plots/stack-bar/layer.ts
Labels: PR: unreviewed, bug

#296 feat: 字符串转数字
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/layer.ts
  src/plots/pie/layer.ts
Labels: PR: unreviewed, enhancement

#305 chore: 修复release action
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  package.json
Labels: PR: reviewed-approved, chore

#307 chore: use ACCESS_TOKEN for release action
  .github/workflows/release.yml
  package.json
Labels: PR: reviewed-approved, chore

#312 chore: update links & site-en
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, chore

#314 fix: homepage link
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#313 fix: 百分比堆积条形图数据顺序 & 垂直滚动条数据范围修复
  src/interaction/helper/data-range.ts
  src/interaction/scrollbar.ts
  src/plots/percentage-stack-bar/layer.ts
Labels: PR: unreviewed, bug

#315 docs(readme): optimize readme style, and fix typo
  README.md
  README.zh-CN.md
Labels: PR: reviewed-approved, documentation

#317 fix: 修复Pie Ring的labelLine 以及area的透明度
  src/plots/area/layer.ts
  src/plots/pie/layer.ts
  src/plots/radar/layer.ts
Labels: PR: reviewed-changes-requested, bug

#322 docs: update changelog for v0.11.1
  CHANGELOG.md
  examples/bar/basic/demo/meta.json
  package.json
Labels: PR: reviewed-approved, documentation
