Repository antvis/G2Plot, pull requests merged in 2019-12, with the labels that each got.

#331 docs: 更新资源地址
  docs/manual/getting-started.zh.md
Labels: PR: unreviewed, documentation

#329 fix: 修复百分比堆积图形在某些数据下出现120%的问题
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/density/layer.ts
  src/plots/histogram/layer.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/layer.ts
  src/plots/pie/layer.ts
  src/plots/ring/layer.ts
  src/util/data.ts
Labels: PR: unreviewed, bug

#332 feat: getting-started-en
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
Labels: PR: unreviewed, enhancement

#333 fix: remove sideEffects flag for now
  package.json
Labels: PR: reviewed-approved, bug

#336 fix: minichart docs typo
  docs/manual/plots/tinyPlot-progress.en.md
  docs/manual/plots/tinyPlot-progress.zh.md
  docs/manual/plots/tinyPlot-ring-progress.en.md
  docs/manual/plots/tinyPlot-ring-progress.zh.md
Labels: PR: unreviewed, bug

#342 docs: update CHANGELOG
  CHANGELOG.md
Labels: PR: reviewed-approved, documentation

#343 docs: CHANGELOG修改 & release action调整
  .github/workflows/release.yml
  CHANGELOG.md
Labels: PR: reviewed-approved, documentation

#338 doc: add line chart document english version
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
Labels: PR: reviewed-changes-requested, doc, documentation

#344 progress update method support style config
  docs/manual/plots/tinyPlot-progress.zh.md
  src/tiny-plots/progress/component/marker.ts
  src/tiny-plots/progress/index.ts
  src/tiny-plots/progress/layer.ts
Labels: PR: reviewed-approved

#323 docs(readme): optimize readmes
  README.md
  README.zh-CN.md
Labels: PR: unreviewed, documentation

#346 fix: fix auto padding for title & axis
  src/base/controller/padding.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: PR: unreviewed, bug

#353 fix: progress mouseleave event in x dir
  src/tiny-plots/progress/layer.ts
Labels: PR: reviewed-changes-requested, bug

#357 fix: export declaration file
  tsconfig.json
Labels: PR: unreviewed, bug

#359 docs: update G2Plot/docs/manual/introduction.zh.md
  docs/manual/introduction.zh.md
Labels: PR: unreviewed, documentation

#362 fix: column scale
  src/plots/column/layer.ts
  src/plots/radar/layer.ts
Labels: PR: unreviewed, bug

#354 fix: progress mouseenter & mouseleave event triggered by mask
  src/tiny-plots/progress/event.ts
  src/tiny-plots/progress/layer.ts
  src/tiny-plots/ring-progress/event.ts
Labels: PR: unreviewed, bug

#363 docs: umd import usage docs
  .github/workflows/release.yml
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  package.json
  webpack.config.js
Labels: PR: reviewed-changes-requested, documentation

#365 feat(pie-label): 新增自定义饼图outer-label
  .eslintrc
  __tests__/unit/pie-label-spec.ts
  __tests__/unit/pie-upgradeLabel-spec.ts
  __tests__/unit/utils-text-spec.ts
  package.json
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/component/label/upgrade-label/index.ts
  src/plots/pie/component/label/utils/index.ts
  src/plots/pie/component/label/utils/text.ts
  src/plots/pie/layer.ts
Labels: PR: unreviewed, enhancement

#369 test(pie-coverage): 增加pie-label测试断言
  __tests__/unit/pie-label-spec.ts
  src/plots/pie/component/label/outer-label.ts
Labels: PR: reviewed-approved, test

#374 fix: fix dependency version
  package.json
Labels: PR: reviewed-approved, bug

#373 feat: label添加adjustPosition选项
  .github/workflows/release.yml
  examples/bar/basic/API.zh.md
  examples/column/basic/API.zh.md
  package.json
  src/interface/config.ts
  src/plots/bar/component/label/bar-label.ts
Labels: PR: unreviewed, enhancement

#375 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, documentation

#371 feat: 散点图 & 气泡图功能优化
  demos/bubble-basic.ts
  demos/scatter-basic.ts
  package.json
  src/plots/bubble/component/label/bubble-label.ts
  src/plots/bubble/layer.ts
  src/plots/column/component/label/column-label.ts
  src/plots/scatter/components/quadrant.ts
  src/plots/scatter/components/trendline.ts
  src/plots/scatter/layer.ts
  src/util/math.ts
Labels: PR: unreviewed, enhancement

#379 fix(pie-label): 修复饼图label 调用空对象getBBox 方法
  src/plots/pie/component/label/outer-label.ts
Labels: PR: reviewed-approved, bug

#383 add scatter & bubble plot demos
  demos/bubble-basic.ts
  examples/bubble/basic/API.en.md
  examples/bubble/basic/API.zh.md
  examples/bubble/basic/demo/basic.js
  examples/bubble/basic/demo/meta.json
  examples/bubble/basic/demo/trendline.js
  examples/bubble/basic/design.en.md
  examples/bubble/basic/design.zh.md
  examples/bubble/basic/index.en.md
  examples/bubble/basic/index.zh.md
  examples/data/revenue.json
  examples/data/smoking-rate.json
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
  examples/scatter/basic/demo/basic.js
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/design.en.md
  examples/scatter/basic/design.zh.md
  examples/scatter/basic/index.en.md
  examples/scatter/basic/index.zh.md
  gatsby-config.js
  package.json
  src/geoms/point/circle.ts
  src/plots/bubble/layer.ts
  src/plots/scatter/components/quadrant.ts
  src/plots/scatter/components/trendline.ts
Labels: WIP

#390 docs: Sparkline progress API 文档 小修改
  docs/manual/plots/sparkline-progress.en.md
  docs/manual/plots/sparkline-ring-progress.en.md
  examples/sparkline/multiple/API.zh.md
Labels: PR: reviewed-approved, documentation

#391 fix(label): move label into foreground
  __tests__/unit/groupColumn-spec.ts
  __tests__/unit/pie-spec.ts
  package.json
  src/plots/line/layer.ts
Labels: PR: unreviewed, bug

#395 Feat heatmap
  __tests__/data/heatmap.ts
  __tests__/unit/heatmap-spec.ts
  examples/bubble/basic/API.zh.md
  examples/general/axis/API.zh.md
  examples/general/guideLine/API.zh.md
  examples/general/guideLine/design.zh.md
  examples/general/title-description/design.zh.md
  examples/pie/ring/design.zh.md
  examples/scatter/basic/API.zh.md
  src/geoms/heatmap/linear.ts
  src/index.ts
  src/plots/heatmap/components/background.ts
  src/plots/heatmap/components/legend.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/layer.ts
  src/plots/line/layer.ts
Labels: PR: unreviewed

#398 chore: update g2 & scale dependency
  .github/workflows/release.yml
  package.json
Labels: PR: reviewed-approved, chore

#399 chore: correct site-publish token
  .github/workflows/release.yml
Labels: PR: unreviewed, chore

#380 feat: 添加漏斗图
  demos/funnel-basic.ts
  src/index.ts
  src/interface/config.ts
  src/plots/funnel/animation/funnel-fade-out.ts
  src/plots/funnel/animation/funnel-scale-in-y.ts
  src/plots/funnel/index.ts
  src/plots/funnel/layer.ts
  src/plots/funnel/theme.ts
Labels: PR: unreviewed, enhancement

#195 feat: combo charts
  __tests__/unit/area-spec.ts
  __tests__/unit/combo-spec.ts
  __tests__/unit/line-spec.ts
  __tests__/unit/lineLabel-spec.ts
  __tests__/unit/responsiveLine-spec.ts
  docs/manual/advanced/responsive.en.md
  docs/manual/advanced/responsive.zh.md
  docs/manual/general-config.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/ring.zh.md
  docs/manual/plots/stack-area.en.md
  docs/manual/plots/stack-area.zh.md
  package.json
  site/pages/index.zh.tsx
  src/base/controller/padding.ts
  src/base/layer.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/combo-plots/base.ts
  src/combo-plots/overlapped.ts
  src/combo-plots/util/adjustColorConfig.ts
  src/combo-plots/util/globalAxis.ts
  src/combo-plots/util/globalLegend.ts
  src/combo-plots/util/globalTooltip.ts
  src/combo-plots/util/index.ts
  src/combo-plots/util/padding.ts
  src/index.ts
  src/plots/index.ts
  src/plots/line/layer.ts
  src/theme/default.ts
  src/util/responsive/theme.ts
Labels: PR: unreviewed, enhancement

#406 demo: 跟随标签图例的 demo，换成国家 GDP 趋势对比
  examples/data/GDP.json
  examples/data/IMDB副本.json
  examples/line/multiple/demo/line-label.js
  src/plots/line/animation/clipIn-with-data.ts
Labels: PR: unreviewed, demo

#405 refactor(pie): 优化pie outer-label布局摆放
  __tests__/unit/pie-label-spec.ts
  __tests__/unit/pie-outerLabel-spec.ts
  __tests__/utils/dom.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/outer-label.ts
Labels: PR: reviewed-approved, refactor

#409 feat: 支持lark的自定义多角度axis label auto rotate
  package.json
  src/base/controller/padding.ts
  src/interface/config.ts
Labels: PR: reviewed-changes-requested, enhancement

#410 魔改大法好: 条形图legend & tooltip数据顺序颠倒
  src/interface/config.ts
  src/plots/group-bar/layer.ts
Labels: PR: unreviewed

#411 chore: update g2 to beta 11
  package.json
Labels: PR: reviewed-approved, chore

#415 魔改大法好2: label参与auto-padding计算
  package.json
  src/base/controller/padding.ts
Labels: 2, PR: reviewed-changes-requested, PR: unreviewed

#417 删除重复描述
  docs/manual/advanced/responsive.zh.md
Labels: PR: unreviewed

#414 En typo
  docs/manual/general-config.en.md
Labels: PR: unreviewed

#412 fix(spider-label): 蜘蛛布局小步重构
  __tests__/unit/pie-spec.ts
  __tests__/unit/pie-spiderLabel-spec.ts
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  src/plots/pie/component/label/spider-label.ts
Labels: PR: unreviewed, bug

#421 fix(issue-419): spider-label pie点击图例 label绘制出错
  __tests__/bugs/issue-419-spec.ts
  src/plots/pie/component/label/spider-label.ts
Labels: PR: reviewed-changes-requested, bug

#420 chore: 添加所有图表页面
  examples/gallary/index.en.md
  examples/gallary/index.zh.md
  examples/line/basic/index.zh.md
  gatsby-config.js
  package.json
Labels: PR: unreviewed, chore

#424 fix(site): 🐛 gallary => gallery
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  gatsby-config.js
  package.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#427 fix: 只有一个数据时 autoPadding 报错
  src/base/controller/padding.ts
Labels: PR: reviewed-changes-requested, bug

#428 docs: fix examples url 404
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, documentation

#429 fix(ts): ts definition fix
  src/base/plot.ts
  src/base/view-layer.ts
  src/interface/config.ts
  src/interface/types.ts
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/line/layer.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/radar/layer.ts
  src/plots/ring/layer.ts
  src/plots/scatter/components/label/scatter-label.ts
  src/util/event.ts
  src/util/responsive/responsive.ts
  src/util/state-manager.ts
Labels: PR: reviewed-approved, bug

#433 fix: 修复column/bar数据标签position配置在负数值情况的位置
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/column/layer.ts
Labels: PR: reviewed-changes-requested, bug

#435 chore: add umd module field
  package.json
Labels: PR: reviewed-approved, chore

#389 feat(waterfall): 添加瀑布图
  __tests__/unit/waterfall-spec.ts
  examples/column/waterfall/API.en.md
  examples/column/waterfall/API.zh.md
  examples/column/waterfall/demo/basic.js
  examples/column/waterfall/demo/meta.json
  examples/column/waterfall/design.en.md
  examples/column/waterfall/design.zh.md
  examples/column/waterfall/index.en.md
  examples/column/waterfall/index.zh.md
  src/plots/index.ts
  src/plots/waterfall/component/label/diff-label.ts
  src/plots/waterfall/component/label/waterfall-label.ts
  src/plots/waterfall/event.ts
  src/plots/waterfall/geometry/shape/waterfall.ts
  src/plots/waterfall/index.ts
  src/plots/waterfall/layer.ts
Labels: PR: unreviewed, enhancement

#439 feat(line): 折线图Y轴设置默认从0开始
  examples/column/waterfall/index.zh.md
  src/plots/bubble/layer.ts
  src/plots/line/layer.ts
  src/plots/scatter/layer.ts
  src/util/scale.ts
Labels: PR: unreviewed, enhancement

#438 chore: add ci and coverage badges
  README.md
  README.zh-CN.md
Labels: PR: unreviewed, chore

#441 尾部跟随label动画
  src/plots/line/animation/clipIn-with-data.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-approved

#442 fix: 直方图绘制失效
  src/plots/histogram/layer.ts
Labels: PR: reviewed-changes-requested, bug

#423 feat: 水波图开发、漏斗图微调
  demos/liquid-basic.ts
  demos/liquid-percent.ts
  src/plots/funnel/layer.ts
  src/plots/index.ts
  src/plots/liquid/animation/liquid-move-in.ts
  src/plots/liquid/geometry/shape/liquid.ts
  src/plots/liquid/index.ts
  src/plots/liquid/layer.ts
Labels: PR: unreviewed, enhancement

#443 fix: fix radar errors #436
  demos/radar-basic.ts
  demos/radar-series.ts
  src/base/view-layer.ts
  src/plots/radar/layer.ts
Labels: PR: reviewed-changes-requested, bug
