Repository antvis/G2Plot, pull requests merged in 2019-09, with the labels that each got.

#22 开启responsiveTheme注册
  __tests__/unit/pie.spec2.js
  __tests__/unit/ring.spec2.js
  __tests__/unit/stateManager-spec.js
  package.json
  src/base/controller/theme.ts
  src/components/tooltip/state.ts
  src/interface/config.ts
  src/plots/column/applyResponsive/axis.ts
  src/plots/column/applyResponsive/element.ts
  src/plots/column/applyResponsive/label.ts
  src/plots/column/applyResponsive/theme.ts
  src/plots/column/index.ts
  src/plots/line/applyResponsive/axis.ts
  src/plots/line/applyResponsive/label.ts
  src/plots/line/applyResponsive/theme.ts
  src/plots/line/index.ts
  src/plots/ring/applyResponsive/element.ts
  src/plots/ring/applyResponsive/theme.ts
  src/plots/ring/index.ts
  src/theme/default.ts
  src/util/responsive/constraints/ringThickness.ts
Labels: PR: unreviewed

#23 fix(responsive): 修复图表重绘时responsive失效问题
  __tests__/unit/lineLabel-spec.js
  package.json
  src/plots/column/applyResponsive/axis.ts
  src/plots/column/applyResponsive/label.ts
  src/plots/column/applyResponsive/theme.ts
  src/plots/column/index.ts
  src/plots/line/applyResponsive/axis.ts
  src/plots/line/applyResponsive/label.ts
  src/plots/line/index.ts
  src/plots/ring/index.ts
Labels: PR: unreviewed, bug

#24 fix(pie): spider label配置项与其他label统一
  __tests__/unit/pie.spec.js
  __tests__/unit/pie.spec2.js
  __tests__/unit/ring.spec2.js
  package.json
  src/plots/pie/guide/label/spiderLabel.ts
  src/plots/pie/index.ts
Labels: PR: reviewed-changes-requested, bug

#26 fix: 允许label格式化时获取到原始数据点
  src/components/label/parser.ts
Labels: PR: reviewed-changes-requested, bug

#27 Remove unnecessary event off
  __tests__/unit/biztheme.spec.js
  __tests__/unit/liquid.spec.js
  src/base/plot.ts
  src/util/event.ts
Labels: PR: reviewed-changes-requested

#28 feat(bar): bar chart responsive theme
  __tests__/unit/responsive-bar-spec.js
  src/base/plot.ts
  src/plots/area/applyResponsive/axis.ts
  src/plots/area/applyResponsive/index.ts
  src/plots/area/index.ts
  src/plots/bar/applyResponsive/axis.ts
  src/plots/bar/applyResponsive/index.ts
  src/plots/bar/component/label/bar-label.ts
  src/plots/bar/index.ts
  src/plots/column/component/label/column-label.ts
  src/plots/column/index.ts
  src/plots/gauge/geometry/shape/pointer.ts
  src/plots/gauge/index.ts
  src/plots/line/component/annotation/timeGroupAnnotation.ts
  src/plots/line/component/label/line-label.ts
  src/plots/line/component/label/point-label.ts
  src/plots/line/index.ts
  src/plots/liquid/geometry/shape/liquid.ts
  src/plots/liquid/index.ts
  src/plots/pie/component/label/spiderLabel.ts
  src/plots/pie/index.ts
  src/plots/ring/component/annotation/centralText_template.ts
  src/plots/ring/index.ts
  src/plots/stack-bar/component/label/stackBar-label.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-column/component/label/stackColumn-label.ts
  src/plots/stack-column/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#30 Fix issue 29
  __tests__/unit/pie.spec.js
  src/plots/ring/component/annotation/centralText_template.ts
  src/plots/ring/index.ts
Labels: PR: reviewed-changes-requested

#31 fix: auto padding for flipped legend
  src/base/controller/padding.ts
Labels: PR: reviewed-changes-requested, bug

#32 add connectedArea component
  __tests__/unit/connectedArea-spec.js
  src/base/controller/padding.ts
  src/base/controller/state.ts
  src/components/connectedArea.ts
  src/geoms/point/guide.ts
  src/plots/radar/index.ts
  src/plots/stack-column/index.ts
Labels: PR: unreviewed, WIP

#33 WIP: add area label
  __tests__/unit/stack-area.spec.js
  src/components/connectedArea.ts
  src/plots/stack-area/component/label.ts
  src/plots/stack-area/index.ts
Labels: WIP

#36 Fix line point
  __tests__/unit/line.spec.js
  src/geoms/point/guide.ts
Labels: PR: reviewed-changes-requested

#38 fix(tinyPlot): 迷你图表配置项调整
  __tests__/unit/tinyPlot/progress.js
  __tests__/unit/tinyPlot/tinyArea.js
  __tests__/unit/tinyPlot/tinyColumn.js
  __tests__/unit/tinyPlot/tinyLine.js
  src/geoms/line/mini.ts
  src/tinyPlots/progress/event.ts
  src/tinyPlots/progress/index.ts
  src/tinyPlots/ring-progress/animation/index.ts
  src/tinyPlots/ring-progress/event.ts
  src/tinyPlots/ring-progress/index.ts
  src/tinyPlots/tiny-area/event.ts
  src/tinyPlots/tiny-area/index.ts
  src/tinyPlots/tiny-column/event.ts
  src/tinyPlots/tiny-column/index.ts
  src/tinyPlots/tiny-line/event.ts
  src/tinyPlots/tiny-line/index.ts
  src/tinyPlots/tinyPlot.ts
Labels: PR: reviewed-changes-requested, bug

#40 miniChart unit test
  __tests__/unit/area-spec.js
  __tests__/unit/bar-spec.js
  __tests__/unit/biztheme-spec.js
  __tests__/unit/column-spec.js
  __tests__/unit/gauge-spec.js
  __tests__/unit/groupBar-spec.js
  __tests__/unit/groupColumn-spec.js
  __tests__/unit/index-spec.js
  __tests__/unit/line-spec.js
  __tests__/unit/liquid-spec.js
  __tests__/unit/pie-spec.js
  __tests__/unit/radar-spec.js
  __tests__/unit/ring-spec.js
  __tests__/unit/stackArea-spec.js
  __tests__/unit/stackBar-spec.js
  __tests__/unit/stackColumn-spec.js
  __tests__/unit/theme-spec.js
  __tests__/unit/tinyPlot/progress-spec.js
  __tests__/unit/tinyPlot/progress.js
  __tests__/unit/tinyPlot/ringProgress-spec.js
  __tests__/unit/tinyPlot/tinyArea-spec.js
  __tests__/unit/tinyPlot/tinyArea.js
  __tests__/unit/tinyPlot/tinyColumn-spec.js
  __tests__/unit/tinyPlot/tinyColumn.js
  __tests__/unit/tinyPlot/tinyLine-spec.js
  __tests__/unit/tinyPlot/tinyLine.js
  package.json
  src/components/guideLine.ts
  src/tinyPlots/progress/index.ts
  src/tinyPlots/ring-progress/index.ts
Labels: PR: merged

#49 fix(legend): use legend.getBBox for auto padding
  src/base/controller/padding.ts
Labels: PR: reviewed-changes-requested, bug

#39 调整区域图配置接口及各种bug
  __tests__/unit/area-spec.js
  src/geoms/area/main.ts
  src/geoms/line/guide.ts
  src/plots/area/index.ts
Labels: PR: unreviewed

#50 fix(legend): 修复theme legend设置失效问题
  package.json
  src/base/plot.ts
  src/plots/group-bar/index.ts
  src/plots/group-column/index.ts
  src/plots/stack-area/index.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-column/index.ts
Labels: PR: unreviewed, bug

#51 feat(plot): update liquid & gauge unit test.
  __tests__/unit/gauge-spec.js
  __tests__/unit/liquid-spec.js
Labels: PR: unreviewed, enhancement

#52 完善、增加堆叠面积图的测试用例
  __tests__/unit/stackArea-spec.js
Labels: PR: reviewed-changes-requested

#54 fix: support axis grid function config
  src/components/axis/parser.ts
  src/index.ts
  src/interface/config.ts
  src/util/scale.ts
Labels: PR: reviewed-changes-requested, bug

#56 add state unit test
  __tests__/unit/areaLabel-spec.js
  __tests__/unit/connectedArea-spec.js
  __tests__/unit/responsive/registerConstraint-spec.js
  __tests__/unit/responsive/registerResponsiveTheme-spec.js
  __tests__/unit/responsive/registerRule-spec.js
  __tests__/unit/state-spec.js
  __tests__/unit/stateManager-spec.js
  src/base/controller/padding.ts
  src/base/controller/state.ts
  src/components/connectedArea.ts
  src/plots/column/theme.ts
  src/util/responsive/rules/clearOverlapping.ts
Labels: PR: reviewed-changes-requested, WIP

#57 fix: prevent undefined exception when render/update plot multiple times
  src/base/plot.ts
Labels: PR: reviewed-changes-requested, bug

#58 规范responsive相关模块参数及调用方式
  __tests__/unit/responsiveColumnLabel-spec.js
  src/plots/area/applyResponsive/axis.ts
  src/plots/bar/applyResponsive/axis.ts
  src/plots/column/applyResponsive/axis.ts
  src/plots/column/applyResponsive/geomtery.ts
  src/plots/column/applyResponsive/index.ts
  src/plots/column/applyResponsive/label.ts
  src/plots/column/applyResponsive/theme.ts
  src/plots/line/applyResponsive/axis.ts
  src/plots/line/applyResponsive/label.ts
  src/plots/line/applyResponsive/theme.ts
  src/plots/ring/applyResponsive/geometry.ts
  src/plots/ring/applyResponsive/index.ts
  src/plots/ring/applyResponsive/theme.ts
  src/util/responsive/constraints/index.ts
  src/util/responsive/responsive.ts
  src/util/responsive/rules/clearOverlapping.ts
  src/util/responsive/rules/datetimeStringAbbrevaite.ts
  src/util/responsive/rules/digitsAbbreviate.ts
  src/util/responsive/rules/nodeJitter.ts
  src/util/responsive/rules/nodeJitterUpward.ts
  src/util/responsive/rules/nodesResampling.ts
  src/util/responsive/rules/nodesResamplingByAbbrevate.ts
  src/util/responsive/rules/nodesResamplingByChange.ts
  src/util/responsive/rules/nodesResamplingByState.ts
  src/util/responsive/rules/robustAbbrevaite.ts
  src/util/responsive/rules/textAbbreviate.ts
  src/util/responsive/rules/textRotation.ts
  src/util/responsive/rules/textWrapper.ts
  src/util/responsive/theme.ts
Labels: PR: unreviewed, WIP

#59 chore(responsive): applyResponsive模块抽象
  src/index.ts
  src/plots/area/applyResponsive/axis.ts
  src/plots/bar/applyResponsive/axis.ts
  src/plots/column/applyResponsive/axis.ts
  src/plots/column/applyResponsive/geomtery.ts
  src/plots/column/applyResponsive/label.ts
  src/plots/line/applyResponsive/axis.ts
  src/plots/line/applyResponsive/label.ts
  src/plots/ring/applyResponsive/geometry.ts
  src/tinyPlots/progress/index.ts
  src/util/layout/annealing.ts
  src/util/layout/verticalShatter.ts
  src/util/responsive/apply/axis.ts
  src/util/responsive/apply/base.ts
  src/util/responsive/apply/label.ts
  src/util/responsive/constraints/index.ts
  src/util/responsive/node/shapeNodes.ts
  src/util/responsive/node/variableNode.ts
  src/util/responsive/responsive.ts
  src/util/responsive/rules/index.ts
  src/util/responsive/theme.ts
Labels: PR: reviewed-changes-requested, chore

#60 迁移demos
  demos/app.js
  demos/assets/bootstrap-4.1.0/bootstrap-grid.min.css
  demos/assets/bootstrap-4.1.0/bootstrap.min.css
  demos/assets/bootstrap-4.1.0/bootstrap.min.js
  demos/assets/clipboard-1.7.1.min.js
  demos/assets/codemirror-5.29.0/codemirror-merged.min.css
  demos/assets/codemirror-5.29.0/codemirror-merged.min.js
  demos/assets/common.css
  demos/assets/file-saver-1.3.8.min.js
  demos/assets/index.css
  demos/assets/index.js
  demos/assets/jquery-3.2.1.min.js
  demos/assets/jquery.resizable-0.20.0.js
  demos/assets/lazyload-2.0.0-beta.2.min.js
  demos/assets/lodash-4.17.4.min.js
  demos/assets/moment.min.js
  demos/assets/popper.js-1.12.5/popper-utils.min.js
  demos/assets/popper.js-1.12.5/popper.min.js
  demos/assets/routie-0.3.2.min.js
  demos/bar-basic.html
  demos/bar-labelColorAdjust.html
  demos/bar-labelPosition.html
  demos/column-basic.html
  demos/column-label.html
  demos/column-labelColorAdjust.html
  demos/column-labelPosition.html
  demos/data/income.json
  demos/general-titleDescription1.html
  demos/general-titleDescription2.html
  demos/groupBar.html
  demos/groupColumn.html
  demos/index.njk
  demos/line-animation.html
  demos/line-basic.html
  demos/line-dataPoints.html
  demos/line-groupedAxis.html
  demos/line-lineLabel.html
  demos/line-multiple.html
  demos/line-pointLabel.html
  demos/line-pointStyle.html
  demos/line-smooth.html
  demos/pie-basic1.html
  demos/pie-basic2.html
  demos/pie-innerLabel.html
  demos/pie-outerLabel.html
  demos/pie-radius.html
  demos/pie-spiderLabel.html
  demos/ring-basic.html
  demos/ring-centralText.html
  demos/ring-innerOuter.html
  demos/stackBar-adjustLabelDisplay.html
  demos/stackBar.html
  demos/stackColumn-adjustLabelDisplay.html
  demos/stackColumn.html
  package.json
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/line/component/label/line-label.ts
  src/plots/line/component/label/point-label.ts
  webpack.config.js
Labels: PR: unreviewed, WIP

#61 add new demos
  __tests__/unit/tinyPlot/tinyArea-spec.js
  __tests__/unit/tinyPlot/tinyLine-spec.js
  demos/area-basic.html
  demos/column-colorMapping.html
  demos/data/fireworks-sales.json
  demos/data/oil.json
  demos/gauge-style.html
  demos/gauge.html
  demos/general-defaultState.html
  demos/general-setActive.html
  demos/general-setDisable.html
  demos/general-setSelected.html
  demos/liqiud-basic.html
  demos/liqiud-percent.html
  demos/stackArea-areaLabel.html
  demos/stackArea-lineLabel.html
  demos/stackArea.html
  demos/stackColumn-connectedArea-interactive.html
  demos/stackColumn-connectedArea-style.html
  demos/stackColumn-connectedArea.html
  demos/tinyPlot-area-guideLine.html
  demos/tinyPlot-area.html
  demos/tinyPlot-column-guideLine.html
  demos/tinyPlot-column.html
  demos/tinyPlot-line-guideLine.html
  demos/tinyPlot-line.html
  demos/tinyPlot-progress-setColor.html
  demos/tinyPlot-progress-update.html
  demos/tinyPlot-progress.html
  demos/tinyPlot-ringProgress.html
  src/geoms/line/guide.ts
  src/plots/area/index.ts
  src/plots/stack-area/component/label/areaLabel.ts
  src/plots/stack-area/component/label/lineLabel.ts
  src/plots/stack-area/index.ts
Labels: PR: unreviewed, WIP

#63 wip: add docs
  docs/advanced/responsivePlot.zh-CN.md
  docs/advanced/stateAndChartsConnetion.zh-CN.md
  docs/generalConfig.zh-CN.md
  docs/gettingStarted.zh-CN.md
  docs/img/lineLabel.jpg
  docs/img/pieLabel.jpg
  docs/img/responsive-construction.jpg
  docs/img/ugly-chart.jpg
  docs/introduction.zh-CN.md
  docs/plots/area.zh-CN.md
  docs/plots/bar.zh-CN.md
  docs/plots/column.zh-CN.md
  docs/plots/gauge.zh-CN.md
  docs/plots/group-bar.zh-CN.md
  docs/plots/group-column.zh-CN.md
  docs/plots/line.zh-CN.md
  docs/plots/pie.zh-CN.md
  docs/plots/rardar.zh-CN.md
  docs/plots/ring.zh-CN.md
  docs/plots/stack-area.zh-CN.md
  docs/plots/stack-bar.zh-CN.md
  docs/plots/stack-column.zh-CN.md
  docs/plots/tinyPlot-area.zh-CN.md
  docs/plots/tinyPlot-column.zh-CN.md
  docs/plots/tinyPlot-line.zh-CN.md
  docs/plots/tinyPlot-progress.zh-CN.md
  docs/plots/tinyPlot-ringProgress.zh-CN.md
Labels: WIP

#65 add readme file
  CONTRIBUTING.md
  README.md
  docs/advanced/responsivePlot.zh-CN.md
  docs/advanced/stateAndChartsConnetion.zh-CN.md
  docs/generalConfig.zh-CN.md
  docs/plots/group-bar.zh-CN.md
  docs/plots/group-column.zh-CN.md
  docs/plots/ring.zh-CN.md
  docs/plots/stack-area.zh-CN.md
  docs/plots/stack-bar.zh-CN.md
  docs/plots/stack-column.zh-CN.md
Labels: PR: reviewed-changes-requested

#62 Bxfeat
  package.json
  src/interface/config.ts
  src/plots/line/component/label/line-label.ts
  src/plots/line/component/label/point-label.ts
  src/theme/ali-dark.ts
  src/theme/ali-light.ts
  src/theme/index.ts
  src/tinyPlots/tinyPlot.ts
Labels: PR: unreviewed

#66 Fix coordinate
  package.json
  src/plots/column/applyResponsive/geomtery.ts
  src/plots/line/index.ts
  src/plots/ring/applyResponsive/geometry.ts
  tsconfig.json
Labels: PR: unreviewed

#68 add demo & update readme
  README.md
  __tests__/unit/stateManager-spec.js
  demos/general-chartsConnection.html
  docs/introduction.zh-CN.md
  src/base/plot.ts
  src/geoms/line/guide.ts
  src/index.ts
  src/plots/radar/index.ts
Labels: PR: reviewed-changes-requested

#69 fix(geom): fix guide-point config error
  README.md
  demos/general-chartsConnection.html
  demos/line-pointStyle.html
  docs/introduction.zh-CN.md
  src/geoms/point/guide.ts
Labels: PR: reviewed-changes-requested, bug

#70 fix(state): fix set defaultState error when auto padding was auto
  demos/general-chartsConnection.html
  src/base/ViewLayer.ts
  src/base/controller/state.ts
Labels: PR: reviewed-changes-requested, bug

#71 label position 和style 支持function 。
  src/components/label/parser.ts
  src/geoms/interval/main.ts
Labels: PR: reviewed-changes-requested

#72 chore: update deps
  package.json
  src/base/ViewLayer.ts
  src/base/controller/state.ts
  src/components/connectedArea.ts
  src/components/factory.ts
  src/components/label/state.ts
  src/plots/area/applyResponsive/index.ts
  src/plots/bar/applyResponsive/index.ts
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/column/event.ts
  src/plots/column/theme.ts
  src/plots/line/applyResponsive/theme.ts
  src/plots/line/component/label/line-label.ts
  src/plots/pie/component/label/spiderLabel.ts
  src/plots/ring/applyResponsive/theme.ts
  src/plots/stack-area/component/label/lineLabel.ts
  src/tinyPlots/progress/event.ts
  src/tinyPlots/ring-progress/event.ts
  src/tinyPlots/tiny-area/event.ts
  src/tinyPlots/tiny-column/event.ts
  src/tinyPlots/tiny-line/event.ts
  src/util/responsive/apply/base.ts
  src/util/responsive/apply/label.ts
  src/util/responsive/constraints/ringThickness.ts
  src/util/responsive/responsive.ts
  src/util/responsive/rules/index.ts
  src/util/responsive/rules/nodesResamplingByChange.ts
  src/util/responsive/theme.ts
Labels: PR: unreviewed, chore

#74 fix: update to latest coord with getWidth/getHeight
  __tests__/unit/pie-spec.js
  package.json
  src/plots/column/applyResponsive/geomtery.ts
  src/plots/line/animation/clipInWithData.ts
  src/plots/line/component/annotation/timeGroupAnnotation.ts
  src/plots/pie/component/label/spiderLabel.ts
Labels: PR: unreviewed, bug

#80 update docs Closes#75
  README.md
  docs/advanced/stateAndChartsConnetion.zh-CN.md
Labels: PR: unreviewed

#81 fix(plot): 允许用户自行设置pixelRatio，否则在g底层自动获取 Closes #79
  src/base/controller/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#82 docs: update code style and some error.
  CONTRIBUTING.zh-CN.md
  README.md
Labels: PR: unreviewed, documentation

#83 docs: update README.md
  README.md
Labels: PR: unreviewed, documentation

#84 fix(pie): spider label line drawing error
  src/plots/pie/component/label/spiderLabel.ts
Labels: PR: unreviewed, bug

#90 feat: add prepublish script to auto build for publish
  package.json
Labels: PR: unreviewed, enhancement

#91 feat: add connectNulls option to linePlot & areaPlot
  src/geoms/area/main.ts
  src/geoms/line/main.ts
  src/interface/config.ts
Labels: PR: reviewed-changes-requested, enhancement

#92 chore: auto padding在responsive之后
  src/base/ViewLayer.ts
  src/base/controller/padding.ts
  src/plots/area/AreaLayer.ts
  src/plots/bar/BarLayer.ts
  src/plots/column/ColumnLayer.ts
  src/plots/line/LineLayer.ts
Labels: PR: reviewed-changes-requested, chore
