Repository antvis/G2Plot, pull requests merged in 2019-10, with the labels that each got.

#93 缩略轴添加前景和背景条的颜色配置项
  src/geoms/line/main.ts
  src/interface/config.ts
  src/layers/SliderLayer.ts
  src/plots/column/index.ts
  src/plots/line/index.ts
Labels: PR: reviewed-approved

#106 feat(testcases-fix): 修复测试用例没有跑全的问题
  __tests__/unit/area-spec.js
  __tests__/unit/areaLabel-spec.js
  __tests__/unit/bar-spec.js
  __tests__/unit/biztheme-spec.js
  __tests__/unit/column-spec.js
  __tests__/unit/forcefit.js
  __tests__/unit/gauge-spec.js
  __tests__/unit/groupBar-spec.js
  __tests__/unit/line-spec.js
  __tests__/unit/line.spec2.js
  __tests__/unit/lineLabel-spec.js
  __tests__/unit/liquid-spec.js
  __tests__/unit/miniLineShape.js
  __tests__/unit/pie-spec.js
  __tests__/unit/radar-spec.js
  __tests__/unit/radar.spec2.js
  __tests__/unit/responsive-bar-spec.js
  __tests__/unit/responsiveColumn-spec.js
  __tests__/unit/responsiveColumnLabel-spec.js
  __tests__/unit/responsiveLine-spec.js
  __tests__/unit/responsiveRing-spec.js
  __tests__/unit/ring-spec.js
  __tests__/unit/ring.spec2.js
  __tests__/unit/stackArea-spec.js
  __tests__/unit/stackBar-spec.js
  __tests__/unit/stackColumn-spec.js
  __tests__/unit/state-spec.js
  __tests__/unit/stateManager-spec.js
  __tests__/unit/theme-spec.js
  __tests__/unit/tinyPlot/progress-spec.js
  __tests__/unit/tinyPlot/ringProgress-spec.js
  __tests__/unit/tinyPlot/tinyArea-spec.js
  __tests__/unit/tinyPlot/tinyColumn-spec.js
  __tests__/unit/tinyPlot/tinyLine-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#105 fix(spiderLabel): 修复view销毁状态下,执行draw报错问题
  __tests__/unit/area-spec.js
  __tests__/unit/areaLabel-spec.js
  __tests__/unit/bar-spec.js
  __tests__/unit/biztheme-spec.js
  __tests__/unit/column-spec.js
  __tests__/unit/forcefit.js
  __tests__/unit/gauge-spec.js
  __tests__/unit/groupBar-spec.js
  __tests__/unit/line-spec.js
  __tests__/unit/line.spec2.js
  __tests__/unit/lineLabel-spec.js
  __tests__/unit/liquid-spec.js
  __tests__/unit/miniLineShape.js
  __tests__/unit/pie-spec.js
  __tests__/unit/radar-spec.js
  __tests__/unit/radar.spec2.js
  __tests__/unit/responsive-bar-spec.js
  __tests__/unit/responsiveColumn-spec.js
  __tests__/unit/responsiveColumnLabel-spec.js
  __tests__/unit/responsiveLine-spec.js
  __tests__/unit/responsiveRing-spec.js
  __tests__/unit/ring-spec.js
  __tests__/unit/ring.spec2.js
  __tests__/unit/stackArea-spec.js
  __tests__/unit/stackBar-spec.js
  __tests__/unit/stackColumn-spec.js
  __tests__/unit/state-spec.js
  __tests__/unit/stateManager-spec.js
  __tests__/unit/theme-spec.js
  __tests__/unit/tinyPlot/progress-spec.js
  __tests__/unit/tinyPlot/ringProgress-spec.js
  __tests__/unit/tinyPlot/tinyArea-spec.js
  __tests__/unit/tinyPlot/tinyColumn-spec.js
  __tests__/unit/tinyPlot/tinyLine-spec.js
  src/plots/pie/component/label/spiderLabel.ts
Labels: PR: unreviewed, bug

#103 fix(guide-point): 修复没有return的方法 进行变量赋值
  src/geoms/point/guide.ts
Labels: PR: reviewed-changes-requested, bug

#107 fix(pieLayer): 无法注册自定义pieLabel
  src/plots/pie/PieLayer.ts
Labels: PR: reviewed-changes-requested, bug

#109 获取顶层g2 plot 实例的接口
  src/base/Plot.ts
Labels: PR: reviewed-changes-requested

#111 fix(responsive): axis visibility conflict with responsive
  src/util/responsive/apply/axis.ts
Labels: PR: unreviewed, bug

#118 新增百分比堆叠图表
  __tests__/unit/responsiveLine-spec.js
  demos/percentage-stack-bar.html
  demos/percentageStackArea.html
  demos/percentageStackColumn.html
  src/base/ViewLayer.ts
  src/index.ts
  src/plots/percentage-stack-area/index.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/index.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/index.ts
  src/plots/percentage-stack-column/layer.ts
  src/tinyPlots/progress/ProgressLayer.ts
Labels: PR: reviewed-changes-requested

#121 fix(spider-pie-label-events): 修复spider pie监听label事件失效
  __tests__/unit/pie.spec2.js
  src/plots/pie/component/label/spiderLabel.ts
Labels: PR: reviewed-changes-requested, bug

#123 support scrollbar interaction
  demos/area-scrollbar.html
  demos/bar-scrollbar.html
  demos/column-scrollbar.html
  demos/stackArea-scrollbar.html
  demos/stackBar-scrollbar.html
  src/base/Plot.ts
  src/base/ViewLayer.ts
  src/interaction/BaseInteraction.ts
  src/interaction/ScrollBarInteraction.ts
  src/interaction/SliderInteraction.ts
  src/interaction/index.ts
  src/interface/config.ts
  src/plots/area/AreaLayer.ts
  src/plots/bar/BarLayer.ts
  src/plots/column/ColumnLayer.ts
  src/plots/gauge/GaugeLayer.ts
  src/plots/line/LineLayer.ts
  src/plots/liquid/LiquidLayer.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/layer.ts
  src/plots/pie/PieLayer.ts
  src/plots/radar/RadarLayer.ts
  src/tinyPlots/TinyLayer.ts
  src/tinyPlots/progress/ProgressLayer.ts
Labels: PR: unreviewed

#129 fix: 修复滚动条在设置了meta config后alias缺失问题
  src/interaction/ScrollBarInteraction.ts
  src/interface/config.ts
Labels: PR: reviewed-changes-requested, bug

#126 axis 增加scale type ；fix forceFit 失效；新增 layer afterrender的勾子；
  package.json
  src/base/Layer.ts
  src/base/Plot.ts
  src/base/ViewLayer.ts
  src/base/controller/canvas.ts
  src/base/controller/padding.ts
  src/interface/config.ts
  src/plots/area/AreaLayer.ts
  src/plots/bar/BarLayer.ts
  src/plots/column/ColumnLayer.ts
  src/plots/group-column/GroupColumnLayer.ts
  src/plots/line/LineLayer.ts
  src/plots/pie/PieLayer.ts
  src/plots/radar/RadarLayer.ts
  src/plots/ring/RingLayer.ts
  src/tinyPlots/progress/ProgressLayer.ts
  src/tinyPlots/ring-progress/RingProgressLayer.ts
  src/tinyPlots/tiny-area/TinyAreaLayer.ts
  src/tinyPlots/tiny-column/TinyColumnLayer.ts
  src/tinyPlots/tiny-line/TinyLineLayer.ts
  src/util/scale.ts
Labels: PR: unreviewed

#131 fix: prevent scrollbar scroll to negative ratio
  src/interaction/ScrollBarInteraction.ts
Labels: PR: reviewed-changes-requested, bug

#132 fix: 如果axis config中设置了scale type则覆盖meta中的type配置
  src/base/ViewLayer.ts
Labels: PR: reviewed-changes-requested, bug

#127 add histogram
  __tests__/unit/histogram-spec.js
  demos/histogram.html
  src/base/ViewLayer.ts
  src/index.ts
  src/plots/histogram/index.ts
  src/plots/histogram/layer.ts
Labels: PR: unreviewed

#134 Refactor theme
  __tests__/unit/biztheme-spec.js
  __tests__/unit/theme-spec.js
  __tests__/unit/theme/index-spec.js
  src/base/ViewLayer.ts
  src/base/controller/theme.ts
  src/plots/area/theme.ts
  src/plots/bar/theme.ts
  src/plots/column/theme.ts
  src/plots/gauge/theme.ts
  src/plots/line/theme.ts
  src/plots/liquid/theme.ts
  src/plots/pie/theme.ts
  src/plots/radar/theme.ts
  src/plots/ring/applyResponsive/geometry.ts
  src/theme/default.ts
  src/theme/global.ts
  src/theme/index.ts
  src/theme/responsive.ts
  src/theme/theme.ts
  src/theme/utils.ts
  src/util/responsive/default.ts
  src/util/responsive/theme.ts
Labels: PR: reviewed-changes-requested

#136 fix: 事件解析bug
  src/base/ViewLayer.ts
Labels: PR: reviewed-changes-requested, bug

#146 fix: 兼容g2里面暴露的事件
  src/base/ViewLayer.ts
Labels: PR: reviewed-changes-requested, bug

#147 fix: 用户自定义theme配置项需要覆盖自定义theme
  src/base/controller/theme.ts
Labels: PR: reviewed-changes-requested, bug

#154 refactor(canvas-controller): refactor & bugfix
  src/base/Plot.ts
  src/base/controller/canvas.ts
Labels: PR: reviewed-approved, refactor

#155 chore: 使用Github Actions代替travis CI
  .github/workflows/ci.yml
  .travis.yml
Labels: PR: reviewed-approved, chore

#159 chore: RADME中的build status badge指向actions
  .github/workflows/ci.yml
  README.md
Labels: PR: reviewed-approved

#160 fix: slider和scrollbar更新
  package.json
  src/interaction/ScrollBarInteraction.ts
  src/interaction/SliderInteraction.ts
  src/interaction/helper/data-range.ts
Labels: PR: reviewed-approved

#162 fix: config all meta scale in meta config
  src/base/ViewLayer.ts
Labels: PR: reviewed-changes-requested
