Repository antvis/G2Plot, pull requests merged in 2020-11, with the labels that each got.

#1838 fix(#1836): fix gauge animate not work
  __tests__/bugs/issue-1836-spec.ts
  src/plots/gauge/adaptor.ts
Labels: PR: reviewed-approved

#1839 test: coverage up
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  __tests__/unit/utils/matrix-spec.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/pie/interactions/pie-legend-action.ts
  src/utils/g-util.ts
  src/utils/matrix.ts
Labels: PR: partially-approved

#1840 chore: v2.0.6
  CHANGELOG.md
  __tests__/bugs/issue-1836-spec.ts
  __tests__/unit/lab-spec.ts
  package.json
  src/index.ts
  src/lab.ts
Labels: PR: reviewed-approved

#1841 test: 提升histogram的测试覆盖率
  __tests__/unit/plots/histogram/axis-spec.ts
  __tests__/unit/plots/histogram/index-spec.ts
Labels: PR: partially-approved

#1844 test: 提升bullet的测试覆盖率以及优化代码
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/label-spec.ts
  src/plots/bullet/adaptor.ts
Labels: PR: reviewed-approved

#1842 fix: type define of legend, axis
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/scatter/legend-spec.ts
  src/types/animation.ts
  src/types/axis.ts
  src/types/legend.ts
Labels: PR: partially-approved

#1848 fix: Scatter regression line and Dual Axes change data
  __tests__/unit/plots/dual-axes/change-data-spec.ts
  __tests__/unit/plots/histogram/change-data-spec.ts
  __tests__/unit/plots/scatter/legend-spec.ts
  __tests__/unit/plots/scatter/regression-line-spec.ts
  __tests__/unit/utils/path-spec.ts
  src/plots/dual-axes/index.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/annotations/path.ts
  src/plots/scatter/util.ts
  src/utils/path.ts
Labels: PR: reviewed-approved

#1845 feat: radial bar color demo
  __tests__/unit/plots/radial-bar/index-spec.ts
  __tests__/unit/plots/radial-bar/utils-spec.ts
  examples/radial-bar/basic/demo/color.ts
  examples/radial-bar/basic/demo/meta.json
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/types.ts
Labels: PR: reviewed-approved

#1849 test: coverage for util/path
  __tests__/unit/plots/histogram/index-spec.ts
  __tests__/unit/utils/path-spec.ts
  src/utils/path.ts
Labels: PR: unreviewed

#1853 fix: 去除 defaultOption 依赖
  __tests__/unit/plots/dual-axes/default-options-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  __tests__/unit/plots/scatter/tooltip-spec.ts
  __tests__/unit/plots/sunburst/change-data-spec.ts
  __tests__/unit/plots/sunburst/index-spec.ts
  src/core/plot.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/util/option.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/index.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/index.ts
  src/plots/histogram/index.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/index.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/index.ts
  src/utils/data.ts
Labels: PR: reviewed-approved

#1852 feat(column/bar): migrate connected area interaction
  __tests__/unit/adaptor/connected-area-spec.ts
  src/adaptor/connected-area.ts
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
Labels: PR: reviewed-approved

#1854 update docs
  docs/common/component.en.md
  docs/common/component.zh.md
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/box.en.md
  docs/manual/plots/box.zh.md
  docs/manual/plots/bullet.en.md
  docs/manual/plots/bullet.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/funnel.en.md
  docs/manual/plots/funnel.zh.md
  docs/manual/plots/heatmap.en.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/histogram.en.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/radial-bar.en.md
  docs/manual/plots/radial-bar.zh.md
  docs/manual/plots/rose.en.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/stock.en.md
  docs/manual/plots/stock.zh.md
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  docs/manual/plots/word-cloud.en.md
  docs/manual/plots/word-cloud.zh.md
Labels: PR: partially-approved

#1843 feat: add multi-view plot
  __tests__/unit/lab-spec.ts
  __tests__/unit/plots/multi-view/index-spec.ts
  __tests__/unit/plots/multi-view/multi-pie-spec.ts
  src/adaptor/geometries/base.ts
  src/lab.ts
  src/plots/multi-layer/adaptor.ts
  src/plots/multi-layer/index.ts
  src/plots/multi-layer/types.ts
Labels: PR: partially-approved

#1847 Fix/duax yaxis object
  __tests__/unit/adaptor/connected-area-spec.ts
  __tests__/unit/plots/dual-axes/axis-spec.ts
  __tests__/unit/plots/dual-axes/index-spec.ts
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/plots/dual-axes/tooltip-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  __tests__/unit/plots/sunburst/change-data-spec.ts
  docs/manual/plots/dual-axes.en.md
  docs/manual/plots/dual-axes.zh.md
  examples/dual-axes/column-line/API.en.md
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/column-line/demo/demo-more-1.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/geometry.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: unreviewed

#1855 feat: changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#1856 fix(conversion-tag): set an uniqe id for every shape
  __tests__/unit/adaptor/connected-area-spec.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  src/adaptor/conversion-tag.ts
Labels: PR: reviewed-approved

#1857 fix: 画布添加默认高度
  __tests__/unit/core/index-spec.ts
  src/core/plot.ts
Labels: PR: reviewed-approved

#1859 feat(examples): 更新 radar demo & icon
  examples/radar/basic/demo/basic.ts
  gatsby-config.js
Labels: PR: partially-approved

#1863 fix: ci
  .github/workflows/build.yml
Labels: PR: unreviewed

#1866 chore(word-cloud): 完善测试
  __tests__/unit/plots/word-cloud/index-spec.ts
  src/plots/word-cloud/index.ts
Labels: PR: reviewed-approved

#1868 docs: line plot
  .github/workflows/build.yml
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  docs/common/theme.en.md
  docs/common/theme.zh.md
  docs/common/xy-field.en.md
  docs/common/xy-field.zh.md
  docs/manual/contact.en.md
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  docs/manual/graphic-style.en.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  docs/manual/plot-api.en.md
  docs/manual/plot-api.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  docs/manual/plugin.en.md
  docs/manual/upgrade.en.md
  examples/bar/basic/demo/basic.ts
Labels: PR: reviewed-approved

#1871 docs: for plugin dev
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
  examples/plugin/basic/API.en.md
  examples/plugin/basic/API.zh.md
  examples/plugin/basic/demo/hill-column.ts
  examples/plugin/basic/demo/meta.json
  examples/plugin/basic/index.en.md
  examples/plugin/basic/index.zh.md
  gatsby-config.js
  src/plugin/index.ts
Labels: PR: partially-approved

#1876 docs: update banner notifications
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved

#1875 refactor(docs-radar): 更新雷达图文档 & api 走查功能是否具备
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  examples/radar/basic/demo/area-alternate-grid.ts
  examples/radar/basic/demo/area-grid.ts
  examples/radar/basic/demo/area.ts
  examples/radar/basic/demo/basic.ts
  examples/radar/basic/demo/line-alternate-grid.ts
  examples/radar/basic/demo/line-grid.ts
  examples/radar/basic/demo/line.ts
  examples/radar/basic/demo/meta.json
Labels: PR: partially-approved

#1879 walkthrough pie
  __tests__/unit/plots/pie/index-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  docs/common/component-no-axis.en.md
  docs/common/component-no-axis.zh.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny.zh.md
  docs/common/component.zh.md
  docs/common/label.en.md
  docs/common/label.zh.md
  docs/common/legend.en.md
  docs/common/legend.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/rose.en.md
  docs/manual/plots/rose.zh.md
  examples/pie/basic/demo/basic.ts
  examples/pie/basic/demo/pie-state.ts
  examples/pie/basic/demo/pie-texture.ts
  examples/pie/basic/demo/spider-label.ts
  examples/pie/donut/demo/basic.ts
  examples/radial-bar/basic/API.en.md
  examples/radial-bar/basic/API.zh.md
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
  src/plots/pie/label/index.ts
  src/plots/pie/label/inner-label.ts
  src/plots/pie/types.ts
  src/plots/pie/utils.ts
  src/plots/rose/types.ts
  src/types/label.ts
Labels: PR: partially-approved

#1878 fix(#1870): when y are same in dual-axes, axis position is wrong
  __tests__/bugs/issue-1870-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/constant.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: partially-approved

#1880 docs: api 走查
  __tests__/unit/core/index-spec.ts
  __tests__/utils/dom.ts
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  examples/scatter/basic/demo/custom-shape.ts
  examples/scatter/basic/demo/meta.json
  src/core/plot.ts
Labels: PR: reviewed-approved

#1885 fix(#1882): add limitInPoit options for G2.Chart
  __tests__/bugs/issue-1882-spec.ts
  src/core/plot.ts
Labels: PR: partially-approved

#1884 docs: area
  docs/common/chart-options.zh.md
  docs/common/color.en.md
  docs/common/color.zh.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/radial-bar.en.md
  docs/manual/plots/radial-bar.zh.md
Labels: PR: reviewed-approved

#1886 docs: mini plots
  docs/common/chart-options.zh.md
  docs/common/component-progress.zh.md
  docs/manual/plots/gauge.en.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/progress.en.md
  docs/manual/plots/progress.zh.md
  docs/manual/plots/ring-progress.en.md
  docs/manual/plots/ring-progress.zh.md
  docs/manual/plots/tiny-area.en.md
  docs/manual/plots/tiny-area.zh.md
  docs/manual/plots/tiny-column.en.md
  docs/manual/plots/tiny-column.zh.md
  docs/manual/plots/tiny-line.en.md
  docs/manual/plots/tiny-line.zh.md
Labels: PR: partially-approved

#1887 fix: badge img
  README.md
  README.zh-CN.md
Labels: PR: reviewed-approved

#1889 test: coverage up
  __tests__/unit/plots/scatter/regression-line-spec.ts
  __tests__/unit/plots/sunburst/hierarchy/partition-spec.ts
  __tests__/unit/plots/sunburst/hierarchy/util-spec.ts
  src/plots/scatter/util.ts
Labels: PR: partially-approved

#1888 feat/duax: 关闭多个图例
  __tests__/unit/plots/dual-axes/legend-spec.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: partially-approved

#1890 chore: release 2.0.8
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#1891 revert: limitInPlot
  __tests__/bugs/issue-1882-spec.ts
  package.json
  src/core/plot.ts
  src/index.ts
Labels: PR: unreviewed

#1895 chore: 2.0.9
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved

#1897 fix: surge preview in wrong ref
  .github/workflows/preview.yml
Labels: PR: reviewed-approved

#1896 docs: fix docs
  docs/manual/plots/bullet.en.md
  docs/manual/plots/bullet.zh.md
Labels: PR: reviewed-approved

#1900 feat: add g2plot-column plugin link
  docs/manual/plugin.zh.md
Labels: PR: reviewed-approved

#1892 statistic use html-annotation
  __tests__/bugs/issue-1174-spec.ts
  __tests__/unit/plots/gauge/index-spec.ts
  __tests__/unit/plots/gauge/statistic-spec.ts
  __tests__/unit/plots/liquid/statistic-spec.ts
  __tests__/unit/plots/pie/annotation-spec.ts
  __tests__/unit/plots/pie/html-statistic-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/utils/index-spec.ts
  __tests__/unit/plots/pie/utils/statistic-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  __tests__/unit/plots/ring-progress/statistic-spec.ts
  __tests__/unit/utils/kebab-case-spec.ts
  docs/common/component-no-axis.zh.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny.zh.md
  docs/common/component.zh.md
  docs/common/statistic.zh.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/ring-progress.zh.md
  examples/gauge/basic/demo/basic.ts
  examples/liquid/basic/demo/basic.ts
  examples/liquid/basic/demo/style.ts
  examples/pie/basic/demo/basic.ts
  examples/pie/donut/demo/basic.ts
  examples/pie/donut/demo/custom-statistics.ts
  examples/pie/donut/demo/meta.json
  examples/pie/donut/demo/statistics.ts
  src/plots/gauge/adaptor.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
  src/plots/pie/interactions/pie-statistic-action.ts
  src/plots/pie/utils/index.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/index.ts
  src/types/statistic.ts
  src/utils/index.ts
  src/utils/kebab-case.ts
  src/utils/statistic.ts
Labels: PR: partially-approved

#1904 feat: review and modify radial-bar docs
  docs/manual/plots/radial-bar.zh.md
  examples/radial-bar/basic/API.en.md
  examples/radial-bar/basic/API.zh.md
Labels: PR: partially-approved

#1907 feat(default-options): update default option for plots
  src/plots/area/index.ts
  src/plots/histogram/index.ts
  src/plots/line/index.ts
  src/plots/rose/index.ts
Labels: PR: reviewed-approved

#1908 refactor: 文档优优化 - pie radar waterfall
  docs/common/color.en.md
  docs/common/color.zh.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/waterfall.zh.md
  examples/case/line/demo/basic.ts
  examples/case/line/demo/meta.json
  examples/case/line/design.en.md
  examples/case/line/design.zh.md
  examples/case/line/index.en.md
  examples/case/line/index.zh.md
  examples/case/trend/demo/basic.ts
  examples/case/trend/demo/meta.json
  examples/case/trend/index.en.md
  examples/case/trend/index.zh.md
  examples/waterfall/basic/demo/annotation.ts
  src/plots/liquid/shapes/liquid.ts
Labels: PR: reviewed-approved

#1911 docs: 柱形图条形图文档补充
  docs/common/connected-area.en.md
  docs/common/connected-area.zh.md
  docs/common/conversion-tag.en.md
  docs/common/conversion-tag.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
Labels: PR: partially-approved

#1910 Walkthrough demo
  __tests__/bugs/issue-1836-spec.ts
  examples/case/line/demo/meta.json
  examples/column/basic/demo/region-annotation.ts
  examples/gauge/basic/demo/basic.ts
  examples/gauge/basic/demo/complex.ts
  examples/gauge/basic/demo/gradient.ts
  examples/gauge/basic/demo/meta.json
  examples/gauge/basic/demo/single-gradient.ts
  examples/general/annotation/demo/image-annotation.ts
  examples/general/annotation/demo/line-annotation1.ts
  examples/general/theme/demo/custom-theme.ts
  examples/general/theme/demo/meta.json
  src/plots/gauge/adaptor.ts
  src/plots/gauge/index.ts
  src/plots/gauge/shapes/gauge.ts
Labels: PR: unreviewed

#1913 feat: multi layer 支持配置 annotations & label
  __tests__/unit/plots/multi-view/index-spec.ts
  examples/case/multi-views/demo/donut.ts
  examples/case/multi-views/demo/meta.json
  examples/case/multi-views/index.en.md
  examples/case/multi-views/index.zh.md
  src/adaptor/geometries/base.ts
  src/plots/bullet/adaptor.ts
  src/plots/multi-layer/adaptor.ts
  src/plots/multi-layer/types.ts
Labels: PR: partially-approved

#1912 feat: add line type into radial-bar
  __tests__/unit/plots/radial-bar/index-spec.ts
  docs/manual/plots/radial-bar.zh.md
  examples/radial-bar/basic/demo/line.ts
  examples/radial-bar/basic/demo/meta.json
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/types.ts
Labels: PR: partially-approved

#1918 Walkthrough website
  __tests__/unit/plots/liquid/statistic-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/ring-progress/statistic-spec.ts
  __tests__/unit/plots/waterfall/component-spec.ts
  __tests__/unit/utils/measure-text-spec.ts
  examples/case/customize/demo/basic.ts
  examples/case/customize/demo/customize-tooltip.ts
  examples/case/customize/demo/meta.json
  examples/case/customize/design.en.md
  examples/case/customize/design.zh.md
  examples/case/customize/index.en.md
  examples/case/customize/index.zh.md
  examples/case/line/demo/meta.json
  examples/case/line/index.en.md
  examples/case/line/index.zh.md
  examples/case/multi-views/demo/meta.json
  examples/case/multi-views/demo/nobel-prize.ts
  examples/case/multi-views/index.en.md
  examples/case/multi-views/index.zh.md
  examples/case/tooltip/design.en.md
  examples/case/tooltip/design.zh.md
  examples/case/tooltip/index.en.md
  examples/case/tooltip/index.zh.md
  examples/gauge/basic/demo/single-gradient.ts
  examples/liquid/basic/demo/basic.ts
  examples/liquid/basic/demo/meta.json
  examples/liquid/basic/demo/style.ts
  examples/pie/donut/demo/custom-statistics.ts
  examples/pie/donut/demo/meta.json
  examples/tiny/ring-progress/demo/meta.json
  examples/tiny/ring-progress/demo/ring-progress-style.ts
  src/index.ts
  src/plots/liquid/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/ring-progress/adaptor.ts
  src/utils/index.ts
  src/utils/measure-text.ts
  src/utils/statistic.ts
Labels: PR: reviewed-approved

#1921 Walkthrough website
  __tests__/unit/plots/multi-view/index-spec.ts
  examples/case/multi-view/demo/drinks.ts
  examples/case/multi-view/demo/meta.json
  examples/case/multi-view/demo/nobel-prize.ts
  examples/case/multi-view/demo/series-columns.ts
  examples/case/multi-view/index.en.md
  examples/case/multi-view/index.zh.md
  examples/case/multi-views/demo/meta.json
  examples/case/multi-views/index.en.md
  examples/gauge/basic/demo/complex.ts
  examples/gauge/basic/demo/custom-color.ts
  examples/gauge/basic/demo/meta.json
  examples/pie/donut/demo/meta.json
  gatsby-config.js
  src/lab.ts
  src/plots/multi-view/adaptor.ts
  src/plots/multi-view/index.ts
  src/plots/multi-view/types.ts
Labels: PR: unreviewed

#1920 fix(#1909): opacity 配置不生效
  __tests__/bugs/issue-1909-spec.ts
  src/plots/liquid/shapes/liquid.ts
Labels: PR: partially-approved

#1923 Walkthrough demos & fix waterfall yAxis
  __tests__/unit/plots/waterfall/axis-spec.ts
  __tests__/unit/plots/waterfall/component-spec.ts
  examples/case/customize/demo/line-marker.ts
  examples/case/customize/demo/line-style.ts
  examples/case/customize/demo/meta.json
  examples/case/multi-view/demo/meta.json
  examples/line/basic/demo/line-annotation-color.ts
  examples/line/basic/demo/line-annotation.ts
  examples/line/basic/demo/line-smooth.ts
  examples/line/basic/demo/line.ts
  examples/line/basic/demo/meta.json
  examples/line/multiple/demo/line-style.ts
  examples/line/multiple/demo/meta.json
  examples/line/multiple/demo/style-callback.ts
  examples/liquid/basic/demo/meta.json
  examples/pie/basic/demo/meta.json
  examples/pie/donut/demo/statistics.ts
  examples/waterfall/basic/demo/meta.json
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/index.ts
Labels: PR: reviewed-approved

#1922 feat:补充example中柱形图column缺失的设计指引
  examples/column/percent/design.en.md
  examples/column/percent/design.zh.md
  examples/column/range/design.en.md
  examples/column/range/design.zh.md
  examples/radial-bar/basic/design.en.md
  examples/radial-bar/basic/design.zh.md
Labels: PR: reviewed-approved

#1906 docs: 更新manual英文文档
  docs/manual/contact.en.md
  docs/manual/graphic-style.en.md
  docs/manual/plot-api.en.md
  docs/manual/plot-api.zh.md
  docs/manual/plugin.en.md
  docs/manual/upgrade.en.md
Labels: PR: reviewed-approved

#1935 feat: update gatsby-theme-antv version
  gatsby-config.js
  package.json
Labels: PR: reviewed-approved

#1932 feat: 新增百分比面积图
  __tests__/data/area.ts
  __tests__/unit/plots/area/percent-spec.ts
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  examples/area/percent/API.en.md
  examples/area/percent/API.zh.md
  examples/area/percent/demo/basic.ts
  examples/area/percent/demo/meta.json
  examples/area/percent/design.en.md
  examples/area/percent/design.zh.md
  examples/area/percent/index.en.md
  examples/area/percent/index.zh.md
  gatsby-config.js
  src/plots/area/adaptor.ts
  src/plots/area/types.ts
Labels: PR: reviewed-approved

#1936 test: coverage for util
  __tests__/unit/utils/kebab-case-spec.ts
  src/utils/kebab-case.ts
Labels: PR: partially-approved

#1937 docs: 更新升级文档
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved

#1931 refactor(bidirectional)
  __tests__/unit/plots/bidirectional-bar/axis-spec.ts
  __tests__/unit/plots/bidirectional-bar/interaction-spec.ts
  __tests__/unit/plots/bidirectional-bar/layout-spec.ts
  __tests__/unit/plots/bidirectional-bar/utils-spec.ts
  docs/manual/plots/bidirectional-bar.en.md
  docs/manual/plots/bidirectional-bar.zh.md
  examples/bidirectional-bar/basic/API.en.md
  examples/bidirectional-bar/basic/API.zh.md
  examples/bidirectional-bar/basic/demo/basic.ts
  examples/bidirectional-bar/basic/demo/layout.ts
  examples/bidirectional-bar/basic/demo/meta.json
  examples/bidirectional-bar/basic/design.en.md
  examples/bidirectional-bar/basic/design.zh.md
  examples/bidirectional-bar/basic/index.en.md
  examples/bidirectional-bar/basic/index.zh.md
  gatsby-config.js
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/bidirectional-bar/index.ts
  src/plots/bidirectional-bar/utils.ts
  src/types/common.ts
Labels: PR: reviewed-approved

#1919 stock优化
  __tests__/data/stock.ts
  __tests__/unit/plots/stock/tooltip-spec.ts
  src/plots/stock/adaptor.ts
  src/plots/stock/constant.ts
  src/plots/stock/index.ts
Labels: PR: reviewed-approved

#1916 fix: funnel
  __tests__/unit/plots/funnel/basic-spec.ts
  __tests__/unit/plots/funnel/compare-spec.ts
  __tests__/unit/plots/funnel/conversion-tag-spec.ts
  __tests__/unit/plots/funnel/dynamic-height-spec.ts
  __tests__/unit/plots/funnel/index-spec.ts
  __tests__/unit/plots/funnel/label-spec.ts
  __tests__/unit/plots/funnel/tooltip-spec.ts
  examples/funnel/basic/demo/basic-transpose.ts
  examples/funnel/basic/demo/compare-transpose.ts
  examples/funnel/basic/demo/compare.ts
  examples/funnel/basic/demo/dynamic-height-transpose.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/constant.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/dynamic-height.ts
  src/plots/funnel/index.ts
Labels: PR: partially-approved

#1938 chore: only sync gh-pages to Gitee Mirror
  .github/workflows/mirror.yml
  __tests__/unit/plots/multi-view/index-spec.ts
  __tests__/unit/plots/stock/tooltip-spec.ts
Labels: PR: partially-approved

#1939 test(gauge): coverage increase
  __tests__/unit/plots/gauge/shapes/index-spec.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/shapes/gauge.ts
Labels: PR: unreviewed

#1943 Feat/funnel tooltip demo
  examples/case/statistical-charts/demo/funnel.ts
  examples/case/statistical-charts/demo/meta.json
Labels: PR: partially-approved

#1942 docs: 更新manual/plots英文文档
  docs/manual/plots/area.en.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/box.en.md
  docs/manual/plots/funnel.en.md
  docs/manual/plots/liquid.en.md
Labels: PR: reviewed-approved

#1947 fix: remove tiny default formatter & mask in axis not work
  __tests__/bugs/issue-1944-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  src/constant.ts
  src/plots/tiny-column/constants.ts
  src/plots/tiny-line/constants.ts
Labels: PR: partially-approved

#1950 test: coverage for conversion-tag
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/utils/conversion-spec.ts
  src/adaptor/conversion-tag.ts
  src/utils/conversion.ts
Labels: PR: reviewed-approved

#1952 test: fix test error when no network
  __tests__/bugs/issue-292-spec.ts
  __tests__/data/sunburst.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/plots/area/point-spec.ts
  __tests__/unit/plots/heatmap/type-spec.ts
  __tests__/unit/plots/sunburst/change-data-spec.ts
  __tests__/unit/plots/sunburst/index-spec.ts
Labels: PR: partially-approved

#1954 docs: 更新下条形图转化率DEMO的数据顺序
  examples/bar/basic/demo/conversion-tag.ts
Labels: PR: unreviewed

#1958 Fix/duax interaction
  __tests__/unit/plots/dual-axes/color-spec.ts
  __tests__/unit/plots/dual-axes/interaction-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  examples/dual-axes/column-line/demo/column-line.ts
  examples/dual-axes/column-line/demo/column-multi-line.ts
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/column-line/demo/meta.json
  examples/dual-axes/dual-line/demo/dual-multi-line.ts
  examples/dual-axes/dual-line/demo/meta.json
  examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-multi-line.ts
  examples/dual-axes/grouped-column-line/demo/meta.json
  examples/dual-axes/grouped-stacked-line/demo/stacked-grouped-column-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/meta.json
  examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-multi-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-percent-column-line.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/util/legend.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: partially-approved

#1959 chore: release 2.0.10
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#1962 docs: 修复柱形图条形图DEMO中的数据标签遮挡
  examples/bar/grouped/demo/basic.ts
  examples/bar/stacked/demo/basic.ts
  examples/column/grouped/demo/basic.ts
  examples/column/stacked/demo/basic.ts
Labels: PR: partially-approved

#1960 docs: 补充四象限气泡图
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/quadrant-tooltip.ts
Labels: PR: reviewed-approved

#1964 chore: gitee mirror action
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved

#1966 漏斗图 demo 优化 & 迷你缩略图替换
  examples/case/statistical-charts/demo/funnel.ts
  examples/tiny/progress/demo/meta.json
  examples/tiny/progress/demo/progress-style.ts
  examples/tiny/progress/demo/progress.ts
  examples/tiny/ring-progress/demo/meta.json
Labels: PR: partially-approved

#1948 refactor: demo 优化
  docs/common/component-polygon.en.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.en.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny-en.md
  docs/common/component-tiny.zh.md
  docs/common/theme.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/bidirectional-bar.en.md
  docs/manual/plots/bidirectional-bar.zh.md
  docs/manual/plots/box.zh.md
  docs/manual/plots/bullet.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/dual-axes.en.md
  docs/manual/plots/dual-axes.zh.md
  docs/manual/plots/funnel.zh.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/radial-bar.zh.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/stock.zh.md
  docs/manual/plots/waterfall.zh.md
  docs/manual/plots/word-cloud.zh.md
  examples/case/customize/demo/customize-tooltip.ts
  examples/case/customize/demo/line-marker.ts
  examples/case/customize/demo/line-style.ts
  examples/case/customize/demo/line.ts
  examples/case/customize/demo/meta.json
  examples/case/multi-view/demo/series-columns.ts
  examples/case/statistical-charts/demo/line-association.ts
  examples/case/statistical-charts/demo/line.ts
  examples/case/statistical-charts/demo/meta.json
  examples/gauge/basic/demo/meta.json
  examples/general/theme/API.en.md
  examples/general/theme/API.zh.md
  examples/general/theme/demo/custom-theme.ts
  examples/general/theme/demo/dark.ts
  examples/general/theme/demo/meta.json
  examples/general/theme/demo/register-theme.ts
  examples/liquid/basic/demo/meta.json
  examples/liquid/basic/demo/style.ts
Labels: PR: unreviewed

#1972 fix: change the triggering condition
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved

#1967 docs(funnel): 场景漏斗图 DEMO
  examples/bar/basic/demo/meta.json
  examples/case/funnel/demo/funnel.jsx
  examples/case/funnel/demo/meta.json
  examples/case/funnel/index.en.md
  examples/case/funnel/index.zh.md
  examples/column/basic/demo/basic.ts
  examples/column/basic/demo/color.ts
  examples/column/basic/demo/conversion-tag.ts
  examples/column/basic/demo/region-annotation.ts
  examples/column/basic/demo/width.ts
  gatsby-browser.js
  package.json
Labels: PR: partially-approved

#1971 Demo walkthrough 1120
  examples/case/customize/demo/customize-tooltip.ts
  examples/case/customize/demo/line.ts
  examples/case/customize/demo/meta.json
  examples/line/basic/demo/line.ts
Labels: PR: partially-approved

#1974 Demo walkthrough 1121
  examples/column/percent/demo/interaction.ts
  examples/column/percent/demo/meta.json
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/pie-texture.ts
Labels: PR: reviewed-approved

#1976 fix(word-cloud): 修复错误的边界值导致的重叠及间隙过大问题
  __tests__/bugs/issue-1970-spec.ts
  src/plots/word-cloud/index.ts
  src/utils/transform/word-cloud.ts
Labels: PR: reviewed-approved

#1980 refactor(demo): 将 case 案例进行一个归类，重命名为统计场景 & 更新gastby
  examples/case/funnel/demo/meta.json
  examples/case/funnel/index.en.md
  examples/case/funnel/index.zh.md
  examples/case/statistical-charts/index.en.md
  examples/case/statistical-charts/index.zh.md
  examples/case/statistical-scenario/API.en.md
  examples/case/statistical-scenario/API.zh.md
  examples/case/statistical-scenario/demo/funnel.jsx
  examples/case/statistical-scenario/demo/funnel.ts
  examples/case/statistical-scenario/demo/line-association.ts
  examples/case/statistical-scenario/demo/meta.json
  examples/case/statistical-scenario/demo/pie.ts
  examples/case/statistical-scenario/design.en.md
  examples/case/statistical-scenario/design.zh.md
  examples/case/statistical-scenario/index.en.md
  examples/case/statistical-scenario/index.zh.md
  package.json
Labels: PR: partially-approved

#1979 fix: 修复热力图颜色映射错误
  __tests__/unit/plots/heatmap/shape-spec.ts
  src/plots/heatmap/adaptor.ts
  src/plots/heatmap/shapes/circle.ts
  src/plots/heatmap/shapes/square.ts
Labels: PR: reviewed-approved

#1975 docs: demo走查
  examples/bullet/basic/demo/basic.ts
  examples/bullet/basic/demo/color.ts
  examples/bullet/basic/demo/grouped.ts
  examples/bullet/basic/demo/layout.ts
  examples/bullet/basic/demo/stacked.ts
  examples/general/state/demo/meta.json
  examples/heatmap/density/demo/basic.ts
Labels: PR: unreviewed

#1981 fix: 修复 g2plot 文案
  docs/manual/upgrade.en.md
  examples/case/multi-view/design.en.md
  examples/case/multi-view/design.zh.md
  examples/case/statistical-scenario/API.en.md
  examples/case/statistical-scenario/API.zh.md
  examples/case/statistical-scenario/demo/meta.json
  examples/case/statistical-scenario/design.en.md
  examples/case/statistical-scenario/design.zh.md
Labels: PR: reviewed-approved

#1982 fix: 对称条形图 & 迷你折柱面图 demo
  examples/bidirectional-bar/basic/demo/meta.json
  examples/case/statistical-scenario/demo/meta.json
  examples/tiny/tiny-area/demo/area-annotation.ts
  examples/tiny/tiny-area/demo/basic-area.ts
  examples/tiny/tiny-area/demo/filled-area.ts
  examples/tiny/tiny-area/demo/meta.json
  examples/tiny/tiny-column/demo/basic-column.ts
  examples/tiny/tiny-column/demo/column-annotation.ts
  examples/tiny/tiny-column/demo/meta.json
  examples/tiny/tiny-line/demo/basic-line.ts
  examples/tiny/tiny-line/demo/line-annotation.ts
  examples/tiny/tiny-line/demo/meta.json
Labels: PR: partially-approved

#1984 chore: 完善单测,去除only
  __tests__/unit/plots/heatmap/shape-spec.ts
Labels: PR: reviewed-approved

#1986 fix: 修复主题切换不生效问题
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/column/index-spec.ts
  src/adaptor/conversion-tag.ts
  src/adaptor/geometries/interval.ts
  src/plots/column/adaptor.ts
Labels: PR: partially-approved

#1987 docs: 调整色值
  examples/heatmap/basic/demo/calendar.ts
  examples/heatmap/basic/demo/shape.ts
  examples/heatmap/basic/demo/size.ts
  examples/heatmap/density/demo/basic.ts
Labels: PR: reviewed-approved

#1985 Demo/multi view
  examples/case/customize/demo/meta.json
  examples/case/multi-view/demo/nobel-prize.ts
  examples/case/multi-view/demo/series-columns.ts
  examples/case/multi-view/design.en.md
  examples/case/multi-view/design.zh.md
  examples/case/multi-view/index.en.md
  examples/case/multi-view/index.zh.md
  examples/case/statistical-scenario/demo/meta.json
Labels: PR: reviewed-approved

#1989 fix: 自定义图形颜色和主题切换
  examples/plugin/basic/demo/hill-column.ts
  examples/plugin/basic/demo/meta.json
Labels: PR: partially-approved

#1988 fix(demo): fix line, area demo
  examples/area/basic/demo/basic-slider.ts
  examples/line/basic/demo/line-point-style.ts
  examples/line/basic/demo/meta.json
Labels: PR: reviewed-approved

#1991 refactor(demo): 更新 demo 截图
  examples/column/percent/demo/meta.json
Labels: PR: unreviewed

#1992 Feat/duax annotation
  __tests__/unit/plots/dual-axes/annotation-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  docs/manual/plots/dual-axes.en.md
  docs/manual/plots/dual-axes.zh.md
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/column-line/demo/demo-more-1.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: partially-approved

#1990 chore: release 2.2.11
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#1993 Refactor trend chart
  examples/case/statistical-scenario/demo/line-association.ts
  examples/case/statistical-scenario/demo/meta.json
  examples/case/statistical-scenario/demo/trend.jsx
Labels: PR: partially-approved

#1998 daily walkthrough
  examples/case/customize/demo/customize-tooltip.ts
  package.json
  site/pages/index.zh.tsx
Labels: PR: partially-approved

#1999 docs: theme & interactions
  docs/common/component-polygon.en.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.en.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny-en.md
  docs/common/component-tiny.zh.md
  docs/common/interactions.en.md
  docs/common/interactions.zh.md
  docs/common/theme.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/bidirectional-bar.en.md
  docs/manual/plots/bidirectional-bar.zh.md
  docs/manual/plots/box.zh.md
  docs/manual/plots/bullet.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/dual-axes.en.md
  docs/manual/plots/dual-axes.zh.md
  docs/manual/plots/funnel.zh.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/histogram.en.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/radial-bar.zh.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/stock.en.md
  docs/manual/plots/stock.zh.md
  docs/manual/plots/waterfall.zh.md
  docs/manual/plots/word-cloud.zh.md
  examples/general/annotation/demo/image-annotation.ts
  examples/general/theme/API.en.md
  examples/general/theme/API.zh.md
  examples/pie/basic/demo/basic.ts
Labels: PR: partially-approved

#1994 fix: 只允许在基础柱形图和条形图上开启转化率组件
  __tests__/unit/adaptor/conversion-tag-spec.ts
  src/adaptor/conversion-tag.ts
  src/plots/column/adaptor.ts
Labels: PR: partially-approved

#2002 feat: 打开 limit in plot 配置
  __tests__/bugs/issue-1882-spec.ts
  __tests__/unit/core/index-spec.ts
  src/core/plot.ts
  src/types/common.ts
Labels: PR: reviewed-approved

#2007 fix(line): do not set default range as [0, 1]
  __tests__/unit/plots/area/index-spec.ts
  __tests__/unit/plots/line/index-spec.ts
  examples/area/basic/demo/basic-gradients.ts
  examples/area/basic/demo/basic.ts
  src/constant.ts
  src/plots/line/adaptor.ts
Labels: PR: partially-approved

#2009 feat: auto set limitInPlot based on yAxis config
  __tests__/bugs/issue-1882-spec.ts
  __tests__/unit/plots/area/limit-in-plot-spec.ts
  __tests__/unit/plots/bar/limit-in-plot-spec.ts
  __tests__/unit/plots/column/limit-in-plot-spec.ts
  __tests__/unit/plots/line/limit-in-plot-spec.ts
  package.json
  src/adaptor/common.ts
  src/plots/area/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/line/adaptor.ts
Labels: PR: partially-approved

#2012 fix: auto adjust scale min to zero for column/bar
  __tests__/unit/plots/bar/y-meta-min-max-spec.ts
  __tests__/unit/plots/column/y-meta-min-max-spec.ts
  src/plots/column/adaptor.ts
Labels: PR: reviewed-approved

#2010 feat: scatter regression 新增 top 配置
  __tests__/unit/plots/scatter/regression-line-spec.ts
  docs/common/chart-options.en.md
  docs/common/chart-options.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  src/plots/scatter/adaptor.ts
  src/plots/scatter/types.ts
Labels: PR: reviewed-approved

#2013 fix(y-scale): update y scale min, max
  __tests__/unit/utils/data-spec.ts
  src/utils/data.ts
Labels: PR: reviewed-approved

#2011 chore: release 2.2.12
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2017 fix(word-cloud): 修复字体权重值都相同时，不显示的问题
  __tests__/unit/plots/word-cloud/utils-spec.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved

#2022 fix(tiny): 迷你三个图的 yAxis.min/max 设置不生效
  __tests__/bugs/issue-2021-spec.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/constants.ts
Labels: PR: partially-approved

#2020 fix: 双轴图和对称条形图的 limitinplot
  __tests__/unit/adaptor/common-spec.ts
  __tests__/unit/plots/bidirectional-bar/limit-in-plot-spec.ts
  __tests__/unit/plots/dual-axes/limit-in-plot-spec.ts
  src/adaptor/common.ts
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: partially-approved

#2019 fix: 修复散点图 tooltip 默认 fields 丢失
  __tests__/bugs/issue-2015-spec.ts
  __tests__/unit/plots/scatter/default-config-spec.ts
  __tests__/unit/plots/scatter/legend-spec.ts
  __tests__/unit/plots/scatter/tooltip-spec.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
Labels: PR: reviewed-approved

#2024 chore: release 2.2.13
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2027 docs: 新增网格配置demo
  examples/line/multiple/demo/line-grid.ts
  examples/line/multiple/demo/meta.json
Labels: PR: reviewed-approved

#2033 fix: 双轴图 label.formatter
  __tests__/bugs/issue-2021-spec.ts
  __tests__/unit/plots/dual-axes/column-spec.ts
  __tests__/unit/plots/dual-axes/interaction-spec.ts
  __tests__/unit/plots/funnel/compare-spec.ts
  __tests__/unit/plots/gauge/shapes/index-spec.ts
  __tests__/unit/plots/pie/html-statistic-spec.ts
  examples/dual-axes/dual-line/demo/custom-dual-line.ts
  src/plots/dual-axes/util/geometry.ts
Labels: PR: partially-approved
