Repository antvis/G2Plot, pull requests merged in 2020-10, with the labels that each got.

#1682 fix: column和bar默认type为cat
  __tests__/data/sales.ts
  __tests__/unit/plots/bar/axis-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/column/axis-spec.ts
  __tests__/unit/plots/column/index-spec.ts
  src/plots/bar/index.ts
  src/plots/column/index.ts
Labels: PR: partially-approved, bug

#1686 feat(axis): add type config axis, it will picked into scale config
  __tests__/bugs/issue-968-spec.ts
  src/constant.ts
  src/types/axis.ts
Labels: PR: unreviewed, enhancement

#1688 fix(dual-axes): 双轴图问题走查
  __tests__/bugs/issue-1684-spec.ts
  __tests__/unit/plots/dual-axes/column-spec.ts
  __tests__/unit/plots/dual-axes/default-options-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  examples/area/basic/demo/basic-gradients.ts
  examples/area/basic/demo/basic-slider.ts
  examples/area/basic/demo/basic.ts
  examples/column/percent/demo/basic.ts
  examples/dual-axes/column-line/demo/column-line.ts
  examples/dual-axes/column-line/demo/column-multi-line.ts
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/column-line/demo/demo-more-1.ts
  examples/dual-axes/dual-line/demo/custom-dual-line.ts
  examples/dual-axes/dual-line/demo/dual-line.ts
  examples/dual-axes/dual-line/demo/dual-multi-line.ts
  examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-multi-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-multi-line.ts
  examples/general/theme/demo/dark.ts
  examples/line/basic/demo/line-slider.ts
  examples/line/basic/demo/line.ts
  src/core/plot.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/constant.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/util/legend.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: unreviewed, bug

#1689 fix(template): remove regex usage of lookbehind assertions
  __tests__/unit/utils/template-spec.ts
  src/utils/template.ts
Labels: PR: reviewed-approved, bug

#1691 chore: v2.0.2
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, chore

#1694 fix(website): style for bk image
  site/pages/index.less
Labels: PR: partially-approved, bug

#1693 fix(issue-1174): pie statistics content formatter does not work
  __tests__/bugs/issue-1174-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  examples/pie/donut/demo/statistics.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interaction/pie-statistic-action.ts
Labels: PR: unreviewed, bug

#1695 build(webpack): update webpack loader configure, to avoid umd bundle error
  package.json
  webpack.config.js
Labels: PR: partially-approved, build

#1680 docs(rose): 设置玫瑰图label的layout类型为limit-in-shape
  __tests__/unit/plots/rose/label-spec.ts
  src/plots/rose/adaptor.ts
  src/plots/rose/index.ts
Labels: PR: partially-approved, documentation

#1704 docs: add column slider scrollbar demo
  examples/column/basic/demo/meta.json
  examples/column/basic/demo/scrollbar.ts
  examples/column/basic/demo/slider.ts
Labels: PR: partially-approved, documentation

#1697 feat(waterfall): 初始化瀑布图
  __tests__/unit/plots/waterfall/annotation-spec.ts
  __tests__/unit/plots/waterfall/axis-spec.ts
  __tests__/unit/plots/waterfall/index-spec.ts
  __tests__/unit/plots/waterfall/label-spec.ts
  __tests__/unit/plots/waterfall/shape-spec.ts
  __tests__/unit/plots/waterfall/style-spec.ts
  __tests__/unit/plots/waterfall/utils-spec.ts
  examples/waterfall/basic/API.en.md
  examples/waterfall/basic/API.zh.md
  examples/waterfall/basic/demo/absolute-label.ts
  examples/waterfall/basic/demo/basic.ts
  examples/waterfall/basic/demo/custom-color.ts
  examples/waterfall/basic/demo/meta.json
  examples/waterfall/basic/design.en.md
  examples/waterfall/basic/design.zh.md
  examples/waterfall/basic/index.en.md
  examples/waterfall/basic/index.zh.md
  gatsby-config.js
  src/adaptor/geometries/base.ts
  src/index.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/constants.ts
  src/plots/waterfall/index.ts
  src/plots/waterfall/shape.ts
  src/plots/waterfall/types.ts
  src/plots/waterfall/utils.ts
Labels: PR: unreviewed, WIP, enhancement

#1705 feat(line): line area support isStack options
  __tests__/bugs/issue-968-spec.ts
  __tests__/unit/plots/area/stack-spec.ts
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/plots/dual-axes/stack-spec.ts
  __tests__/unit/plots/line/stack-spec.ts
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  package.json
  src/plots/area/adaptor.ts
  src/plots/area/index.ts
  src/plots/area/types.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/geometry.ts
  src/plots/line/adaptor.ts
  src/plots/line/index.ts
  src/plots/line/types.ts
Labels: PR: partially-approved, enhancement

#1711 docs: 优化升级文档
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved, documentation

#1707 feat(tiny-area): update tiny area default color
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/index.ts
Labels: PR: reviewed-approved, enhancement

#1715 fix: update axis tickMethod type
  docs/common/axis.en.md
  docs/common/axis.zh.md
  src/types/axis.ts
Labels: PR: partially-approved, bug

#1713 fix: v1 label formatter 无效
  __tests__/unit/utils/transform-label-spec.ts
  __tests__/unit/utils/transform-tooltip-spec.ts
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  src/adaptor/common.ts
  src/plots/area/adaptor.ts
  src/plots/box/adaptor.ts
  src/plots/bullet/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/heatmap/adaptor.ts
  src/plots/histogram/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/rose/adaptor.ts
  src/plots/scatter/adaptor.ts
  src/plots/stock/adaptor.ts
  src/plots/sunburst/adaptor.ts
  src/plots/waterfall/adaptor.ts
  src/types/label.ts
  src/types/tooltip.ts
  src/utils/index.ts
  src/utils/label.ts
  src/utils/tooltip.ts
Labels: PR: unreviewed, bug

#1714 bugfix: 走查
  __tests__/bugs/issue-1708-spec.ts
  __tests__/unit/plots/bar/legend-spec.ts
  __tests__/unit/plots/column/legend-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/plots/area/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/ring-progress/adaptor.ts
Labels: PR: unreviewed, bugfix

#1719 fix(types): 修复 瀑布图 类型定义命名问题
  src/index.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/index.ts
  src/plots/waterfall/types.ts
Labels: PR: partially-approved

#1720 feat(mapping): color shape size 字段只去对应的字段即可
  __tests__/unit/adaptor/geometries/base-spec.ts
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  __tests__/unit/plots/scatter/size-spec.ts
  __tests__/unit/plots/waterfall/index-spec.ts
  src/adaptor/geometries/base.ts
  src/plots/waterfall/adaptor.ts
Labels: PR: partially-approved, enhancement

#1721 v2.0.3
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#1725 feat(demo): 瀑布图添加标注demo
  examples/waterfall/basic/demo/annotation.ts
  examples/waterfall/basic/demo/meta.json
Labels: PR: reviewed-approved, enhancement

#1731 refactor: 去掉histogram的data-set
  __tests__/unit/utils/transform/histogram-spec.ts
  src/plots/histogram/adaptor.ts
  src/utils/transform/histogram.ts
Labels: PR: reviewed-approved, refactor

#1733 docs: 升级指南表格化
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved, documentation

#1730 feat: tooltip, label 增加 formatter 能力
  __tests__/unit/plots/radar/label-spec.ts
  __tests__/unit/plots/radar/legend-spec.ts
  __tests__/unit/plots/radar/tooltip-spec.ts
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  src/adaptor/common.ts
  src/plots/bar/index.ts
  src/plots/column/index.ts
  src/plots/radar/adaptor.ts
  src/types/tooltip.ts
  src/utils/label.ts
  src/utils/percent-tooltip.ts
  src/utils/tooltip.ts
Labels: PR: reviewed-approved, enhancement

#1734 fix(404): link 404 on index page
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#1735 chore: correct apiKey for search
  gatsby-config.js
Labels: PR: reviewed-approved, chore

#1732 refactor(word-cloud): remove data set for word cloud
  __tests__/unit/utils/transform/word-cloud-spec.ts
  src/plots/word-cloud/utils.ts
  src/utils/transform/word-cloud.ts
Labels: PR: reviewed-approved, refactor

#1739 feat: 旭日图移除 DataSet
  package.json
  src/plots/sunburst/hierarchy/partition.ts
  src/plots/sunburst/hierarchy/treemap.ts
  src/plots/sunburst/hierarchy/util.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
Labels: PR: unreviewed, enhancement

#1742 Feat gallery
  __tests__/unit/plots/line/interaction-spec.ts
  __tests__/unit/plots/line/point-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  examples/gallery/trend/demo/basic.ts
  examples/gallery/trend/demo/mobile.ts
  src/adaptor/geometries/point.ts
  src/plots/line/index.ts
  src/plots/line/interactions/index.ts
  src/plots/line/interactions/marker-active.ts
  src/plots/pie/index.ts
  src/plots/pie/interactions/index.ts
  src/plots/pie/interactions/pie-legend-action.ts
  src/plots/pie/interactions/pie-statistic-action.ts
Labels: PR: partially-approved

#1741 docs: legend -> lengend , Unexpected semicolon
  docs/common/legend.en.md
  docs/common/legend.zh.md
Labels: PR: reviewed-approved, documentation

#1728 refactor: remove data-set dependence
  __tests__/unit/utils/transform/histogram-spec.ts
  __tests__/unit/utils/transform/percent-spec.ts
  __tests__/unit/utils/transform/word-cloud-spec.ts
  package.json
  src/plots/column/adaptor.ts
  src/plots/column/utils.ts
  src/plots/histogram/adaptor.ts
  src/plots/stock/adaptor.ts
  src/plots/sunburst/hierarchy/partition.ts
  src/plots/sunburst/hierarchy/treemap.ts
  src/plots/sunburst/hierarchy/util.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/utils.ts
  src/utils/transform/histogram.ts
  src/utils/transform/percent.ts
  src/utils/transform/word-cloud.ts
Labels: PR: unreviewed, refactor

#1745 chore(word-cloud): 主要完善词云图的测试用例
  __tests__/unit/utils/transform/word-cloud-spec.ts
  src/plots/word-cloud/shapes/word-cloud.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
  src/utils/transform/word-cloud.ts
Labels: PR: reviewed-approved, chore

#1747 chore: v2.0.4
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, chore

#1752 feat: heatmap
  __tests__/unit/plots/heatmap/axis-spec.ts
  __tests__/unit/plots/heatmap/calendar-spec.ts
  __tests__/unit/plots/heatmap/shape-spec.ts
  __tests__/unit/plots/heatmap/size-spec.ts
  __tests__/unit/plots/heatmap/type-spec.ts
  src/plots/heatmap/adaptor.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/shapes/boundary-polygon.ts
  src/plots/heatmap/types.ts
Labels: PR: reviewed-approved

#1759 fix(1758): 面积图 line.color 设置不生效的问题
  __tests__/bugs/issue-1758-spec.ts
  src/plots/tiny-area/index.ts
Labels: PR: partially-approved

#1760 docs: 补充热力图 demos
  __tests__/unit/plots/heatmap/calendar-spec.ts
  __tests__/unit/plots/heatmap/shape-spec.ts
  __tests__/unit/plots/heatmap/size-spec.ts
  __tests__/unit/plots/heatmap/type-spec.ts
  examples/heatmap/basic/API.en.md
  examples/heatmap/basic/API.zh.md
  examples/heatmap/basic/demo/basic.ts
  examples/heatmap/basic/demo/calendar.ts
  examples/heatmap/basic/demo/meta.json
  examples/heatmap/basic/demo/shape.ts
  examples/heatmap/basic/demo/size.ts
  examples/heatmap/basic/design.en.md
  examples/heatmap/basic/design.zh.md
  examples/heatmap/basic/index.en.md
  examples/heatmap/basic/index.zh.md
  examples/heatmap/density/API.en.md
  examples/heatmap/density/API.zh.md
  examples/heatmap/density/demo/basic.ts
  examples/heatmap/density/demo/meta.json
  examples/heatmap/density/design.en.md
  examples/heatmap/density/design.zh.md
  examples/heatmap/density/index.en.md
  examples/heatmap/density/index.zh.md
  gatsby-config.js
  src/plots/heatmap/adaptor.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/shapes/boundary-polygon.ts
  src/plots/heatmap/shapes/circle.ts
  src/plots/heatmap/shapes/square.ts
  src/plots/heatmap/types.ts
  src/types/index.ts
  src/types/tuple.ts
Labels: PR: unreviewed

#1763 fix: formatter 样式丢失
  __tests__/bugs/issue-1757-spec.ts
  __tests__/unit/plots/column/percent-spec.ts
  src/utils/tooltip.ts
Labels: PR: reviewed-approved

#1764 fix(1761): 辅助 geometry 的 color 样式跟随主元素的 color 配置
  __tests__/bugs/issue-1758-spec.ts
  __tests__/bugs/issue-1761-spec.ts
  src/plots/area/adaptor.ts
  src/plots/line/adaptor.ts
Labels: PR: partially-approved

#1766 fix: 订正双轴图&漏斗图文档
  examples/dual-axes/column-line/API.en.md
  examples/dual-axes/column-line/API.zh.md
  examples/funnel/basic/API.en.md
  examples/funnel/basic/API.zh.md
Labels: PR: reviewed-approved

#1762 fix(word-cloud): fix tooltip and add demo for custom tooltip
  __tests__/bugs/issue-1754-spec.ts
  __tests__/unit/plots/word-cloud/color-spec.ts
  __tests__/unit/plots/word-cloud/style-spec.ts
  __tests__/unit/utils/transform/word-cloud-spec.ts
  docs/manual/plots/word-cloud.en.md
  docs/manual/plots/word-cloud.zh.md
  examples/word-cloud/basic/API.en.md
  examples/word-cloud/basic/API.zh.md
  examples/word-cloud/basic/demo/color-field.ts
  examples/word-cloud/basic/demo/custom-tooltip.ts
  examples/word-cloud/basic/demo/meta.json
  package.json
  src/plots/word-cloud/adaptor.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/shapes/word-cloud.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
  src/utils/transform/word-cloud.ts
Labels: PR: reviewed-approved

#1765 feat: add lab domain
  __tests__/unit/lab-spec.ts
  src/index.ts
  src/lab.ts
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/index.ts
  src/plots/radial-bar/types.ts
Labels: PR: partially-approved

#1771 fix(point-shape): 修复 point 的 shape 映射
  src/adaptor/geometries/point.ts
  src/plots/line/adaptor.ts
Labels: PR: reviewed-approved

#1772 feat: 迁移转化率组件
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/core/index-spec.ts
  examples/bar/basic/demo/conversion-tag.ts
  examples/bar/basic/demo/meta.json
  examples/column/basic/demo/conversion-tag.ts
  examples/column/basic/demo/meta.json
  src/adaptor/common.ts
  src/adaptor/conversion-tag.ts
  src/core/plot.ts
  src/plots/bar/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
  src/types/annotation.ts
Labels: PR: partially-approved

#1773 feat: 补充自定义 Tooltip
  examples/gallery/tooltip/demo/basic.ts
  examples/gallery/tooltip/demo/meta.json
  examples/gallery/tooltip/index.en.md
  examples/gallery/tooltip/index.zh.md
Labels: PR: reviewed-approved

#1776 fix: line-column legend color & custom legend
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/plots/funnel/compare-spec.ts
  examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/legend.ts
Labels: PR: partially-approved

#1774 feat(tooltip): add tooltip fields, formatter
  __tests__/bugs/issue-1757-spec.ts
  __tests__/unit/plots/radar/tooltip-spec.ts
  __tests__/unit/utils/tooltip-spec.ts
  __tests__/unit/utils/transform-tooltip-spec.ts
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  src/adaptor/common.ts
  src/adaptor/geometries/area.ts
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/interval.ts
  src/adaptor/geometries/line.ts
  src/adaptor/geometries/point.ts
  src/adaptor/geometries/polygon.ts
  src/plots/box/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/stock/adaptor.ts
  src/types/attr.ts
  src/types/tooltip.ts
  src/utils/index.ts
  src/utils/tooltip.ts
Labels: PR: partially-approved

#1777 demo 更新(雷达图 & 瀑布图)
  examples/radar/basic/demo/area-alternate-grid.ts
  examples/radar/basic/demo/area-grid.ts
  examples/radar/basic/demo/area.ts
  examples/radar/basic/demo/line-alternate-grid.ts
  examples/radar/basic/demo/line-grid.ts
  examples/radar/basic/demo/line.ts
  examples/radar/basic/demo/meta.json
  examples/radar/basic/demo/series.ts
  examples/waterfall/basic/demo/absolute-label.ts
  examples/waterfall/basic/demo/annotation.ts
  src/plots/radar/index.ts
Labels: PR: partially-approved

#1780 chore: test coverage
  __tests__/unit/plots/waterfall/state-sepc.ts
  package.json
  src/plots/radar/index.ts
  src/plots/radar/interactions/index.ts
  src/plots/radar/interactions/radar-tooltip-action.ts
Labels: PR: partially-approved

#1781 refactor: demo 走查
  examples/pie/basic/demo/basic.ts
  examples/pie/basic/demo/legend-interaction.ts
  examples/pie/basic/demo/outer-label.ts
  examples/pie/basic/demo/spider-label.ts
  examples/pie/donut/demo/basic.ts
  examples/pie/donut/demo/statistics.ts
  examples/waterfall/basic/demo/annotation.ts
  examples/waterfall/basic/demo/custom-color.ts
  examples/waterfall/basic/demo/meta.json
Labels: PR: partially-approved

#1782 fix(word-cloud): 修复tooltip小圆点的颜色不显示
  __tests__/bugs/issue-1754-spec.ts
  examples/word-cloud/basic/demo/custom-tooltip.ts
  src/plots/word-cloud/index.ts
Labels: PR: partially-approved

#1783 fix: 修复bullet的demo写错问题
  examples/bullet/basic/demo/basic.ts
Labels: PR: reviewed-approved

#1784 fix: demo style
  __tests__/bugs/issue-1761-spec.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/plots/area/line-spec.ts
  __tests__/unit/plots/area/point-spec.ts
  __tests__/unit/plots/area/stack-spec.ts
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/plots/gauge/index-spec.ts
  __tests__/unit/plots/line/stack-spec.ts
  examples/area/stacked/demo/basic.ts
  examples/gauge/basic/demo/basic.ts
  examples/gauge/basic/demo/complex.ts
  examples/line/basic/demo/line-annotation-color.ts
  examples/line/multiple/demo/color-callback.ts
  examples/line/multiple/demo/line-color.ts
  examples/line/multiple/demo/line-large-data.ts
  examples/line/multiple/demo/line-multiple.ts
  examples/line/multiple/demo/line-style.ts
  examples/line/multiple/demo/marker-active.ts
  examples/liquid/basic/demo/basic.ts
  examples/liquid/basic/demo/style.ts
  site/pages/index.less
  src/adaptor/geometries/base.ts
  src/plots/area/index.ts
  src/plots/gauge/adaptor.ts
  src/plots/line/index.ts
Labels: PR: unreviewed

#1779 fix: adjust default column width ratio
  examples/bar/basic/demo/conversion-tag.ts
  examples/column/basic/demo/conversion-tag.ts
  src/adaptor/conversion-tag.ts
  src/plots/bar/index.ts
  src/plots/column/index.ts
Labels: PR: partially-approved

#1785 fix(tooltip): 走查 tooltip 实现逻辑
  __tests__/bugs/issue-1754-spec.ts
  __tests__/unit/adaptor/geometries/base-spec.ts
  __tests__/unit/plots/dual-axes/stack-spec.ts
  __tests__/unit/utils/tooltip-spec.ts
  package.json
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/point.ts
  src/index.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/scatter/adaptor.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/index.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/types.ts
  src/utils/tooltip.ts
Labels: PR: unreviewed

#1786 chore: changelog
  CHANGELOG.md
Labels: PR: unreviewed

#1790 refactor(bullet): 调整 bullet 的 style api
  __tests__/unit/plots/bullet/style-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
  src/plots/bullet/types.ts
Labels: PR: reviewed-approved

#1788 fix(line): when data all gt 0, or lt 0, set the default min/max
  __tests__/bugs/issue-1754-spec.ts
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/column/percent-spec.ts
  __tests__/unit/plots/line/y-meta-min-max-spec.ts
  __tests__/unit/utils/data-spec.ts
  __tests__/unit/utils/transform/histogram-spec.ts
  src/adaptor/geometries/line.ts
  src/constant.ts
  src/plots/gauge/adaptor.ts
  src/plots/heatmap/index.ts
  src/plots/line/index.ts
  src/plots/sunburst/adaptor.ts
  src/plots/tiny-area/index.ts
  src/types/axis.ts
  src/types/common.ts
  src/types/index.ts
  src/types/meta.ts
  src/utils/data.ts
  src/utils/transform/percent.ts
Labels: PR: partially-approved

#1792 feat(gauge): add indicator = false, to hide the indicator
  __tests__/unit/plots/gauge/index-spec.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/types.ts
Labels: PR: partially-approved

#1795 Fix typos
  src/plots/liquid/shapes/liquid.ts
Labels: PR: reviewed-approved

#1793 Demo 走查之双轴图&漏斗图&进度环图&进度条图
  examples/dual-axes/column-line/demo/column-line.ts
  examples/dual-axes/column-line/demo/column-multi-line.ts
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/dual-line/demo/custom-dual-line.ts
  examples/dual-axes/dual-line/demo/dual-line.ts
  examples/dual-axes/dual-line/demo/dual-multi-line.ts
  examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-multi-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-multi-line.ts
  examples/funnel/basic/demo/basic-transpose.ts
  examples/funnel/basic/demo/basic.ts
  examples/funnel/basic/demo/compare-transpose.ts
  examples/funnel/basic/demo/compare.ts
  examples/funnel/basic/demo/dynamic-height-transpose.ts
  examples/funnel/basic/demo/dynamic-height.ts
  examples/progress/basic/demo/progress-style-callback.ts
  examples/progress/basic/demo/progress-style.ts
  examples/progress/basic/demo/progress-width.ts
  examples/ring-progress/basic/demo/meta.json
  examples/ring-progress/basic/demo/ring-progress-radius.ts
  examples/ring-progress/basic/demo/ring-progress-style-callback.ts
  examples/ring-progress/basic/demo/ring-progress-style.ts
  examples/ring-progress/basic/demo/ring-progress.ts
  src/plots/dual-axes/index.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/index.ts
Labels: PR: partially-approved

#1794 docs: 去除重复图表
  examples/bar/range/demo/basic.ts
  examples/bar/range/demo/label.ts
  examples/bar/range/demo/meta.json
  examples/column/range/demo/basic.ts
  examples/column/range/demo/label.ts
  examples/column/range/demo/meta.json
  examples/scatter/basic/demo/axis-right.ts
  examples/scatter/basic/demo/basic.ts
  examples/scatter/basic/demo/color-mapping.ts
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/size.ts
  src/plots/scatter/index.ts
  src/plots/scatter/types.ts
Labels: PR: reviewed-approved

#1798 docs: 补充 annotations api
  docs/common/annotations.en.md
  docs/common/annotations.zh.md
  docs/common/component-no-axis.en.md
  docs/common/component-no-axis.zh.md
  docs/common/component-polygon.en.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.en.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny-en.md
  docs/common/component-tiny.zh.md
  docs/common/component.en.md
  docs/common/component.zh.md
Labels: PR: reviewed-approved

#1802 fix: correct spelling
  examples/general/annotation/index.en.md
Labels: PR: reviewed-approved

#1796 fix: 修复 sunburst tooltip
  __tests__/unit/plots/sunburst/index-spec.ts
  examples/sunburst/basic/demo/basic.ts
  examples/sunburst/basic/demo/reflect.ts
  src/plots/sunburst/index.ts
  src/plots/sunburst/utils.ts
Labels: PR: unreviewed

#1803 feat: 基于 annotation shape 实现 regression line
  __tests__/unit/plots/scatter/regression-line-spec.ts
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
  examples/scatter/basic/demo/line.ts
  examples/scatter/basic/demo/meta.json
  package.json
  src/plots/scatter/adaptor.ts
  src/plots/scatter/annotations/path.ts
  src/plots/scatter/types.ts
  src/utils/index.ts
  src/utils/path.ts
Labels: PR: reviewed-approved

#1809 fix: correct spelling for "default"
  docs/common/meta.en.md
Labels: PR: reviewed-approved

#1808 fix: column/bar/histogram/stock demo 修复"
  __tests__/unit/plots/bar/legend-spec.ts
  __tests__/unit/plots/column/legend-spec.ts
  __tests__/unit/plots/stock/legend-spec.ts
  examples/bar/basic/demo/basic.ts
  examples/bar/basic/demo/color.ts
  examples/bar/basic/demo/label.ts
  examples/bar/basic/demo/meta.json
  examples/bar/basic/demo/width.ts
  examples/bar/grouped/demo/basic.ts
  examples/bar/grouped/demo/meta.json
  examples/bar/percent/demo/basic.ts
  examples/bar/percent/demo/meta.json
  examples/column/basic/demo/basic.ts
  examples/column/basic/demo/color.ts
  examples/column/basic/demo/label.ts
  examples/column/basic/demo/meta.json
  examples/column/basic/demo/region-annotation.ts
  examples/column/basic/demo/width.ts
  examples/column/grouped/demo/basic.ts
  examples/column/grouped/demo/margin.ts
  examples/column/grouped/demo/meta.json
  examples/column/percent/demo/basic.ts
  examples/column/percent/demo/meta.json
  examples/column/stacked/demo/basic.ts
  examples/column/stacked/demo/label.ts
  examples/column/stacked/demo/meta.json
  examples/histogram/basic/demo/meta.json
  examples/stock/basic/demo/meta.json
  src/plots/bar/index.ts
  src/plots/column/index.ts
  src/plots/histogram/index.ts
  src/plots/stock/adaptor.ts
  src/plots/stock/index.ts
Labels: PR: partially-approved

#1810 fix: pie annotation 默认关闭 text 的动画
  __tests__/unit/plots/pie/index-spec.ts
  src/plots/pie/index.ts
Labels: PR: reviewed-approved

#1812 fix: correct spelling for Configuration
  docs/common/meta.en.md
Labels: PR: reviewed-approved

#1746 feat: 对称条形图（Bi-directional）
  __tests__/data/bi-directional.ts
  __tests__/unit/plots/bidirectional-bar/axis-spec.ts
  __tests__/unit/plots/bidirectional-bar/data-spec.ts
  __tests__/unit/plots/bidirectional-bar/index-spec.ts
  __tests__/unit/plots/bidirectional-bar/label-spec.ts
  __tests__/unit/plots/bidirectional-bar/layout-spec.ts
  __tests__/unit/plots/bidirectional-bar/legend-spec.ts
  __tests__/unit/plots/bidirectional-bar/style-spec.ts
  src/index.ts
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/bidirectional-bar/constant.ts
  src/plots/bidirectional-bar/index.ts
  src/plots/bidirectional-bar/types.ts
  src/plots/bidirectional-bar/utils.ts
Labels: PR: partially-approved, enhancement

#1805 fix(word-cloud): 修复重复渲染动画卡顿
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/word-cloud/utils-spec.ts
  examples/word-cloud/basic/demo/basic.ts
  examples/word-cloud/basic/demo/color-field.ts
  examples/word-cloud/basic/demo/custom-tooltip.ts
  examples/word-cloud/basic/demo/image-mask-base64.ts
  examples/word-cloud/basic/demo/image-mask.ts
  examples/word-cloud/basic/demo/interaction.ts
  examples/word-cloud/basic/demo/placement-strategy.ts
  examples/word-cloud/basic/demo/same-place.ts
  src/core/plot.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved

#1816 feat: add axis base, exponent option to scale
  src/constant.ts
Labels: PR: partially-approved

#1811 fix: docs
  docs/common/legend.en.md
  docs/common/legend.zh.md
  examples/rose/grouped/demo/basic.ts
  examples/rose/grouped/demo/meta.json
  examples/rose/stacked/demo/basic.ts
  examples/rose/stacked/demo/meta.json
  examples/sunburst/basic/demo/meta.json
  examples/word-cloud/basic/demo/basic.ts
  examples/word-cloud/basic/demo/custom-tooltip.ts
  examples/word-cloud/basic/demo/interaction.ts
  examples/word-cloud/basic/demo/meta.json
  src/plots/box/index.ts
Labels: PR: reviewed-approved

#1824 refactor: demo 走查
  examples/radar/basic/demo/basic.ts
  examples/radar/basic/demo/meta.json
  examples/waterfall/basic/demo/absolute-label.ts
  examples/waterfall/basic/demo/annotation.ts
  src/plots/bullet/index.ts
Labels: PR: partially-approved

#1825 test: use pull_request_target
  .github/workflows/preview.yml
Labels: PR: reviewed-approved

#1818 feat: radial-bar chart
  __tests__/data/antv-star.ts
  __tests__/unit/plots/radial-bar/axis-spec.ts
  __tests__/unit/plots/radial-bar/index-spec.ts
  __tests__/unit/plots/radial-bar/style-spec.ts
  __tests__/unit/plots/radial-bar/tooltip-spec.ts
  __tests__/unit/plots/radial-bar/utils-spec.ts
  docs/manual/plots/radial-bar.en.md
  docs/manual/plots/radial-bar.zh.md
  examples/radial-bar/basic/API.en.md
  examples/radial-bar/basic/API.zh.md
  examples/radial-bar/basic/demo/basic.ts
  examples/radial-bar/basic/demo/meta.json
  examples/radial-bar/basic/design.en.md
  examples/radial-bar/basic/design.zh.md
  examples/radial-bar/basic/index.en.md
  examples/radial-bar/basic/index.zh.md
  gatsby-config.js
  src/index.ts
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/index.ts
  src/plots/radial-bar/types.ts
  src/plots/radial-bar/utils.ts
Labels: PR: reviewed-approved

#1823 fix: 双轴图 point 颜色映射错误和参数丢失
  __tests__/unit/plots/dual-axes/point-spec.ts
  src/plots/dual-axes/util/geometry.ts
Labels: PR: unreviewed

#1828 fix: 调整 bar 默认的柱子顺序
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/column/percent-spec.ts
  docs/common/slider.en.md
  docs/common/slider.zh.md
  examples/bar/basic/demo/meta.json
  examples/bar/basic/demo/scrollbar.ts
  examples/bar/grouped/demo/meta.json
  examples/bar/percent/demo/meta.json
  examples/bar/range/demo/meta.json
  examples/bar/stacked/demo/meta.json
  src/plots/bar/adaptor.ts
Labels: PR: partially-approved

#1827 Feat/duax plot expand
  __tests__/data/pv-uv.ts
  __tests__/unit/plots/column/percent-spec.ts
  __tests__/unit/plots/dual-axes/column-spec.ts
  __tests__/unit/plots/dual-axes/stack-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  __tests__/utils/dom.ts
  examples/dual-axes/column-line/demo/meta.json
  examples/dual-axes/column-line/demo/range-column-line.ts
  examples/dual-axes/dual-line/demo/dual-step-line.ts
  examples/dual-axes/dual-line/demo/meta.json
  examples/dual-axes/stacked-column-line/demo/meta.json
  examples/dual-axes/stacked-column-line/demo/stacked-percent-column-line.ts
  src/plots/column/adaptor.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/geometry.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: partially-approved

#1829 fix: coveralls ci not working
  .github/workflows/ci.yml
Labels: PR: unreviewed
