Repository antvis/G2Plot, pull requests merged in 2020-01, with the labels that each got.

#408 combo chart doc
  __tests__/unit/combo-spec.ts
  __tests__/unit/heatmap-spec.ts
  docs/manual/advanced/overlapped-combo-plot.en.md
  docs/manual/advanced/overlapped-combo-plot.zh.md
  examples/combo/basic/API.en.md
  examples/combo/basic/API.zh.md
  examples/combo/basic/demo/column-line.js
  examples/combo/basic/demo/column-scatter-line.js
  examples/combo/basic/demo/meta.json
  examples/combo/basic/design.en.md
  examples/combo/basic/design.zh.md
  examples/combo/basic/index.en.md
  examples/combo/basic/index.zh.md
  gatsby-config.js
  src/combo-plots/base.ts
  src/combo-plots/index.ts
  src/combo-plots/overlapped.ts
  src/combo-plots/util/adjustColorConfig.ts
  src/combo-plots/util/globalAxis.ts
  src/combo-plots/util/globalLegend.ts
  src/combo-plots/util/globalTooltip.ts
  src/combo-plots/util/index.ts
  src/geoms/point/guide.ts
  src/index.ts
Labels: PR: unreviewed

#446 refactor: use unpkg other than browser field in package.json
  package.json
Labels: PR: reviewed-approved, refactor

#453 heatmap demo & doc
  docs/manual/plots/heatmap.en.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/scatter.zh.md
  examples/data/global-temp.json
  examples/data/heatmap.json
  examples/data/jobpaying.json
  examples/heatmap/basic/API.en.md
  examples/heatmap/basic/API.zh.md
  examples/heatmap/basic/demo/basic.js
  examples/heatmap/basic/demo/heatmap-background.js
  examples/heatmap/basic/demo/meta.json
  examples/heatmap/basic/design.en.md
  examples/heatmap/basic/design.zh.md
  examples/heatmap/basic/index.en.md
  examples/heatmap/basic/index.zh.md
  src/plots/heatmap/components/legend.ts
Labels: PR: unreviewed

#459 fix: 修复 dist 中出现 es6 代码问题，#436
  package.json
  webpack.config.js
Labels: PR: unreviewed, bug

#465 add dual line demo
  examples/combo/basic/demo/dual-line.js
  examples/combo/basic/demo/meta.json
  examples/data/weather.json
  src/base/controller/padding.ts
  src/combo-plots/base.ts
  src/combo-plots/overlapped.ts
  src/combo-plots/util/globalAxis.ts
  src/combo-plots/util/globalLegend.ts
Labels: PR: unreviewed

#468 fix: 修复不同plot设置theme option互相影响
  __tests__/bugs/issue-467-spec.ts
  src/base/controller/theme.ts
Labels: PR: reviewed-changes-requested, bug

#470 feat(label): 数据标签精度和后缀单位配置
  docs/manual/general-config.zh.md
  src/components/label/parser.ts
  src/interface/config.ts
  src/plots/funnel/component/label/parser.ts
  src/plots/funnel/layer.ts
  src/util/formatter.ts
Labels: PR: reviewed-changes-requested, enhancement

#472 docs: fix code block format
  examples/pie/basic/API.en.md
  examples/pie/basic/API.zh.md
  examples/pie/ring/API.en.md
  examples/pie/ring/API.zh.md
Labels: PR: reviewed-approved, documentation

#473 feat: 面包屑组件
  __tests__/unit/components/breadcrumb-spec.ts
  package.json
  src/components/base.ts
  src/components/breadcrumb.ts
Labels: PR: reviewed-changes-requested, enhancement

#486 refactor: pie outer label
  __tests__/bugs/issue-485-spec.ts
  __tests__/unit/pie-outerLabel-spec.ts
  __tests__/unit/pie-utils-spec.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/component/label/utils/index.ts
  src/plots/pie/component/label/utils/text.ts
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested, refactor

#484 fix: 条形度暗黑主题修复
  __tests__/bugs/issue-478-spec.ts
  docs/manual/general-config.en.md
  docs/manual/general-config.zh.md
  src/plots/bar/layer.ts
Labels: PR: unreviewed, bug

#492 fix: 修复 dark 下图表 label 问题 issue #489
  demos/radar-series.ts
  src/plots/bar/component/label/bar-label.ts
  src/plots/column/component/label/column-label.ts
  src/plots/radar/layer.ts
  src/plots/scatter/components/label/scatter-label.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: PR: reviewed-approved, bug

#493 feat: 饼图 inner label
  __tests__/unit/pie-innerLabel-spec.ts
  __tests__/unit/pie-spec.ts
  __tests__/unit/utils-math-spec.ts
  src/plots/pie/component/label/inner-label.ts
  src/plots/pie/layer.ts
  src/util/math.ts
Labels: PR: reviewed-approved, enhancement

#490 Feat step line
  __tests__/unit/plots/step/index-spec.ts
  examples/step/basic/API.en.md
  examples/step/basic/API.zh.md
  examples/step/basic/demo/meta.json
  examples/step/basic/demo/step-point-style.js
  examples/step/basic/demo/step-slider.js
  examples/step/basic/demo/step-style.js
  examples/step/basic/demo/step.js
  examples/step/basic/design.en.md
  examples/step/basic/design.zh.md
  examples/step/basic/index.en.md
  examples/step/basic/index.zh.md
  examples/step/multiple/API.en.md
  examples/step/multiple/API.zh.md
  examples/step/multiple/demo/meta.json
  examples/step/multiple/demo/step-label.js
  examples/step/multiple/demo/step-multiple.js
  examples/step/multiple/design.en.md
  examples/step/multiple/design.zh.md
  examples/step/multiple/index.en.md
  examples/step/multiple/index.zh.md
  gatsby-config.js
  src/geoms/line/main.ts
  src/plots/index.ts
  src/plots/step/index.ts
  src/plots/step/layer.ts
Labels: PR: unreviewed

#500 fix(step-line): rename step to step-line
  __tests__/unit/plots/step/index-spec.ts
  examples/step-line/basic/API.en.md
  examples/step-line/basic/API.zh.md
  examples/step-line/basic/demo/meta.json
  examples/step-line/basic/demo/step-point-style.js
  examples/step-line/basic/demo/step-slider.js
  examples/step-line/basic/demo/step-style.js
  examples/step-line/basic/demo/step.js
  examples/step-line/basic/design.en.md
  examples/step-line/basic/design.zh.md
  examples/step-line/basic/index.en.md
  examples/step-line/basic/index.zh.md
  examples/step-line/multiple/API.en.md
  examples/step-line/multiple/API.zh.md
  examples/step-line/multiple/demo/meta.json
  examples/step-line/multiple/demo/step-label.js
  examples/step-line/multiple/demo/step-multiple.js
  examples/step-line/multiple/design.en.md
  examples/step-line/multiple/design.zh.md
  examples/step-line/multiple/index.en.md
  examples/step-line/multiple/index.zh.md
  gatsby-config.js
  src/plots/index.ts
  src/plots/step-line/index.ts
  src/plots/step-line/layer.ts
  src/plots/step/index.ts
Labels: PR: reviewed-changes-requested, bug

#503 fix(type-define): add color field for config
  src/plots/bar/layer.ts
Labels: PR: unreviewed, bug

#508 漏斗图优化与文档更新
  examples/funnel/basic/demo/basic.js
  examples/funnel/basic/demo/percent.js
  examples/liquid/basic/demo/basic.js
  examples/liquid/basic/demo/meta.json
  src/plots/funnel/layer.ts
Labels: PR: reviewed-changes-requested

#510 fix: set default background color for breadcrumb
  src/components/breadcrumb.ts
Labels: PR: reviewed-changes-requested, PR: unreviewed, bug

#512 feat: update radar docs and config
  demos/radar-basic.ts
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  src/interface/config.ts
  src/plots/radar/layer.ts
Labels: PR: unreviewed, enhancement

#524 chore: add stale and auto merge workflows
  .github/workflows/auto-merge.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/pr-size-label.yml
  .github/workflows/stale.yml
Labels: PR: reviewed-approved, automerge, chore, size/M

#521 feat: close waterfall legend & add api-docs
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  examples/column/waterfall/API.zh.md
  src/plots/waterfall/layer.ts
Labels: PR: unreviewed, enhancement, size/L

#519 feat(rose-api): 补全玫瑰图 api 文档
  examples/rose/basic/API.en.md
  examples/rose/basic/API.zh.md
  examples/rose/basic/index.zh.md
  src/plots/rose/layer.ts
Labels: PR: unreviewed, enhancement, size/L

#514 fix: padding controller clear fix & unit test
  __tests__/unit/base/controller/padding-spec.ts
  src/base/controller/padding.ts
Labels: PR: unreviewed, automerge, size/L

#528 fix(types): correct data types and point style types
  .github/workflows/auto-merge.yml
  src/base/view-layer.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-changes-requested, automerge, bug, size/XS

#526 fix(inner-label): inner-label支持百分比offset & 默认调整label offset
  __tests__/unit/ring-spec.ts
  src/plots/pie/component/label/inner-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/layer.ts
  src/plots/ring/layer.ts
Labels: PR: unreviewed, bug, size/L

#530 fix: heatmap & matrix legend visible Closes #511
  package.json
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/plots/heatmap/components/legend.ts
  src/plots/heatmap/layer.ts
  src/plots/matrix/component/legend.ts
  src/plots/matrix/layer.ts
Labels: PR: unreviewed, bug, size/M

#534 fix(types): fix combo base interface
  src/combo-plots/base.ts
Labels: PR: reviewed-approved, bug

#537 Fix outer components
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/description.ts
  src/plots/heatmap/components/legend.ts
  src/plots/matrix/component/legend.ts
Labels: PR: reviewed-changes-requested, size/S
