Repository antvis/G2Plot, pull requests merged in 2020-08, with the labels that each got.

#1381 V2 bar
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/types.ts
  src/plots/column/adaptor.ts
Labels: PR: reviewed-changes-requested

#1383 v2 饼图若干修复
  __tests__/unit/plots/pie/interaction-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interaction/index.ts
  src/plots/pie/interaction/pie-legend-action.ts
Labels: PR: reviewed-changes-requested

#1331 feat: [V2_combo] 混合图表-双折线图
  __tests__/data/pv-uv.ts
  __tests__/unit/plots/biax/axis-spec.ts
  __tests__/unit/plots/biax/double-line-spec.ts
  __tests__/unit/plots/biax/index-spec.ts
  __tests__/unit/plots/biax/scale.ts
  src/adaptor/geometries/area.ts
  src/adaptor/geometries/line.ts
  src/adaptor/geometries/point.ts
  src/common/helper.ts
  src/core/adaptor.ts
  src/index.ts
  src/plots/biax/adaptor.ts
  src/plots/biax/constant.ts
  src/plots/biax/index.ts
  src/plots/biax/types.ts
  src/plots/biax/util.ts
Labels: PR: unreviewed, enhancement

#1391 feat(v2/column): extract common interval geometry
  __tests__/unit/plots/column/index-spec.ts
  src/adaptor/geometries/index.ts
  src/adaptor/geometries/interval.ts
  src/plots/column/adaptor.ts
Labels: PR: unreviewed, enhancement

#1390 fix(#1389): 修复 GroupedColumnLine 右侧 tooltip formatter 不生效
  __tests__/bugs/issue-1389-spec.ts
  src/combo/column-line/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1395 fix: 修改蜘蛛网布局中被剔除 label 仍出现在画布（左上角）
  src/plots/pie/component/label/spider-label.ts
Labels: PR: reviewed-changes-requested, bug

#1398 chore: release 1.1.20
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1396 fix(waterfall): 修复瀑布图label.formatter失效问题
  __tests__/unit/plots/waterfall/waterfall-spec.ts
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  examples/column/waterfall/demo/basic.js
  src/plots/waterfall/component/label/waterfall-label.ts
  src/plots/waterfall/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1400 feat: Liquid and Donut options statistic supported HTMLDivElement
  __tests__/unit/plots/donut/donut-htmlContent-spec.ts
  __tests__/unit/plots/donut/dount-htmlDivElement-spec.ts
  __tests__/unit/plots/liquid/liquid-htmlDivElement-spec.ts
  src/components/statistic.ts
  src/plots/donut/component/ring-statistic.ts
  src/plots/donut/component/statistic.ts
  src/plots/donut/layer.ts
  src/plots/liquid/component/liquid-statistic.ts
  src/plots/liquid/layer.ts
Labels: PR: unreviewed, enhancement

#1370 feat: new chart type - heatmap
  __tests__/data/basic-heatmap.ts
  __tests__/unit/plots/heatmap/axis-spec.ts
  __tests__/unit/plots/heatmap/index-spec.ts
  __tests__/unit/plots/heatmap/label-spec.ts
  __tests__/unit/plots/heatmap/shape-spec.ts
  __tests__/unit/plots/heatmap/size-spec.ts
  __tests__/unit/plots/heatmap/style-spec.ts
  __tests__/unit/plots/heatmap/tooltip-spec.ts
  __tests__/unit/plots/line/tooltip-spec.ts
  src/constant.ts
  src/index.ts
  src/plots/heatmap/adaptor.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/shapes/circle.ts
  src/plots/heatmap/shapes/square.ts
  src/plots/heatmap/types.ts
  src/types/index.ts
  src/types/tuple.ts
Labels: PR: partially-approved, enhancement

#1406 fix: 修复饼图事件不生效的问题
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1407 chore: release 1.1.22
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1409 fix: issue 1405
  __tests__/bugs/issue-1405-spec.ts
  src/base/view-layer.ts
Labels: PR: reviewed-approved, bug

#1411 增加饼、环图文档 ，同时补全饼图能力
  __tests__/unit/plots/pie/label-spec.ts
  __tests__/unit/plots/pie/legend-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  __tests__/utils/event.ts
  examples/pie/basic/API.en.md
  examples/pie/basic/API.zh.md
  examples/pie/basic/demo/basic.ts
  examples/pie/basic/demo/custom-label.ts
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/outer-label.ts
  examples/pie/basic/demo/pie-texture.ts
  examples/pie/basic/index.en.md
  examples/pie/basic/index.zh.md
  examples/pie/donut/API.en.md
  examples/pie/donut/API.zh.md
  examples/pie/donut/demo/basic.ts
  examples/pie/donut/demo/meta.json
  examples/pie/donut/demo/statistics.ts
  examples/pie/donut/index.en.md
  examples/pie/donut/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  src/adaptor/common.ts
  src/core/plot.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
  src/plots/pie/label/index.ts
  src/plots/pie/label/inner-label.ts
  src/plots/pie/types.ts
  src/plots/pie/utils.ts
Labels: PR: reviewed-changes-requested

#1412 feat(event): add plot events bind
  __tests__/unit/core/index-spec.ts
  src/core/plot.ts
Labels: PR: reviewed-approved, enhancement

#1408 docs: add design
  examples/scatter/basic/API.ch.md
  examples/scatter/basic/design.en.md
  examples/scatter/basic/design.zh.md
Labels: PR: reviewed-approved, documentation

#1413 Feat line demo
  __tests__/unit/utils/dom-spec.ts
  examples/line/basic/demo/line-point-style.ts
  examples/line/basic/demo/line-smooth.ts
  examples/line/basic/demo/line-with-point.ts
  examples/line/basic/demo/line.ts
  examples/line/basic/demo/meta.json
  examples/line/basic/design.en.md
  examples/line/basic/design.zh.md
  examples/line/basic/index.en.md
  examples/line/basic/index.zh.md
  examples/line/multiple/demo/color-callback.ts
  examples/line/multiple/demo/line-color.ts
  examples/line/multiple/demo/line-label.ts
  examples/line/multiple/demo/line-large-data.ts
  examples/line/multiple/demo/line-multiple.ts
  examples/line/multiple/demo/line-style.ts
  examples/line/multiple/demo/marker-active.ts
  examples/line/multiple/demo/meta.json
  examples/line/multiple/design.en.md
  examples/line/multiple/design.zh.md
  examples/line/multiple/index.en.md
  examples/line/multiple/index.zh.md
  gatsby-config.js
  package.json
  src/adaptor/geometries/point.ts
  src/core/plot.ts
  src/utils/dom.ts
  src/utils/index.ts
Labels: PR: unreviewed

#1416 fix: 修复全 0 数据饼图 spider 布局 label 报错的问题
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/layer.ts
Labels: PR: partially-approved, bug

#1417 chore: release 1.1.23
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1419 Feat radar demo
  __tests__/unit/plots/radar/axis-spec.ts
  examples/pie/basic/API.zh.md
  examples/radar/basic/API.en.md
  examples/radar/basic/API.zh.md
  examples/radar/basic/demo/basic.ts
  examples/radar/basic/demo/meta.json
  examples/radar/basic/demo/series.ts
  examples/radar/basic/index.en.md
  examples/radar/basic/index.zh.md
  gatsby-config.js
  src/plots/radar/adaptor.ts
  src/plots/radar/constants.ts
  src/plots/radar/index.ts
  src/types/common.ts
Labels: PR: partially-approved

#1423 docs: add demos
  __tests__/unit/plots/line/axis-spec.ts
  __tests__/unit/plots/radar/axis-spec.ts
  __tests__/unit/plots/scatter/default-config-spec.ts
  examples/scatter/basic/demo/basic.ts
  examples/scatter/basic/demo/color-mapping.ts
  examples/scatter/basic/demo/label.ts
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/shape-mapping.ts
  examples/scatter/basic/demo/size.ts
  src/core/plot.ts
  src/plots/scatter/index.ts
Labels: PR: reviewed-approved, documentation

#1422 docs: 增加histogram的example和文档
  examples/histogram/basic/API.en.md
  examples/histogram/basic/API.zh.md
  examples/histogram/basic/demo/basic.ts
  examples/histogram/basic/demo/binWidth.ts
  examples/histogram/basic/demo/meta.json
  examples/histogram/basic/demo/stack.ts
  examples/histogram/basic/design.en.md
  examples/histogram/basic/design.zh.md
  examples/histogram/basic/index.en.md
  examples/histogram/basic/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved, documentation

#1429 fix(v2/radar): 修复雷达图单测
  __tests__/unit/plots/radar/axis-spec.ts
Labels: PR: partially-approved, bug

#1430 refactor(common-helper): 将 common helper 移动到 utils 目录中
  __tests__/unit/utils/geometry-spec.ts
  src/plots/area/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/heatmap/adaptor.ts
  src/plots/histogram/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/scatter/adaptor.ts
  src/utils/geometry.ts
  src/utils/index.ts
Labels: PR: partially-approved, refactor

#1424 feat(v2/pie-demo): 饼图 demo 的优化
  examples/pie/basic/demo/basic.ts
  examples/pie/basic/demo/custom-label.ts
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/outer-label.ts
  examples/pie/basic/demo/pie-texture.ts
  examples/pie/donut/demo/basic.ts
  examples/pie/donut/demo/meta.json
  examples/pie/donut/demo/statistics.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/constants.ts
  src/plots/pie/index.ts
  src/types/legend.ts
Labels: PR: partially-approved, enhancement

#1431 fix(#1268): 修复 undefined 问题
  src/components/axis/state.ts
  src/util/responsive/apply/axis.ts
Labels: PR: partially-approved, bug

#1436 docs: 修改网站地址
  examples/gallery/index.en.md
  examples/scatter/basic/index.en.md
  gatsby-config.js
Labels: PR: reviewed-approved, documentation

#1435 feat(v2/column): add demos for column plot
  examples/column/basic/demo/basic.ts
  examples/column/basic/demo/color.ts
  examples/column/basic/demo/label-position.ts
  examples/column/basic/demo/label.ts
  examples/column/basic/demo/meta.json
  examples/column/basic/demo/width.ts
  examples/column/basic/design.en.md
  examples/column/basic/design.zh.md
  examples/column/basic/index.en.md
  examples/column/basic/index.zh.md
  examples/column/grouped/demo/basic.ts
  examples/column/grouped/demo/label-position.ts
  examples/column/grouped/demo/label.ts
  examples/column/grouped/demo/margin.ts
  examples/column/grouped/demo/meta.json
  examples/column/grouped/design.en.md
  examples/column/grouped/design.zh.md
  examples/column/grouped/index.en.md
  examples/column/grouped/index.zh.md
  examples/column/stacked/demo/basic.ts
  examples/column/stacked/demo/label-position.ts
  examples/column/stacked/demo/label.ts
  examples/column/stacked/demo/meta.json
  examples/column/stacked/design.en.md
  examples/column/stacked/design.zh.md
  examples/column/stacked/index.en.md
  examples/column/stacked/index.zh.md
  gatsby-config.js
  src/plots/column/adaptor.ts
Labels: PR: reviewed-changes-requested, enhancement

#1437 chore: v2.0.0-beta.1
  CHANGELOG.md
  README.md
  README.zh-CN.md
  __tests__/unit/index-spec.ts
  examples/line/multiple/demo/marker-active.ts
  package.json
  src/index.ts
Labels: PR: partially-approved, chore

#1439 docs: 添加图表通用配置
  docs/common/chart-options.en.md
  docs/common/chart-options.zh.md
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
  package.json
Labels: PR: reviewed-approved, documentation

#1440 fix: 解决空路径 demos 不可用问题
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
Labels: PR: reviewed-approved, bug

#1441 fix(pie): 修复 chart 初始化获取不到 filteredData，使用 text content 回调替代 获取
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/utils.ts
Labels: PR: reviewed-approved, bug

#1447 test: 修改histogram直方图的测试用例
  __tests__/unit/plots/histogram/index-spec.ts
  package.json
Labels: PR: reviewed-approved, test

#1446 feat: 导出 G2 和 Tooltip 类型定义
  __tests__/unit/core/index-spec.ts
  src/index.ts
  src/types/index.ts
Labels: PR: reviewed-approved, enhancement

#1456 fix: 修改 scatter 写法
  package.json
  src/plots/scatter/adaptor.ts
  src/plots/scatter/reflect.ts
Labels: PR: reviewed-approved, bug

#1457 feat: add theme config
  __tests__/unit/plots/pie/theme-spec.ts
  __tests__/unit/plots/tiny-area/theme-spec.ts
  __tests__/unit/plots/tiny-column/theme-spec.ts
  __tests__/unit/plots/tiny-line/theme-spec.ts
  examples/general/theme/API.en.md
  examples/general/theme/API.zh.md
  examples/general/theme/demo/dark.ts
  examples/general/theme/demo/meta.json
  examples/general/theme/demo/registerTheme.ts
  examples/general/theme/index.en.md
  examples/general/theme/index.zh.md
  gatsby-config.js
  src/adaptor/common.ts
  src/plots/biax/adaptor.ts
  src/plots/biax/types.ts
  src/plots/pie/index.ts
  src/plots/scatter/index.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-line/types.ts
  src/types/common.ts
  src/types/style.ts
Labels: PR: partially-approved, enhancement

#1452 docs: 添加 tooltip
  docs/common/chart-options.zh.md
  docs/common/line-style.en.md
  docs/common/line-style.zh.md
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  docs/common/text-style.en.md
  docs/common/text-style.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  examples/scatter/basic/API.zh.md
Labels: PR: reviewed-approved, documentation

#1455 Chore walkthrough
  src/core/plot.ts
  src/utils/g-util.ts
Labels: PR: reviewed-approved

#1458 代码走查
  src/adaptor/common.ts
  src/core/plot.ts
  src/plots/biax/adaptor.ts
  src/plots/progress/types.ts
  src/plots/ring-progress/types.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/types.ts
  src/types/common.ts
Labels: PR: partially-approved

#1460 feat(state): 添加 setState 方法，通过条件设置三种状态的激活与否
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/pie/state-spec.ts
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/pie-state.ts
  src/adaptor/common.ts
  src/core/plot.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/types.ts
  src/types/common.ts
  src/types/index.ts
  src/types/state.ts
  src/utils/geometry.ts
  src/utils/index.ts
Labels: PR: partially-approved, enhancement

#1465 docs: 添加 axis
  docs/common/axis.en.md
  docs/common/axis.zh.md
  docs/common/label.en.md
  docs/common/label.zh.md
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
Labels: PR: reviewed-approved, documentation

#1466 feat(lint-md): add markdown lint & fix markdown error
  examples/biax/basic/API.zh.md
  examples/histogram/basic/API.en.md
  examples/histogram/basic/API.zh.md
  package.json
Labels: PR: partially-approved, enhancement

#1467 fix: 文档路径错误
  docs/common/axis.en.md
  docs/common/axis.zh.md
Labels: PR: reviewed-approved, bug

#1471 fix: 修改 changeData
  src/core/plot.ts
Labels: PR: reviewed-approved, bug

#1470 docs: 统一通用文档样式
  docs/common/axis.en.md
  docs/common/axis.zh.md
  docs/common/chart-methods.en.md
  docs/common/chart-methods.zh.md
  docs/common/label.en.md
  docs/common/label.zh.md
  docs/common/line-style.en.md
  docs/common/line-style.zh.md
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  docs/common/text-style.en.md
  docs/common/text-style.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
Labels: PR: reviewed-approved, documentation

#1474 fix(bullet): 子弹图图例隐藏，修改 demo，设置图例 offsetY 偏移
  examples/bullet/basic/demo/basic.js
  examples/bullet/basic/demo/color-range.js
  examples/bullet/basic/demo/group-color-range.js
  examples/bullet/basic/demo/group.js
  examples/bullet/basic/demo/multi-targets.js
  examples/bullet/basic/demo/overflow.js
Labels: PR: reviewed-approved, bug

#1475 fix: heatmap shapeStyle设置callback无效
  src/plots/heatmap/layer.ts
Labels: PR: reviewed-approved, bug

#1483 chore: 修改版本号和 CHANGELOG
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved, chore

#1486 feat: add bar demos
  __tests__/data/box.ts
  examples/bar/basic/demo/basic.ts
  examples/bar/basic/demo/color.ts
  examples/bar/basic/demo/label-position.ts
  examples/bar/basic/demo/label.ts
  examples/bar/basic/demo/meta.json
  examples/bar/basic/demo/width.ts
  examples/bar/basic/design.en.md
  examples/bar/basic/design.zh.md
  examples/bar/basic/index.en.md
  examples/bar/basic/index.zh.md
  examples/bar/grouped/demo/basic.ts
  examples/bar/grouped/demo/label-position.ts
  examples/bar/grouped/demo/label.ts
  examples/bar/grouped/demo/margin.ts
  examples/bar/grouped/demo/meta.json
  examples/bar/grouped/design.en.md
  examples/bar/grouped/design.zh.md
  examples/bar/grouped/index.en.md
  examples/bar/grouped/index.zh.md
  examples/bar/stacked/demo/basic.ts
  examples/bar/stacked/demo/label-position.ts
  examples/bar/stacked/demo/label.ts
  examples/bar/stacked/demo/meta.json
  examples/bar/stacked/design.en.md
  examples/bar/stacked/design.zh.md
  examples/bar/stacked/index.en.md
  examples/bar/stacked/index.zh.md
  gatsby-config.js
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#1487 chore: export TooltipCfg
  src/interface/config.ts
Labels: PR: unreviewed, chore

#1489 走查 & 重构
  src/adaptor/common.ts
  src/index.ts
  src/plots/area/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/heatmap/adaptor.ts
  src/plots/histogram/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interaction/pie-legend-action.ts
  src/plots/progress/adaptor.ts
  src/plots/radar/adaptor.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/scatter/adaptor.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-line/adaptor.ts
Labels: PR: partially-approved

#1382 feat: a new chart type - Box Chart
  __tests__/data/box.ts
  __tests__/unit/plots/box/axis-spec.ts
  __tests__/unit/plots/box/group-spec.ts
  __tests__/unit/plots/box/index-spec.ts
  __tests__/unit/plots/box/legend-spec.ts
  __tests__/unit/plots/box/outliers-spec.ts
  __tests__/unit/plots/box/style-spec.ts
  __tests__/unit/plots/box/tooltip-spec.ts
  examples/box/basic/demo/basic.ts
  examples/box/basic/demo/group.ts
  examples/box/basic/demo/meta.json
  examples/box/basic/demo/outliers.ts
  examples/box/basic/index.en.md
  examples/box/basic/index.zh.md
  examples/histogram/basic/API.en.md
  examples/histogram/basic/API.zh.md
  examples/pie/basic/API.en.md
  examples/pie/basic/API.zh.md
  examples/pie/basic/demo/meta.json
  examples/pie/donut/API.en.md
  examples/pie/donut/API.zh.md
  examples/pie/donut/demo/meta.json
  gatsby-config.js
  package.json
  src/index.ts
  src/plots/box/adaptor.ts
  src/plots/box/constant.ts
  src/plots/box/index.ts
  src/plots/box/types.ts
Labels: PR: partially-approved, enhancement

#1492 docs(waterfall): 修复瀑布图文档, 更新 tooltip 使用方式
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
Labels: PR: partially-approved, documentation

#1490 fix: 存在 width 或 height 时优先使用，可以只指定 height 或 width
  src/core/plot.ts
Labels: PR: unreviewed, bug

#1497 chore(template): add plot template
  src/plots/_template/adaptor.ts
  src/plots/_template/index.ts
  src/plots/_template/types.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
Labels: PR: partially-approved, chore

#1454 feat(v2): 添加玫瑰图配置项
  __tests__/unit/plots/rose/animation-spec.ts
  __tests__/unit/plots/rose/axis-spec.ts
  __tests__/unit/plots/rose/index-spec.ts
  __tests__/unit/plots/rose/label-spec.ts
  __tests__/unit/plots/rose/style-spec.ts
  __tests__/unit/plots/rose/tooltip-spec.ts
  src/index.ts
  src/plots/rose/adaptor.ts
  src/plots/rose/index.ts
  src/plots/rose/types.ts
Labels: PR: reviewed-approved, enhancement

#1500 走查修改
  src/index.ts
  src/plots/rose/adaptor.ts
Labels: PR: reviewed-approved

#1505 fix: 1.x bugfix
  CHANGELOG.md
  package.json
  src/combo/groupedColumn-line/layer.ts
  src/plots/funnel/layer.ts
Labels: PR: partially-approved, bug

#1504 fix: 解决 changeData 无效问题
  src/core/plot.ts
Labels: PR: unreviewed, bug

#1507 perf: 新增 animation 并更正其它图表 getDefaultOptions
  __tests__/unit/plots/pie/empty-data-spec.ts
  __tests__/unit/plots/pie/state-spec.ts
  src/core/plot.ts
  src/plots/box/index.ts
  src/plots/pie/index.ts
  src/plots/radar/index.ts
  src/types/animation.ts
Labels: PR: reviewed-approved, performance
