Repository antvis/G2Plot, pull requests merged in 2020-06, with the labels that each got.

#1172 chore: add ts skipLibCheck to skip ts errors in node_modules
  tsconfig.json
Labels: PR: reviewed-approved, chore

#1189 饼及环图的 label 以及 Statistics 的内容可受 scale 影响
  __tests__/bugs/donut-statistic-spec.ts
  src/plots/donut/component/ring-statistic.ts
  src/plots/pie/component/label/base-label.ts
Labels: PR: reviewed-changes-requested

#1190 chore: release 1.1.7
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1218 Fix donut statistic
  src/plots/donut/component/statistic-template.ts
  src/plots/donut/component/statistic.ts
Labels: PR: reviewed-changes-requested

#1223 fix(pie): 修复饼图数据全为 0 展示
  __tests__/bugs/issue-1161-spec.ts
  examples/line/multiple/demo/marker-active.js
  src/plots/pie/layer.ts
Labels: PR: partially-approved, bug

#1229 fix: fix line renderer without data
  src/plots/line/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1176 折线图的 point stroke 不能写死，shape为空心的时候stroke无法配置
  src/dependents.ts
  src/index.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-changes-requested

#1202 fix: update scrollbar and data label when changeData
  __tests__/bugs/issue-1137-spec.ts
  src/base/constants.ts
  src/base/view-layer.ts
  src/components/label/base.ts
  src/interaction/scrollbar.ts
  src/plots/bar/component/label-auto.ts
  src/plots/column/component/label-auto.ts
Labels: PR: partially-approved, bug

#1233 fix: percent-stacked-column tooltip is not a number
  __tests__/bugs/issue-821-spec.ts
  src/util/data.ts
Labels: PR: reviewed-approved, bug
