Repository antvis/G2Plot, pull requests merged in 2020-03, with the labels that each got.

#694 1.x 子弹图走查
  examples/bullet/basic/API.zh.md
  src/plots/bullet/layer.ts
  src/plots/bullet/theme.ts
  src/theme/theme.ts
Labels: size/M

#685 【0.1.x】fix: 支持饼图 label line 上的样式配置
  src/plots/pie/layer.ts
Labels: bug, size/XS

#681 [0.1.x ] fix: 饼图 tooltip 需要调用 layer 里的 tooltip 方法
  src/plots/pie/layer.ts
Labels: bug, size/XS

#696 Feat: 词云图 Tooltip 定制和背景色支持透明
  __tests__/unit/word-cloud-spec.ts
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/word-cloud-tooltips.ts
  src/plots/word-cloud/wordcloud2.ts
Labels: Feat, PR: unreviewed, size/M

#695 1.x 饼图 & 瀑布图走查
  src/plots/bullet/theme.ts
  src/plots/pie/theme.ts
  src/plots/waterfall/layer.ts
  src/theme/theme.ts
Labels: size/M

#697 fix(types): fix type definition error
  src/plots/range-bar/layer.ts
  src/plots/range-column/layer.ts
Labels: PR: unreviewed, bug

#703 feat(bug): fix image cross-origin bug
  src/plots/word-cloud/layer.ts
Labels: enhancement, size/XS

#686 feat(g2 4.0): word-cloud's text support animatable appear config
  __tests__/unit/plots/word-cloud/word-cloud-spec.ts
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/wordcloud2.ts
Labels: enhancement, size/L

#701 Feat svg supported
  .eslintrc
  __tests__/unit/base/controller/canvas-controller-spec.ts
  __tests__/unit/plots/pie/pie-spider-label-spec.ts
  __tests__/utils/dom.ts
  src/base/controller/canvas.ts
  src/base/layer.ts
  src/components/description.ts
  src/dependents.ts
  src/plots/bar/component/label.ts
  src/plots/heatmap/components/legend.ts
  src/plots/line/component/label/line-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/stack-column/layer.ts
Labels: size/L

#707 按照新模板更新并修订文档
  docs/manual/general-config.en.md
  docs/manual/plots/column.zh-.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/general-config.zh.md
  docs/manual/plots/line.zh-.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/pie.zh-.md
  docs/manual/plots/pie.zh.md
  examples/line/multiple/demo/color-callback.js
  examples/line/multiple/demo/line-color.js
  examples/line/multiple/demo/line-style.js
  examples/line/multiple/demo/meta.json
Labels: PR: reviewed-changes-requested, size/XXL

#710 [1.x] rose 走查：axis grid 配置失效
  src/components/axis/parser.ts
  src/plots/rose/layer.ts
Labels: PR: reviewed-changes-requested, size/XS

#666 Feat: add calendar
  __tests__/unit/plots/calendar/util-spec.ts
  __tests__/unit/util/date-spec.ts
  examples/calendar/basic/API.en.md
  examples/calendar/basic/API.zh.md
  examples/calendar/basic/demo/calendar.js
  examples/calendar/basic/demo/meta.json
  examples/calendar/basic/design.en.md
  examples/calendar/basic/design.zh.md
  examples/calendar/basic/index.en.md
  examples/calendar/basic/index.zh.md
  examples/data/contributions.json
  src/plots/calendar/constant.ts
  src/plots/calendar/index.ts
  src/plots/calendar/layer.ts
  src/plots/calendar/shape.ts
  src/plots/calendar/util.ts
  src/plots/index.ts
  src/util/date.ts
Labels: Feat, PR: reviewed-approved, PR: unreviewed, size/XL

#713 feat: 把slider的样式配置都暴露出来
  __tests__/unit/interaction/slider-spec.ts
  src/interaction/slider.ts
  src/interface/config.ts
Labels: PR: reviewed-approved, enhancement, size/L

#714 fix: 修复dark theme
  __tests__/unit/base/controller/canvas-controller-spec.ts
  src/base/controller/canvas.ts
  src/components/axis/parser.ts
  src/theme/dark.ts
Labels: PR: reviewed-approved, bug, size/M

#700 heatmap & treemap & minicharts单测
  __tests__/unit/plots/column/column-spec.ts
  __tests__/unit/plots/matrix/matrix-spec.ts
  package.json
  src/plots/matrix/layer.ts
Labels: PR: unreviewed, WIP, size/L

#721 fix: 辅助线样式设置
  __tests__/unit/plots/column/column-spec.ts
  __tests__/unit/plots/range-column/rangeColumn-spec.ts
  package.json
  src/components/guide-line.ts
Labels: PR: unreviewed, bug, size/L

#723 fix: 修复 radar 单测问题
  __tests__/unit/plots/radar/radar-spec.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#727 【1.x】radar 补充 grid type 与 alternateColor 单测
  __tests__/unit/plots/radar/radar-spec.ts
Labels: PR: reviewed-approved, size/M

#722 【1.x】scatter label 替换与单测补充
  __tests__/data/country-economy.ts
  __tests__/unit/plots/scatter/scatter-quadrant-spec.ts
  __tests__/unit/plots/scatter/scatter-spec.ts
  __tests__/unit/plots/scatter/scatter-trendline-spec.ts
  demos/scatter-basic.ts
  src/geoms/point/circle.ts
  src/plots/scatter/components/label.ts
  src/plots/scatter/layer.ts
Labels: PR: reviewed-approved, size/XXL

#724 Chart investigate
  src/plots/ring/component/ring-statistic.ts
  src/plots/ring/component/statistic.ts
  src/plots/rose/layer.ts
Labels: PR: reviewed-approved, size/S

#729 feat: 绘图属性文档
  docs/manual/graphic-style.zh.md
Labels: PR: reviewed-changes-requested, enhancement, size/L

#731 chore: 文档排序
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/bubble.zh.md
  docs/manual/plots/bullet.zh.md
  docs/manual/plots/calendar.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/density-heatmap.zh.md
  docs/manual/plots/donut.zh.md
  docs/manual/plots/gauge.en.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/grouped-bar.en.md
  docs/manual/plots/grouped-bar.zh.md
  docs/manual/plots/grouped-column.en.md
  docs/manual/plots/grouped-column.zh.md
  docs/manual/plots/grouped-rose.zh.md
  docs/manual/plots/heatmap.en.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/range-bar.zh.md
  docs/manual/plots/range-column.zh.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/stacked-area.zh.md
  docs/manual/plots/stacked-bar.en.md
  docs/manual/plots/stacked-bar.zh.md
  docs/manual/plots/stacked-column.en.md
  docs/manual/plots/stacked-column.zh.md
  docs/manual/plots/stacked-rose.zh.md
  docs/manual/plots/treemap.en.md
  docs/manual/plots/treemap.zh.md
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  docs/manual/plots/word-clourd.zh.md
Labels: PR: unreviewed, chore, size/XXL

#733 chore: Improve lint staged prettier workflow
  package.json
Labels: PR: reviewed-approved, chore, size/M

#734 fix: 修复 scatter 四象限问题及添加测试用例
  __tests__/unit/plots/scatter/scatter-quadrant-spec.ts
  src/plots/scatter/components/quadrant.ts
  src/plots/scatter/layer.ts
Labels: PR: reviewed-changes-requested, bug, size/XL

#737 feat(bubble): 添加单元测试
  __tests__/unit/plots/bubble/bubble-spec.ts
  src/plots/bubble/layer.ts
  src/plots/scatter/layer.ts
Labels: PR: reviewed-changes-requested, enhancement, size/M

#735 feat: gauge迁移
  examples/gauge/basic/demo/basic.js
  examples/gauge/basic/demo/fan.js
  examples/gauge/basic/demo/half.js
  examples/gauge/basic/demo/meta.json
  examples/gauge/basic/demo/meter.js
  examples/gauge/basic/demo/style.js
  src/plots/fan-gauge/index.ts
  src/plots/fan-gauge/layer.ts
  src/plots/gauge/geometry/shape/gauge-shape.ts
  src/plots/gauge/geometry/shape/options.ts
  src/plots/gauge/index.ts
  src/plots/gauge/layer.ts
  src/plots/gauge/options.ts
  src/plots/gauge/theme.ts
  src/plots/index.ts
  src/plots/meter-gauge/index.ts
  src/plots/meter-gauge/layer.ts
Labels: PR: unreviewed, enhancement, size/XXL

#738 【1.x】G2Plot label.formatter 兼容 G2 4.x label.content
  __tests__/unit/plots/scatter/scatter-spec.ts
  src/components/label/parser.ts
  src/plots/scatter/layer.ts
Labels: PR: reviewed-approved, size/M

#706 漏斗图系列G2 4.0 迁移
  demos/bar-conversion.ts
  demos/column-conversion.ts
  demos/funnel-compare-transpose.ts
  examples/bar/basic/API.zh.md
  examples/bar/basic/demo/bar-conversion.js
  examples/bar/basic/demo/meta.json
  examples/column/basic/API.zh.md
  examples/column/basic/demo/column-conversion.js
  examples/column/basic/demo/meta.json
  src/components/conversion-tag.ts
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/funnel/animation/funnel-scale-in-x.ts
  src/plots/funnel/animation/funnel-scale-in-y.ts
  src/plots/funnel/apply-responsive/axis.ts
  src/plots/funnel/apply-responsive/index.ts
  src/plots/funnel/event.ts
  src/plots/funnel/geometry/shape/funnel-basic-rect.ts
  src/plots/funnel/geometry/shape/funnel-dynamic-rect.ts
  src/plots/funnel/index.ts
  src/plots/funnel/layer.ts
  src/plots/funnel/theme.ts
  src/plots/index.ts
Labels: PR: unreviewed, WIP, size/XXL

#740 bugfix-0310
  examples/heatmap/density/demo/heatmap-background.js
  examples/rose/basic/demo/meta.json
  examples/rose/basic/demo/single-color.js
  examples/scatter/basic/demo/label-placement.js
  src/base/controller/padding.ts
  src/plots/density-heatmap/components/legend.ts
  src/plots/density-heatmap/layer.ts
  src/plots/heatmap/layer.ts
  src/plots/index.ts
  src/plots/line/layer.ts
  src/plots/radar/layer.ts
  src/util/math.ts
  src/util/responsive/apply/axis.ts
  src/util/responsive/apply/label.ts
  src/util/responsive/rules/datetime-string-abbrevaite.ts
  src/util/responsive/rules/nodes-resampling-by-abbrevate.ts
Labels: PR: unreviewed, size/L

#741 fix: 迁移修复折线图lineActive和lineSelect交互
  __tests__/unit/plots/line/line-interaction-spec.ts
  src/base/view-layer.ts
  src/dependents.ts
  src/plots/line/interaction/line-active.ts
  src/plots/line/interaction/line-select.ts
  src/plots/line/layer.ts
  src/plots/line/theme.ts
Labels: PR: unreviewed, bug, size/L

#743 feat: support custom widthRatio & update g2
  __tests__/unit/pie-innerLabel-spec.ts
  __tests__/utils/number.ts
  package.json
  src/base/view-layer.ts
  src/geoms/base.ts
  src/plots/rose/layer.ts
  src/util/scale.ts
Labels: PR: reviewed-approved, enhancement, size/M

#742 文档更新
  __tests__/unit/plots/line/lineLabel-spec.ts
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/bubble.zh.md
  docs/manual/plots/bullet.zh.md
  docs/manual/plots/calendar.zh.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/density-heatmap.zh.md
  docs/manual/plots/donut.zh.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/grouped-bar.zh.md
  docs/manual/plots/grouped-column.zh.md
  docs/manual/plots/grouped-rose.zh.md
  docs/manual/plots/heatmap.zh.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/range-bar.zh.md
  docs/manual/plots/range-column.zh.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/stacked-area.zh.md
  docs/manual/plots/stacked-bar.zh.md
  docs/manual/plots/stacked-column.zh.md
  docs/manual/plots/stacked-rose.zh.md
  docs/manual/plots/stepLine.zh.md
  docs/manual/plots/treemap.zh.md
  docs/manual/plots/waterfall.zh.md
  docs/manual/plots/word-clourd.zh.md
  examples/gauge/basic/demo/basic.js
  examples/gauge/basic/demo/fan.js
  examples/gauge/basic/demo/meter.js
  examples/general/state/demo/default-state.js
  package.json
  src/base/controller/state.ts
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/density-heatmap/layer.ts
  src/plots/fan-gauge/layer.ts
  src/plots/gauge/event.ts
  src/plots/gauge/geometry/shape/gauge-shape.ts
  src/plots/gauge/layer.ts
  src/plots/grouped-rose/layer.ts
  src/plots/heatmap/layer.ts
  src/plots/meter-gauge/layer.ts
  src/plots/radar/layer.ts
  src/plots/range-bar/layer.ts
  src/plots/rose/layer.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-rose/layer.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: PR: unreviewed, size/XXL

#751 fix(remove-lodash): remove lodash in inner-label
  src/plots/pie/component/label/inner-label.ts
Labels: bug, size/XS

#750 【1.x】scatter & bubble 视觉走查
  __tests__/unit/plots/bubble/bubble-spec.ts
  src/geoms/point/circle.ts
  src/plots/bubble/layer.ts
  src/plots/bubble/shape.ts
  src/plots/bubble/theme.ts
  src/plots/scatter/layer.ts
  src/plots/scatter/theme.ts
Labels: size/L

#752 fix: set default min scrollbar size
  __tests__/unit/plots/bar/bar-scrollbar-spec.ts
  src/interaction/scrollbar.ts
Labels: bug, size/M

#757 fix(types): add mask for ITimeAxis
  src/interface/config.ts
Labels: PR: reviewed-changes-requested, bug

#755 yunfengdie issue批量修复
  examples/bar/basic/demo/basic.js
  examples/bar/basic/demo/label-position.js
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/liquid/layer.ts
  src/sparkline/progress/layer.ts
Labels: PR: unreviewed, size/M

#764 fix: typo in doc: mata -> meta
  docs/manual/general-config.zh.md
Labels: PR: reviewed-approved, bug

#772 chore: update package.json
  package.json
  src/combo-plots/util/globalAxis.ts
Labels: PR: reviewed-changes-requested, chore, size/S

#775 fix: util import in sparkline
  __tests__/bugs/issue-556-spec.ts
  __tests__/bugs/issue-598-spec.ts
  __tests__/unit/rangeBar-spec.ts
  __tests__/unit/rangeColumn-spec.ts
  __tests__/unit/sunburst-spec.ts
  src/plots/scatter/layer.ts
  src/sparkline/progress/layer.ts
Labels: PR: unreviewed, bug, size/L

#780 [0.x] fix: show area labels with empty stackField
  src/plots/stack-area/component/label/area-label.ts
Labels: PR: reviewed-changes-requested, bug, size/M

#785 feat(donut): 环图指标卡新增`totalLabel`配置
  docs/manual/plots/donut.en.md
  docs/manual/plots/donut.zh.md
  examples/pie/donut/API.zh.md
  src/plots/donut/component/ring-statistic.ts
  src/plots/donut/layer.ts
Labels: PR: reviewed-changes-requested, enhancement, size/S

#787 更新网站广告位
  examples/pie/donut/API.zh.md
  site/pages/index.zh.tsx
Labels: PR: unreviewed, size/S

#797 fix: cleanup dependencies and imports
  .gitignore
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  __tests__/unit/util/common-spec.ts
  package.json
  src/combo-plots/util/globalAxis.ts
  src/combo-plots/util/globalLegend.ts
  src/combo-plots/util/globalTooltip.ts
  src/components/breadcrumb.ts
  src/dependents.ts
  src/plots/funnel/layer.ts
  src/plots/gauge/geometry/shape/gauge-shape.ts
  src/plots/treemap/interaction/drillDown.ts
  src/util/common.ts
  src/util/responsive/node/shape-nodes.ts
  src/util/responsive/responsive.ts
  src/util/responsive/rules/clear-overlapping.ts
  src/util/responsive/rules/digits-abbreviate.ts
  src/util/responsive/rules/node-jitter-upward.ts
  src/util/responsive/rules/node-jitter.ts
  src/util/responsive/rules/nodes-resampling-by-change.ts
  src/util/responsive/rules/nodes-resampling-by-state.ts
  src/util/responsive/rules/robust-abbrevaite.ts
  src/util/responsive/rules/text-abbreviate.ts
  src/util/responsive/rules/text-hide.ts
  src/util/responsive/rules/text-rotation.ts
  src/util/responsive/rules/text-wrapper.ts
  webpack.config.js
Labels: PR: reviewed-changes-requested, bug, size/L

#795 fix bugs
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/area/layer.ts
  src/plots/bar/layer.ts
  src/plots/bubble/layer.ts
  src/plots/calendar/layer.ts
  src/plots/column/layer.ts
  src/plots/density-heatmap/layer.ts
  src/plots/grouped-bar/layer.ts
  src/plots/grouped-column/layer.ts
  src/plots/grouped-rose/layer.ts
  src/plots/heatmap/layer.ts
  src/plots/line/layer.ts
  src/plots/pie/layer.ts
  src/plots/radar/layer.ts
  src/plots/rose/layer.ts
  src/plots/scatter/layer.ts
  src/plots/stacked-area/layer.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-column/layer.ts
  src/plots/stacked-rose/layer.ts
  src/plots/treemap/layer.ts
  src/plots/waterfall/layer.ts
  src/sparkline/progress/component/marker.ts
  src/sparkline/progress/layer.ts
  src/util/scale.ts
Labels: PR: unreviewed, size/L

#802 fix: cleanup webpack config
  webpack.config.js
Labels: PR: reviewed-changes-requested, bug, size/XS

#804 修复 tooltip 偏移的问题
  __tests__/bugs/issue-803-spec.ts
  src/base/controller/canvas.ts
Labels: PR: reviewed-changes-requested, size/M

#807 fix: pie meta Closes #806
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested, bug, size/XS

#808 chore: fix coverage badge
  README.md
Labels: PR: unreviewed, chore, size/XS

#809 fix: columnStyle/barStyle callback params
  __tests__/bugs/issue-769-spec.ts
  __tests__/data/sales.json
  __tests__/data/subsales.json
  __tests__/typing.d.ts
  src/geoms/interval/main.ts
Labels: PR: reviewed-changes-requested, bug, size/L

#812 feat: legend title
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, enhancement, size/XS

#791 Refactor docs
  docs/manual/plots/donut.en.md
  docs/manual/plots/donut.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  examples/pie/donut/API.zh.md
Labels: PR: reviewed-approved, size/XL

#816 fix demos
  examples/advanced/responsive/demo/responsive-axis.js
  examples/advanced/responsive/demo/responsive-label.js
  examples/line/multiple/demo/meta.json
  gatsby-browser.js
  src/plots/line/animation/clipIn-with-data.ts
Labels: PR: unreviewed, size/L

#819 feat: advanced sunburst color & style
  __tests__/unit/sunburst-spec.ts
  src/plots/sunburst/layer.ts
Labels: PR: reviewed-changes-requested, enhancement, size/M

#823 [0.x] yAxis设置min max后connectedArea没有同步截断
  src/components/connected-area.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#828 fix: upgrade g2
  package.json
  src/dependents.ts
  src/geoms/heatmap/linear.ts
Labels: PR: reviewed-changes-requested, bug, size/XS

#829 fix: donut statistic function name typo
  src/components/connected-area.ts
  src/components/conversion-tag.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/donut/component/statistic.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/range-bar/component/label.ts
  src/plots/range-column/component/label.ts
  src/plots/stacked-area/component/label/area-label.ts
  src/plots/treemap/components/label.ts
Labels: PR: unreviewed, bug, size/S

#832 Fix 0.x bugs
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/inner-label.ts
Labels: PR: unreviewed, size/S

#833 fix: remove type from gauge default options
  src/combo-plots/overlapped.ts
  src/combo-plots/util/globalAxis.ts
  src/plots/density-heatmap/layer.ts
  src/plots/gauge/options.ts
Labels: PR: unreviewed, bug, size/L

#839 fix: pie label autoRotate failed
  __tests__/bugs/issue-830-spec.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/utils/index.ts
Labels: PR: reviewed-approved, bug, size/L

#781 feat(marker-point): 标注点组件
  __tests__/unit/components/marker-point-spec.ts
  __tests__/unit/plots/line/line-with-markerPoint-spec.ts
  examples/line/marker/API.en.md
  examples/line/marker/API.zh.md
  examples/line/marker/demo/animate.js
  examples/line/marker/demo/basic.js
  examples/line/marker/demo/custom-image.js
  examples/line/marker/demo/custom-symbol.js
  examples/line/marker/demo/meta.json
  examples/line/marker/demo/multi-markerpoint.js
  examples/line/marker/design.en.md
  examples/line/marker/design.zh.md
  examples/line/marker/index.en.md
  examples/line/marker/index.zh.md
  src/components/marker-point.ts
  src/dependents.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-approved, WIP, enhancement, size/XXL

#849 feat(pie-label): 饼图标签允许关闭自动调整位置
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/outer-center-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/layer.ts
Labels: PR: reviewed-approved, enhancement, size/L

#848 图表通用属性走查 & fix
  examples/line/multiple/demo/line-label.js
  src/base/layer.ts
  src/base/view-layer.ts
  src/combo-plots/overlapped.ts
  src/components/breadcrumb.ts
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/density-heatmap/components/legend.ts
  src/plots/funnel/layer.ts
  src/plots/gauge/options.ts
  src/plots/heatmap/component/legend.ts
  src/plots/line/animation/clipIn-with-data.ts
  src/plots/line/layer.ts
  src/plots/liquid/layer.ts
  src/plots/waterfall/layer.ts
  src/sparkline/progress/layer.ts
Labels: PR: unreviewed, size/L

#851 折柱饼系列图表类型定义走查
  examples/line/marker/API.en.md
  examples/line/marker/API.zh.md
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/area/layer.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/donut/layer.ts
  src/plots/line/layer.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/layer.ts
  src/plots/radar/layer.ts
  src/plots/range-column/layer.ts
  src/plots/rose/layer.ts
  src/plots/stacked-area/layer.ts
  src/plots/waterfall/component/label/diff-label.ts
  src/plots/waterfall/layer.ts
Labels: PR: unreviewed, size/L

#853 fix: donut statistic auto size Closes #850
  src/plots/donut/component/ring-statistic.ts
  src/plots/donut/component/statistic.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#854 feat: 修复updateConfig后状态量更新失效
  src/base/controller/state.ts
Labels: PR: reviewed-changes-requested, enhancement

#837 refactor: common label component & label customize
  __tests__/unit/plots/bar/component/label-spec.ts
  __tests__/unit/plots/column/component/label-spec.ts
  __tests__/unit/plots/grouped-bar/groupedBar-spec.ts
  __tests__/unit/plots/grouped-column/groupedColumn-spec.ts
  __tests__/unit/plots/stacked-bar/stackedBar-spec.ts
  __tests__/unit/plots/stacked-column/component/label-spec.ts
  __tests__/unit/plots/stacked-column/stackColumn-spec.ts
  src/base/view-layer.ts
  src/components/base.ts
  src/components/label/label.ts
  src/dependents.ts
  src/interaction/scrollbar.ts
  src/interface/config.ts
  src/plots/bar/component/label.ts
  src/plots/bar/layer.ts
  src/plots/column/component/label.ts
  src/plots/column/layer.ts
  src/plots/index.ts
  src/plots/stacked-bar/component/label.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-column/component/label.ts
  src/plots/stacked-column/layer.ts
  src/plots/waterfall/component/label/waterfall-label.ts
  src/plots/waterfall/layer.ts
  src/util/view.ts
Labels: PR: reviewed-approved, refactor, size/XXL

#855 fix: shapeStyle
  docs/manual/plots/heatmap.en.md
  docs/manual/plots/heatmap.zh.md
  examples/heatmap/basic/API.zh.md
  src/plots/bullet/layer.ts
  src/plots/density-heatmap/layer.ts
  src/plots/funnel/layer.ts
  src/plots/gauge/options.ts
  src/plots/heatmap/component/legend.ts
  src/plots/heatmap/layer.ts
  src/plots/heatmap/shape.ts
  src/plots/liquid/geometry/shape/liquid.ts
  src/plots/liquid/layer.ts
  src/plots/scatter/layer.ts
Labels: PR: unreviewed, bug, size/L

#857 fix(#745): fix resize loop because canvas style
  src/base/controller/canvas.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#862 fix: percentStackedColumn demo Closes #859
  examples/column/percent-stacked/demo/basic.js
Labels: PR: unreviewed, bug, size/XS

#864 fix: treemap types
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/treemap/interaction/drillDown.ts
  src/plots/treemap/layer.ts
  src/sparkline/progress/layer.ts
Labels: PR: unreviewed, bug, size/M

#867 gauge style api
  src/plots/fan-gauge/layer.ts
  src/plots/gauge/geometry/shape/gauge-shape.ts
  src/plots/gauge/geometry/shape/options.ts
  src/plots/gauge/interface.ts
  src/plots/gauge/layer.ts
  src/plots/gauge/options.ts
  src/plots/gauge/theme.ts
  src/plots/liquid/layer.ts
  src/plots/meter-gauge/layer.ts
Labels: PR: unreviewed, size/XL
