Repository antvis/G2Plot, pull requests merged in 2020-09, with the labels that each got.

#1513 test(eslint): add import-order rules for eslint
  .eslintrc
  package.json
  src/core/plot.ts
  src/plots/_template/index.ts
  src/plots/area/index.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/box/adaptor.ts
  src/plots/column/index.ts
  src/plots/dual-axes/index.ts
  src/plots/line/index.ts
  src/plots/pie/index.ts
  src/plots/pie/label/index.ts
  src/plots/pie/label/inner-label.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/index.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/index.ts
  src/plots/rose/adaptor.ts
  src/plots/rose/index.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/index.ts
Labels: PR: reviewed-approved, test

#1516 V1 combo bugfix
  CHANGELOG.md
  package.json
  src/combo/base.ts
  src/combo/dual-line/layer.ts
Labels: PR: unreviewed

#1519 feat(plugin): add plugin plot for customize
  __tests__/unit/plugin/index-spec.ts
  __tests__/unit/plugin/step-line.ts
  src/core/plot.ts
  src/index.ts
  src/plugin/index.ts
Labels: PR: partially-approved, enhancement

#1499 feat(liquid): add new plot liquid
  __tests__/unit/plots/liquid/index-spec.ts
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  src/index.ts
  src/plots/_template/adaptor.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
  src/types/style.ts
  src/utils/g-util.ts
Labels: PR: unreviewed, enhancement

#1517 Feat/funnel
  examples/funnel/basic/demo/basic-transpose.ts
  examples/funnel/basic/demo/basic.ts
  examples/funnel/basic/demo/compare-transpose.ts
  examples/funnel/basic/demo/compare.ts
  examples/funnel/basic/demo/dynamic-height-transpose.ts
  examples/funnel/basic/demo/dynamic-height.ts
  examples/funnel/basic/demo/meta.json
  examples/funnel/basic/design.en.md
  examples/funnel/basic/design.zh.md
  examples/funnel/basic/index.en.md
  examples/funnel/basic/index.zh.md
  gatsby-config.js
  src/core/plot.ts
  src/index.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/constant.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/dynamic-height.ts
  src/plots/funnel/geometries/util.ts
  src/plots/funnel/index.ts
  src/plots/funnel/types.ts
Labels: PR: partially-approved

#1527 chore: add limit-size
  package.json
  webpack.config.js
Labels: PR: unreviewed, chore

#1529 refactor: remove groupField, colorField, stackField in bar and column
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/column/index-spec.ts
  __tests__/unit/plots/column/label-spec.ts
  examples/bar/basic/demo/color.ts
  examples/bar/grouped/demo/basic.ts
  examples/bar/grouped/demo/label-position.ts
  examples/bar/grouped/demo/label.ts
  examples/bar/grouped/demo/margin.ts
  examples/bar/stacked/demo/basic.ts
  examples/bar/stacked/demo/label-position.ts
  examples/bar/stacked/demo/label.ts
  examples/column/basic/demo/color.ts
  examples/column/grouped/demo/basic.ts
  examples/column/grouped/demo/label-position.ts
  examples/column/grouped/demo/label.ts
  examples/column/grouped/demo/margin.ts
  examples/column/stacked/demo/basic.ts
  examples/column/stacked/demo/label-position.ts
  examples/column/stacked/demo/label.ts
  examples/dual-axes/dual-line/API.en.md
  examples/dual-axes/dual-line/API.zh.md
  examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-multi-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
  examples/dual-axes/stacked-column-line/demo/stacked-column-multi-line.ts
  src/adaptor/geometries/interval.ts
  src/plots/box/types.ts
  src/plots/column/types.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/geometry.ts
Labels: PR: partially-approved, refactor

#1522 feat: scatter chart supported quadrant
  __tests__/unit/plots/scatter/quadrant-spec.ts
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/quadrant.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/types.ts
  src/plots/scatter/util.ts
  src/types/common.ts
Labels: PR: unreviewed, enhancement

#1502 feat(v2/candle): add candle plot
  __tests__/data/stock.ts
  __tests__/unit/plots/stock/axis-spec.ts
  __tests__/unit/plots/stock/index-spec.ts
  __tests__/unit/plots/stock/tooltip-spec.ts
  package.json
  src/index.ts
  src/plots/stock/adaptor.ts
  src/plots/stock/constant.ts
  src/plots/stock/index.ts
  src/plots/stock/types.ts
Labels: PR: reviewed-approved, enhancement

#1531 chore: 2.0.0-beta.3
  __tests__/unit/plugin/index-spec.ts
  __tests__/unit/plugin/step-line.ts
  package.json
  src/core/plot.ts
  src/index.ts
  src/plugin/index.ts
Labels: PR: partially-approved, chore

#1535 fix: 修复散点图单测问题
  __tests__/unit/plots/scatter/tooltip-spec.ts
Labels: PR: unreviewed, bug

#1427 feat: v2版子弹图bullet初稿
  __tests__/data/bullet.ts
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/data-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/label-spec.ts
  __tests__/unit/plots/bullet/legend-spec.ts
  __tests__/unit/plots/bullet/tooltip-spec.ts
  src/index.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
  src/plots/bullet/types.ts
  src/plots/bullet/utils.ts
Labels: PR: unreviewed, enhancement

#1534 Fix/dual axes
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-column/theme-spec.ts
  examples/dual-axes/column-line/demo/column-line.ts
  examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
  src/adaptor/geometries/interval.ts
  src/adaptor/geometries/line.ts
  src/adaptor/geometries/point.ts
  src/core/plot.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/util/option.ts
  src/plots/pie/interaction/pie-legend-action.ts
  src/plots/rose/adaptor.ts
Labels: PR: partially-approved

#1538 chore: upgrade to latest g2
  package.json
Labels: PR: partially-approved, chore

#1541 chore: area 走查优化
  __tests__/unit/plots/area/index-spec.ts
  examples/area/basic/demo/basic-gradients.ts
  examples/area/basic/demo/basic-slider.ts
  examples/area/basic/demo/meta.json
  examples/area/stacked/demo/basic-slider.ts
  examples/area/stacked/demo/meta.json
  src/plots/area/index.ts
Labels: PR: reviewed-approved, chore

#1543 feat: demo upgrade
  examples/pie/basic/demo/basic.ts
  examples/pie/basic/demo/pie-state.ts
  examples/pie/basic/demo/pie-texture.ts
  examples/pie/donut/demo/basic.ts
  examples/radar/basic/demo/basic.ts
  examples/radar/basic/demo/crosshairs.ts
  examples/radar/basic/demo/grid-axis.ts
  examples/radar/basic/demo/meta.json
  src/plots/pie/label/inner-label.ts
  src/plots/radar/index.ts
Labels: PR: reviewed-approved, enhancement

#1533 feat(legend): add legend to dual-axes
  src/core/plot.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: partially-approved, WIP, enhancement

#1544 Fix line bugs
  __tests__/unit/plots/line/annotation-spec.ts
  api-extractor.json
  examples/area/basic/demo/basic-annotation.ts
  examples/area/basic/demo/meta.json
  examples/line/basic/demo/line-annotation.ts
  examples/line/basic/demo/line-slider.ts
  examples/line/basic/demo/meta.json
  src/plots/line/index.ts
Labels: PR: reviewed-approved

#1530 feat(v2/word-cloud): 新增词云图
  __tests__/unit/plots/word-cloud/animation-spec.ts
  __tests__/unit/plots/word-cloud/axis-spec.ts
  __tests__/unit/plots/word-cloud/index-spec.ts
  __tests__/unit/plots/word-cloud/label-spec.ts
  __tests__/unit/plots/word-cloud/legend-spec.ts
  __tests__/unit/plots/word-cloud/style-spec.ts
  __tests__/unit/plots/word-cloud/tooltip-spec.ts
  src/index.ts
  src/plots/word-cloud/adaptor.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/shapes/word-cloud.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved, enhancement

#1545 feat: 新改动子弹图和新增docs
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/data-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/label-spec.ts
  __tests__/unit/plots/bullet/tooltip-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/basic.ts
  examples/bullet/basic/demo/color.ts
  examples/bullet/basic/demo/grouped.ts
  examples/bullet/basic/demo/meta.json
  examples/bullet/basic/demo/stacked.ts
  examples/bullet/basic/design.en.md
  examples/bullet/basic/design.zh.md
  examples/bullet/basic/index.en.md
  examples/bullet/basic/index.zh.md
  gatsby-config.js
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
  src/plots/bullet/types.ts
  src/plots/bullet/utils.ts
Labels: PR: reviewed-approved, enhancement

#1548 refactor plot attr
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  __tests__/unit/plots/pie/index-spec.ts
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  examples/pie/basic/demo/pie-texture.ts
  examples/progress/basic/demo/progress-style-callback.ts
  examples/ring-progress/basic/demo/ring-progress-style-callback.ts
  examples/tiny-column/basic/demo/column-style-callback.ts
  examples/tiny-column/basic/demo/column.ts
  examples/tiny-line/basic/demo/line-style.ts
  examples/tiny-line/basic/demo/line.ts
  src/plots/histogram/adaptor.ts
  src/plots/histogram/types.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/types.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/types.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/types.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/rose/adaptor.ts
  src/plots/rose/types.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/types.ts
  src/types/common.ts
  src/types/tooltip.ts
Labels: PR: partially-approved

#1553 fix: 解决走查问题和修复遗漏问题（#1536）
  examples/histogram/basic/demo/basic.ts
  src/plots/bullet/index.ts
Labels: PR: reviewed-approved, bug

#1552 docs: 添加玫瑰图文档及demo
  examples/rose/basic/API.en.md
  examples/rose/basic/API.zh.md
  examples/rose/basic/demo/basic.ts
  examples/rose/basic/demo/inner-label.ts
  examples/rose/basic/demo/interaction.ts
  examples/rose/basic/demo/meta.json
  examples/rose/basic/demo/rose-state.ts
  examples/rose/basic/design.en.md
  examples/rose/basic/design.zh.md
  examples/rose/basic/index.en.md
  examples/rose/basic/index.zh.md
  examples/rose/grouped/API.en.md
  examples/rose/grouped/API.zh.md
  examples/rose/grouped/demo/basic.ts
  examples/rose/grouped/demo/meta.json
  examples/rose/grouped/design.en.md
  examples/rose/grouped/design.zh.md
  examples/rose/grouped/index.en.md
  examples/rose/grouped/index.zh.md
  examples/rose/stacked/API.en.md
  examples/rose/stacked/API.zh.md
  examples/rose/stacked/demo/basic.ts
  examples/rose/stacked/demo/meta.json
  examples/rose/stacked/design.en.md
  examples/rose/stacked/design.zh.md
  examples/rose/stacked/index.en.md
  examples/rose/stacked/index.zh.md
  gatsby-config.js
  src/plots/rose/adaptor.ts
  src/plots/rose/types.ts
Labels: PR: reviewed-approved, documentation

#1561 docs: 通用文档补充
  docs/common/color.en.md
  docs/common/color.zh.md
  docs/common/events.en.md
  docs/common/events.zh.md
  docs/common/legend.en.md
  docs/common/legend.zh.md
  docs/common/marker.en.md
  docs/common/marker.zh.md
  docs/common/meta.en.md
  docs/common/meta.zh.md
  docs/common/template.en.md
  docs/common/template.zh.md
  docs/common/theme.en.md
  docs/common/theme.zh.md
  docs/common/xy-field.en.md
  docs/common/xy-field.zh.md
  docs/manual/theme.en.md
  docs/manual/theme.zh.md
  examples/rose/basic/API.en.md
  examples/rose/basic/API.zh.md
  examples/rose/grouped/API.en.md
  examples/rose/grouped/API.zh.md
  examples/rose/stacked/API.en.md
  examples/rose/stacked/API.zh.md
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
Labels: PR: unreviewed, documentation

#1568 fix: [1.x]修复漏斗图不能设置label visible false的问题
  CHANGELOG.md
  package.json
  src/plots/funnel/layer.ts
Labels: PR: partially-approved, bug

#1566 feat: v2增强子弹图
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/label-spec.ts
  __tests__/unit/plots/bullet/layout-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/layout.ts
  examples/bullet/basic/demo/meta.json
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
  src/plots/bullet/types.ts
Labels: PR: reviewed-approved, enhancement

#1567 add Stock docs and demo
  examples/stock/basic/API.en.md
  examples/stock/basic/API.zh.md
  examples/stock/basic/demo/basic.ts
  examples/stock/basic/demo/meta.json
  examples/stock/basic/index.en.md
  examples/stock/basic/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#1565 走查修复进度条图，进度环图
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/constant.ts
  src/plots/progress/index.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/index.ts
  src/plots/ring-progress/types.ts
Labels: PR: partially-approved

#1572 Demo walkthrough
  examples/general/annotation/demo/image-annotation.ts
  examples/general/annotation/demo/meta.json
  examples/general/annotation/demo/range-annotation.ts
  examples/general/state/API.en.md
  examples/general/state/API.zh.md
  examples/general/state/demo/custom-state-style.ts
  examples/general/state/demo/meta.json
  examples/general/state/demo/set-state.ts
  examples/general/state/index.en.md
  examples/general/state/index.zh.md
  examples/radar/basic/demo/basic.ts
  examples/radar/basic/demo/grid-axis.ts
  examples/radar/basic/demo/meta.json
  examples/radar/basic/demo/series.ts
  src/plots/radar/interaction/index.ts
Labels: PR: reviewed-approved

#1573 attr mapping string
  .lintmdrc
  __tests__/unit/adaptor/geometries/base-spec.ts
  __tests__/unit/plots/scatter/size-spec.ts
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/interval.ts
  src/adaptor/geometries/point.ts
  src/core/plot.ts
  src/plots/box/types.ts
  src/plots/histogram/adaptor.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/types.ts
  src/types/common.ts
Labels: PR: unreviewed

#1575 fix(geometry): 修改 geometry/base 中存在多个相同的时候,导致索引出错
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/interval.ts
  src/core/adaptor.ts
Labels: PR: partially-approved, bug

#1577 fix: fix api-extractor does not support the export * as syntax
  package.json
  src/index.ts
Labels: PR: reviewed-approved, bug

#1576 Liquid demo
  examples/liquid/basic/demo/basic.ts
  examples/liquid/basic/demo/meta.json
  examples/liquid/basic/demo/style.ts
  examples/liquid/basic/design.en.md
  examples/liquid/basic/design.zh.md
  examples/liquid/basic/index.en.md
  examples/liquid/basic/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#1578 fix: 修复迷你图 tooltip 不统一
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/constants.ts
  src/plots/tiny-line/types.ts
  src/types/tooltip.ts
Labels: PR: reviewed-approved, bug

#1584 fix(liquid): 升级 G2,使用正确的方式向自定义 shape 传参
  package.json
  src/plots/liquid/adaptor.ts
  src/plots/liquid/shapes/liquid.ts
Labels: PR: reviewed-approved, bug

#1579 refactor: 改造v2子弹图为统一风格方式
  __tests__/data/bullet.ts
  __tests__/unit/plots/bullet/data-spec.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/utils.ts
  src/plots/histogram/adaptor.ts
Labels: PR: reviewed-approved, refactor

#1582 docs: 补充使用文档
  docs/common/events.en.md
  docs/common/events.zh.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  docs/manual/graphic-style.en.md
  docs/manual/graphic-style.zh.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  docs/manual/theme.en.md
  docs/manual/theme.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: unreviewed, documentation

#1587 refactor(statistic): 统一中心文本结构
  examples/liquid/basic/demo/style.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/types.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/types.ts
  src/types/index.ts
  src/types/statistic.ts
Labels: PR: reviewed-approved, refactor

#1571 docs(word-cloud): 添加词云图文档和demo
  __tests__/unit/plots/word-cloud/style-spec.ts
  examples/word-cloud/basic/API.en.md
  examples/word-cloud/basic/API.zh.md
  examples/word-cloud/basic/demo/basic.ts
  examples/word-cloud/basic/demo/image-mask.ts
  examples/word-cloud/basic/demo/meta.json
  examples/word-cloud/basic/design.en.md
  examples/word-cloud/basic/design.zh.md
  examples/word-cloud/basic/index.en.md
  examples/word-cloud/basic/index.zh.md
  gatsby-config.js
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/types.ts
Labels: PR: reviewed-approved, documentation

#1592 docs: 修改文档和优化demo
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  examples/bullet/basic/demo/basic.ts
  examples/bullet/basic/demo/color.ts
  examples/bullet/basic/demo/grouped.ts
  examples/bullet/basic/demo/layout.ts
  examples/bullet/basic/demo/meta.json
  examples/bullet/basic/demo/stacked.ts
  src/plots/bullet/utils.ts
Labels: PR: reviewed-approved, documentation

#1593 docs: 修改 word cloud 套娃路径
  examples/word-cloud/basic/API.en.md
  examples/word-cloud/basic/API.zh.md
Labels: PR: unreviewed, documentation

#1590 refactor(ring): 环图中心文本统一结构
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interaction/pie-statistic-action.ts
  src/plots/pie/types.ts
  src/plots/pie/utils.ts
  src/types/statistic.ts
Labels: PR: reviewed-approved, refactor

#1594 fix: 修复 slider demos, 新增 scrollbar
  docs/common/chart-methods.en.md
  docs/common/chart-methods.zh.md
  docs/manual/upgrade.zh.md
  examples/area/basic/demo/basic-slider.ts
  examples/area/stacked/demo/basic-slider.ts
  examples/line/basic/demo/line-slider.ts
  examples/tiny-line/basic/demo/line-style.ts
  src/adaptor/common.ts
  src/plots/column/adaptor.ts
  src/plots/word-cloud/utils.ts
  src/types/common.ts
  src/types/scrollbar.ts
  src/types/slider.ts
Labels: PR: reviewed-approved, bug

#1596 feat: 发布新版本
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, enhancement

#1598 fix: 默默修复颜色问题，定义不同映射颜色的key
  __tests__/unit/plots/bullet/data-spec.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/utils.ts
Labels: PR: partially-approved, bug

#1595 Fix/dual axes
  __tests__/unit/plots/dual-axes/column-line-spec.ts
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/geometry.ts
  src/plots/dual-axes/util/legend.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: unreviewed

#1600 fix(sync-view-padding): add syncViewPadding in core plot
  package.json
  src/core/plot.ts
  src/types/common.ts
Labels: PR: unreviewed, bug

#1602 refactor(example): 主题、状态量、标注等demo和截图走查
  examples/general/annotation/demo/meta.json
  examples/general/annotation/demo/region-annotation.ts
  examples/general/state/demo/meta.json
  examples/general/theme/demo/dark.ts
Labels: PR: reviewed-approved, refactor

#1601 feat(pie): support spider-label
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/spider-label.ts
  src/plots/pie/adaptor.ts
Labels: PR: partially-approved, enhancement

#1607 fix(word-cloud): word cloud should exec data-set transform when resize
  examples/word-cloud/basic/demo/basic.ts
  examples/word-cloud/basic/demo/image-mask.ts
  src/core/plot.ts
  src/plots/word-cloud/index.ts
Labels: PR: reviewed-approved, bug

#1608 fix: 优化散点图 demos
  examples/scatter/basic/demo/basic.ts
  examples/scatter/basic/demo/color-mapping.ts
  examples/scatter/basic/demo/label.ts
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/quadrant.ts
  examples/scatter/basic/demo/shape-mapping.ts
  examples/scatter/basic/demo/size.ts
Labels: PR: reviewed-approved, bug

#1603 feat(word-cloud): 主要是添加图表尺寸变化时自动重渲染
  examples/word-cloud/basic/API.zh.md
  examples/word-cloud/basic/demo/interaction.ts
  examples/word-cloud/basic/demo/meta.json
  src/plots/word-cloud/adaptor.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
Labels: PR: partially-approved, enhancement

#1614 fix: 修复双轴图相关 bugs
  CHANGELOG.md
  __tests__/unit/combo/columnLine-spec.ts
  package.json
  src/combo/column-line/index.ts
  src/combo/column-line/layer.ts
  src/combo/dual-line/index.ts
  src/combo/dual-line/layer.ts
Labels: PR: unreviewed, bug

#1618 Fix duax animation
  examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: partially-approved

#1605 feat: 增加显示目标值label #1599
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/label-spec.ts
  __tests__/unit/plots/bullet/legend-spec.ts
  __tests__/unit/plots/bullet/tooltip-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/basic.ts
  examples/bullet/basic/demo/color.ts
  examples/bullet/basic/demo/grouped.ts
  examples/bullet/basic/demo/layout.ts
  examples/bullet/basic/demo/stacked.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
  src/plots/bullet/types.ts
Labels: PR: reviewed-approved, enhancement

#1625 fix(line): fix error when color field is cat
  __tests__/unit/adaptor/geometries/base-spec.ts
  src/adaptor/geometries/base.ts
Labels: PR: reviewed-approved, bug

#1627 fix(v2-bullet): 修复legend错误
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
Labels: PR: reviewed-approved, bug

#1628 Fix dual axes view filter
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/legend.ts
Labels: PR: reviewed-approved

#1617 feat(word-cloud): imageMask选项支持url字符串格式
  examples/word-cloud/basic/API.en.md
  examples/word-cloud/basic/API.zh.md
  examples/word-cloud/basic/demo/image-mask-base64.ts
  examples/word-cloud/basic/demo/image-mask.ts
  examples/word-cloud/basic/demo/meta.json
  package.json
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/types.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved, enhancement

#1630 feat: 旭日图类型定义和实现
  __tests__/unit/plots/sunburst/index-spec.ts
  src/adaptor/geometries/index.ts
  src/adaptor/geometries/polygon.ts
  src/index.ts
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/index.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
Labels: PR: unreviewed, enhancement

#1631 Fix/dual axes column
  __tests__/data/pv-uv.ts
  __tests__/unit/plots/dual-axes/axis-spec.ts
  __tests__/unit/plots/dual-axes/column-line-spec.ts
  __tests__/unit/plots/dual-axes/column-spec.ts
  __tests__/unit/plots/dual-axes/double-line-spec.ts
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/plots/dual-axes/line-spec.ts
  examples/dual-axes/column-line/demo/column-multi-line.ts
  examples/dual-axes/column-line/demo/custom-column-line.ts
  examples/dual-axes/column-line/demo/demo-more-1.ts
  examples/dual-axes/column-line/demo/meta.json
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/constant.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/util/legend.ts
  src/plots/dual-axes/util/option.ts
  src/utils/index.ts
  src/utils/view.ts
Labels: PR: partially-approved

#1633 docs: 新增旭日图 demos 和 API
  __tests__/unit/plots/sunburst/index-spec.ts
  docs/common/component-polygon.en.md
  docs/common/component-polygon.zh.md
  examples/sunburst/basic/API.en.md
  examples/sunburst/basic/API.zh.md
  examples/sunburst/basic/demo/basic.ts
  examples/sunburst/basic/demo/meta.json
  examples/sunburst/basic/demo/reflect.ts
  examples/sunburst/basic/design.en.md
  examples/sunburst/basic/design.zh.md
  examples/sunburst/basic/index.en.md
  examples/sunburst/basic/index.zh.md
  gatsby-config.js
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
Labels: PR: unreviewed, documentation

#1635 feat: modified version
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, enhancement

#1613 feat(gauge): new plot gauge
  __tests__/unit/plots/gauge/index-spec.ts
  src/index.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/constant.ts
  src/plots/gauge/index.ts
  src/plots/gauge/shapes/gauge.ts
  src/plots/gauge/types.ts
  src/plots/gauge/utils.ts
Labels: PR: partially-approved, enhancement

#1637 Feat plugin docs
  README.md
  README.zh-CN.md
  __tests__/unit/adaptor/geometries/base-spec.ts
  __tests__/unit/plugin/index-spec.ts
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/introduction.zh.md
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  src/index.ts
  src/plugin/index.ts
Labels: PR: partially-approved

#1639 fix: demos and reaname dual axes option
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  examples/pie/basic/API.en.md
  examples/pie/basic/API.zh.md
  examples/radar/basic/API.en.md
  examples/radar/basic/API.zh.md
  examples/scatter/basic/API.zh.md
  src/index.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/index.ts
  src/plots/dual-axes/types.ts
  src/plots/dual-axes/util/option.ts
  src/plots/word-cloud/index.ts
Labels: PR: reviewed-approved, bug

#1638 docs: 增加一个line的annatation的demo
  examples/line/basic/demo/line-annotation-color.ts
  examples/line/basic/demo/meta.json
Labels: PR: reviewed-approved, documentation

#1641 chore(word-cloud): remove any type
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved, chore

#1640 docs(introduction): 更新简介英文文档
  docs/manual/getting-started.en.md
  docs/manual/introduction.en.md
Labels: PR: reviewed-approved, documentation

#1643 chore(word-cloud): 完善词云图单测
  __tests__/unit/plots/word-cloud/utils-spec.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved, chore

#1644 test: 增加修改bullet测试用例
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/data-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
Labels: PR: reviewed-approved, test

#1650 chore: v2.0.0
  package.json
  src/index.ts
Labels: PR: unreviewed, chore

#1648 docs(linestyle): 更新line-style英文文档
  docs/common/line-style.en.md
Labels: PR: unreviewed, documentation

#1651 docs(meta): 更新meta英文文档
  docs/common/meta.en.md
Labels: PR: unreviewed, documentation

#1652 docs(xyfield): 更新xyfield英文文档
  docs/common/xy-field.en.md
Labels: PR: unreviewed, documentation

#1654 docs: 更新common文档中的英文标题
  docs/common/API.en.md
  docs/common/component-no-axis.en.md
  docs/common/component-polygon.en.md
  docs/common/component-progress.en.md
  docs/common/component-tiny-en.md
  docs/common/component.en.md
Labels: PR: reviewed-approved, documentation

#1656 fix(website): 直接显示1.x给人感觉是当前是 1.x 版本
  gatsby-config.js
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, bug

#1653 feat(gauge): add statistic, demo, docs
  __tests__/unit/plots/gauge/index-spec.ts
  examples/gauge/basic/API.en.md
  examples/gauge/basic/API.zh.md
  examples/gauge/basic/demo/basic.ts
  examples/gauge/basic/demo/complex.ts
  examples/gauge/basic/demo/meta.json
  examples/gauge/basic/design.en.md
  examples/gauge/basic/design.zh.md
  examples/gauge/basic/index.en.md
  examples/gauge/basic/index.zh.md
  gatsby-config.js
  src/plots/gauge/adaptor.ts
  src/plots/gauge/index.ts
Labels: PR: partially-approved, enhancement

#1658 docs: 修改文档描述
  docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved, documentation

#1636 fix: 修复 column/bar 图例设置 & demo 更新
  __tests__/unit/plots/column/index-spec.ts
  examples/bar/basic/demo/label-position.ts
  examples/bar/basic/demo/label.ts
  examples/bar/basic/demo/meta.json
  examples/bar/grouped/demo/label-position.ts
  examples/bar/grouped/demo/label.ts
  examples/bar/grouped/demo/meta.json
  examples/bar/stacked/demo/label-position.ts
  examples/bar/stacked/demo/label.ts
  examples/bar/stacked/demo/meta.json
  examples/column/basic/demo/label-position.ts
  examples/column/basic/demo/label.ts
  examples/column/basic/demo/meta.json
  examples/column/grouped/demo/label-position.ts
  examples/column/grouped/demo/label.ts
  examples/column/grouped/demo/meta.json
  examples/column/stacked/demo/label-position.ts
  examples/column/stacked/demo/label.ts
  examples/column/stacked/demo/meta.json
  package.json
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
Labels: PR: unreviewed, bug

#1660 feat: changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, enhancement

#1661 docs: 修复缩略图 demo 不一致, 删除重复 demo
  examples/area/basic/demo/meta.json
  examples/area/stacked/demo/area-large-data.ts
  examples/area/stacked/demo/basic.ts
  examples/area/stacked/demo/meta.json
  examples/bar/basic/demo/meta.json
  examples/bar/grouped/demo/basic.ts
  examples/bar/grouped/demo/label.ts
  examples/bar/grouped/demo/margin.ts
  examples/bar/grouped/demo/meta.json
  examples/bar/stacked/demo/basic.ts
  examples/bar/stacked/demo/label.ts
  examples/bar/stacked/demo/meta.json
  examples/box/basic/demo/meta.json
  examples/bullet/basic/demo/meta.json
  examples/column/basic/demo/meta.json
  examples/column/grouped/demo/basic.ts
  examples/column/grouped/demo/label.ts
  examples/column/grouped/demo/margin.ts
  examples/column/grouped/demo/meta.json
  examples/column/stacked/demo/basic.ts
  examples/column/stacked/demo/label.ts
  examples/dual-axes/column-line/demo/column-line.ts
  examples/dual-axes/column-line/demo/meta.json
  examples/dual-axes/dual-line/demo/meta.json
  examples/dual-axes/stacked-column-line/demo/meta.json
  examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
  examples/funnel/basic/demo/meta.json
  examples/gauge/basic/demo/meta.json
  examples/line/basic/demo/line-with-point.ts
  examples/line/basic/demo/meta.json
  examples/line/multiple/demo/line-color.ts
  examples/line/multiple/demo/meta.json
  examples/liquid/basic/demo/meta.json
  examples/liquid/basic/demo/style.ts
  examples/progress/basic/demo/meta.json
  examples/progress/basic/demo/progress.ts
  examples/ring-progress/basic/demo/meta.json
  examples/rose/basic/demo/basic.ts
  examples/rose/basic/demo/interaction.ts
  examples/rose/basic/demo/meta.json
  examples/rose/basic/demo/rose-state.ts
  examples/rose/grouped/index.en.md
  examples/rose/grouped/index.zh.md
  examples/rose/stacked/index.en.md
  examples/rose/stacked/index.zh.md
  examples/stock/basic/demo/meta.json
  examples/sunburst/basic/demo/meta.json
  examples/tiny-area/basic/demo/meta.json
  examples/tiny-column/basic/demo/meta.json
  examples/tiny-line/basic/demo/meta.json
  examples/word-cloud/basic/demo/meta.json
Labels: PR: unreviewed, documentation

#1664 chore: 完善词云图和玫瑰图的单测用例
  __tests__/unit/plots/rose/label-spec.ts
  __tests__/unit/plots/rose/legend-spec.ts
  __tests__/unit/plots/word-cloud/index-spec.ts
  __tests__/unit/plots/word-cloud/utils-spec.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved, chore

#1668 fix(word-cloud): 修复this指向问题
  src/plots/word-cloud/index.ts
Labels: PR: reviewed-approved, bug

#1666 fix(tiny): tiny 图的 tooltip 默认给一个格式化,修改 demo 和单测
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  examples/tiny-area/basic/demo/area-style.ts
  examples/tiny-area/basic/demo/area.ts
  examples/tiny-column/basic/demo/column.ts
  examples/tiny-line/basic/demo/line.ts
  gatsby-config.js
  src/plots/tiny-line/constants.ts
Labels: PR: partially-approved, bug

#1663 feat: trend demo
  examples/gallery/trend/demo/basic.ts
  examples/gallery/trend/demo/meta.json
  examples/gallery/trend/demo/mobile.ts
  examples/gallery/trend/index.en.md
  examples/gallery/trend/index.zh.md
  gatsby-config.js
  src/plots/line/adaptor.ts
Labels: PR: partially-approved, enhancement

#1670 fix(bullet): 修复文档和demo的问题
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/color.ts
  examples/bullet/basic/demo/layout.ts
Labels: PR: reviewed-approved, bug

#1672 fix(geometry): line, area color field ignore xField
  __tests__/unit/adaptor/geometries/base-spec.ts
  src/adaptor/geometries/base.ts
  src/plots/pie/interaction/pie-statistic-action.ts
  src/plots/tiny-line/constants.ts
Labels: PR: unreviewed, bug

#1674 feat(transform): add supportCSSTransform option
  src/core/plot.ts
  src/types/common.ts
Labels: PR: reviewed-approved, enhancement

#1673 fix(indicator): when indicator > 1 or < 0 in gauge, progress, ring
  __tests__/unit/plots/gauge/index-spec.ts
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/core/plot.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/index.ts
  src/plots/progress/adaptor.ts
Labels: PR: unreviewed, bug

#1676 fix: 修复一些demo的小问题
  examples/column/stacked/demo/basic.ts
  examples/line/multiple/demo/line-label.ts
Labels: PR: reviewed-approved, bug

#1675 feat(website): add css for demo container
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: unreviewed, enhancement

#1677 chore: run PR preview on pull_request
  .github/workflows/preview.yml
  package.json
Labels: PR: reviewed-approved, chore

#1681 feat: open mirror
  .github/workflows/mirror.yml
Labels: PR: unreviewed, enhancement
