Repository antvis/G2Plot, pull requests merged in 2020-04, with the labels that each got.

#870 refactor: 折线图/面积图/堆积面积图的point label
  __tests__/unit/components/label/point-spec.ts
  __tests__/unit/plots/area/areaLabel-spec.ts
  __tests__/unit/plots/stacked-area/stackArea-label-spec.ts
  src/base/controller/canvas.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/components/base.ts
  src/components/label/base.ts
  src/components/label/point.ts
  src/plots/area/layer.ts
  src/plots/bar/component/label.ts
  src/plots/column/component/label.ts
  src/plots/line/layer.ts
  src/plots/stacked-area/layer.ts
  src/plots/stacked-bar/component/label.ts
  src/plots/stacked-column/component/label.ts
  src/plots/waterfall/component/label/waterfall-label.ts
Labels: PR: unreviewed, refactor, size/L

#878 docs: fix English gallery page wrong order
  examples/step-line/basic/index.en.md
  examples/step-line/multiple/index.en.md
Labels: PR: reviewed-approved, documentation, size/XS

#880 fix: changeData and updateConfig fix
  __tests__/bugs/issue-813-spec.ts
  __tests__/bugs/issue-866-spec.ts
  __tests__/utils/common.ts
  package.json
  src/base/layer.ts
  src/base/view-layer.ts
  src/interaction/base.ts
  src/interaction/slider.ts
Labels: PR: unreviewed, bug, size/L

#885 feat: 数据标签动画补上
  __tests__/unit/components/label/label-spec.ts
  __tests__/unit/plots/stacked-area/stackArea-label-spec.ts
  __tests__/unit/plots/stacked-column/component/label-spec.ts
  src/components/label/base.ts
  src/components/label/point.ts
  src/dependents.ts
  src/plots/bar/component/label.ts
  src/plots/column/component/label.ts
Labels: PR: reviewed-approved, enhancement, size/L

#889 feat: line point shape callback
  src/geoms/point/guide.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-approved, enhancement, size/S

#892 docs: Remove unwanted merge conflicts code
  examples/bullet/basic/index.en.md
Labels: PR: unreviewed, documentation

#871 feat: add timeline
  __tests__/data/life-expectancy.ts
  __tests__/unit/components/timeline-spec.ts
  __tests__/unit/plots/bubble/bubble-spec.ts
  demos/bubble-timeline.ts
  docs/manual/plots/bubble.en.md
  docs/manual/plots/bubble.zh.md
  examples/bubble/basic/API.zh.md
  examples/bubble/basic/demo/meta.json
  examples/bubble/basic/demo/timeline.js
  examples/data/life-expectancy.json
  src/components/base.ts
  src/components/timeline/button.ts
  src/components/timeline/index.ts
  src/interaction/index.ts
  src/interaction/timeline.ts
  src/interface/config.ts
  src/plots/bubble/layer.ts
  src/plots/scatter/layer.ts
  src/util/scale.ts
Labels: PR: reviewed-approved, enhancement, size/XXL

#896 chore: remove unnecessary link Closes #859
  docs/manual/getting-started.zh.md
  docs/manual/plots/column.zh.md
  examples/advanced/connection/demo/meta.json
  examples/area/basic/demo/meta.json
  examples/area/percent-stacked/demo/meta.json
  examples/area/stacked/demo/meta.json
  examples/bar/basic/demo/meta.json
  examples/bar/grouped/demo/meta.json
  examples/bar/percent-stacked/demo/meta.json
  examples/bar/range/demo/meta.json
  examples/bar/stacked/demo/meta.json
  examples/bubble/basic/demo/meta.json
  examples/bullet/basic/demo/meta.json
  examples/calendar/basic/demo/meta.json
  examples/column/basic/demo/meta.json
  examples/column/grouped/demo/meta.json
  examples/column/histogram/demo/meta.json
  examples/column/percent-stacked/demo/meta.json
  examples/column/range/demo/meta.json
  examples/column/stacked/demo/meta.json
  examples/column/waterfall/demo/meta.json
  examples/combo/basic/demo/meta.json
  examples/funnel/basic/demo/meta.json
  examples/gauge/gauge/demo/meta.json
  examples/general/axis/demo/meta.json
  examples/general/label/demo/meta.json
  examples/general/legend/demo/meta.json
  examples/heatmap/basic/demo/meta.json
  examples/heatmap/density/demo/meta.json
  examples/line/basic/demo/meta.json
  examples/line/marker/demo/meta.json
  examples/line/multiple/demo/meta.json
  examples/liquid/basic/demo/meta.json
  examples/pie/basic/demo/meta.json
  examples/pie/donut/demo/meta.json
  examples/radar/basic/demo/meta.json
  examples/rose/rose/demo/meta.json
  examples/scatter/basic/demo/meta.json
  examples/step-line/basic/demo/meta.json
  examples/treemap/rect/demo/meta.json
  examples/word-cloud/basic/demo/meta.json
Labels: PR: unreviewed, chore, size/L

#891 fix(word-cloud2): under the IE11 settings.animatable not allowed duplicate define
  src/plots/word-cloud/wordcloud2.ts
Labels: PR: reviewed-changes-requested, bug

#905 fix: correct label position for negative data
  __tests__/data/common.ts
  __tests__/unit/plots/bar/component/label-spec.ts
  __tests__/unit/plots/column/component/label-spec.ts
  package.json
  src/interface/config.ts
  src/plots/bar/component/label.ts
  src/plots/column/component/label.ts
  src/plots/line/layer.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/layer.ts
  src/plots/stacked-area/layer.ts
Labels: PR: reviewed-approved, bug, size/L

#908 fix: auto inner padding calc for axis component
  src/base/controller/padding.ts
  src/dependents.ts
  src/interface/config.ts
  src/util/common.ts
Labels: PR: reviewed-changes-requested, bug, size/M

#869 fix(pie): add pie label percent
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  src/plots/pie/component/label/base-label.ts
Labels: PR: reviewed-approved, bug, size/M

#903 feat: customize tooltip
  examples/general/tooltip/API.en.md
  examples/general/tooltip/API.zh.md
  examples/general/tooltip/demo/meta.json
  examples/general/tooltip/demo/tooltip-inner-chart.js
  examples/general/tooltip/demo/tooltip-statistic-value.js
  examples/general/tooltip/design.en.md
  examples/general/tooltip/design.zh.md
  examples/general/tooltip/index.en.md
  examples/general/tooltip/index.zh.md
  src/base/view-layer.ts
  src/interface/config.ts
  src/plots/pie/component/label/base-label.ts
Labels: PR: unreviewed, enhancement, size/L

#920 fix: pie chart types Closes #884, #912
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  src/interface/config.ts
Labels: PR: unreviewed, bug, size/XS

#911 feat: point auto label for better experience
  __tests__/unit/components/label/label-spec.ts
  __tests__/unit/components/label/point-auto-spec.ts
  __tests__/unit/components/label/point-spec.ts
  __tests__/unit/interaction/scrollbar-spec.ts
  __tests__/unit/interaction/slider-spec.ts
  __tests__/unit/plots/bar/component/label-auto-spec.ts
  __tests__/unit/plots/bar/component/label-spec.ts
  __tests__/unit/plots/bubble/bubble-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/column/component/label-auto-spec.ts
  __tests__/unit/plots/column/component/label-spec.ts
  __tests__/unit/plots/scatter/scatter-spec.ts
  __tests__/unit/plots/stacked-bar/component/label-auto-spec.ts
  __tests__/unit/plots/stacked-bar/component/label-spec.ts
  __tests__/unit/plots/stacked-column/component/label-auto-spec.ts
  src/components/label/base.ts
  src/components/label/point-auto.ts
  src/components/label/point.ts
  src/dependents.ts
  src/plots/bar/component/label-auto.ts
  src/plots/bar/component/label.ts
  src/plots/bar/index.ts
  src/plots/bar/interface.ts
  src/plots/bar/layer.ts
  src/plots/bar/theme.ts
  src/plots/column/component/label-auto.ts
  src/plots/column/component/label.ts
  src/plots/column/index.ts
  src/plots/column/interface.ts
  src/plots/column/layer.ts
  src/plots/column/theme.ts
  src/plots/funnel/theme.ts
  src/plots/grouped-bar/layer.ts
  src/plots/grouped-bar/theme.ts
  src/plots/grouped-column/layer.ts
  src/plots/grouped-column/theme.ts
  src/plots/histogram/layer.ts
  src/plots/line/layer.ts
  src/plots/liquid/layer.ts
  src/plots/range-bar/layer.ts
  src/plots/range-column/layer.ts
  src/plots/stacked-bar/component/label-auto.ts
  src/plots/stacked-bar/component/label.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-bar/theme.ts
  src/plots/stacked-column/component/label-auto.ts
  src/plots/stacked-column/layer.ts
  src/plots/stacked-column/theme.ts
  src/util/color.ts
  src/util/view.ts
Labels: PR: reviewed-approved, enhancement, size/XXL

#928 Isolate tooltip demo
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  examples/general/tooltip/demo/test.js
  src/base/view-layer.ts
  src/interaction/core.ts
Labels: PR: unreviewed, size/M

#940 feat: auto layout label for area and stacked area
  __tests__/unit/plots/area/component/label/area-point-auto-spec.ts
  __tests__/unit/plots/stacked-area/component/label/area-point-auto-spec.ts
  package.json
  src/components/label/point-auto.ts
  src/components/label/point.ts
  src/plots/area/component/label/area-point-auto.ts
  src/plots/area/component/label/area-point.ts
  src/plots/area/index.ts
  src/plots/area/interface.ts
  src/plots/area/layer.ts
  src/plots/area/theme.ts
  src/plots/compatiblePlots/stack-area/index.ts
  src/plots/density/layer.ts
  src/plots/percent-stacked-area/layer.ts
  src/plots/stacked-area/component/label/area-point-auto.ts
  src/plots/stacked-area/component/label/area-point.ts
  src/plots/stacked-area/interface.ts
  src/plots/stacked-area/layer.ts
  src/plots/stacked-area/theme.ts
  src/util/math.ts
Labels: PR: reviewed-approved, enhancement, size/XL

#944 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved, chore, size/S

#921 mobile events
  __tests__/unit/base/events-spec.ts
  package.json
  src/base/controller/canvas.ts
  src/base/controller/event.ts
  src/base/view-layer.ts
  src/dependents.ts
  src/plots/area/event.ts
  src/plots/bar/event.ts
  src/plots/bullet/event.ts
  src/plots/calendar/event.ts
  src/plots/column/event.ts
  src/plots/density-heatmap/event.ts
  src/plots/donut/event.ts
  src/plots/funnel/event.ts
  src/plots/gauge/event.ts
  src/plots/heatmap/event.ts
  src/plots/line/event.ts
  src/plots/liquid/event.ts
  src/plots/pie/event.ts
  src/plots/radar/event.ts
  src/plots/rose/event.ts
  src/plots/scatter/event.ts
  src/plots/treemap/event.ts
  src/sparkline/progress/event.ts
  src/sparkline/ring-progress/event.ts
  src/util/event.ts
Labels: PR: reviewed-approved, size/XL

#948 fix: view lifecycle events & unit test
  __tests__/unit/base/events-spec.ts
  src/base/view-layer.ts
  src/util/event.ts
Labels: PR: reviewed-changes-requested, bug, size/M

#949 chore: modify data file
  __tests__/data/legend.json
Labels: PR: unreviewed, chore, size/XXL

#953 fix: lint
  __tests__/unit/plots/column/responsiveColumn-spec.ts
Labels: PR: reviewed-changes-requested, bug, size/XS

#955 fix: 辅助数据点无法显示
  __tests__/unit/geoms/guide-point-spec.ts
  package.json
  src/geoms/point/guide.ts
Labels: PR: reviewed-approved, bug, size/M

#958 chore: add sourcesContent to sourcemap
  tsconfig.json
Labels: PR: reviewed-approved, chore, size/XS

#960 chore: release action lint
  .github/workflows/release.yml
Labels: PR: reviewed-approved, chore, size/XS

#964 fix: color config for line
  __tests__/unit/geoms/line/main-spec.ts
  package.json
  src/geoms/line/main.ts
Labels: PR: reviewed-changes-requested, bug, size/M

#965 fix: funnel label text error Closes #963
  __tests__/bugs/issue-963-spec.ts
  src/plots/funnel/layer.ts
Labels: PR: reviewed-approved, bug, size/M

#967 fix: 兼容 0.x 数据标签 formatter 的参数
  src/components/label/point.ts
  src/dependents.ts
  src/interface/config.ts
  src/interface/types.ts
  src/plots/area/layer.ts
  src/plots/bar/component/label.ts
  src/plots/bar/layer.ts
  src/plots/column/component/label.ts
  src/plots/column/layer.ts
  src/plots/funnel/layer.ts
  src/plots/line/layer.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-column/layer.ts
Labels: PR: reviewed-approved, bug, size/L

#974 feat: support legend style & formatter Closes #966, #876, #856, #877
  __tests__/unit/components/legend-spec.ts
  src/base/view-layer.ts
  src/interface/config.ts
  src/theme/dark.ts
Labels: PR: reviewed-approved, enhancement, size/L

#987 fix: donut spider label
  __tests__/bugs/issue-883-spec.ts
  __tests__/unit/plots/donut/donut-spec.ts
  __tests__/unit/plots/funnel/funnel-spec.ts
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  __tests__/unit/plots/pie/pie-spec.ts
  package.json
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/guide-line.ts
  src/plots/donut/apply-responsive/geometry.ts
  src/plots/donut/apply-responsive/index.ts
  src/plots/donut/apply-responsive/theme.ts
  src/plots/donut/layer.ts
  src/plots/funnel/layer.ts
  src/plots/pie/layer.ts
Labels: PR: unreviewed, bug, size/L

#982 fix: color parse for interval and area geometry
  __tests__/unit/geoms/area/main-spec.ts
  __tests__/unit/geoms/interval/main-spec.ts
  src/geoms/area/main.ts
  src/geoms/interval/main.ts
  src/geoms/line/guide.ts
  src/geoms/point/guide.ts
Labels: PR: reviewed-changes-requested, bug, size/L

#992 chore: remove dep bot auto merge action
  .github/workflows/dependabot-auto-merge.yml
  package.json
Labels: PR: unreviewed, chore, size/S

#996 fix: rgb2arr and typo
  src/plots/bar/component/label-auto.ts
  src/plots/column/component/label-auto.ts
  src/util/color.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#993 feat: combo charts
  __tests__/unit/base/events-spec.ts
  __tests__/unit/combo/columnLine-spec.ts
  __tests__/unit/combo/dualLine-spec.ts
  __tests__/unit/combo/groupedColumnLine-spec.ts
  __tests__/unit/combo/stackedColumnLine-spec.ts
  __tests__/unit/plots/combo-plot/combo-spec.ts
  src/base/controller/canvas.ts
  src/base/view-layer.ts
  src/combo-plots/base.ts
  src/combo-plots/overlapped.ts
  src/combo-plots/util/adjustColorConfig.ts
  src/combo-plots/util/globalAxis.ts
  src/combo-plots/util/globalLegend.ts
  src/combo-plots/util/globalTooltip.ts
  src/combo-plots/util/index.ts
  src/combo-plots/util/padding.ts
  src/combo/base.ts
  src/combo/column-line/index.ts
  src/combo/column-line/layer.ts
  src/combo/dual-line/index.ts
  src/combo/dual-line/layer.ts
  src/combo/groupedColumn-line/index.ts
  src/combo/groupedColumn-line/layer.ts
  src/combo/stackedColumn-line/index.ts
  src/combo/stackedColumn-line/layer.ts
  src/combo/util/interface.ts
  src/components/description.ts
  src/index.ts
  src/plots/line/layer.ts
  src/util/event.ts
Labels: PR: unreviewed, enhancement, size/XXL
