Repository antvis/G2Plot, pull requests merged in 2020-05, with the labels that each got.

#1004 fix: refactor padding
  __tests__/bugs/issue-963-spec.ts
  __tests__/bugs/issue-980-spec.ts
  __tests__/unit/combo/dualLine-spec.ts
  __tests__/unit/components/legend-spec.ts
  __tests__/unit/plots/bar/component/label-auto-spec.ts
  __tests__/unit/plots/heatmap/heatmap-spec.ts
  package.json
  src/base/controller/canvas.ts
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/description.ts
  src/plots/funnel/layer.ts
  src/util/common.ts
Labels: PR: unreviewed, bug, size/L

#1008 fix: combo yAxis hide effect
  __tests__/unit/combo/columnLine-spec.ts
  package.json
  src/base/controller/padding.ts
  src/combo/base.ts
Labels: PR: reviewed-changes-requested, bug, size/S

#1012 fix(tooltip): not use document to query ".g2-tooltip". (#1011)
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, bug

#1010 fix(dependents): fix SyntaxError of import. (#954)
  src/dependents.ts
Labels: PR: reviewed-changes-requested, bug

#1013 chore: remove pr size label action
  .github/workflows/pr-size-label.yml
Labels: PR: reviewed-approved, chore

#1015 fix: fix chart name typo
  src/index.ts
Labels: PR: reviewed-changes-requested, bug

#1017 fix: fix dual line render error without legend config
  src/combo/dual-line/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1018 fix: typo fix
  src/base/view-layer.ts
  src/dependents.ts
Labels: PR: reviewed-changes-requested, bug

#782 fix: fix percent chart type error
  src/plots/percent-stacked-area/index.ts
  src/plots/percent-stacked-bar/index.ts
  src/plots/percent-stacked-column/index.ts
Labels: PR: reviewed-approved, bug

#1019 add combo plots demo
  examples/combo/basic/demo/column-line.js
  examples/combo/basic/demo/column-line2.js
  examples/combo/basic/demo/dual-line.js
  examples/combo/basic/demo/meta.json
  examples/combo/basic/index.en.md
  examples/combo/basic/index.zh.md
  examples/combo/column-line/API.en.md
  examples/combo/column-line/API.zh.md
  examples/combo/column-line/demo/basic.js
  examples/combo/column-line/demo/custom-style.js
  examples/combo/column-line/demo/disable-axis-colorMapping.js
  examples/combo/column-line/demo/meta.json
  examples/combo/column-line/design.en.md
  examples/combo/column-line/design.zh.md
  examples/combo/column-line/index.en.md
  examples/combo/column-line/index.zh.md
  examples/combo/dual-line/API.en.md
  examples/combo/dual-line/API.zh.md
  examples/combo/dual-line/demo/basic.js
  examples/combo/dual-line/demo/line-style.js
  examples/combo/dual-line/demo/meta.json
  examples/combo/dual-line/demo/same-scale.js
  examples/combo/dual-line/design.en.md
  examples/combo/dual-line/design.zh.md
  examples/combo/dual-line/index.en.md
  examples/combo/dual-line/index.zh.md
  examples/combo/groupedColumn-line/API.en.md
  examples/combo/groupedColumn-line/API.zh.md
  examples/combo/groupedColumn-line/demo/basic.js
  examples/combo/groupedColumn-line/demo/meta.json
  examples/combo/groupedColumn-line/design.en.md
  examples/combo/groupedColumn-line/design.zh.md
  examples/combo/groupedColumn-line/index.en.md
  examples/combo/groupedColumn-line/index.zh.md
  examples/combo/stackedColumn-line/API.en.md
  examples/combo/stackedColumn-line/API.zh.md
  examples/combo/stackedColumn-line/demo/basic.js
  examples/combo/stackedColumn-line/demo/meta.json
  examples/combo/stackedColumn-line/design.en.md
  examples/combo/stackedColumn-line/design.zh.md
  examples/combo/stackedColumn-line/index.en.md
  examples/combo/stackedColumn-line/index.zh.md
  gatsby-config.js
  src/combo/base.ts
Labels: PR: unreviewed

#1036 fix: pie radius
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  __tests__/unit/plots/pie/pie-spec.ts
  src/plots/pie/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1037 feat: customTooltip 配置项更新
  examples/general/tooltip/demo/isolate-tooltip.js
  examples/general/tooltip/demo/tooltip-inner-chart.js
  examples/general/tooltip/demo/tooltip-statistic-value.js
  package.json
  src/base/view-layer.ts
  src/combo/column-line/layer.ts
  src/combo/dual-line/layer.ts
  src/combo/groupedColumn-line/layer.ts
  src/combo/stackedColumn-line/layer.ts
  src/interface/config.ts
Labels: PR: reviewed-approved, enhancement

#1040 feat: 接入tooltip customContent配置
  CHANGELOG.md
  __tests__/unit/plots/bar/bar-spec.ts
  package.json
  src/base/view-layer.ts
  src/interface/config.ts
Labels: PR: reviewed-approved, enhancement

#1044 docs: fix typo
  examples/line/marker/API.en.md
  examples/line/marker/API.zh.md
Labels: PR: reviewed-approved, documentation

#1043 fix(types): fix scrollbar type definitions
  src/plots/area/interface.ts
  src/plots/bar/interface.ts
  src/plots/column/interface.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1051 chore(deps): 升级 matrix-util
  __tests__/bugs/issue-830-spec.ts
  package.json
  src/plots/funnel/animation/funnel-scale-in-x.ts
  src/plots/funnel/animation/funnel-scale-in-y.ts
  src/plots/pie/component/label/base-label.ts
  src/util/g-util.ts
  src/util/math.ts
  src/util/path.ts
Labels: PR: reviewed-changes-requested, dependencies

#1086 fix: guideline Closes #1063
  __tests__/bugs/issue-883-spec.ts
  __tests__/unit/plots/percent-stacked-column/percentageStackColumn-spec.ts
  src/components/guide-line.ts
  src/util/data.ts
Labels: PR: reviewed-approved, bug

#1065 line.pointLabel响应式下沉至组件配置项
  __tests__/unit/plots/line/lineLabel-spec.ts
  src/components/label/point.ts
  src/util/common.ts
Labels: PR: reviewed-approved

#971 feat: add public methods for charts
  src/base/plot.ts
  src/base/view-layer.ts
  src/plots/bubble/index.ts
  src/plots/bubble/layer.ts
  src/plots/donut/index.ts
  src/plots/funnel/layer.ts
  src/plots/grouped-bar/layer.ts
  src/plots/grouped-column/layer.ts
  src/plots/grouped-rose/layer.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/layer.ts
  src/plots/line/layer.ts
  src/plots/pie/index.ts
  src/plots/pie/layer.ts
  src/plots/radar/index.ts
  src/plots/radar/layer.ts
  src/plots/rose/index.ts
  src/plots/rose/layer.ts
  src/plots/stacked-area/layer.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-column/layer.ts
  src/plots/stacked-rose/index.ts
  src/plots/stacked-rose/layer.ts
Labels: PR: reviewed-approved, enhancement, size/L

#1032 feat: 移动端指标卡组件
  __tests__/unit/components/breadcrumb-spec.ts
  __tests__/unit/components/tooltip-indicator-spec.ts
  __tests__/unit/interaction/tooltip-indicator-spec.ts
  __tests__/unit/plots/line/line-mobile-spec.ts
  __tests__/unit/util/utils-text-spec.ts
  __tests__/utils/event.ts
  package.json
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/base.ts
  src/components/breadcrumb.ts
  src/components/label/base.ts
  src/components/timeline/button.ts
  src/components/timeline/index.ts
  src/components/tooltip-indicator.ts
  src/dependents.ts
  src/interaction/base.ts
  src/interaction/index.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/interaction/timeline.ts
  src/interaction/tooltip-indicator.ts
  src/interface/config.ts
  src/plots/line/layer.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/treemap/interaction/drillDown.ts
  src/theme/default.ts
  src/util/bbox.ts
  src/util/common.ts
  src/util/text.ts
  src/util/view.ts
Labels: PR: reviewed-approved, enhancement

#1100 fix: polar axis padding Closes #1085
  __tests__/bugs/issue-1085-spec.ts
  __tests__/bugs/issue-972-spec.ts
  __tests__/unit/plots/stacked-bar/component/label-auto-spec.ts
  __tests__/unit/plots/stacked-column/component/label-auto-spec.ts
  docs/manual/combo-charts/column-line.en.md
  docs/manual/combo-charts/dual-line.en.md
  docs/manual/combo-charts/groupedColumn-line.en.md
  docs/manual/combo-charts/stackedColumn-line.en.md
  docs/manual/plots/area.en.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bubble.en.md
  docs/manual/plots/bullet.en.md
  docs/manual/plots/calendar.en.md
  docs/manual/plots/column.en.md
  docs/manual/plots/density-heatmap.en.md
  docs/manual/plots/donut.en.md
  docs/manual/plots/gauge.en.md
  docs/manual/plots/grouped-bar.en.md
  docs/manual/plots/grouped-column.en.md
  docs/manual/plots/grouped-rose.en.md
  docs/manual/plots/heatmap.en.md
  docs/manual/plots/histogram.en.md
  docs/manual/plots/line.en.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/range-bar.en.md
  docs/manual/plots/range-column.en.md
  docs/manual/plots/rose.en.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/stacked-area.en.md
  docs/manual/plots/stacked-bar.en.md
  docs/manual/plots/stacked-column.en.md
  docs/manual/plots/stacked-rose.en.md
  docs/manual/plots/stepLine.en.md
  docs/manual/plots/treemap.en.md
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/word-clourd.en.md
  gatsby-config.js
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/plots/gauge/geometry/shape/gauge-shape.ts
  src/plots/gauge/layer.ts
  src/plots/liquid/layer.ts
Labels: PR: reviewed-approved, bug

#1110 Feat: 词云图禁用动画模式增加
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/wordcloud2.ts
Labels: Feat, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#1111 fix: spider label 修复
  src/plots/pie/component/label/spider-label.ts
Labels: PR: reviewed-changes-requested, bug

#1112 feat: add selected tooltip interaction
  __tests__/unit/plots/line/interaction/selected-tooltip-spec.ts
  src/base/view-layer.ts
  src/dependents.ts
  src/index.ts
  src/plots/line/interaction/index.ts
  src/plots/line/interaction/selected-tooltip.ts
  src/plots/line/layer.ts
Labels: PR: reviewed-approved, enhancement

#1120 fix: close #1059 close #1005
  __tests__/bugs/issue-1005-spec.ts
  __tests__/bugs/issue-1059-spec.ts
  src/base/view-layer.ts
  src/plots/percent-stacked-bar/layer.ts
  src/plots/percent-stacked-column/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1115 feat: news
  gatsby-config.js
  package.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, enhancement

#1132 fix: 图例通过 margin 配置来对齐
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/interface/config.ts
  src/theme/default.ts
Labels: PR: partially-approved, bug

#1139 chore: release v1.1.5
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1143 fix: 修改 theme config 失效，需要转换为 g2 主题
  __tests__/unit/theme/theme-spec.ts
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  src/base/controller/theme.ts
  src/theme/interface.ts
  src/theme/theme.ts
Labels: PR: reviewed-approved, bug

#1148 fix: 修复通过updateConfig删除interaction配置不生效问题
  __tests__/unit/plots/line/interaction/selected-tooltip-spec.ts
  src/base/view-layer.ts
Labels: PR: reviewed-changes-requested, bug

#1149 fix(types): fix Donut statistic type definitions
  src/plots/donut/component/ring-statistic.ts
  src/plots/donut/component/statistic.ts
  src/plots/donut/layer.ts
Labels: PR: unreviewed, bug

#1150 fix: fix #1042
  src/plots/donut/component/ring-statistic.ts
Labels: PR: reviewed-changes-requested, bug

#1151 feat: 添加 active marker，自定义 tooltip controller
  examples/line/multiple/demo/marker-active.js
  examples/line/multiple/demo/meta.json
  src/geoms/point/guide.ts
  src/plots/line/interaction/index.ts
  src/plots/line/interaction/marker-active.ts
Labels: PR: partially-approved, enhancement
