Repository antvis/G2Plot, pull requests merged in 2020-02, with the labels that each got.

#469 treemap
  __tests__/bugs/issue-485-spec.ts
  __tests__/data/mobile.ts
  __tests__/unit/components/breadcrumb-spec.ts
  __tests__/unit/heatmap-spec.ts
  __tests__/unit/plots/step/index-spec.ts
  __tests__/unit/ring-spec.ts
  __tests__/unit/treemap-spec.ts
  __tests__/unit/treemap-spec2.ts
  __tests__/unit/utils-math-spec.ts
  docs/manual/plots/treemap.en.md
  docs/manual/plots/treemap.zh.md
  examples/treemap/rect/API.en.md
  examples/treemap/rect/API.zh.md
  examples/treemap/rect/demo/basic.js
  examples/treemap/rect/demo/drilldown.js
  examples/treemap/rect/demo/label.js
  examples/treemap/rect/demo/meta.json
  examples/treemap/rect/design.en.md
  examples/treemap/rect/design.zh.md
  examples/treemap/rect/index.en.md
  examples/treemap/rect/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  src/components/breadcrumb.ts
  src/plots/index.ts
  src/plots/line/layer.ts
  src/plots/treemap/components/label.ts
  src/plots/treemap/event.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interaction/animation.ts
  src/plots/treemap/interaction/drillDown.ts
  src/plots/treemap/interaction/index.ts
  src/plots/treemap/layer.ts
  src/plots/treemap/layout/dice.ts
  src/plots/treemap/layout/slice.ts
  src/plots/treemap/layout/squarify.ts
  src/theme/default.ts
  src/util/event.ts
  src/util/math.ts
  src/util/responsive/rules/digits-abbreviate.ts
Labels: PR: unreviewed, size/XXL

#550 Fix guideline
  src/components/guide-line.ts
Labels: PR: unreviewed, size/M

#555 fix: non-nullable field SiteSiteMetadata.id
  package.json
Labels: PR: unreviewed, bug, size/XS

#513 Word cloud Support
  __tests__/unit/word-cloud-spec.ts
  examples/data/word-cloud.json
  examples/word-cloud/basic/API.en.md
  examples/word-cloud/basic/API.zh.md
  examples/word-cloud/basic/demo/basic.js
  examples/word-cloud/basic/demo/meta.json
  examples/word-cloud/basic/design.en.md
  examples/word-cloud/basic/design.zh.md
  examples/word-cloud/basic/index.en.md
  examples/word-cloud/basic/index.zh.md
  gatsby-config.js
  src/base/layer.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/plots/index.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/word-cloud-tooltips.ts
  src/plots/word-cloud/wordcloud.ts
  src/plots/word-cloud/wordcloud2.js
Labels: PR: unreviewed, size/XXL, word-cloud

#557 feat(word-cloud): update to 0.11.24(word-cloud support)
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, enhancement, size/XS

#560 fix: 单折线不允许设置尾部跟随label
  examples/column/waterfall/API.zh.md
  examples/combo/basic/API.zh.md
  examples/combo/basic/design.zh.md
  examples/combo/basic/index.zh.md
  examples/heatmap/basic/API.zh.md
  examples/heatmap/matrix/API.zh.md
  examples/rose/basic/API.zh.md
  examples/rose/basic/design.zh.md
  examples/rose/basic/index.zh.md
  examples/treemap/rect/API.zh.md
  examples/word-cloud/basic/API.zh.md
  src/plots/line/layer.ts
Labels: PR: unreviewed, bug, size/L

#559 fix: bar plot error when responsive setted as true
  src/util/responsive/apply/axis.ts
Labels: PR: unreviewed, bug, size/S

#565 fix(wordcloud): rename wordcloud2.js to .js
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/wordcloud.ts
  src/plots/word-cloud/wordcloud2.js
  src/plots/word-cloud/wordcloud2.ts
Labels: PR: reviewed-approved, bug, size/XXL

#568 feat(word-cloud): update to 0.11.25
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, enhancement, size/XS

#551 update scale
  docs/manual/general-config.zh.md
  examples/area/stack/demo/area-large-data.js
  examples/bubble/basic/demo/quadrant.js
  examples/general/axis/demo/axis-style.js
  package.json
  src/base/view-layer.ts
  src/components/axis/parser.ts
  src/util/scale.ts
Labels: PR: unreviewed, size/M

#585 fix: waterfall yAxis
  __tests__/bugs/issue-556-spec.ts
  src/plots/waterfall/layer.ts
Labels: PR: reviewed-approved, bug, size/L

#584 饼图 label line 优化绘制
  src/plots/bullet/base-layer.ts
  src/plots/bullet/event.ts
  src/plots/bullet/index.ts
  src/plots/bullet/layer.ts
  src/plots/index.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/layer.ts
Labels: PR: reviewed-approved, size/L

#588 迁移折线图
  __tests__/unit/line-spec.ts
  package.json
  src/base/controller/canvas.ts
  src/base/controller/padding.ts
  src/base/layer.ts
  src/base/view-layer.ts
  src/components/axis/parser.ts
  src/geoms/point/guide.ts
  src/interface/config.ts
  src/plots/line/animation/clipIn-with-data.ts
  src/plots/line/component/label/line-label.ts
  src/plots/line/component/label/point-label.ts
  src/plots/line/layer.ts
  src/theme/dark.ts
  src/theme/default.ts
  src/util/bbox.ts
  src/util/g-util.ts
Labels: PR: unreviewed, WIP, size/L

#597 chore: update g2 & scale version
  package.json
  src/interface/config.ts
Labels: automerge, chore, size/XS

#596 类型错误修复
  src/base/controller/event.ts
  src/base/controller/padding.ts
  src/base/controller/state.ts
  src/base/plot.ts
  src/base/view-layer.ts
  src/components/description.ts
  src/interaction/base.ts
  src/interface/config.ts
  src/plots/line/animation/clipIn-with-data.ts
  src/util/math.ts
  src/util/scale.ts
Labels: WIP, size/L

#600 fix: 🆙 upgrade gatsby theme version
  package.json
Labels: PR: draft, bug, size/XS

#603 fix: 修复更新scale新版本后的问题
  src/components/axis/parser.ts
  src/interface/config.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/percentage-stack-column/layer.ts
  src/util/scale.ts
Labels: automerge, bug, size/S

#599 迁移条形图
  package.json
  src/base/layer.ts
  src/base/view-layer.ts
  src/components/axis/parser.ts
  src/geoms/base.ts
  src/geoms/interval/main.ts
  src/interface/config.ts
  src/plots/bar/apply-responsive/axis.ts
  src/plots/bar/apply-responsive/index.ts
  src/plots/bar/component/label.ts
  src/plots/bar/event.ts
  src/plots/bar/index.ts
  src/plots/bar/layer.ts
  src/plots/bar/theme.ts
  src/plots/group-bar/index.ts
  src/plots/group-bar/layer.ts
  src/plots/index.ts
  src/plots/percentage-stack-bar/index.ts
  src/plots/percentage-stack-bar/layer.ts
  src/plots/stack-bar/component/label.ts
  src/plots/stack-bar/index.ts
  src/plots/stack-bar/layer.ts
Labels: WIP, size/XL

#608 fix heatmap legend position
  src/plots/heatmap/components/legend.ts
  src/plots/matrix/component/legend.ts
Labels: size/S

#609 fix: 水波图图形剪裁问题修复
  src/plots/liquid/layer.ts
Labels: bug, size/S

#607 feat(area): migrate to G2 4.0
  demos/area-basic.ts
  src/components/description.ts
  src/geoms/area/main.ts
  src/index.ts
  src/plots/area/apply-responsive/axis.ts
  src/plots/area/apply-responsive/index.ts
  src/plots/area/event.ts
  src/plots/area/index.ts
  src/plots/area/layer.ts
  src/plots/area/theme.ts
  src/plots/index.ts
  src/plots/line/component/label/line-label.ts
  src/plots/percentage-stack-area/index.ts
  src/plots/percentage-stack-area/layer.ts
  src/plots/stack-area/component/label/area-label.ts
  src/plots/stack-area/component/label/line-label.ts
  src/plots/stack-area/index.ts
  src/plots/stack-area/layer.ts
  src/util/bbox.ts
Labels: WIP, enhancement, size/XL

#613 fix: remove geom cliper in liquid
  src/plots/liquid/layer.ts
Labels: bug, size/M

#612 迁移热力图
  __tests__/unit/heatmap-spec.ts
  package.json
  src/geoms/heatmap/linear.ts
  src/plots/heatmap/components/background.ts
  src/plots/heatmap/components/index.ts
  src/plots/heatmap/components/legend.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/layer.ts
  src/plots/index.ts
  src/plots/stack-bar/component/label.ts
Labels: WIP, size/XXL

#611 fix: pie label type update error
  __tests__/bugs/issue-598-spec.ts
  src/plots/pie/layer.ts
Labels: bug, size/L

#616 migrate area label
  src/components/description.ts
  src/plots/line/component/label/line-label.ts
  src/plots/line/layer.ts
  src/plots/stack-area/component/index.ts
  src/plots/stack-area/component/label/area-label.ts
  src/plots/stack-area/component/label/line-label.ts
  src/plots/stack-area/layer.ts
  src/util/bbox.ts
Labels: size/L

#618 迁移 mini charts
  __tests__/unit/sparkline/progress-spec.ts
  __tests__/unit/sparkline/ringProgress-spec.ts
  __tests__/unit/sparkline/tinyArea-spec.ts
  __tests__/unit/sparkline/tinyColumn-spec.ts
  __tests__/unit/sparkline/tinyLine-spec.ts
  package.json
  src/geoms/area/mini.ts
  src/geoms/line/mini.ts
  src/interface/config.ts
  src/plots/index.ts
  src/sparkline/progress/component/marker.ts
  src/sparkline/progress/event.ts
  src/sparkline/progress/index.ts
  src/sparkline/progress/layer.ts
  src/sparkline/ring-progress/event.ts
  src/sparkline/ring-progress/index.ts
  src/sparkline/ring-progress/layer.ts
  src/sparkline/tiny-area/event.ts
  src/sparkline/tiny-area/index.ts
  src/sparkline/tiny-area/layer.ts
  src/sparkline/tiny-column/event.ts
  src/sparkline/tiny-column/index.ts
  src/sparkline/tiny-column/layer.ts
  src/sparkline/tiny-layer.ts
  src/sparkline/tiny-line/event.ts
  src/sparkline/tiny-line/index.ts
  src/sparkline/tiny-line/layer.ts
  src/sparkline/tiny-plot.ts
Labels: WIP, size/XL

#622 Migrate word cloud
  src/base/plot.ts
  src/plots/index.ts
  src/plots/word-cloud/index.ts
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/word-cloud-tooltips.ts
  src/plots/word-cloud/wordcloud2.ts
Labels: size/XXL

#620 migrate matrix plot
  __tests__/unit/matrix-spec.ts
  package.json
  src/plots/index.ts
  src/plots/matrix/component/index.ts
  src/plots/matrix/component/label.ts
  src/plots/matrix/component/legend.ts
  src/plots/matrix/index.ts
  src/plots/matrix/layer.ts
  src/plots/matrix/shape.ts
  src/plots/stack-area/layer.ts
Labels: WIP, size/XXL

#623 migrate rangeBar & rangeColumn
  __tests__/unit/rangeBar-spec.ts
  __tests__/unit/rangeColumn-spec.ts
  package.json
  src/plots/bar/layer.ts
  src/plots/column/component/label.ts
  src/plots/column/layer.ts
  src/plots/index.ts
  src/plots/range-bar/animation.ts
  src/plots/range-bar/component/label.ts
  src/plots/range-bar/index.ts
  src/plots/range-bar/layer.ts
  src/plots/range-column/animation.ts
  src/plots/range-column/component/label.ts
  src/plots/range-column/index.ts
  src/plots/range-column/layer.ts
Labels: WIP, size/XL

#624 feat: 迁移scrollbar & slider 交互
  __tests__/unit/interaction/scrollbar-spec.ts
  __tests__/unit/interaction/slider-spec.ts
  src/base/view-layer.ts
  src/interaction/base.ts
  src/interaction/index.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/interface/config.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
Labels: PR: unreviewed, enhancement, size/XL

#625 fix: waterfall meta adjust error
  src/plots/waterfall/layer.ts
Labels: bug, size/XS

#621 feat(migrate): 饼图从G2 3.6.x 迁移至G2 4.0
  examples/pie/basic/demo/basic.js
  examples/pie/basic/demo/outer-center-label.js
  examples/pie/basic/demo/outer-label.js
  examples/pie/basic/demo/spider-label.js
  src/base/view-layer.ts
  src/index.ts
  src/plots/index.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/index.ts
  src/plots/pie/component/label/inner-label.ts
  src/plots/pie/component/label/outer-center-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/component/label/utils/index.ts
  src/plots/pie/component/label/utils/text.ts
  src/plots/pie/event.ts
  src/plots/pie/index.ts
  src/plots/pie/layer.ts
  src/plots/pie/theme.ts
Labels: enhancement, size/XXL

#552 WIP: 转化率组件
  demos/bar-conversion.ts
  demos/column-conversion.ts
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.zh.md
  examples/bar/basic/API.zh.md
  examples/bar/basic/demo/bar-conversion.js
  examples/bar/basic/demo/meta.json
  examples/column/basic/API.zh.md
  examples/column/basic/demo/column-conversion.js
  examples/column/basic/demo/meta.json
  src/base/controller/padding.ts
  src/components/conversion-tag.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/funnel/layer.ts
Labels: WIP, size/L

#619 feat: add legend config marker
  demos/pie-basic2.ts
  docs/manual/general-config.zh.md
  src/base/view-layer.ts
  src/interface/config.ts
Labels: enhancement, size/S

#629 Migrate rose
  __tests__/unit/rose-spec.ts
  examples/rose/basic/demo/basic.js
  src/base/view-layer.ts
  src/plots/index.ts
  src/plots/rose/event.ts
  src/plots/rose/index.ts
  src/plots/rose/layer.ts
Labels: PR: unreviewed, size/XL

#631 【1.x】迁移 radar 到 G2 4.x
  __tests__/unit/radar-spec.ts
  demos/radar-basic.ts
  demos/radar-series.ts
  examples/radar/basic/demo/basic.js
  examples/radar/basic/demo/series.js
  gatsby-browser.js
  src/base/view-layer.ts
  src/components/axis/parser.ts
  src/interface/config.ts
  src/plots/index.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/radar/event.ts
  src/plots/radar/index.ts
  src/plots/radar/layer.ts
  src/plots/radar/theme.ts
  src/sparkline/progress/layer.ts
Labels: size/XL

#632 fix: treemap tooltip Closes #576
  src/plots/treemap/layer.ts
Labels: bug, size/XS

#633 迁移水波图
  __tests__/unit/liquid-spec.ts
  package.json
  src/base/view-layer.ts
  src/plots/index.ts
  src/plots/liquid/animation/liquid-move-in.ts
  src/plots/liquid/geometry/shape/liquid.ts
  src/plots/liquid/index.ts
  src/plots/liquid/layer.ts
  src/plots/liquid/theme.ts
  src/util/g-util.ts
Labels: size/XL

#635 fix: guide geom tooltip & add clip in canvas renderer Closes #635
  src/base/view-layer.ts
  src/geoms/line/guide.ts
  src/geoms/point/guide.ts
  src/interface/config.ts
Labels: bug, size/XS

#628 迁移矩形树图
  __tests__/unit/treemap-spec.ts
  package.json
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/base.ts
  src/components/breadcrumb.ts
  src/geoms/line/guide.ts
  src/geoms/point/guide.ts
  src/interaction/base.ts
  src/interaction/core.ts
  src/interface/config.ts
  src/plots/index.ts
  src/plots/treemap/components/label.ts
  src/plots/treemap/event.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interaction/animation.ts
  src/plots/treemap/interaction/drillDown.ts
  src/plots/treemap/interaction/index.ts
  src/plots/treemap/layer.ts
  src/plots/treemap/layout/dice.ts
  src/plots/treemap/layout/slice.ts
  src/plots/treemap/layout/squarify.ts
Labels: size/XXL

#637 迁移直方图 & 密度图
  __tests__/unit/density-spec.ts
  package.json
  src/plots/density/index.ts
  src/plots/density/layer.ts
  src/plots/histogram/index.ts
  src/plots/histogram/layer.ts
  src/plots/index.ts
Labels: size/L

#640 Migrate waterfall
  __tests__/unit/waterfall-spec.ts
  src/plots/index.ts
  src/plots/waterfall/component/label/diff-label.ts
  src/plots/waterfall/component/label/waterfall-label.ts
  src/plots/waterfall/event.ts
  src/plots/waterfall/geometry/shape/waterfall.ts
  src/plots/waterfall/index.ts
  src/plots/waterfall/layer.ts
Labels: size/XL

#639 迁移环图
  __tests__/unit/ring-spec.ts
  package.json
  src/plots/index.ts
  src/plots/ring/apply-responsive/geometry.ts
  src/plots/ring/apply-responsive/index.ts
  src/plots/ring/apply-responsive/theme.ts
  src/plots/ring/component/ring-statistic.ts
  src/plots/ring/component/statistic-template.ts
  src/plots/ring/component/statistic.ts
  src/plots/ring/event.ts
  src/plots/ring/index.ts
  src/plots/ring/layer.ts
Labels: WIP, size/L

#579 feat: bullet
  __tests__/unit/plots/bullet/index-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/basic.js
  examples/bullet/basic/demo/color-range.js
  examples/bullet/basic/demo/group-color-range.js
  examples/bullet/basic/demo/group.js
  examples/bullet/basic/demo/meta.json
  examples/bullet/basic/demo/multi-targets.js
  examples/bullet/basic/demo/overflow.js
  examples/bullet/basic/demo/stack.js
  examples/bullet/basic/design.en.md
  examples/bullet/basic/design.zh.md
  examples/bullet/basic/index.en.md
  examples/bullet/basic/index.zh.md
  gatsby-config.js
  src/interface/config.ts
  src/plots/bullet/base-layer.ts
  src/plots/bullet/component/bulletRect.ts
  src/plots/bullet/component/bulletTarget.ts
  src/plots/bullet/layer.ts
Labels: PR: unreviewed, WIP, enhancement, size/XXL

#641 migrate scatter and bubble
  demos/bubble-basic.ts
  demos/bubble-quadrant.ts
  demos/scatter-basic.ts
  examples/bubble/basic/demo/basic.js
  examples/bubble/basic/demo/quadrant.js
  examples/bubble/basic/demo/trendline.js
  examples/scatter/basic/demo/basic.js
  examples/scatter/basic/demo/color-mapping.js
  examples/scatter/basic/demo/label-placement.js
  examples/scatter/basic/demo/trendline.js
  src/geoms/point/circle.ts
  src/plots/bubble/index.ts
  src/plots/bubble/layer.ts
  src/plots/index.ts
  src/plots/scatter/components/label.ts
  src/plots/scatter/components/quadrant.ts
  src/plots/scatter/components/trendline.ts
  src/plots/scatter/event.ts
  src/plots/scatter/index.ts
  src/plots/scatter/layer.ts
  src/plots/waterfall/component/label/diff-label.ts
Labels: size/XXL

#602 feat(pie): add tooltip and label percent
  demos/pie-labelPercent.ts
  src/plots/pie/layer.ts
Labels: enhancement, size/L

#642 chore: update version to 0.11.32
  CHANGELOG.md
  package.json
Labels: chore

#643 fix: 修复饼图label隐藏的bug
  examples/pie/basic/demo/basic.js
  examples/pie/basic/demo/outer-center-label.js
  examples/pie/basic/demo/outer-label.js
  examples/pie/basic/demo/spider-label.js
  site/images/gatsby-astronaut-1.png
  src/plots/pie/component/label/outer-center-label.ts
  src/plots/pie/component/label/outer-label.ts
Labels: bug, size/M

#647 [1.x] 修复 scatter 迁移问题
  demos/bubble-basic.ts
  demos/bubble-quadrant.ts
  examples/bubble/basic/demo/basic.js
  examples/bubble/basic/demo/quadrant.js
  examples/scatter/basic/demo/basic.js
  examples/scatter/basic/demo/color-mapping.js
  src/plots/scatter/layer.ts
Labels: size/M

#648 fix：修复 pie outer-center-label 下引线 path 问题
  src/plots/pie/component/label/outer-center-label.ts
Labels: size/XS

#650 feat(pie-label): 添加标签抽样，优先显示占比大的标签的配置
  src/plots/pie/component/label/base-label.ts
Labels: enhancement, size/S

#653 feat: 子弹图迁移
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/bullet/stack-spec.ts
  examples/bullet/basic/API.en.md
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/basic.js
  examples/bullet/basic/demo/color-range.js
  examples/bullet/basic/demo/group-color-range.js
  examples/bullet/basic/demo/group.js
  examples/bullet/basic/demo/meta.json
  examples/bullet/basic/demo/multi-targets.js
  examples/bullet/basic/demo/overflow.js
  examples/bullet/basic/demo/stack.js
  examples/bullet/basic/design.en.md
  examples/bullet/basic/design.zh.md
  examples/bullet/basic/index.en.md
  examples/bullet/basic/index.zh.md
  src/base/view-layer.ts
  src/plots/bullet/component/bulletRect.ts
  src/plots/bullet/component/bulletTarget.ts
  src/plots/bullet/event.ts
  src/plots/bullet/index.ts
  src/plots/bullet/layer.ts
  src/plots/heatmap/layer.ts
  src/plots/waterfall/component/label/diff-label.ts
  src/theme/dark.ts
  src/theme/default.ts
Labels: enhancement, size/XXL

#652 fix(types): export TreemapConfig
  package.json
  src/plots/index.ts
Labels: bug

#660 fix: 修复升级scale后的label超出区域问题
  package.json
  src/base/view-layer.ts
  src/util/bbox.ts
Labels: bug, size/M

#667 feat(word-cloud): fix render bug without imageMask
  src/plots/word-cloud/layer.ts
Labels: enhancement, size/S

#664 Migrate ring: 增加环图label
  src/plots/ring/layer.ts
Labels: ring

#668 fix: 修复1.x上的TS错误
  src/components/axis/parser.ts
  src/components/connected-area.ts
  src/interaction/base.ts
  src/interaction/helper/get-color-def.ts
  src/plots/area/layer.ts
  src/plots/bar/layer.ts
  src/plots/bullet/layer.ts
  src/plots/density/layer.ts
  src/plots/line/interaction/line-active.ts
  src/plots/line/interaction/line-select.ts
  src/plots/line/layer.ts
  src/plots/pie/component/label/utils/text.ts
  src/plots/pie/layer.ts
  src/plots/range-column/animation.ts
  src/plots/rose/layer.ts
  src/plots/stack-column/component/label/stack-column-label.ts
  src/plots/waterfall/geometry/shape/waterfall.ts
  src/plots/word-cloud/layer.ts
  src/plots/word-cloud/word-cloud-tooltips.ts
  src/sparkline/progress/layer.ts
Labels: bug, size/L

#661 1.x 组件及布局走查
  demos/general-titleDescription1.ts
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/group.js
  package.json
  src/base/controller/padding.ts
  src/base/view-layer.ts
  src/components/connected-area.ts
  src/components/description.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/plots/bar/layer.ts
  src/plots/column/layer.ts
  src/plots/stack-column/layer.ts
  src/util/common.ts
Labels: size/L

#662 Migrate pie label
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/outer-center-label.ts
  src/plots/pie/component/label/outer-label.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/layer.ts
Labels: PR: unreviewed, size/L

#678 fix(ring): 修复环图中心文本定位问题
  src/plots/ring/layer.ts
Labels: bug, size/XS

#679 fix: ring statistic 在resize下，重复渲染
  src/plots/ring/component/statistic.ts
  src/plots/ring/layer.ts
Labels: bug, size/XS

#651 sunburst
  __tests__/data/mobile2.ts
  __tests__/unit/sunburst-spec.ts
  examples/bullet/basic/API.zh.md
  examples/bullet/basic/demo/group.js
  package.json
  src/plots/index.ts
  src/plots/sunburst/components/label.ts
  src/plots/sunburst/index.ts
  src/plots/sunburst/interaction/drillDown.ts
  src/plots/sunburst/interaction/index.ts
  src/plots/sunburst/layer.ts
  src/plots/sunburst/layout/partition.ts
  src/plots/sunburst/layout/round.ts
Labels: WIP, size/XXL

#683 [1.x ] 柱条系列图形单侧 & Axis 样式配置
  __tests__/unit/plots/area/area-spec.ts
  __tests__/unit/plots/bar/bar-spec.ts
  __tests__/unit/plots/column/column-spec.ts
  __tests__/unit/plots/group-bar/groupBar-spec.ts
  __tests__/unit/plots/group-column/groupColumn-spec.ts
  __tests__/unit/plots/pie/pie-inner-label-spec.ts
  __tests__/unit/plots/pie/pie-outer-label-spec.ts
  __tests__/unit/plots/stack-bar/stackBar-spec.ts
  __tests__/unit/plots/stack-column/stackColumn-spec.ts
  src/base/plot.ts
  src/interface/config.ts
  src/plots/bar/component/label.ts
  src/plots/bar/layer.ts
  src/plots/column/component/label.ts
  src/plots/column/layer.ts
  src/plots/line/component/label/line-label.ts
  src/plots/treemap/components/label.ts
  src/util/style-parser.ts
Labels: size/XL
