Repository antvis/G2Plot, pull requests merged in 2020-07, with the labels that each got.

#1242 fix: fix guide line render error without plot data
  src/components/guide-line.ts
Labels: PR: reviewed-changes-requested, bug

#1240 fix: prevent js error when adjust tooltip
  src/plots/grouped-bar/layer.ts
Labels: PR: partially-approved, bug

#1237 docs: remove url for General configurations and fix typos
  docs/manual/getting-started.en.md
Labels: PR: reviewed-approved, documentation

#1238 docs: fix typo in filename
  docs/manual/plots/word-cloud.en.md
  docs/manual/plots/word-cloud.zh.md
Labels: PR: reviewed-approved, documentation

#1231 docs: update CONTRIBUTING.md and CONTRIBUTING.zh-CN.md
  CONTRIBUTING.md
  CONTRIBUTING.zh-CN.md
Labels: PR: reviewed-approved, documentation

#1246 fix: 修复下热力图配置更新时候的错误
  __tests__/bugs/heatmap-update-config-spec.ts
  src/base/controller/padding.ts
Labels: PR: reviewed-changes-requested, bug

#1248 环图 Statistics 区域优化
  __tests__/bugs/donut-statistic-spec.ts
  src/plots/donut/component/ring-statistic.ts
  src/plots/donut/component/statistic-template.ts
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/spider-label.ts
Labels: PR: unreviewed

#1250 feat: 环比 statistic.htmlContent 回调参数补充 size，容器宽度设置
  __tests__/bugs/donut-statistic-spec.ts
  __tests__/bugs/issue-1137-spec.ts
  src/plots/donut/component/ring-statistic.ts
Labels: PR: unreviewed, enhancement

#1249 chore: release 1.1.9
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1251 chore: release 1.1.10
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1255 feat(line): add code example by line
  __tests__/data/party-support.ts
  __tests__/unit/plots/line/index-spec.ts
  __tests__/utils/dom.ts
  package.json
  src/core/adaptor.ts
  src/core/plot.ts
  src/plots/line/adaptor.ts
  src/plots/line/index.ts
  src/plots/line/types.ts
  src/types/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#1272 折线图实现
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/line/index-spec.ts
  package.json
  src/core/plot.ts
  src/index.ts
  src/plots/line/adaptor.ts
  src/plots/line/index.ts
  src/plots/line/types.ts
  src/types/animation.ts
  src/types/axis.ts
  src/types/common.ts
  src/types/index.ts
  src/types/interaction.ts
  src/types/label.ts
  src/types/legend.ts
  src/types/style.ts
  src/types/tooltip.ts
Labels: PR: partially-approved

#1279 fix: 修复云凤蝶紧急问题
  __tests__/bugs/issue-1269-spec.ts
  __tests__/unit/plots/liquid/liquid-htmlContent-spec.ts
  src/combo/base.ts
  src/components/statistic.ts
  src/interaction/scrollbar.ts
  src/interaction/slider.ts
  src/plots/liquid/component/liquid-statistic.ts
  src/plots/liquid/component/statistic-template.ts
  src/plots/liquid/layer.ts
Labels: PR: reviewed-approved, bug

#1265 fix(issue-1241): 修复饼、环 label设置为spider，数据都为0时，展示为1
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/layer.ts
  src/plots/pie/utils.ts
Labels: PR: partially-approved, bug

#1285 feat(flow): adaptor 使用 flow 的方式处理,让逻辑散开且容易复用
  __tests__/unit/utils/flow-spec.ts
  src/core/adaptor.ts
  src/core/plot.ts
  src/plots/line/adaptor.ts
  src/plots/line/index.ts
  src/utils/flow.ts
  src/utils/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#1284 docs: uniform AntV navbar's order and naming
  gatsby-config.js
Labels: PR: reviewed-changes-requested, documentation

#1283 feat: 基于 dumi 新增临时 docs
  .gitignore
  .umirc.ts
  docs/demos/scatter.md
  docs/index.md
  package.json
  src/core/plot.ts
  src/index.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/scatter/types.ts
  src/types/axis.ts
  src/types/common.ts
  src/types/tooltip.ts
Labels: PR: reviewed-approved, enhancement

#1287 feat: export g2
  src/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#1290 Feat pie
  __tests__/unit/plots/pie/index-spec.ts
  package.json
  src/common/adaptor.ts
  src/core/adaptor.ts
  src/index.ts
  src/plots/line/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
  src/plots/pie/types.ts
  src/types/style.ts
Labels: PR: partially-approved

#1292 chore: issue template with https://new-issue.antv.vision
  .github/ISSUE_TEMPLATE/config.yaml
Labels: PR: unreviewed, chore

#1293 chore: issue template with https://new-issue.antv.vision
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: unreviewed, chore

#1291 feat(line): add line options
  __tests__/unit/plots/line/label-spec.ts
  __tests__/unit/plots/line/shape-spec.ts
  __tests__/unit/plots/line/style-spec.ts
  __tests__/unit/plots/line/tooltip-spec.ts
  src/common/adaptor.ts
  src/core/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
  src/plots/scatter/adaptor.ts
  src/types/label.ts
  src/types/style.ts
  src/types/tooltip.ts
Labels: PR: partially-approved, enhancement, v2

#1296 feat(pie/label): add pie options
  __tests__/unit/plots/pie/index-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: partially-approved, enhancement, v2

#1301 feat(pie-annotation): add pie options
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/constants.ts
  src/plots/pie/index.ts
  src/plots/pie/interaction.ts
  src/plots/pie/types.ts
  src/plots/pie/utils.ts
  src/types/interaction.ts
  src/types/style.ts
Labels: PR: unreviewed, enhancement, v2

#1303 fix: 指标区域移除后需要置空
  __tests__/unit/plots/bar/component/label-spec.ts
  src/plots/donut/layer.ts
Labels: PR: reviewed-approved, bug

#1306 chore: release v1.1.13
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1304 feat: add tiny-line
  __tests__/unit/plots/tiny-line/index-spec.ts
  src/core/adaptor.ts
  src/index.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/index.ts
  src/plots/tiny-line/types.ts
Labels: PR: partially-approved, enhancement

#1309 Refactor base types
  __tests__/unit/core/index-spec.ts
  src/core/plot.ts
  src/plots/line/types.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/types.ts
  src/types/common.ts
  src/types/index.ts
Labels: PR: partially-approved

#1311 V2 mini chart tiny column
  __tests__/unit/plots/tiny-column/index-spec.ts
  src/index.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-column/types.ts
Labels: PR: reviewed-approved

#1310 fix: rangeStyle not ringStyle
  src/plots/gauge/geometry/shape/gauge-shape.ts
Labels: PR: reviewed-changes-requested, bug

#1314 V2 mini chart tiny area
  __tests__/unit/plots/tiny-area/index-spec.ts
  src/index.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-area/types.ts
Labels: PR: reviewed-approved

#1313 chore: release 1.1.14
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1320 docs(donut, liquid): modify based on issue #1260
  docs/manual/plots/donut.en.md
  docs/manual/plots/donut.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
Labels: PR: unreviewed, documentation

#1308 feat: line options
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/line/animation-spec.ts
  __tests__/unit/plots/line/point-spec.ts
  src/common/adaptor.ts
  src/index.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
  src/plots/pie/adaptor.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/types.ts
  src/types/animation.ts
  src/types/common.ts
Labels: PR: unreviewed, enhancement

#1316 feat(v2/column): 添加基础柱形图
  __tests__/data/sales.ts
  __tests__/unit/plots/column/axis-spec.ts
  __tests__/unit/plots/column/index-spec.ts
  __tests__/unit/plots/column/label-spec.ts
  __tests__/unit/plots/column/style-spec.ts
  src/common/helper.ts
  src/constant.ts
  src/core/plot.ts
  src/index.ts
  src/plots/column/adaptor.ts
  src/plots/column/index.ts
  src/plots/column/types.ts
  src/plots/line/adaptor.ts
Labels: PR: partially-approved, enhancement

#1318 v2 pie/enhance
  __tests__/unit/plots/pie/index-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interaction/index.ts
  src/plots/pie/interaction/pie-legend-action.ts
  src/plots/pie/interaction/pie-statistic-action.ts
  src/utils/g-util.ts
Labels: PR: unreviewed

#1317 feat: add progress
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/index.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/index.ts
  src/plots/progress/types.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/index.ts
  src/plots/ring-progress/types.ts
Labels: PR: unreviewed, enhancement

#1322 feat: 完善散点图功能、新增测试用例
  __tests__/data/gender.ts
  __tests__/unit/plots/scatter/axis-spec.ts
  __tests__/unit/plots/scatter/color-spec.ts
  __tests__/unit/plots/scatter/shape-spec.ts
  __tests__/unit/plots/scatter/size-spec.ts
  __tests__/unit/plots/scatter/style-spec.ts
  __tests__/unit/plots/scatter/tooltip-spec.ts
  docs/demos/scatter.md
  src/plots/scatter/adaptor.ts
  src/plots/scatter/reflect.ts
  src/plots/scatter/types.ts
Labels: PR: unreviewed, enhancement

#1330 feat(v2/bar): add basic bar chart
  __tests__/unit/plots/bar/axis-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/bar/style-spec.ts
  src/index.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/bar/types.ts
  src/types/style.ts
Labels: PR: reviewed-changes-requested, enhancement

#1323 feat: add radar plot
  __tests__/data/radar.ts
  __tests__/unit/plots/radar/area-spec.ts
  __tests__/unit/plots/radar/axis-spec.ts
  __tests__/unit/plots/radar/index-spec.ts
  __tests__/unit/plots/radar/point-spec.ts
  __tests__/unit/plots/radar/style-spec.ts
  __tests__/unit/plots/radar/tooltip-spec.ts
  src/index.ts
  src/plots/radar/adaptor.ts
  src/plots/radar/constants.ts
  src/plots/radar/index.ts
  src/plots/radar/types.ts
Labels: PR: partially-approved, enhancement

#1333 feat(v2/column): support grouped and stacked column
  __tests__/data/sales.ts
  __tests__/unit/plots/column/index-spec.ts
  __tests__/unit/plots/column/label-spec.ts
  __tests__/utils/dom.ts
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
Labels: PR: reviewed-changes-requested, enhancement

#1336 fix(pie): 修复饼图数据全空时的处理
  __tests__/bugs/pie-empty-data-spec.ts
  jest.setup.js
  package.json
  src/plots/pie/component/label/base-label.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/layer.ts
  src/plots/pie/utils.ts
Labels: PR: partially-approved, WIP, bug

#1337 feat(v2/radar): 自定义 radar tooltip，允许横向对比显示 tooltip
  __tests__/data/radar.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/radar/tooltip-spec.ts
  src/plots/radar/index.ts
  src/plots/radar/interaction/index.ts
  src/plots/radar/interaction/radar-tooltip-action.ts
  src/plots/radar/types.ts
Labels: PR: unreviewed, enhancement

#1335 feat(v2/pie): 饼图数据全为 0 的处理
  __tests__/unit/plots/pie/empty-data-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: partially-approved, enhancement

#1329 feat: 新增直方图以及测试用例，修复之前问题
  __tests__/data/histogram-data.ts
  __tests__/unit/plots/histogram/index-spec.ts
  __tests__/unit/plots/histogram/interaction-spec.ts
  package.json
  src/index.ts
  src/plots/histogram/adaptor.ts
  src/plots/histogram/index.ts
  src/plots/histogram/types.ts
Labels: PR: partially-approved, enhancement

#1321 feat(v2/pie): 饼图字段配置错误处理
  __tests__/bugs/issue-1245-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: reviewed-approved, enhancement

#1343 fix: revert
  __tests__/bugs/bar-scrollbar-spec.ts
  __tests__/bugs/issue-1269-spec.ts
  __tests__/data/scales.ts
  src/interaction/scrollbar.ts
  src/plots/range-bar/animation.ts
  src/plots/range-bar/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1346 fix: interaction scrollbar
  __tests__/bugs/bar-scrollbar-spec.ts
  __tests__/bugs/issue-1269-spec.ts
  __tests__/data/scales.ts
  src/interaction/scrollbar.ts
  src/plots/range-bar/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1344 feat(util): add invariant/log util method
  __tests__/unit/utils/invariant-spec.ts
  src/plots/pie/adaptor.ts
  src/utils/index.ts
  src/utils/invariant.ts
Labels: PR: reviewed-approved, enhancement

#1345 V2 tiny tooltip
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/constants.ts
  src/plots/tiny-line/types.ts
  src/types/tooltip.ts
Labels: PR: reviewed-approved

#1347 chore: 添加windows环境下开发配置和cross-env依赖
  .prettierrc
  package.json
Labels: PR: partially-approved, chore

#1350 fix(issue-1133): 修复瀑布图xy轴设置失效 & 删除无用单测
  __tests__/bugs/issue-1133-spec.ts
  __tests__/bugs/issue-1161-spec.ts
  src/plots/waterfall/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1354 feat(v2/column): support columnWidthRatio and marginRatio
  __tests__/unit/plots/column/index-spec.ts
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
Labels: PR: reviewed-changes-requested, enhancement

#1352 feat: add changelog
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, enhancement

#1351 Fix responsive not work
  src/plots/column/apply-responsive/label.ts
  src/plots/grouped-bar/layer.ts
  src/plots/grouped-column/layer.ts
  src/plots/grouped-rose/layer.ts
  src/plots/line/apply-responsive/label.ts
  src/plots/percent-stacked-area/layer.ts
  src/plots/radar/layer.ts
  src/plots/stacked-area/layer.ts
  src/plots/stacked-bar/layer.ts
  src/plots/stacked-column/component/label.ts
  src/plots/stacked-column/layer.ts
  src/plots/stacked-rose/layer.ts
  src/util/responsive/apply/label.ts
  src/util/responsive/rules/node-jitter-upward.ts
  src/util/responsive/rules/nodes-resampling-by-state.ts
Labels: PR: reviewed-approved

#1358 chore: release 1.1.16
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1349 feat: interaction
  __tests__/unit/plots/scatter/interaction-spec.ts
  __tests__/unit/plots/scatter/style-spec.ts
  docs/demos/scatter.md
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/scatter/interaction/index.ts
  src/plots/scatter/types.ts
Labels: PR: reviewed-approved, enhancement

#1356 feat: 增加支持层叠（堆叠）直方图
  __tests__/data/histogram-data.ts
  __tests__/unit/plots/histogram/axis-spec.ts
  __tests__/unit/plots/histogram/index-spec.ts
  __tests__/unit/plots/histogram/interaction-spec.ts
  __tests__/unit/plots/histogram/label-spec.ts
  __tests__/unit/plots/histogram/style-spec.ts
  __tests__/unit/plots/histogram/tooltip-spec.ts
  src/plots/histogram/adaptor.ts
  src/plots/histogram/types.ts
Labels: PR: reviewed-approved, enhancement

#1360 pie support label to show 数值、文本、百分比 separately
  __tests__/unit/plots/pie/empty-data-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  __tests__/unit/utils/template-spec.ts
  src/plots/pie/adaptor.ts
  src/utils/g-util.ts
  src/utils/index.ts
  src/utils/template.ts
Labels: PR: partially-approved

#1361 feat(area): add plot area
  __tests__/unit/plots/area/animation-spec.ts
  __tests__/unit/plots/area/axis-spec.ts
  __tests__/unit/plots/area/index-spec.ts
  __tests__/unit/plots/area/label-spec.ts
  __tests__/unit/plots/area/line-spec.ts
  __tests__/unit/plots/area/point-spec.ts
  __tests__/unit/plots/area/shape-spec.ts
  __tests__/unit/plots/area/style-spec.ts
  __tests__/unit/plots/area/tooltip-spec.ts
  src/index.ts
  src/plots/area/adaptor.ts
  src/plots/area/index.ts
  src/plots/area/types.ts
  src/plots/line/adaptor.ts
  src/plots/radar/adaptor.ts
Labels: PR: partially-approved, enhancement

#1357 feat(v2/column): support grouped and stacked bar
  __tests__/unit/plots/bar/axis-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/bar/style-spec.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/types.ts
Labels: PR: reviewed-changes-requested, enhancement

#1359 fix: fix scrollbar render error with multi geometry
  src/interaction/scrollbar.ts
Labels: PR: reviewed-approved, bug

#1363 feat(gauge): 调整仪表盘坐标轴文本距离刻度线的间距，增加 offset 属性
  src/plots/gauge/interface.ts
  src/plots/gauge/layer.ts
Labels: PR: reviewed-changes-requested, enhancement

#1364 Daily 0730 fix
  __tests__/bugs/issue-1137-spec.ts
  __tests__/unit/plots/stacked-column/component/label-spec.ts
  src/geoms/line/main.ts
  src/plots/pie/component/label/spider-label.ts
  src/plots/pie/layer.ts
  src/plots/stacked-column/component/label.ts
Labels: PR: partially-approved

#1366 chore: release 1.1.17
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, chore

#1371 fix: 当饼图数据有可能为 null, 会导致计算结果 NaN
  src/plots/pie/component/label/spider-label.ts
Labels: PR: reviewed-changes-requested, bug

#1372 chore: release 1.1.18
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1365 抽取了 point、line、area等 geometry
  src/adaptor/geometries/area.ts
  src/adaptor/geometries/index.ts
  src/adaptor/geometries/line.ts
  src/adaptor/geometries/point.ts
  src/plots/area/adaptor.ts
  src/plots/area/types.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
  src/plots/radar/adaptor.ts
  src/plots/radar/types.ts
Labels: PR: partially-approved

#1373 Refactor: common/adaptor 改为 adaptor/common
  __tests__/unit/plots/bar/style-spec.ts
  __tests__/unit/plots/column/style-spec.ts
  __tests__/unit/plots/histogram/style-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/scatter/axis-spec.ts
  src/adaptor/common.ts
  src/plots/area/adaptor.ts
  src/plots/bar/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/histogram/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/radar/adaptor.ts
  src/plots/scatter/adaptor.ts
Labels: PR: reviewed-changes-requested, refactor

#1375 fix: 从完备的角度看,不应该限制用户自由配置 tooltip 的权利
  src/plots/donut/layer.ts
Labels: PR: reviewed-changes-requested, bug

#1376 chore: release 1.1.19
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, chore

#1377 feat(v2/column): support groupField/stackField options
  __tests__/unit/plots/column/index-spec.ts
  __tests__/unit/plots/column/label-spec.ts
  src/plots/column/adaptor.ts
  src/plots/column/types.ts
Labels: PR: reviewed-changes-requested, enhancement

#1368 feat: 添加 website
  .eslintignore
  .eslintrc
  .umirc.ts
  docs/demos/scatter.md
  docs/index.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  examples/scatter/basic/API.ch.md
  examples/scatter/basic/API.en.md
  examples/scatter/basic/API.zh.md
  examples/scatter/basic/demo/basic.js
  examples/scatter/basic/demo/color-mapping.js
  examples/scatter/basic/demo/meta.json
  examples/scatter/basic/demo/shape-mapping.js
  examples/scatter/basic/index.en.md
  examples/scatter/basic/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  site/locale.json
  site/pages/index.en.tsx
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, enhancement

#1379 fix(issue-1378): 修复多折线图设置 marker point 时，只对一条线生效
  __tests__/bugs/issue-1378-spec.ts
  src/components/marker-point.ts
Labels: PR: reviewed-changes-requested, bug
