Repository antvis/G2Plot, pull requests merged in 2020-12, with the labels that each got.

#2035 feat(docs): plots 文档按照以下格式补全
  docs/manual/plots/radial-bar.zh.md
  docs/manual/plots/rose.en.md
  docs/manual/plots/rose.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/sunburst.en.md
  docs/manual/plots/sunburst.zh.md
  docs/manual/plots/word-cloud.en.md
  docs/manual/plots/word-cloud.zh.md
Labels: PR: partially-approved

#2050 docs: 新增 FAQ 降低答疑成本
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
Labels: PR: reviewed-approved

#2055 fix(word-cloud): 修复当宽高为0时浏览器卡死
  __tests__/unit/plots/word-cloud/utils-spec.ts
  src/plots/word-cloud/utils.ts
Labels: PR: reviewed-approved

#2049 fix(bar): adjust default legend and tooltip order
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/legend-spec.ts
  __tests__/unit/plots/histogram/axis-spec.ts
  __tests__/unit/plots/histogram/index-spec.ts
  package.json
  src/core/plot.ts
  src/plots/bar/adaptor.ts
Labels: PR: unreviewed

#2053 feat(line): support lineShape config
  __tests__/unit/plots/line/line-mapping-spec.ts
  src/adaptor/geometries/line.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
Labels: PR: reviewed-approved

#2016 feat: new plot sankey 桑基图
  __tests__/data/sankey-energy.ts
  __tests__/unit/plots/sankey/index-spec.ts
  __tests__/unit/plots/sankey/util/data-spec.ts
  __tests__/unit/utils/transform/sankey-spec.ts
  docs/manual/plots/sankey.en.md
  docs/manual/plots/sankey.zh.md
  examples/sankey/basic/API.en.md
  examples/sankey/basic/API.zh.md
  examples/sankey/basic/demo/alipay.ts
  examples/sankey/basic/demo/energy.ts
  examples/sankey/basic/demo/meta.json
  examples/sankey/basic/index.en.md
  examples/sankey/basic/index.zh.md
  gatsby-config.js
  package.json
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/edge.ts
  src/adaptor/geometries/index.ts
  src/index.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/constant.ts
  src/plots/sankey/index.ts
  src/plots/sankey/types.ts
  src/plots/sankey/util/data.ts
  src/utils/transform/sankey.ts
Labels: PR: partially-approved

#2060 feat(docs): 增加angular技术栈的g2plot封装收录链接
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
Labels: PR: reviewed-approved

#2057 fix pie label percentage
  __tests__/bugs/issue-2054-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: unreviewed

#2061 feat: add default label layout for line/area/column/bar
  __tests__/unit/plots/area/label-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/column/label-spec.ts
  __tests__/unit/plots/line/label-spec.ts
  src/plots/area/adaptor.ts
  src/plots/bar/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/line/adaptor.ts
Labels: PR: reviewed-approved

#2051 feat(pie-label): 饼图标签文本添加溢出 plot 自动 ellipsis 特性
  __tests__/unit/plots/pie/empty-data-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
Labels: PR: unreviewed

#2062 chore: relase 2.3.1
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2066 fix: fix early create canvas context cause build error in server side
  src/utils/context.ts
  src/utils/measure-text.ts
Labels: PR: reviewed-approved

#2069 chore: fix preview workflow vulnerability
  .github/workflows/preview-build.yml
  .github/workflows/preview-upload.yml
  .github/workflows/preview.yml
Labels: PR: reviewed-approved

#2079 fix(issue-2078): 修复 waterfall 无法关闭 tooltip
  __tests__/bugs/issue-2078-spec.ts
  __tests__/unit/plots/waterfall/component-spec.ts
  src/plots/waterfall/adaptor.ts
Labels: PR: partially-approved

#2071 fix: fix duplicated label renderde for line and area plot
  __tests__/bugs/issue-2064-spec.ts
  src/plots/area/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/radar/adaptor.ts
Labels: PR: partially-approved

#2075 feat: 散点图一个数据点时调整 min max
  __tests__/unit/plots/scatter/data-spec.ts
  __tests__/unit/utils/get-meta-spec.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/util.ts
Labels: PR: reviewed-approved

#2072 fix(sankey): close sankey node tooltip
  __tests__/bugs/issue-2015-spec.ts
  __tests__/unit/plots/scatter/tooltip-spec.ts
  __tests__/unit/utils/tooltip-spec.ts
  src/types/tooltip.ts
  src/utils/tooltip.ts
Labels: PR: partially-approved

#2085 fix(gauge): 仪表盘的 ticks 默认不均匀,且自定义 scale 无效
  __tests__/bugs/issue-charts-367-spec.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/index.ts
Labels: PR: partially-approved

#2087 fix: only enable tooltip for primary geometry for line/area/radar
  __tests__/unit/plots/area/tooltip-spec.ts
  __tests__/unit/plots/line/tooltip-spec.ts
  __tests__/unit/plots/radar/tooltip-spec.ts
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  src/plots/area/adaptor.ts
  src/plots/line/adaptor.ts
  src/plots/radar/adaptor.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-line/adaptor.ts
Labels: PR: reviewed-approved

#2090 fix: 修改官网样式覆盖问题
  gatsby-browser.js
Labels: PR: reviewed-approved

#2092 fix(pie-statistic): 修复环图中心文本从 false 更新为 null，读取空对象属性出错
  __tests__/bugs/issue-2080-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/utils/statistic-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: partially-approved

#2095 Fix/compare funnel label
  __tests__/unit/plots/funnel/label-spec.ts
  docs/manual/plots/funnel.en.md
  docs/manual/plots/funnel.zh.md
  src/plots/funnel/adaptor.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/dynamic-height.ts
Labels: PR: partially-approved

#2098 chore: 2.3.2
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2099 feat(liquid): add outline, wave options for customize
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  __tests__/bugs/issue-1909-spec.ts
  __tests__/bugs/issue-charts-367-spec.ts
  __tests__/unit/plots/liquid/index-spec.ts
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  examples/liquid/basic/demo/basic.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
Labels: PR: partially-approved

#2103 docs: 日常走查
  docs/common/label.en.md
  docs/common/label.zh.md
  src/adaptor/geometries/interval.ts
Labels: PR: reviewed-approved

#2106 refactor(demo): 诺贝尔奖可视化 demo 优化
  examples/case/multi-view/demo/nobel-prize.ts
  src/plots/multi-view/adaptor.ts
Labels: PR: partially-approved

#2107 fix(2105): fix percent column/bar yAxis lable > 1
  __tests__/bugs/issue-2105-spec.ts
  src/plots/column/adaptor.ts
Labels: PR: reviewed-approved

#2112 docs: 修复文档 404
  examples/general/annotation/API.en.md
  examples/general/annotation/API.zh.md
Labels: PR: reviewed-approved

#2115 docs: fix image url is http
  README.md
  README.zh-CN.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
Labels: PR: reviewed-approved

#2108 feat: add chart type source in container
  __tests__/unit/core/index-spec.ts
  src/core/plot.ts
Labels: PR: partially-approved

#2113 fix(#2111): appendPadding not update
  __tests__/bugs/issue-21111-spec.ts
  src/core/plot.ts
Labels: PR: reviewed-approved

#2109 修复折线图类型错误 & 调整默认 autoHide 配置
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/histogram/axis-spec.ts
  __tests__/unit/plots/histogram/index-spec.ts
  src/core/plot.ts
  src/plots/line/types.ts
Labels: PR: partially-approved

#2118 fix(#2116): percent transform should keep data order
  __tests__/bugs/issue-2111-spec.ts
  __tests__/bugs/issue-2116-spec.ts
  __tests__/unit/utils/number-spec.ts
  __tests__/unit/utils/transform/percent-spec.ts
  src/utils/number.ts
  src/utils/transform/percent.ts
Labels: PR: reviewed-approved

#2120 fix: 修复网站demo错误
  examples/case/multi-view/demo/nobel-prize.ts
Labels: PR: partially-approved

#2121 feat: 日常发布
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved

#2073 feat: add plot chord (增加弦图)
  __tests__/data/chord-population.ts
  __tests__/unit/plots/chord/index-spec.ts
  __tests__/unit/plots/sankey/util/data-spec.ts
  __tests__/unit/utils/data-spec.ts
  __tests__/unit/utils/transform/chord-spec.ts
  docs/manual/plots/chord.en.md
  docs/manual/plots/chord.zh.md
  examples/chord/basic/API.en.md
  examples/chord/basic/API.zh.md
  examples/chord/basic/demo/chord-population.ts
  examples/chord/basic/demo/meta.json
  examples/chord/basic/index.en.md
  examples/chord/basic/index.zh.md
  gatsby-config.js
  package.json
  src/index.ts
  src/plots/chord/adaptor.ts
  src/plots/chord/constant.ts
  src/plots/chord/index.ts
  src/plots/chord/types.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/util/data.ts
  src/types/relation-data.ts
  src/utils/data.ts
  src/utils/transform/chord.ts
Labels: PR: unreviewed

#2123 fix(issue-2122): 修复对称条形图数据为空，报错
  __tests__/bugs/issue-2122-spec.ts
  src/index.ts
  src/plots/bidirectional-bar/adaptor.ts
Labels: PR: unreviewed

#2127 修复 chord 单测和增加 pie 单测
  __tests__/bugs/issue-2096-spec.ts
  __tests__/unit/plots/chord/index-spec.ts
Labels: PR: partially-approved

#2128 docs legend
  docs/api/components/legend.en.md
  docs/api/components/legend.zh.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  docs/common/legend.en.md
  docs/common/legend.zh.md
  docs/common/marker.en.md
  docs/common/marker.zh.md
  docs/styles/legend.md
  docs/styles/style.md
  gatsby-config.js
Labels: PR: partially-approved

#2132 docs: 修复链接 404
  docs/api/plots/scatter.en.md
  docs/api/plots/scatter.zh.md
Labels: PR: partially-approved

#2131 fix(esm): remove all the lib import
  package.json
  src/adaptor/conversion-tag.ts
  src/adaptor/geometries/line.ts
  src/core/plot.ts
  src/plots/bullet/types.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/legend.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/dynamic-height.ts
  src/plots/gauge/shapes/gauge.ts
  src/plots/heatmap/shapes/circle.ts
  src/plots/heatmap/shapes/square.ts
  src/plots/multi-view/types.ts
  src/plots/pie/interactions/pie-legend-action.ts
  src/plots/pie/interactions/pie-statistic-action.ts
  src/plots/pie/utils/index.ts
  src/plots/radar/interactions/radar-tooltip-action.ts
  src/plots/radial-bar/types.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/shape.ts
  src/plots/word-cloud/shapes/word-cloud.ts
  src/plots/word-cloud/utils.ts
  src/types/animation.ts
  src/types/annotation.ts
  src/types/attr.ts
  src/types/axis.ts
  src/types/common.ts
  src/types/label.ts
  src/types/legend.ts
  src/types/meta.ts
  src/types/scrollbar.ts
  src/types/slider.ts
  src/types/state.ts
  src/types/tooltip.ts
  src/utils/geometry.ts
  src/utils/path.ts
  src/utils/statistic.ts
Labels: PR: unreviewed

#2136 docs: 修复文档 404
  docs/api/plot-api.en.md
  docs/api/plot-api.zh.md
  docs/common/animate-option.en.md
  docs/common/animate-option.zh.md
  docs/common/interactions.zh.md
  docs/common/legend-cfg.zh.md
Labels: PR: reviewed-approved

#2138 fix(#2124): fix funnel crash when data contains null, 0
  __tests__/bugs/issue-2124-spec.ts
  __tests__/unit/plots/funnel/basic-spec.ts
  __tests__/unit/plots/funnel/compare-spec.ts
  __tests__/unit/plots/funnel/conversion-tag-spec.ts
  __tests__/unit/plots/funnel/dynamic-height-spec.ts
  __tests__/unit/plots/funnel/facet-spec.ts
  __tests__/unit/utils/conversion-spec.ts
  src/adaptor/conversion-tag.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/dynamic-height.ts
  src/utils/conversion.ts
Labels: PR: partially-approved

#2144 docs: 修改图例 marker 配置的说明文档
  docs/common/marker.en.md
  docs/common/marker.zh.md
Labels: PR: partially-approved

#2141 feat: add default label layout for bullet
  __tests__/unit/plots/bullet/label-spec.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/types.ts
Labels: PR: partially-approved

#2145 feat: chore: release 2.3.4
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2150 fix: funnel undefined render
  __tests__/bugs/issue-2124-spec.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/dynamic-height.ts
Labels: PR: reviewed-approved

#2152 chore: v2.3.5
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2153 feat: area support changeData
  __tests__/unit/plots/area/change-data-spec.ts
  __tests__/unit/plots/funnel/conversion-tag-spec.ts
  examples/area/basic/demo/basic.ts
  examples/area/basic/demo/meta.json
  src/plots/area/adaptor.ts
  src/plots/area/index.ts
  src/plots/area/utils.ts
Labels: PR: unreviewed

#2023 feat: treemap init
  __tests__/data/treemap-nest.ts
  __tests__/data/treemap.ts
  __tests__/unit/plots/treemap/axis-spec.ts
  __tests__/unit/plots/treemap/basic-spec.ts
  __tests__/unit/plots/treemap/legend-spec.ts
  __tests__/unit/plots/treemap/tooltip-spec.ts
  __tests__/unit/plots/treemap/treemap-nest-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  __tests__/unit/utils/hierarchy/partition-spec.ts
  __tests__/unit/utils/hierarchy/util-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  examples/more-plots/treemap/API.en.md
  examples/more-plots/treemap/API.zh.md
  examples/more-plots/treemap/demo/basic.ts
  examples/more-plots/treemap/demo/meta.json
  examples/more-plots/treemap/demo/treemap-nest.ts
  examples/more-plots/treemap/design.en.md
  examples/more-plots/treemap/design.zh.md
  examples/more-plots/treemap/index.en.md
  examples/more-plots/treemap/index.zh.md
  gatsby-config.js
  src/index.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/index.ts
  src/plots/treemap/types.ts
  src/plots/treemap/utils.ts
  src/utils/hierarchy/partition.ts
  src/utils/hierarchy/treemap.ts
  src/utils/hierarchy/types.ts
  src/utils/hierarchy/util.ts
Labels: PR: partially-approved

#2159 [漏斗图] 暴露转化率给用户
  docs/api/plots/funnel.en.md
  docs/api/plots/funnel.zh.md
  examples/more-plots/funnel/demo/basic-transpose.ts
  examples/more-plots/funnel/demo/compare-transpose.ts
  src/index.ts
  src/plots/funnel/index.ts
Labels: PR: partially-approved

#2160 fix(conversion): conversion calculate error
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/utils/conversion-spec.ts
  src/utils/conversion.ts
Labels: PR: unreviewed

#2162 chore: v2.3.6
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2166 feat(open-ability): 开放通用的 adaptors 给自定义扩展图表使用
  __tests__/unit/index-spec.ts
  src/index.ts
Labels: PR: reviewed-approved
