Repository antvis/G2Plot, pull requests merged in 2021-12, with the labels that each got.

#3011 feat(sunburst): 旭日图支持图例配置 & 单测
  __tests__/unit/plots/sunburst/legend-spec.ts
  package.json
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/constant.ts
  src/plots/sunburst/types.ts
Labels: PR: partially-approved

#3013 fix(issue-3012): 修复条形图图例转置 & 单测
  __tests__/bugs/issue-3012-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/legend-spec.ts
  src/plots/bar/adaptor.ts
Labels: PR: unreviewed

#3015 fix(venn): fix venn color option type compatibility
  src/plots/venn/types.ts
Labels: PR: reviewed-approved

#3016 chore: release 2.4.0 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3024 fix(bar): 修复条形图 xAxis、yAxis 互相影响
  __tests__/bugs/bar-axis-label-spec.ts
  src/plots/bar/adaptor.ts
Labels: PR: reviewed-approved

#3025 chore: v2.4.1 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#3033 Update auto-inspection.yml
  .github/workflows/auto-inspection.yml
Labels: PR: unreviewed

#3036 chore: ci 升级到 yarn
  .github/workflows/auto-inspection.yml
Labels: PR: unreviewed

#3034 fix(docs): 文档链接 404
  docs/common/marker.en.md
  docs/common/marker.zh.md
Labels: PR: unreviewed

#3032 refactor: line 带 point 标注点时，进行空数据过滤，优化渲染
  __tests__/bugs/issue-1757-spec.ts
  __tests__/bugs/issue-1761-spec.ts
  __tests__/bugs/issue-2064-spec.ts
  __tests__/unit/plots/line/area-spec.ts
  __tests__/unit/plots/line/change-data-spec.ts
  __tests__/unit/plots/line/interaction-spec.ts
  __tests__/unit/plots/line/point-spec.ts
  __tests__/unit/plots/line/stack-spec.ts
  __tests__/unit/plots/line/tooltip-spec.ts
  __tests__/unit/plots/multi-view/utils-spec.ts
  src/plots/line/adaptor.ts
  src/plots/line/constants.ts
  src/plots/line/interactions/marker-active.ts
Labels: PR: unreviewed

#3037 refactor(area): 优化面积图渲染耗时, point 几何图形绘制在单独的 view 上，空数据不渲染
  __tests__/bugs/issue-1761-spec.ts
  __tests__/bugs/issue-2064-spec.ts
  __tests__/unit/plots/area/change-data-spec.ts
  __tests__/unit/plots/area/line-spec.ts
  __tests__/unit/plots/area/point-spec.ts
  __tests__/unit/plots/area/tooltip-spec.ts
  __tests__/unit/plots/gauge/shapes/index-spec.ts
  __tests__/unit/plots/line/change-data-spec.ts
  examples/line/basic/demo/custom-marker.ts
  examples/line/multiple/demo/marker-active.ts
  src/index.ts
  src/plots/area/adaptor.ts
  src/plots/area/constants.ts
  src/plots/area/index.ts
  src/plots/line/index.ts
  src/plots/line/interactions/marker-active.ts
  src/utils/geometry.ts
Labels: PR: unreviewed

#3038 chore: v2.4.2 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#3043 fix(line): 修复折线图 marker-active 交互，在point为空时存在隐藏错误
  src/plots/line/interactions/marker-active.ts
Labels: PR: unreviewed

#3044 chore: v2.4.3 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3051 Revert refactor 折线图和面积图的性能优化
  CHANGELOG.md
  __tests__/bugs/issue-1757-spec.ts
  __tests__/bugs/issue-1761-spec.ts
  __tests__/bugs/issue-2064-spec.ts
  __tests__/unit/plots/area/change-data-spec.ts
  __tests__/unit/plots/area/line-spec.ts
  __tests__/unit/plots/area/point-spec.ts
  __tests__/unit/plots/area/tooltip-spec.ts
  __tests__/unit/plots/gauge/shapes/index-spec.ts
  __tests__/unit/plots/line/area-spec.ts
  __tests__/unit/plots/line/change-data-spec.ts
  __tests__/unit/plots/line/interaction-spec.ts
  __tests__/unit/plots/line/point-spec.ts
  __tests__/unit/plots/line/stack-spec.ts
  __tests__/unit/plots/line/tooltip-spec.ts
  __tests__/unit/plots/multi-view/utils-spec.ts
  examples/line/basic/demo/custom-marker.ts
  examples/line/multiple/demo/marker-active.ts
  package.json
  src/index.ts
  src/plots/area/adaptor.ts
  src/plots/area/constants.ts
  src/plots/area/index.ts
  src/plots/line/adaptor.ts
  src/plots/line/constants.ts
  src/plots/line/index.ts
  src/plots/line/interactions/marker-active.ts
  src/utils/geometry.ts
Labels: PR: unreviewed

#3052 chore: v2.4.4
  package.json
  src/index.ts
Labels: PR: unreviewed

#3053 feat(area): 面积图支持line独立设置state，避免填充颜色出现问题
  __tests__/unit/plots/area/state-spec.ts
  docs/api/plots/area.en.md
  docs/api/plots/area.zh.md
  src/plots/area/adaptor.ts
  src/plots/area/types.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
Labels: PR: unreviewed

#3054 chore: v2.4.5 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3060 feat: 增加 sortZIndex 参数
  package.json
  src/plots/gauge/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/progress/adaptor.ts
Labels: PR: unreviewed
