Repository antvis/G2Plot, pull requests merged in 2021-04, with the labels that each got.

#2481 docs: 图表组件文档完善
  __tests__/unit/adaptor/geometries/interval-spec.ts
  __tests__/unit/plots/treemap/lable-spec.ts
  docs/api/components/axis.en.md
  docs/api/components/axis.zh.md
  docs/api/components/conversion-tag.en.md
  docs/api/components/conversion-tag.zh.md
  docs/api/components/label.en.md
  docs/api/components/label.zh.md
  docs/api/components/tooltip.en.md
  docs/api/components/tooltip.zh.md
  docs/common/axis.en.md
  docs/common/axis.zh.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  examples/component/legend/API.en.md
  examples/component/legend/API.zh.md
Labels: PR: partially-approved

#2489 feat(options): 13+图表提供获取默认配置项的静态方法
  __tests__/unit/plots/bidirectional-bar/index-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  __tests__/unit/plots/heatmap/index-spec.ts
  __tests__/unit/plots/histogram/index-spec.ts
  __tests__/unit/plots/radial-bar/index-spec.ts
  __tests__/unit/plots/rose/index-spec.ts
  __tests__/unit/plots/scatter/default-config-spec.ts
  __tests__/unit/plots/stock/index-spec.ts
  __tests__/unit/plots/sunburst/index-spec.ts
  __tests__/unit/plots/waterfall/index-spec.ts
  __tests__/unit/plots/waterfall/utils-spec.ts
  __tests__/unit/plots/word-cloud/index-spec.ts
  src/plots/bidirectional-bar/index.ts
  src/plots/box/constant.ts
  src/plots/box/index.ts
  src/plots/bullet/constant.ts
  src/plots/bullet/index.ts
  src/plots/chord/constant.ts
  src/plots/chord/index.ts
  src/plots/funnel/index.ts
  src/plots/heatmap/constant.ts
  src/plots/heatmap/index.ts
  src/plots/histogram/constant.ts
  src/plots/histogram/index.ts
  src/plots/radial-bar/constant.ts
  src/plots/radial-bar/index.ts
  src/plots/rose/constant.ts
  src/plots/rose/index.ts
  src/plots/scatter/constant.ts
  src/plots/scatter/index.ts
  src/plots/stock/constant.ts
  src/plots/stock/index.ts
  src/plots/sunburst/constant.ts
  src/plots/sunburst/index.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/constant.ts
  src/plots/waterfall/constants.ts
  src/plots/waterfall/index.ts
  src/plots/waterfall/utils.ts
  src/plots/word-cloud/constant.ts
  src/plots/word-cloud/index.ts
Labels: PR: partially-approved

#2488 feat: 为双轴图增加 setState 功能
  __tests__/unit/plots/dual-axes/state-spec.ts
  __tests__/unit/utils/geometry-spec.ts
  src/plots/dual-axes/index.ts
  src/utils/geometry.ts
  src/utils/index.ts
Labels: PR: unreviewed

#2499 fix(issue-2486): 不直接引用 @antv/matrix-util, 使用 G2 的 Util
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
Labels: PR: partially-approved

#2501 fix(gauge-theme): 仪表盘主题需要放在第一个设置，否则设置主题会失效
  __tests__/bugs/issue-2422-spec.ts
  src/plots/gauge/adaptor.ts
Labels: PR: partially-approved

#2500 docs: 文档错误
  docs/api/multi-view.en.md
  docs/api/multi-view.zh.md
Labels: PR: partially-approved

#2503 fix(sankey): depth is not right
  __tests__/unit/plots/sankey/layout-spec.ts
  src/plots/sankey/layout.ts
  src/plots/sankey/sankey/sankey.ts
Labels: PR: reviewed-approved

#2504 chore: update change log
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2505 fix: 修复双轴图单测
  __tests__/unit/plots/dual-axes/color-spec.ts
Labels: PR: reviewed-approved

#2508 fix: 升级官网主题 & 修复文档命名错误
  docs/common/component-tiny.en.md
  docs/common/component.en.md
  docs/common/component.zh.md
  docs/common/slider.en.md
  docs/common/slider.zh.md
  package.json
Labels: PR: unreviewed

#2509 docs: 文档日常更新 & 网站导航增加周边生态
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/gauge.en.md
  docs/manual/plots/gauge.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  examples/component/annotation/demo/area-with-line-annotation.ts
  examples/component/annotation/demo/line-annotation.ts
  examples/component/annotation/demo/meta.json
  gatsby-config.js
Labels: PR: unreviewed

#2517 docs(chord): 和弦图增加examples处的文档
  examples/relation-plots/chord/API.en.md
  examples/relation-plots/chord/API.zh.md
Labels: PR: unreviewed

#2519 chore: 2.319 & changelog
  CHANGELOG.md
  gatsby-config.js
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2513 fix: 修改桑基图 的 来源字段 type 类型为cat
  __tests__/unit/plots/sankey/type-spec.ts
  src/plots/sankey/adaptor.ts
Labels: PR: reviewed-approved

#2522 docs: 修改 theme-set 链接
  gatsby-config.js
Labels: PR: reviewed-approved

#2520 docs: 子弹图提供自定义 ticks 的 demo
  examples/progress-plots/bullet/demo/basic.ts
Labels: PR: unreviewed

#2524 modify url
  gatsby-config.js
Labels: PR: unreviewed

#2521 feat(sankey): add nodeDraggable interaction configure
  .github/workflows/build.yml
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/sankey/draggable-spec.ts
  __tests__/unit/plots/word-cloud/change-data-spec.ts
  docs/api/plots/sankey.en.md
  docs/api/plots/sankey.zh.md
  package.json
  src/plots/sankey/adaptor.ts
  src/plots/sankey/constant.ts
  src/plots/sankey/index.ts
  src/plots/sankey/interactions/actions/node-drag.ts
  src/plots/sankey/interactions/index.ts
  src/plots/sankey/interactions/node-draggable.ts
  src/plots/sankey/sankey/sankey.ts
  src/plots/sankey/types.ts
Labels: PR: partially-approved

#2527 feat(chord): 和弦图增加 state 通道 & 文档移除 color 配置
  docs/common/chord.zh.md
  docs/common/theme.en.md
  docs/common/theme.zh.md
  src/index.ts
  src/plots/chord/adaptor.ts
  src/utils/transform/chord.ts
Labels: PR: unreviewed
