Repository antvis/G2Plot, pull requests merged in 2021-09, with the labels that each got.

#2836 test: venn图的基础配置的单测和文档
  __tests__/unit/plots/venn/color-spec.ts
  __tests__/unit/plots/venn/data-spec.ts
  __tests__/unit/plots/venn/index-spec.ts
  __tests__/unit/plots/venn/label-spec.ts
  __tests__/unit/plots/venn/legend-spec.ts
  __tests__/unit/plots/venn/padding-spec.ts
  __tests__/unit/plots/venn/style-spec.ts
  __tests__/unit/plots/venn/tooltip-spec.ts
  docs/api/plots/venn.en.md
  docs/api/plots/venn.zh.md
  examples/more-plots/venn/API.en.md
  examples/more-plots/venn/API.zh.md
  src/plots/venn/adaptor.ts
Labels: PR: reviewed-approved

#2839 docs: set default lang=zh in readme
  README.en-US.md
  README.md
Labels: PR: reviewed-changes-requested

#2840 feat(dual-axes): 双轴图支持单轴配置legend
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/types.ts
Labels: PR: reviewed-approved

#2838 refactor(padding): venn图增加padding配置项
  __tests__/unit/plots/venn/padding-spec.ts
  src/plots/circle-packing/adaptor.ts
  src/plots/circle-packing/utils.ts
  src/plots/venn/adaptor.ts
  src/utils/padding.ts
Labels: PR: reviewed-approved

#2837 refactor(blend): 优化颜色叠加计算
  __tests__/unit/plots/venn/blend-spec.ts
  __tests__/unit/plots/venn/color-spec.ts
  __tests__/unit/utils/color/blend-spec.ts
  package.json
  src/utils/color/blend.ts
Labels: PR: unreviewed

#2831 feat(venn): 初始化韦恩图
  __tests__/unit/plots/tiny-area/pattern-spec.ts
  __tests__/unit/plots/venn/blend-spec.ts
  __tests__/unit/plots/venn/color-spec.ts
  __tests__/unit/plots/venn/data-spec.ts
  __tests__/unit/plots/venn/index-spec.ts
  __tests__/unit/plots/venn/label-spec.ts
  __tests__/unit/plots/venn/legend-spec.ts
  __tests__/unit/plots/venn/padding-spec.ts
  __tests__/unit/plots/venn/style-spec.ts
  __tests__/unit/plots/venn/tooltip-spec.ts
  __tests__/unit/utils/color/blend-spec.ts
  docs/api/plots/venn.en.md
  docs/api/plots/venn.zh.md
  examples/more-plots/venn/API.en.md
  examples/more-plots/venn/API.zh.md
  examples/more-plots/venn/demo/basic.ts
  examples/more-plots/venn/demo/blend-mode.ts
  examples/more-plots/venn/demo/customize.ts
  examples/more-plots/venn/demo/label.ts
  examples/more-plots/venn/demo/meta.json
  examples/more-plots/venn/demo/tooltip.ts
  examples/more-plots/venn/index.en.md
  examples/more-plots/venn/index.zh.md
  package.json
  src/index.ts
  src/plots/circle-packing/adaptor.ts
  src/plots/circle-packing/utils.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/venn/adaptor.ts
  src/plots/venn/constant.ts
  src/plots/venn/index.ts
  src/plots/venn/layout/circleintersection.ts
  src/plots/venn/layout/diagram.ts
  src/plots/venn/layout/layout.ts
  src/plots/venn/shape.ts
  src/plots/venn/types.ts
  src/plots/venn/utils.ts
  src/utils/color/blend.ts
  src/utils/padding.ts
Labels: PR: reviewed-approved

#2841 chore: v2.3.33 & changelog
  CHANGELOG.md
  examples/case/advanced/demo/meta.json
  gatsby-config.js
  package.json
  src/index.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/legend.ts
Labels: PR: reviewed-approved

#2843 docs(changelog): 删除重复的 changelog
  CHANGELOG.md
Labels: PR: partially-approved

#2855 fix(padding): 兼容非法padding
  __tests__/unit/plots/venn/padding-spec.ts
  src/plots/venn/adaptor.ts
Labels: PR: reviewed-approved

#2853 docs: 增加一个饼图 demo（个性化标签饼图）
  examples/pie/basic/demo/meta.json
  examples/pie/basic/demo/pie-custome-label.ts
Labels: PR: unreviewed

#2848 docs: 增加一个漏斗图分析 demo
  examples/case/statistical-scenario/demo/funnel-analysis.jsx
  examples/case/statistical-scenario/demo/meta.json
Labels: PR: unreviewed, Custom Demo

#2857 fix(venn): 处理非法数据
  __tests__/unit/plots/venn/data-spec.ts
  src/plots/venn/adaptor.ts
  src/plots/venn/utils.ts
Labels: PR: reviewed-approved

#2859 example(compare funnel): 添加了对比漏斗图案例
  examples/case/statistical-scenario/demo/compare-funnel.ts
  examples/case/statistical-scenario/demo/meta.json
  package.json
Labels: PR: unreviewed

#2863 fix(#2486): 完善了进度条progressStyle的回调方法描述文档
  docs/api/plots/progress.en.md
  docs/api/plots/progress.zh.md
Labels: PR: reviewed-approved

#2869 chore(action): change macos to ubuntu
  .github/workflows/build.yml
  package.json
Labels: PR: unreviewed

#2875 docs(label): 增加一个数据标签的 demo
  examples/case/statistical-scenario/demo/meta.json
  examples/component/label/API.en.md
  examples/component/label/API.zh.md
  examples/component/label/demo/custom-label.ts
  examples/component/label/demo/meta.json
  examples/plugin/custom-pattern/demo/meta.json
Labels: PR: unreviewed

#2871 fix(interaction): 添加 venn图 selected 和 active 的交互
  __tests__/unit/plots/venn/interaction-spec.ts
  docs/api/plots/venn.en.md
  docs/api/plots/venn.zh.md
  examples/more-plots/venn/demo/interaction.ts
  examples/more-plots/venn/demo/meta.json
  src/plots/venn/adaptor.ts
  src/plots/venn/interaction/action.ts
  src/plots/venn/interaction/index.ts
Labels: PR: unreviewed

#2876 chore: v2.3.34 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2887 chore: not dingAll when release notify
  .github/workflows/release-notify.yml
Labels: PR: unreviewed
