Repository antvis/G2Plot, pull requests merged in 2021-05, with the labels that each got.

#2531 docs(dualbarmix): 修复双轴图的API文档-图形样式中的链接和国际化问题
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
Labels: PR: reviewed-approved

#2532 docs: 日常文档走查
  docs/api/plots/liquid.en.md
  docs/api/plots/pie.en.md
  docs/api/plots/progress.en.md
  docs/api/plots/ring-progress.en.md
  docs/common/theme.en.md
  docs/common/theme.zh.md
  docs/manual/plots/bullet.en.md
  docs/manual/plots/gauge.en.md
Labels: PR: unreviewed

#2533 feat(sankey): 桑基图支持配置 rawFields, 在节点和边上获取更多原始数据信息
  __tests__/data/parallel-set.ts
  __tests__/unit/plots/sankey/index-spec.ts
  docs/api/plots/sankey.en.md
  docs/api/plots/sankey.zh.md
  examples/relation-plots/sankey/demo/draggable.ts
  examples/relation-plots/sankey/demo/meta.json
  src/plots/sankey/helper.ts
  src/plots/sankey/types.ts
  src/utils/data.ts
Labels: PR: reviewed-approved

#2534 examples: 添加若干 demo
  __tests__/unit/plots/word-cloud/change-data-spec.ts
  examples/component/tooltip/API.en.md
  examples/component/tooltip/API.zh.md
  examples/component/tooltip/demo/html-tooltip.ts
  examples/component/tooltip/demo/meta.json
  examples/component/tooltip/index.en.md
  examples/component/tooltip/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#2528 feat: 支持上层 tree shaking
  package.json
Labels: PR: reviewed-changes-requested

#2539 feat: 柱条形图支持组间和组内padding的像素级设置
  __tests__/bugs/issue-2021-spec.ts
  __tests__/unit/plots/bullet/change-data-spec.ts
  __tests__/unit/plots/sankey/layout-spec.ts
  docs/common/bar-style.en.md
  docs/common/bar-style.zh.md
  docs/common/column-style.en.md
  docs/common/column-style.zh.md
  examples/bar/grouped/demo/dodge-padding.ts
  examples/bar/grouped/demo/interval-padding.ts
  examples/bar/grouped/demo/meta.json
  examples/column/grouped/demo/dodge-padding.ts
  examples/column/grouped/demo/interval-padding.ts
  examples/column/grouped/demo/meta.json
  src/adaptor/geometries/base.ts
  src/adaptor/geometries/interval.ts
  src/plots/column/types.ts
  src/plots/sankey/sankey/sankey.ts
  src/plots/waterfall/adaptor.ts
  src/utils/statistic.ts
Labels: PR: unreviewed

#2537 refactor(multi-view): 将多图层图表更名为 Mix
  __tests__/unit/plots/multi-view/index-spec.ts
  __tests__/unit/plots/multi-view/interactions/association-spec.ts
  __tests__/unit/plots/multi-view/multi-plots-spec.ts
  __tests__/unit/plots/multi-view/tooltip-spec.ts
  __tests__/unit/plots/multi-view/utils-spec.ts
  __tests__/unit/utils/view-spec.ts
  docs/api/mix.en.md
  docs/api/mix.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  examples/case/customize/demo/line.ts
  examples/component/tooltip/demo/html-tooltip.ts
  examples/dynamic-plots/animation/demo/easing-effects.ts
  examples/plugin/association/demo/association-filter.ts
  examples/plugin/association/demo/association-highlight.ts
  examples/plugin/association/demo/association-line.ts
  examples/plugin/association/demo/association-pie.ts
  examples/plugin/multi-view/API.en.md
  examples/plugin/multi-view/API.zh.md
  examples/plugin/multi-view/demo/brush-filter-record.ts
  examples/plugin/multi-view/demo/combo-plot.ts
  examples/plugin/multi-view/demo/drinks.ts
  examples/plugin/multi-view/demo/meta.json
  examples/plugin/multi-view/demo/nobel-prize.ts
  examples/plugin/multi-view/demo/range-area.ts
  examples/plugin/multi-view/demo/sales-analysis.ts
  examples/plugin/multi-view/demo/series-columns.ts
  src/index.ts
  src/lab.ts
  src/plots/mix/adaptor.ts
  src/plots/mix/index.ts
  src/plots/mix/interactions/association.ts
  src/plots/mix/interactions/index.ts
  src/plots/mix/interactions/utils.ts
  src/plots/mix/types.ts
  src/plots/mix/utils.ts
Labels: PR: reviewed-approved

#2542 chore: v2.3.20
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2546 chore: 2.3.21, close 'side-effects' temporary
  gatsby-config.js
  package.json
  src/index.ts
Labels: PR: partially-approved

#2543 docs: update FAQ for liquid background
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
Labels: PR: reviewed-approved

#2552 chore: use real version
  gatsby-config.js
Labels: PR: reviewed-approved

#2553 feat: facet 分面图
  __tests__/unit/plots/facet/geometries-spec.ts
  __tests__/unit/plots/facet/index-spec.ts
  __tests__/unit/plots/facet/use-plot-spec.ts
  __tests__/unit/plots/facet/utils-spec.ts
  __tests__/unit/plots/multi-view/multi-plots-spec.ts
  docs/api/advanced-plots/facet.en.md
  docs/api/advanced-plots/facet.zh.md
  docs/api/advanced-plots/mix.en.md
  docs/api/advanced-plots/mix.zh.md
  docs/api/mix.en.md
  docs/api/mix.zh.md
  docs/common/common-iview.en.md
  docs/common/common-iview.zh.md
  docs/common/facet-title.en.md
  docs/common/facet-title.zh.md
  docs/common/geometry-cfg.en.md
  docs/common/geometry-cfg.zh.md
  docs/common/plot-cfg.en.md
  docs/common/plot-cfg.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  examples/facet/plot/API.en.md
  examples/facet/plot/API.zh.md
  examples/facet/plot/demo/circle.ts
  examples/facet/plot/demo/column.ts
  examples/facet/plot/demo/list.ts
  examples/facet/plot/demo/matrix.ts
  examples/facet/plot/demo/meta.json
  examples/facet/plot/demo/mirror.ts
  examples/facet/plot/demo/rect.ts
  examples/facet/plot/demo/tree-column.ts
  examples/facet/plot/demo/tree.ts
  examples/facet/plot/index.en.md
  examples/facet/plot/index.zh.md
  examples/plugin/multi-view/API.en.md
  examples/plugin/multi-view/API.zh.md
  gatsby-config.js
  package.json
  src/index.ts
  src/plots/facet/adaptor.ts
  src/plots/facet/constant.ts
  src/plots/facet/index.ts
  src/plots/facet/types.ts
  src/plots/facet/utils.ts
  src/plots/mix/utils.ts
  src/types/index.ts
Labels: PR: unreviewed

#2561 docs(radar): 说明 seriesField 的使用
  docs/api/plots/radar.en.md
  docs/api/plots/radar.zh.md
Labels: PR: reviewed-approved

#2563 refactor heatmap
  __tests__/unit/plots/facet/use-plot-spec.ts
  __tests__/unit/plots/heatmap/tooltip-spec.ts
  src/plots/heatmap/adaptor.ts
Labels: PR: reviewed-approved

#2565 fix(issue-2502): 修复对称条形图 axis 设置
  __tests__/bugs/issue-2502-spec.ts
  src/plots/bidirectional-bar/adaptor.ts
Labels: PR: reviewed-approved

#2567 feat(statistic): 中心统计文本支持 content 设置
  __tests__/unit/plots/gauge/statistic-spec.ts
  __tests__/unit/plots/liquid/statistic-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/ring-progress/statistic-spec.ts
  __tests__/unit/utils/statistic-spec.ts
  docs/api/components/slider.zh.md
  docs/api/components/statistic.en.md
  docs/api/components/statistic.zh.md
  docs/common/statistic.en.md
  docs/common/statistic.zh.md
  examples/pie/donut/demo/basic.ts
  src/plots/gauge/adaptor.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/constants.ts
  src/plots/pie/adaptor.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/constants.ts
  src/types/statistic.ts
  src/utils/statistic.ts
Labels: PR: reviewed-approved

#2577 fix(#2573): 修复雷达图设置 point state 状态样式不生效
  __tests__/bugs/issue-2573-spec.ts
  docs/common/point-style.en.md
  docs/common/point-style.zh.md
  src/plots/radar/adaptor.ts
  src/types/state.ts
Labels: PR: reviewed-approved

#2576 fix(#2572): 修复堆叠分组状图 tooltip 展示不正常 (只展示第一个小分组的数据)
  __tests__/bugs/issue-2572-spec.ts
  examples/column/grouped/demo/meta.json
  examples/column/grouped/demo/tooltip-formatter.ts
  src/plots/column/adaptor.ts
  src/utils/index.ts
Labels: PR: partially-approved

#2571 [桑基图] 优化桑基图 cutoffcircle 逻辑，降低时间复杂度
  __tests__/unit/plots/sankey/circle-spec.ts
  src/plots/sankey/circle.ts
Labels: PR: unreviewed

#2564 feat: 补充自动巡检 action
  .github/workflows/auto-inspection.yml
Labels: PR: unreviewed

#2569 feat(violin): 添加小提琴图
  __tests__/data/violin.ts
  __tests__/unit/plots/violin/box-spec.ts
  __tests__/unit/plots/violin/change-data-spec.ts
  __tests__/unit/plots/violin/index-spec.ts
  __tests__/unit/plots/violin/utils-spec.ts
  __tests__/unit/plots/violin/violin-shape-spec.ts
  docs/api/plots/violin.en.md
  docs/api/plots/violin.zh.md
  examples/more-plots/violin/API.en.md
  examples/more-plots/violin/API.zh.md
  examples/more-plots/violin/demo/basic.ts
  examples/more-plots/violin/demo/group.ts
  examples/more-plots/violin/demo/meta.json
  examples/more-plots/violin/demo/shape.ts
  examples/more-plots/violin/demo/tooltip.ts
  examples/more-plots/violin/index.en.md
  examples/more-plots/violin/index.zh.md
  package.json
  src/adaptor/geometries/index.ts
  src/adaptor/geometries/violin.ts
  src/index.ts
  src/plots/violin/adaptor.ts
  src/plots/violin/constant.ts
  src/plots/violin/index.ts
  src/plots/violin/types.ts
  src/plots/violin/utils.ts
  src/utils/transform/quantile.ts
Labels: PR: unreviewed

#2595 Enhance testcases
  __tests__/unit/utils/view-spec.ts
  src/plots/mix/interactions/association.ts
  src/utils/index.ts
  src/utils/view.ts
Labels: PR: reviewed-approved

#2583 feat(box): 重构和增强箱线图
  __tests__/unit/plots/box/tooltip-spec.ts
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  examples/more-plots/box/demo/meta-alias.ts
  examples/more-plots/box/demo/meta.json
  src/plots/box/adaptor.ts
  src/plots/box/constant.ts
Labels: PR: reviewed-approved
