Repository antvis/G2Plot, pull requests merged in 2021-11, with the labels that each got.

#2965 fix typo
  docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved

#2959 docs: correct doc about `rotate`
  docs/api/plots/gauge.en.md
  docs/api/plots/pie.en.md
  docs/api/plots/radar.en.md
  docs/api/plots/radial-bar.en.md
  docs/api/plots/rose.en.md
  docs/api/plots/word-cloud.en.md
  docs/api/plots/word-cloud.zh.md
  docs/common/axis.en.md
  docs/common/label.en.md
  docs/common/label.zh.md
  docs/common/statistic.en.md
Labels: PR: reviewed-approved

#2961 docs: 增加图例自定义 marker 的demo
  docs/common/marker.en.md
  docs/common/marker.zh.md
  examples/component/legend/demo/legend-marker-customize.ts
  examples/component/legend/demo/meta.json
Labels: PR: unreviewed

#2970 chore(release): 2.3.40 published
  .github/workflows/auto-release.yml
  .github/workflows/release-notify.yml
  .releaserc.js
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2971 fix: fix document typo
  examples/plugin/basic/demo/hill-column.ts
Labels: PR: unreviewed

#2973 chore: 移除 semantic-release
  .github/workflows/auto-release.yml
  .github/workflows/release-notify.yml
  .releaserc.js
  package.json
Labels: PR: unreviewed

#2974 docs(bar): 条形图增加 bar 配置文档说明和demo
  __tests__/unit/plots/word-cloud/index-spec.ts
  docs/api/plots/bar.en.md
  docs/api/plots/bar.zh.md
  docs/api/plots/column.en.md
  examples/bar/basic/demo/meta.json
  examples/bar/basic/demo/shape.ts
  examples/column/basic/demo/custom-shape.ts
Labels: PR: unreviewed

#2980 Update package.json
  .github/workflows/test-test.yml
  package.json
Labels: PR: reviewed-approved

#2981 ci: remove test-test.yml
  .github/workflows/test-test.yml
Labels: PR: unreviewed

#2989 chore: fix description of package
  package.json
Labels: PR: unreviewed

#2991 ci: remove node 12
  .github/workflows/release.yml
Labels: PR: unreviewed

#2914 refactor(bar): 条形图重构，不需要反转数据 调整下坐标系即可
  __tests__/bugs/bar-changedata-spec.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/plots/bar/change-data-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/bar/label-spec.ts
  __tests__/unit/plots/bar/pattern-spec.ts
  docs/api/plots/bar.zh.md
  docs/api/plots/column.zh.md
  docs/api/plots/dual-axes.zh.md
  src/adaptor/conversion-tag.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/bar/utils.ts
Labels: PR: unreviewed, BreakingChange

#2998 docs: 补充 legend 文档 & 自定义转化漏斗图 demo
  __tests__/unit/plots/word-cloud/legend-spec.ts
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  examples/case/statistical-scenario/demo/conversion-funnel.ts
  examples/case/statistical-scenario/demo/meta.json
Labels: PR: unreviewed
