Repository antvis/G2Plot, pull requests merged in 2021-08, with the labels that each got.

#2750 issue-2748: treemap color function apply rawFields
  __tests__/unit/plots/treemap/color-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  src/plots/treemap/adaptor.ts
  src/plots/treemap/types.ts
Labels: PR: reviewed-approved

#2756 fix(sankey): 修复桑基图 rawFields 在 label & tooltip 处不生效
  __tests__/bugs/issue-2755-spec.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/index.ts
Labels: PR: unreviewed

#2757 feat(sankey): 桑基图支持 state 配置
  __tests__/unit/plots/sankey/state-spec.ts
  docs/api/plots/sankey.en.md
  docs/api/plots/sankey.zh.md
  examples/relation-plots/sankey/demo/meta.json
  examples/relation-plots/sankey/demo/set-state.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/index.ts
  src/plots/sankey/types.ts
Labels: PR: unreviewed

#2764 docs: Fix a few typos
  CONTRIBUTING.md
  docs/api/options/interactions.en.md
  docs/api/plots/liquid.en.md
  docs/common/interactions.en.md
Labels: PR: reviewed-approved

#2767 fix: 修复错误 & 更新官网展示 github
  gatsby-config.js
  src/core/plot.ts
Labels: PR: unreviewed

#2769 fix: 修复custom tooltip导致容器无限增大
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
Labels: PR: unreviewed

#2768 website: richer demos
  examples/case/advanced/demo/associate-filter.ts
  examples/case/advanced/demo/associate-pie-tooltip.ts
  examples/case/advanced/demo/meta.json
  examples/case/advanced/index.en.md
  examples/case/advanced/index.zh.md
  examples/dynamic-plots/brush/demo/advanced-brush1.ts
  examples/dynamic-plots/brush/demo/advanced-brush2.ts
  gatsby-config.js
Labels: PR: unreviewed

#2770 chore: v2.3.29 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2776 修复: [BUG] 双轴图图例legend使用symbol的时候，颜色不能自动调整
  __tests__/unit/plots/dual-axes/legend-spec.ts
  src/plots/dual-axes/util/legend.ts
Labels: PR: reviewed-approved

#2780 feat(line-pattern): 添加linePattern
  examples/pie/basic/demo/basic.ts
  src/adaptor/pattern.ts
  src/index.ts
  src/plugin/pattern/line.ts
  src/types/attr.ts
  src/utils/pattern/base.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/index.ts
  src/utils/pattern/line.ts
  src/utils/pattern/pattern.ts
Labels: PR: reviewed-approved

#2781 refactor: pattern
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/index.ts
Labels: PR: partially-approved

#2782 feat(square-pattern): 添加square样式贴图
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/index.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
Labels: PR: unreviewed

#2785 refactor(pattern): 内置 pattern 的属性设计 & 优化下创建逻辑
  src/utils/pattern/base.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/index.ts
  src/utils/pattern/line.ts
  src/utils/pattern/pattern.ts
  src/utils/pattern/square.ts
Labels: PR: partially-approved

#2784 fix(dualaxes): configure legend selected
  __tests__/bugs/issue-2783-spec.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: unreviewed

#2786 test(pattern): 修复dot的stagger呈现问题，初步添加util中getCanvasPattern的单测
  __tests__/unit/plots/dual-axes/legend-spec.ts
  __tests__/unit/utils/pattern/index-spec.ts
  package.json
  src/plots/dual-axes/util/legend.ts
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
Labels: PR: unreviewed

#2788 refactor(pattern): 优化pattern的写法，抽出一些方法
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
  src/utils/pattern/util.ts
Labels: PR: reviewed-changes-requested

#2789 refactor(pattern): 使用setTransform方法，rotation作用于整个pattern画布
  __tests__/unit/utils/pattern/dot-spec.ts
  __tests__/unit/utils/pattern/line-spec.ts
  __tests__/unit/utils/pattern/square-spec.ts
  __tests__/unit/utils/pattern/util-spec.ts
  __tests__/utils/getPixelColor.ts
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/index.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
  src/utils/pattern/util.ts
Labels: PR: reviewed-approved

#2787 fix: 修复词云图 legend 配置不起效 修复 词云图 color 回调缺少其他数据
  __tests__/unit/plots/word-cloud/color-spec.ts
  __tests__/unit/plots/word-cloud/legend-spec.ts
  src/plots/word-cloud/adaptor.ts
  src/plots/word-cloud/constant.ts
Labels: PR: reviewed-approved

#2791 fix: 修复双轴图 theme 设置覆盖 columnWidthRatio 设置
  __tests__/bugs/issue-2734-spec.ts
  __tests__/unit/plots/multi-view/state-spec.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: unreviewed

#2793 fix: 修复尖底漏斗图最后一排错位
  __tests__/unit/plots/funnel/basic-spec.ts
  src/plots/funnel/geometries/basic.ts
Labels: PR: reviewed-approved

#2795 chore: v2.3.30 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2798 docs(pattern): 添加pattern的文档
  __tests__/unit/utils/pattern/util-spec.ts
  docs/api/plots/pie.en.md
  docs/api/plots/pie.zh.md
  docs/common/pattern.en.md
  docs/common/pattern.zh.md
  src/types/pattern.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
Labels: PR: reviewed-approved

#2751 fix: 修复无拆分时折线图 color 回调报错
  __tests__/bugs/issue-2749-spec.ts
  src/adaptor/geometries/base.ts
Labels: PR: reviewed-approved

#2800 fix(dual-axes): 修复双轴图使用 color 回调时，legend marker 颜色丢失
  __tests__/bugs/bug-dual-axes-legend-marker-spec.ts
  __tests__/unit/adaptor/geometries/base-spec.ts
  __tests__/unit/plots/dual-axes/legend-spec.ts
  src/adaptor/geometries/base.ts
  src/plots/dual-axes/util/legend.ts
Labels: PR: unreviewed

#2801 fix(line-pattern): 修复linewidth>=spacing 时，绘制异常问题
  examples/plugin/pattern/demo/bar-pattern.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
Labels: PR: reviewed-approved

#2803 chore: v2.3.21 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2807 docs: 增加 2 个转化分析漏斗图 demo, 带跳转
  README.md
  README.zh-CN.md
  __tests__/bugs/issue-2749-spec.ts
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  examples/case/advanced/demo/conversion-analysis-bar.ts
  examples/case/advanced/demo/conversion-analysis.ts
  examples/case/advanced/demo/meta.json
  examples/dynamic-plots/brush/demo/meta.json
Labels: PR: unreviewed

#2811 feat: tiny area pattern
  docs/api/pattern.zh.md
  examples/tiny/tiny-area/demo/meta.json
  examples/tiny/tiny-area/demo/pattern.ts
  src/plots/tiny-area/adaptor.ts
Labels: PR: unreviewed

#2810 feat: rose support pattern
  examples/rose/grouped/demo/basic.ts
  examples/rose/grouped/demo/meta.json
  examples/rose/grouped/demo/pattern.ts
  src/plots/rose/adaptor.ts
Labels: PR: unreviewed

#2812 feat: liquid pattern
  examples/progress-plots/liquid/demo/meta.json
  examples/progress-plots/liquid/demo/pattern.ts
  src/plots/liquid/adaptor.ts
Labels: PR: unreviewed

#2815 test: 补充旭日图等单测和文档
  __tests__/unit/plots/circle-packing/pattern-spec.ts
  __tests__/unit/plots/heatmap/pattern-spec.ts
  __tests__/unit/plots/liquid/pattern-spec.ts
  __tests__/unit/plots/radial-bar/pattern-spec.ts
  __tests__/unit/plots/rose/pattern-spec.ts
  __tests__/unit/plots/sunburst/pattern-spec.ts
  __tests__/unit/plots/tiny-area/pattern-spec.ts
  __tests__/unit/plots/tiny-column/pattern-spec.ts
  docs/api/pattern.zh.md
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  docs/api/plots/rose.en.md
  docs/api/plots/rose.zh.md
  docs/api/plots/sunburst.en.md
  docs/api/plots/sunburst.zh.md
  docs/api/plots/tiny-area.en.md
  docs/api/plots/tiny-area.zh.md
  src/types/attr.ts
Labels: PR: unreviewed

#2813 feat: dual axes pattern
  examples/dual-axes/column-line/demo/pattern.ts
  examples/dual-axes/grouped-column-line/demo/meta.json
  examples/dual-axes/grouped-column-line/demo/pattern-with-callback.ts
  src/plots/dual-axes/util/geometry.ts
Labels: PR: unreviewed

#2817 fix(funnel): 不将 label 的 layout 的 type 设置为 interval-adjust-position
  __tests__/unit/plots/funnel/basic-spec.ts
  src/plots/funnel/geometries/basic.ts
Labels: PR: partially-approved

#2818 docs: 添加pattern精选案例
  __tests__/unit/plots/dual-axes/pattern-spec.ts
  docs/api/pattern.en.md
  docs/api/pattern.zh.md
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
  docs/common/pattern.en.md
  docs/common/pattern.zh.md
  examples/dual-axes/column-line/demo/meta.json
  examples/plugin/pattern/demo/area-pattern.ts
  examples/plugin/pattern/demo/bar-pattern.ts
  examples/plugin/pattern/demo/column-pattern.ts
  examples/plugin/pattern/demo/donut-pattern.ts
  examples/plugin/pattern/demo/group-column-pattern.ts
  examples/plugin/pattern/demo/heatmap-cookie-pattern.ts
  examples/plugin/pattern/demo/heatmap-pattern.ts
  examples/plugin/pattern/demo/legend-marker-with-pattern.ts
  examples/plugin/pattern/demo/liquid-pattern.ts
  examples/plugin/pattern/demo/meta.json
  examples/plugin/pattern/demo/pie-pattern.ts
  examples/plugin/pattern/demo/radial-bar-pattern.ts
  examples/plugin/pattern/demo/stack-bar-pattern.ts
  examples/plugin/pattern/demo/stacked-group-column-pattern.ts
  examples/rose/basic/demo/meta.json
  examples/rose/basic/demo/rose-pattern.ts
  src/plots/dual-axes/types.ts
  src/utils/pattern/dot.ts
  src/utils/pattern/line.ts
  src/utils/pattern/square.ts
Labels: PR: reviewed-approved

#2819 chore: 2.3.32 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2823 docs: annotations 相关文档完善
  docs/api/components/annotations.en.md
  docs/api/components/annotations.zh.md
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
  docs/api/plots/funnel.en.md
  docs/api/plots/funnel.zh.md
  docs/api/plots/scatter.en.md
  docs/api/plots/scatter.zh.md
  docs/common/annotations.en.md
  docs/common/annotations.zh.md
  docs/common/annotations/arc.en.md
  docs/common/annotations/arc.zh.md
  docs/common/annotations/base-annotation.en.md
  docs/common/annotations/base-annotation.zh.md
  docs/common/annotations/data-marker.en.md
  docs/common/annotations/data-marker.zh.md
  docs/common/annotations/data-region.en.md
  docs/common/annotations/data-region.zh.md
  docs/common/annotations/html.en.md
  docs/common/annotations/html.zh.md
  docs/common/annotations/image.en.md
  docs/common/annotations/image.zh.md
  docs/common/annotations/line.en.md
  docs/common/annotations/line.zh.md
  docs/common/annotations/region-filter.en.md
  docs/common/annotations/region-filter.zh.md
  docs/common/annotations/region.en.md
  docs/common/annotations/region.zh.md
  docs/common/annotations/shape.en.md
  docs/common/annotations/shape.zh.md
  docs/common/annotations/text.en.md
  docs/common/annotations/text.zh.md
  docs/common/common-component.en.md
  docs/common/common-component.zh.md
  docs/common/component-no-axis.en.md
  docs/common/component-no-axis.zh.md
  docs/common/component-polygon.en.md
  docs/common/component-polygon.zh.md
  docs/common/component-progress.en.md
  docs/common/component-progress.zh.md
  docs/common/component-tiny.en.md
  docs/common/component-tiny.zh.md
  examples/component/annotation/API.en.md
  examples/component/annotation/API.zh.md
  examples/component/annotation/demo/area-with-line-annotation.ts
  examples/component/annotation/demo/line-annotation-accurate.ts
  examples/component/annotation/demo/line-annotation-position.jsx
  examples/component/annotation/demo/meta.json
  examples/component/annotation/demo/text-annotation1.ts
  examples/component/annotation/demo/text-annotation2.ts
  examples/dual-axes/column-line/demo/meta.json
  examples/more-plots/sunburst/demo/meta.json
  examples/pie/basic/demo/basic.ts
  examples/rose/basic/demo/meta.json
  examples/rose/grouped/demo/meta.json
  examples/tiny/tiny-area/demo/meta.json
Labels: PR: unreviewed
