Repository antvis/G2Plot, pull requests merged in 2021-01, with the labels that each got.

#2167 docs: 修复教程页的 404 链接 & 优化 api 文档的字体间距等样式'
  docs/api/plot-api.zh.md
  docs/api/plots/radar.en.md
  docs/api/plots/radar.zh.md
  docs/common/interactions.zh.md
  docs/common/label.en.md
  docs/common/label.zh.md
  docs/common/line-style.en.md
  docs/common/line-style.zh.md
  docs/common/point-style.en.md
  docs/common/point-style.zh.md
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  docs/common/text-style.en.md
  docs/common/text-style.zh.md
  docs/common/theme.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  docs/manual/getting-started.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  package.json
  site/pages/index.less
Labels: PR: partially-approved

#2168 fix(issue-2161): 修复数据项存在非法 undefined 时，获取数据 max 为 NaN，导致玉珏图渲染页面崩溃
  __tests__/bugs/issue-2161-spec.ts
  __tests__/unit/plots/radial-bar/utils-spec.ts
  src/plots/radial-bar/utils.ts
Labels: PR: partially-approved

#2172 docs: 迁移和弦图文档地址 & 文档样式优化 & 修复 绘图属性文档链接 404
  docs/api/components/legend.zh.md
  docs/api/plots/gauge.zh.md
  docs/common/annotations.en.md
  docs/common/annotations.zh.md
  docs/common/chord.en.md
  docs/common/chord.zh.md
  docs/common/conversion-tag.en.md
  docs/common/conversion-tag.zh.md
  docs/common/legend-cfg.zh.md
  docs/common/shape-style.en.md
  docs/common/shape-style.zh.md
  docs/common/slider.en.md
  docs/common/slider.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved

#2170 fix: stock股票图重写changeData方法
  __tests__/unit/plots/stock/change-data-spec.ts
  __tests__/unit/plots/stock/data-spec.ts
  src/plots/stock/adaptor.ts
  src/plots/stock/index.ts
  src/plots/stock/utils.ts
Labels: PR: reviewed-approved

#2173 feat: tiny area change data
  __tests__/unit/plots/tiny-area/change-data-spec.ts
  src/plots/tiny-area/index.ts
Labels: PR: reviewed-approved

#2176 fix(dual-axes): 双轴图的 y 字段相同的时候,导致 yaxis 配置被覆盖
  __tests__/bugs/bug-dual-axes-same-y-spec.ts
  __tests__/unit/plots/dual-axes/util/option-spec.ts
  gatsby-config.js
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/option.ts
Labels: PR: unreviewed

#2177 feat: 迷你折线图和迷你柱形图重写changeData && 添加单测
  __tests__/unit/plots/tiny-column/change-data-spec.ts
  __tests__/unit/plots/tiny-line/change-data-spec.ts
  __tests__/unit/plots/tiny-line/get-tiny-data-spec.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/index.ts
  src/plots/tiny-line/utils.ts
Labels: PR: reviewed-approved

#2182 docs: 增加 meta options 的配置说明文档 & radar demo 移除数据处理逻辑
  README.md
  README.zh-CN.md
  docs/api/events.en.md
  docs/api/events.zh.md
  docs/api/graphic-style.en.md
  docs/api/graphic-style.zh.md
  docs/api/interactions.en.md
  docs/api/interactions.zh.md
  docs/api/multi-view.en.md
  docs/api/multi-view.zh.md
  docs/api/options/meta.en.md
  docs/api/options/meta.zh.md
  docs/api/theme.en.md
  docs/api/theme.zh.md
  docs/common/events.en.md
  docs/common/events.zh.md
  docs/common/meta.en.md
  docs/common/meta.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  examples/more-plots/radar/demo/area-alternate-grid.ts
  examples/more-plots/radar/demo/area-grid.ts
  examples/more-plots/radar/demo/area.ts
  examples/more-plots/radar/demo/line-alternate-grid.ts
  examples/more-plots/radar/demo/line-grid.ts
  examples/more-plots/radar/demo/line.ts
  gatsby-config.js
  site/pages/index.less
Labels: PR: partially-approved

#2181 docs(plugin-plot): 收录 g2plot-lollipop 自定义图表
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
Labels: PR: reviewed-approved

#2178 feat(sankey): remove the circle data in sankey
  __tests__/unit/plots/sankey/circle-spec.ts
  __tests__/unit/plots/sankey/index-spec.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/circle.ts
Labels: PR: reviewed-approved

#2183 Chore 2.3.7
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2185 fix(radial-bar): 修复line类型的珏玦图，设置color对point不生效
  __tests__/unit/plots/radial-bar/index-spec.ts
  src/plots/radial-bar/adaptor.ts
Labels: PR: partially-approved

#2186 feat(sankey): add default label layout
  src/plots/sankey/index.ts
Labels: PR: reviewed-approved

#2188 [fix/treemap]: label.formatter 传参和 label.field 相对应
  __tests__/data/treemap-nest.ts
  __tests__/data/treemap.ts
  __tests__/unit/plots/treemap/lable-spec.ts
  __tests__/unit/plots/treemap/tooltip-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  src/plots/treemap/utils.ts
Labels: PR: reviewed-approved

#2193 fix(demo): demo 实例容器自适应，不需要加宽高 否则影响动画效果
  examples/more-plots/radial-bar/demo/background.ts
  examples/more-plots/radial-bar/demo/basic.ts
  examples/more-plots/radial-bar/demo/color.ts
  examples/more-plots/radial-bar/demo/line.ts
  examples/more-plots/radial-bar/demo/round-corner.ts
  src/plots/radial-bar/index.ts
Labels: PR: reviewed-approved

#2194 docs: 教程页增加以图表类型分类的图表指引
  docs/api/plots/waterfall.en.md
  docs/api/plots/waterfall.zh.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/plots/area.en.md
  docs/manual/plots/area.zh.md
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/histogram.en.md
  docs/manual/plots/histogram.zh.md
  docs/manual/plots/line.en.md
  docs/manual/plots/line.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plots/radar.en.md
  docs/manual/plots/radar.zh.md
  docs/manual/plots/scatter.en.md
  docs/manual/plots/scatter.zh.md
  docs/manual/plots/waterfall.en.md
  docs/manual/plots/waterfall.zh.md
  examples/bar/basic/design.en.md
  examples/case/statistical-scenario/design.en.md
  examples/case/statistical-scenario/design.zh.md
  examples/more-plots/histogram/demo/basic.ts
  examples/more-plots/radar/demo/basic.ts
  examples/pie/basic/design.en.md
  examples/pie/basic/design.zh.md
  examples/progress-plots/liquid/demo/meta.json
  gatsby-config.js
  site/pages/index.less
  src/plots/liquid/index.ts
Labels: PR: partially-approved

#2197 feat(progress): 进度条&环形进度条支持 changeData
  src/plots/progress/adaptor.ts
  src/plots/progress/index.ts
  src/plots/progress/utils.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/index.ts
Labels: PR: reviewed-approved

#2196 feat(tiny-plot): 迷你图默认开启动画效果 & public 方法提前
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/index.ts
Labels: PR: reviewed-approved

#2198 feat(liquid): 水波图支持动态 changedata
  __tests__/unit/plots/liquid/statistic-spec.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/utils.ts
Labels: PR: unreviewed

#2199 feat(histogram): 直方图支持动态 changedata
  __tests__/unit/plots/histogram/change-data-spec.ts
  src/plots/histogram/index.ts
Labels: PR: reviewed-approved

#2200 feat: 玫瑰图修改 changeData && 添加单测
  __tests__/unit/plots/rose/change-data-spec.ts
  src/plots/rose/index.ts
Labels: PR: reviewed-approved

#2191 Fix/nest treemap
  __tests__/unit/plots/treemap/color-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  __tests__/unit/utils/hierarchy/treemap-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  examples/more-plots/sunburst/demo/reflect.ts
  examples/more-plots/treemap/demo/treemap-nest.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/utils.ts
  src/utils/hierarchy/treemap.ts
  src/utils/hierarchy/types.ts
Labels: PR: partially-approved

#2201 docs(column): 柱状图 图表指引增加一些特性介绍
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  docs/manual/plots/pie.zh.md
Labels: PR: reviewed-approved

#2205 feat: 雷达图重写changeData方法 && 添加单测
  .lintmdrc
  __tests__/unit/plots/radar/change-data-spec.ts
  __tests__/unit/plots/stock/change-data-spec.ts
  __tests__/unit/plots/stock/data-spec.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/radar/index.ts
  src/plots/tiny-column/index.ts
Labels: PR: reviewed-approved

#2206 feat: 玉珏图重写changeData方法 && 添加单测
  __tests__/unit/plots/radial-bar/change-data-spec.ts
  src/plots/radial-bar/index.ts
Labels: PR: reviewed-approved

#2204 fix: 对称条形图数据顺序问题
  __tests__/bugs/issue-2180-spec.ts
  src/plots/bidirectional-bar/adaptor.ts
Labels: PR: reviewed-approved

#2207 fix: 修复玉珏图changeData时未同步变更scale
  __tests__/unit/plots/radial-bar/change-data-spec.ts
  __tests__/unit/plots/radial-bar/utils-spec.ts
  src/plots/radial-bar/index.ts
  src/plots/radial-bar/utils.ts
Labels: PR: reviewed-approved

#2208 feat(word-cloud): 词云图支持展示 legend
  __tests__/unit/plots/word-cloud/legend-spec.ts
  examples/more-plots/word-cloud/demo/douban-2020-movie.ts
  examples/more-plots/word-cloud/demo/meta.json
  src/plots/word-cloud/adaptor.ts
  src/plots/word-cloud/index.ts
Labels: PR: unreviewed

#2211 fix(#2203): crash when percent = NaN
  __tests__/bugs/issue-2203-spec.ts
  __tests__/unit/plots/progress/utils-spec.ts
  src/plots/progress/utils.ts
Labels: PR: unreviewed

#2209 docs: 优化图表示例 api 文档样式
  site/pages/index.less
Labels: PR: reviewed-approved

#2212 feat: 重写瀑布图changeData方法 && 添加单测
  __tests__/unit/plots/waterfall/change-data-spec.ts
  src/plots/waterfall/index.ts
Labels: PR: reviewed-approved

#2213 docs: 添加钉钉联系方式
  README.md
  README.zh-CN.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
Labels: PR: reviewed-approved

#2214 feat: 词云图重写changeData方法 && 添加单测
  __tests__/unit/plots/word-cloud/change-data-spec.ts
  src/plots/word-cloud/index.ts
Labels: PR: reviewed-approved

#2215 feat(column): 柱状图支持圆角 & 添加图表指引
  docs/manual/plots/bar.en.md
  docs/manual/plots/bar.zh.md
  docs/manual/plots/column.en.md
  docs/manual/plots/column.zh.md
  examples/bar/grouped/demo/corner-radius.ts
  examples/bar/grouped/demo/meta.json
  examples/column/grouped/demo/corner-radius.ts
  examples/column/grouped/demo/meta.json
Labels: PR: reviewed-approved

#2217 chore: 2.3.8 & add changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2228 refactor(bullet): 子弹图升级下 & 修复 axis 配置失效
  __tests__/unit/plots/bullet/axis-spec.ts
  __tests__/unit/plots/bullet/index-spec.ts
  docs/api/plots/bullet.en.md
  docs/api/plots/bullet.zh.md
  docs/manual/plots/bullet.en.md
  docs/manual/plots/bullet.zh.md
  examples/more-plots/bidirectional-bar/demo/layout.ts
  examples/more-plots/box/demo/basic.ts
  examples/more-plots/stock/demo/basic.ts
  examples/more-plots/sunburst/demo/basic.ts
  examples/more-plots/waterfall/demo/absolute-label.ts
  examples/more-plots/word-cloud/demo/image-mask-base64.ts
  examples/progress-plots/bullet/demo/basic.ts
  examples/progress-plots/bullet/demo/color.ts
  examples/progress-plots/bullet/demo/grouped.ts
  examples/progress-plots/bullet/demo/layout.ts
  examples/progress-plots/bullet/demo/meta.json
  examples/progress-plots/bullet/demo/stacked.ts
  examples/progress-plots/liquid/demo/style.ts
  examples/scatter/bubble/demo/axis-right.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
Labels: PR: partially-approved

#2221 feat: 重写子弹图changeData方法 && 添加单测
  __tests__/unit/plots/bullet/change-data-spec.ts
  src/plots/bullet/adaptor.ts
  src/plots/bullet/index.ts
Labels: PR: unreviewed, WIP

#2235 feat(waterfall): 瀑布图回调参数增加分类字段
  __tests__/unit/plots/waterfall/label-spec.ts
  src/plots/waterfall/adaptor.ts
Labels: PR: reviewed-approved

#2234 feat: 为 treemap 新增rectstyle 和 hierarchyConfig 属性
  __tests__/unit/plots/treemap/rect-style-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  src/plots/treemap/adaptor.ts
  src/plots/treemap/types.ts
  src/plots/treemap/utils.ts
Labels: PR: partially-approved

#2238 fix(#2236): liquid distance calculate error
  __tests__/bugs/issue-2080-spec.ts
  __tests__/bugs/issue-2236-spec.ts
  __tests__/unit/plots/liquid/index-spec.ts
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  src/plots/liquid/shapes/liquid.ts
Labels: PR: reviewed-approved

#2241 fix(issue-2216): 饼图默认强制关闭 tooltip shared
  __tests__/unit/plots/pie/index-spec.ts
  src/adaptor/common.ts
  src/plots/multi-view/types.ts
  src/plots/pie/adaptor.ts
Labels: PR: reviewed-approved

#2240 fix: 对称条形图 meta 支持 yField 设置别名
  __tests__/bugs/issue-2180-spec.ts
  __tests__/unit/plots/bidirectional-bar/data-spec.ts
  __tests__/unit/plots/bidirectional-bar/index-spec.ts
  __tests__/unit/plots/bidirectional-bar/meta-spec.ts
  __tests__/unit/plots/bidirectional-bar/utils-spec.ts
  docs/api/plots/bidirectional-bar.en.md
  docs/api/plots/bidirectional-bar.zh.md
  docs/api/plots/bullet.en.md
  docs/api/plots/column.en.md
  docs/api/plots/dual-axes.en.md
  docs/api/plots/heatmap.en.md
  docs/api/plots/histogram.en.md
  docs/api/plots/pie.en.md
  docs/api/plots/radar.en.md
  docs/api/plots/rose.en.md
  docs/api/plots/scatter.en.md
  docs/api/plots/stock.en.md
  docs/api/plots/treemap.en.md
  docs/api/plots/waterfall.en.md
  docs/api/plots/word-cloud.en.md
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/bidirectional-bar/constant.ts
  src/plots/bidirectional-bar/types.ts
  src/plots/bidirectional-bar/utils.ts
Labels: PR: partially-approved

#2237 fix: 散点图新增默认size
  __tests__/unit/plots/scatter/size-spec.ts
  src/plots/scatter/adaptor.ts
Labels: PR: partially-approved

#2244 docs: multi-language
  docs/api/components/legend.en.md
  docs/api/graphic-style.en.md
  docs/api/options/meta.en.md
  docs/api/plot-api.en.md
  docs/api/plots/area.en.md
  docs/api/plots/bidirectional-bar.en.md
  docs/api/plots/liquid.en.md
  docs/api/plots/scatter.en.md
  docs/api/plots/sunburst.en.md
  docs/common/animate-option.en.md
  docs/common/annotations.en.md
  docs/common/axis.en.md
  docs/common/chord.en.md
  docs/common/connected-area.en.md
  docs/common/conversion-tag.en.md
  docs/common/events.en.md
  docs/common/interactions.en.md
  docs/common/label.en.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  docs/common/legend.en.md
  docs/common/line-style.en.md
  docs/common/marker.en.md
  docs/common/meta.en.md
  docs/common/point-style.en.md
  docs/common/shape-style.en.md
  docs/common/slider.en.md
  docs/common/statistic.en.md
  docs/common/text-style.en.md
  docs/common/theme.en.md
  docs/common/tooltip.en.md
  docs/common/xy-field.en.md
  docs/manual/upgrade.en.md
Labels: PR: reviewed-approved

#2252 fix(word-cloud): 由于无法判断首次 render 是否ready，changedata时，如果有 imageMask，重渲染
  src/plots/word-cloud/index.ts
Labels: PR: partially-approved

#2251 feat(radial-bar): 玉珏图支持配置开始角度和结束角度
  docs/api/plots/radial-bar.en.md
  docs/api/plots/radial-bar.zh.md
  docs/common/axis.zh.md
  examples/more-plots/radial-bar/demo/line.ts
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/types.ts
Labels: PR: partially-approved

#2253 chore: changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2254 docs: 文档层级错误 & 修改 tooltip domStyles 类型定义
  docs/common/axis.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
Labels: PR: partially-approved

#2255 fix: export multi view options
  src/index.ts
Labels: PR: reviewed-approved

#2262 docs: 补充图表英文文档
  docs/api/plots/bar.en.md
  docs/api/plots/bullet.en.md
  docs/api/plots/column.en.md
  docs/api/plots/dual-axes.en.md
  docs/api/plots/gauge.en.md
  docs/api/plots/heatmap.en.md
  docs/api/plots/histogram.en.md
  docs/api/plots/line.en.md
  docs/api/plots/pie.en.md
  docs/api/plots/progress.en.md
  docs/api/plots/radar.en.md
  docs/api/plots/radial-bar.en.md
  docs/api/plots/ring-progress.en.md
  docs/api/plots/rose.en.md
  docs/api/plots/sankey.en.md
  docs/api/plots/sunburst.en.md
  docs/api/plots/tiny-area.en.md
  docs/api/plots/tiny-column.en.md
  docs/api/plots/tiny-line.en.md
  docs/api/plots/treemap.en.md
  docs/api/plots/waterfall.en.md
  docs/api/plots/word-cloud.en.md
  docs/common/bar-style.en.md
  docs/common/chart-methods.en.md
  docs/common/chord.en.md
  docs/common/column-style.en.md
  examples/general/annotation/API.en.md
  examples/more-plots/bidirectional-bar/API.en.md
Labels: PR: reviewed-approved

#2257 feat(change-data): 饼图支持动态更新数据 & 其他若干处理，见 PR 描述
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/pie/annotation-spec.ts
  __tests__/unit/plots/pie/data-spec.ts
  __tests__/unit/plots/pie/index-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  examples/dynamic-plots/basic/demo/dynamic-pie.ts
  examples/dynamic-plots/basic/demo/meta.json
  src/core/plot.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/contants.ts
  src/plots/pie/index.ts
  src/plots/pie/utils.ts
Labels: PR: unreviewed

#2263 fix: 修复散点图 size 回调不生效
  __tests__/unit/plots/scatter/size-spec.ts
  src/plots/scatter/adaptor.ts
Labels: PR: unreviewed

#2266 feat(pie): 饼图 geometry 默认对 elemenent 的 zIndex 进行反序
  __tests__/unit/plots/pie/data-spec.ts
  __tests__/unit/plots/pie/index-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/contants.ts
Labels: PR: reviewed-approved

#2269 对称条形图处理数据方法简化改造，方便后续处理 changeData
  __tests__/bugs/issue-2180-spec.ts
  __tests__/unit/plots/bidirectional-bar/data-spec.ts
  __tests__/unit/plots/bidirectional-bar/layout-spec.ts
  __tests__/unit/plots/bidirectional-bar/utils-spec.ts
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/bidirectional-bar/utils.ts
Labels: PR: partially-approved

#2268 docs: 图表组件文档
  __tests__/unit/core/index-spec.ts
  docs/api/components/annotations.en.md
  docs/api/components/annotations.zh.md
  docs/api/components/axis.en.md
  docs/api/components/axis.zh.md
  docs/api/components/label.en.md
  docs/api/components/label.zh.md
  docs/api/components/legend.en.md
  docs/api/components/legend.zh.md
  docs/api/components/scrollbar.en.md
  docs/api/components/scrollbar.zh.md
  docs/api/components/slider.en.md
  docs/api/components/slider.zh.md
  docs/api/components/tooltip.en.md
  docs/api/components/tooltip.zh.md
  docs/common/annotations.zh.md
  docs/common/axis.en.md
  docs/common/axis.zh.md
  docs/common/scrollbar.en.md
  docs/common/scrollbar.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
  docs/styles/component.md
  examples/more-plots/bidirectional-bar/demo/basic.ts
  examples/more-plots/bidirectional-bar/demo/layout.ts
Labels: PR: partially-approved

#2270 fix(issue-2264): 修复瀑布图 formatter 不生效
  __tests__/bugs/issue-2264-spec.ts
  __tests__/unit/plots/waterfall/component-spec.ts
  src/plots/waterfall/adaptor.ts
Labels: PR: unreviewed

#2219 feat: 增加交互
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  __tests__/unit/plots/treemap/interactions/util-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  examples/more-plots/treemap/demo/drill-down.ts
  examples/more-plots/treemap/demo/meta.json
  src/plots/treemap/adaptor.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
  src/plots/treemap/interactions/treemap-drill-down.ts
  src/plots/treemap/interactions/util.ts
  src/plots/treemap/utils.ts
Labels: PR: partially-approved

#2272 docs: 图表案例导航顺序调整 & 主题文档修整
  docs/common/theme.en.md
  docs/common/theme.zh.md
  examples/general/theme/demo/register-theme.ts
  gatsby-config.js
Labels: PR: reviewed-approved

#2275 chore: 2.3.10 changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2277 docs: AxisCfg API title.title => title.text
  docs/common/axis.en.md
  docs/common/axis.zh.md
Labels: PR: unreviewed

#2284 docs: add pyg2plot
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
Labels: PR: reviewed-approved
