Repository antvis/G2Plot, pull requests merged in 2021-03, with the labels that each got.

#2371 docs: 文档日常
  docs/common/animate-option.en.md
  docs/common/animate-option.zh.md
  examples/case/customize/demo/desire-heatmap.ts
  examples/column/stacked/demo/meta.json
  src/utils/transform/sankey.ts
Labels: PR: partially-approved

#2367 feat(sankey): changeData API for sankey
  __tests__/unit/plots/sankey/change-data-spec.ts
  __tests__/unit/plots/sankey/index-spec.ts
  __tests__/unit/plots/word-cloud/index-spec.ts
  __tests__/unit/utils/transform/sankey-spec.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/constant.ts
  src/plots/sankey/helper.ts
  src/plots/sankey/index.ts
  src/plots/sankey/types.ts
  src/utils/data.ts
  src/utils/transform/sankey.ts
Labels: PR: reviewed-approved

#2370 feat: treemap 提供 changeData 能力
  __tests__/unit/plots/treemap/basic-spec.ts
  src/plots/treemap/index.ts
Labels: PR: partially-approved

#2362 Feat bidirectional bar change data
  __tests__/unit/plots/bidirectional-bar/change-data-spec.ts
  src/plots/bidirectional-bar/index.ts
Labels: PR: reviewed-approved

#2360 treemap 允许设置纵横比 & 滚动时阻止默认事件
  __tests__/unit/plots/treemap/interactions/view-zoom-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  __tests__/unit/utils/hierarchy/treemap-spec.ts
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  examples/more-plots/treemap/demo/treemap-nest.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/utils.ts
  src/utils/hierarchy/treemap.ts
Labels: PR: partially-approved

#2379 typo
  docs/common/tooltip.zh.md
Labels: PR: reviewed-approved

#2377 typo
  docs/api/plots/scatter.zh.md
Labels: PR: reviewed-approved

#2380 docs(typo): dblclick, not dbclick
  docs/api/options/events.en.md
  docs/api/options/events.zh.md
Labels: PR: reviewed-approved

#2378 feat(sankey): update d3-sankey layout for depth customize
  .github/workflows/build.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-upload.yml
  __tests__/unit/plots/sankey/depth-spec.ts
  __tests__/unit/plots/sankey/layout-spec.ts
  __tests__/unit/plots/sankey/sankey/monkey-spec.ts
  package.json
  src/plots/sankey/helper.ts
  src/plots/sankey/layout.ts
  src/plots/sankey/sankey/align.ts
  src/plots/sankey/sankey/helper.ts
  src/plots/sankey/sankey/index.ts
  src/plots/sankey/sankey/sankey.ts
  src/utils/transform/sankey.ts
Labels: PR: unreviewed

#2381 Feature/liquid shape
  __tests__/bugs/issue-2236-spec.ts
  __tests__/bugs/issue-2303-spec.ts
  __tests__/unit/plots/liquid/index-spec.ts
  __tests__/unit/plots/liquid/liquid-shape-spec.ts
  __tests__/unit/plots/liquid/statistic-spec.ts
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  examples/progress-plots/liquid/demo/custom.ts
  examples/progress-plots/liquid/demo/diamond.ts
  examples/progress-plots/liquid/demo/meta.json
  src/plots/liquid/adaptor.ts
  src/plots/liquid/index.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
  src/utils/statistic.ts
Labels: PR: unreviewed

#2382 chore: new version
  .github/workflows/build.yml
  CHANGELOG.md
  package.json
  src/index.ts
  src/plots/sankey/types.ts
Labels: PR: unreviewed

#2389 docs: update plugin
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
Labels: PR: unreviewed

#2395 feat(gauge): 仪表盘支持配置 style,支持圆角仪表盘
  __tests__/unit/plots/gauge/style-spec.ts
  docs/api/plots/gauge.en.md
  docs/api/plots/gauge.zh.md
  src/plots/gauge/adaptor.ts
  src/plots/gauge/shapes/meter-gauge.ts
  src/plots/gauge/types.ts
  src/plots/gauge/utils.ts
Labels: PR: partially-approved

#2396 Fix/liquid
  __tests__/bugs/issue-1909-spec.ts
  __tests__/bugs/issue-2236-spec.ts
  __tests__/unit/plots/liquid/index-spec.ts
  __tests__/unit/plots/liquid/liquid-shape-spec.ts
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  examples/progress-plots/liquid/demo/custom.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
Labels: PR: unreviewed

#2388 docs(theme): 补充主题样式表的 api 使用文档
  docs/common/theme.en.md
  docs/common/theme.zh.md
  site/pages/index.less
Labels: PR: reviewed-approved

#2390 docs(interactions): 补充交互配置文档
  .github/workflows/build.yml
  docs/common/interactions.en.md
  docs/common/interactions.zh.md
Labels: PR: partially-approved

#2397 fix: bullet的target支持回调函数处理
  __tests__/bugs/issue-2229-spec.ts
  src/plots/bullet/adaptor.ts
Labels: Bug, PR: unreviewed

#2386 Feat/矩形树图下钻交互新增面包屑
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  __tests__/unit/plots/treemap/interactions/util-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  examples/more-plots/treemap/demo/drill-down.ts
  examples/more-plots/treemap/demo/meta.json
  src/plots/treemap/adaptor.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
  src/plots/treemap/interactions/treemap-drill-down.ts
  src/plots/treemap/interactions/util.ts
  src/plots/treemap/utils.ts
  src/plots/word-cloud/utils.ts
  src/utils/padding.ts
Labels: PR: unreviewed

#2413 fix(#2375): 修复饼图中心文本交互没有使用custom-html
  __tests__/bugs/issue-2220-spec.ts
  __tests__/bugs/issue-2375-spec.ts
  __tests__/unit/plots/gauge/utils-spec.ts
  __tests__/unit/plots/pie/annotation-spec.ts
  __tests__/unit/plots/pie/html-statistic-spec.ts
  __tests__/unit/plots/pie/interaction-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/interactions/index.ts
  src/plots/pie/interactions/pie-statistic-action.ts
  src/utils/statistic.ts
Labels: PR: reviewed-approved

#2415 fix(pie-tooltip): tooltip 默认设置fields和formatter只针对全0场景
  __tests__/bugs/issue-2220-spec.ts
  __tests__/unit/plots/pie/data-spec.ts
  __tests__/unit/plots/pie/tooltip-spec.ts
  docs/api/components/tooltip.en.md
  src/plots/pie/adaptor.ts
  src/plots/pie/utils.ts
Labels: PR: partially-approved

#2417 chore: 2.3.14 changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2418 fix(liquid): annotation width
  __tests__/unit/plots/liquid/liquid-shape-spec.ts
  __tests__/unit/plots/liquid/statistic-spec.ts
  package.json
  src/index.ts
  src/utils/statistic.ts
Labels: PR: unreviewed

#2423 docs: statistic 英文文档完善
  docs/api/plots/gauge.en.md
  docs/common/statistic.en.md
  docs/common/statistic.zh.md
  examples/progress-plots/gauge/demo/basic.ts
Labels: PR: unreviewed

#2433 docs(theme): 文档补充主题配置参考链接
  docs/api/options/theme.en.md
  docs/api/options/theme.zh.md
Labels: PR: unreviewed

#2434 [矩形树图] changesize 时重绘面包屑
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
  src/plots/treemap/interactions/treemap-drill-down.ts
Labels: PR: unreviewed

#2428 fix(multi-view): 修复多图层图表折线图联动取数问题
  examples/dual-axes/column-line/demo/slider-column-line.ts
  examples/plugin/association/demo/association-line.ts
  examples/plugin/association/demo/meta.json
  src/plots/multi-view/interactions/association.ts
Labels: PR: reviewed-approved

#2429 feat(second-geometry): 辅助几何图形 point 支持独立设置 state style
  __tests__/bugs/issue-2220-spec.ts
  docs/common/point-style.en.md
  docs/common/point-style.zh.md
  examples/dual-axes/column-line/demo/slider-culumn-line.ts
  src/plots/area/adaptor.ts
  src/plots/area/types.ts
  src/plots/line/adaptor.ts
  src/plots/line/types.ts
  src/plots/radar/adaptor.ts
  src/plots/radar/types.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/types.ts
Labels: PR: reviewed-approved

#2431 [fix] Treemap 面包屑适配 changedata
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
  src/plots/treemap/utils.ts
Labels: PR: partially-approved

#2425 feat: add polar attribute to heatmap
  __tests__/unit/plots/heatmap/coordinate-spec.ts
  docs/api/plots/heatmap.en.md
  docs/api/plots/heatmap.zh.md
  examples/heatmap/basic/demo/meta.json
  examples/heatmap/basic/demo/polar.ts
  src/plots/heatmap/adaptor.ts
  src/plots/heatmap/index.ts
  src/plots/heatmap/types.ts
Labels: PR: unreviewed

#2430 Feat/rect shape for liquid
  __tests__/unit/plots/liquid/liquid-shape-spec.ts
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  src/plots/liquid/shapes/liquid.ts
Labels: PR: unreviewed

#2435 docs(legend): 图例分页导航器的主题样式设置
  docs/api/components/legend.en.md
  docs/api/components/legend.zh.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
Labels: PR: unreviewed

#2436 chore: new version
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2439 docs(tooltip): 更新 tooltip 关于 marker 的文档
  docs/api/components/tooltip.en.md
  docs/api/components/tooltip.zh.md
  docs/common/marker.zh.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
Labels: PR: partially-approved

#2441 feat(conversion-tag): 转化分析 tag 添加 elements 信息,方便业务上使用
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/utils/event.ts
  docs/api/components/annotations.en.md
  docs/api/components/annotations.zh.md
  docs/api/components/axis.en.md
  docs/api/components/axis.zh.md
  docs/api/components/conversion-tag.en.md
  docs/api/components/conversion-tag.zh.md
  docs/api/components/label.en.md
  docs/api/components/label.zh.md
  docs/api/components/legend.en.md
  docs/api/components/legend.zh.md
  docs/api/components/scrollbar.en.md
  docs/api/components/scrollbar.zh.md
  docs/api/components/slider.en.md
  docs/api/components/slider.zh.md
  docs/api/components/tooltip.en.md
  docs/api/components/tooltip.zh.md
  docs/api/plots/bar.en.md
  docs/api/plots/bar.zh.md
  docs/api/plots/column.en.md
  docs/api/plots/column.zh.md
  docs/common/conversion-tag.en.md
  docs/common/conversion-tag.zh.md
  examples/general/events/API.en.md
  examples/general/events/API.zh.md
  examples/general/events/demo/conversion-tag-with-link.ts
  examples/general/events/demo/meta.json
  examples/general/events/index.en.md
  examples/general/events/index.zh.md
  src/adaptor/conversion-tag.ts
Labels: PR: partially-approved

#2449 docs(scrollbar): 补充滚动条滑块的高亮色文档
  docs/common/scrollbar.en.md
  docs/common/scrollbar.zh.md
Labels: PR: partially-approved

#2406 feat(scatter): 散点图支持color和shape同时映射图例字段 & 添加单测
  __tests__/bugs/issue-2122-spec.ts
  __tests__/unit/plots/scatter/color-spec.ts
  __tests__/unit/plots/scatter/legend-spec.ts
  docs/api/plots/scatter.en.md
  docs/api/plots/scatter.zh.md
  examples/scatter/scatter/demo/mapping-color-and-shape.ts
  examples/scatter/scatter/demo/meta.json
  src/plots/scatter/adaptor.ts
  src/plots/scatter/types.ts
Labels: PR: unreviewed

#2448 docs(demo): 补充组合图表 demo & 增加一个插件图表
  docs/manual/plots/pie.en.md
  docs/manual/plots/pie.zh.md
  docs/manual/plugin.en.md
  docs/manual/plugin.zh.md
  examples/plugin/multi-view/demo/combo-plot.ts
  examples/plugin/multi-view/demo/meta.json
Labels: PR: partially-approved

#2447 fix(radial-bar): 修复玉钰图存在非法数据崩溃问题 (#2394)
  __tests__/bugs/issue-2394-spec.ts
  src/plots/radial-bar/adaptor.ts
Labels: PR: unreviewed

#2455 feat(liquid): 水波图支持跟随主题色 & 水波图支持 outline 配置样式 & 文档以及 demo 优化
  __tests__/bugs/issue-2220-spec.ts
  __tests__/unit/plots/liquid/color-spec.ts
  __tests__/unit/plots/liquid/index-spec.ts
  __tests__/unit/plots/liquid/liquid-style-spec.ts
  __tests__/unit/plots/pie/utils-spec.ts
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  docs/manual/plots/pie.en.md
  examples/progress-plots/liquid/demo/meta.json
  examples/progress-plots/liquid/demo/outline-style.ts
  examples/progress-plots/liquid/demo/rect.ts
  examples/progress-plots/liquid/demo/style.ts
  src/plots/liquid/adaptor.ts
  src/plots/liquid/constants.ts
  src/plots/liquid/index.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
  src/plots/pie/adaptor.ts
  src/plots/pie/index.ts
  src/plots/pie/utils.ts
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/index.ts
  src/utils/data.ts
  src/utils/index.ts
Labels: PR: partially-approved

#2445 Fix treemap update
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
Labels: PR: partially-approved

#2453 [issue-2369] 矩形树图增加 path 字段
  __tests__/unit/plots/treemap/lable-spec.ts
  __tests__/unit/plots/treemap/tooltip-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  examples/more-plots/treemap/demo/drill-down.ts
  examples/more-plots/treemap/demo/treemap-nest.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/utils.ts
Labels: PR: unreviewed

#2451 fix: 双轴图 theme 主题设置
  __tests__/unit/plots/dual-axes/theme-spec.ts
  src/plots/dual-axes/adaptor.ts
Labels: PR: unreviewed

#2457 chore: 2.3.17 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2458 docs(liquid): update comments for custom shape API
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
Labels: PR: reviewed-approved

#2459 fix: 更改示例链接至绝对路径 & 更改重复链接
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
  docs/api/plots/scatter.en.md
  docs/api/plots/scatter.zh.md
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  examples/case/statistical-scenario/demo/meta.json
  examples/case/statistical-scenario/demo/trend-funnel.ts
  examples/more-plots/treemap/API.en.md
  examples/more-plots/treemap/API.zh.md
Labels: PR: partially-approved

#2460 docs: 完善 axis 文档（含 title, line, tickLine, subTickLine 等）
  docs/api/graphic-style.en.md
  docs/api/graphic-style.zh.md
  docs/api/plots/area.en.md
  docs/api/plots/area.zh.md
  docs/api/plots/tiny-area.en.md
  docs/api/plots/tiny-area.zh.md
  docs/common/axis.en.md
  docs/common/axis.zh.md
  docs/common/label.en.md
  docs/common/label.zh.md
  docs/common/line-style.en.md
  docs/common/line-style.zh.md
  docs/common/theme.en.md
  docs/common/tooltip.en.md
  docs/common/tooltip.zh.md
Labels: PR: unreviewed

#2470 chore: update build workflows node & add jest maxWorkers
  .github/workflows/build.yml
  __tests__/bugs/issue-2064-spec.ts
  __tests__/bugs/issue-2220-spec.ts
  __tests__/bugs/issue-2260-spec.ts
  __tests__/bugs/issue-2267-spec.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/adaptor/geometries/interval-spec.ts
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/area/limit-in-plot-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/column/limit-in-plot-spec.ts
  __tests__/unit/plots/gauge/shapes/meter-gauge.ts
  __tests__/unit/plots/line/line-mapping-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  __tests__/unit/plots/pie/tooltip-spec.ts
  __tests__/unit/plots/scatter/tooltip-spec.ts
  __tests__/unit/plots/word-cloud/change-data-spec.ts
  __tests__/unit/plots/word-cloud/legend-spec.ts
  package.json
Labels: PR: unreviewed

#2471 fix: 尝试修复词云图单测
  __tests__/unit/plots/word-cloud/change-data-spec.ts
  __tests__/unit/plots/word-cloud/legend-spec.ts
Labels: PR: unreviewed

#2472 chore: 修复控制台 warning
  api-extractor.json
  src/adaptor/geometries/index.ts
  src/index.ts
  src/plots/_template/index.ts
  src/plots/area/index.ts
  src/plots/bar/index.ts
  src/plots/bidirectional-bar/index.ts
  src/plots/box/index.ts
  src/plots/bullet/index.ts
  src/plots/chord/index.ts
  src/plots/column/index.ts
  src/plots/dual-axes/index.ts
  src/plots/funnel/index.ts
  src/plots/gauge/index.ts
  src/plots/gauge/types.ts
  src/plots/heatmap/index.ts
  src/plots/histogram/index.ts
  src/plots/line/index.ts
  src/plots/liquid/index.ts
  src/plots/multi-view/index.ts
  src/plots/pie/index.ts
  src/plots/progress/index.ts
  src/plots/radar/index.ts
  src/plots/radial-bar/index.ts
  src/plots/ring-progress/index.ts
  src/plots/rose/index.ts
  src/plots/sankey/index.ts
  src/plots/scatter/index.ts
  src/plots/stock/index.ts
  src/plots/sunburst/index.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/index.ts
  src/plots/treemap/index.ts
  src/plots/waterfall/index.ts
  src/plots/word-cloud/index.ts
Labels: PR: partially-approved

#2477 docs: 完善图例文档 & 增加图表组件的示例导航 & 补充图例两个demo
  docs/api/components/axis.en.md
  docs/api/components/axis.zh.md
  docs/api/components/legend.en.md
  docs/api/components/legend.zh.md
  docs/api/components/scrollbar.en.md
  docs/api/components/scrollbar.zh.md
  docs/api/components/slider.en.md
  docs/api/components/slider.zh.md
  docs/api/components/tooltip.en.md
  docs/api/components/tooltip.zh.md
  docs/common/axis.en.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  docs/manual/plots/liquid.en.md
  docs/manual/plots/liquid.zh.md
  examples/component/annotation/API.en.md
  examples/component/annotation/API.zh.md
  examples/component/annotation/demo/image-annotation.ts
  examples/component/annotation/demo/line-annotation.ts
  examples/component/annotation/demo/line-annotation1.ts
  examples/component/annotation/demo/meta.json
  examples/component/annotation/demo/region-and-data-marker.ts
  examples/component/annotation/demo/region-annotation.ts
  examples/component/annotation/index.en.md
  examples/component/annotation/index.zh.md
  examples/component/legend/API.en.md
  examples/component/legend/API.zh.md
  examples/component/legend/demo/legend-item-value.ts
  examples/component/legend/demo/legend-position.jsx
  examples/component/legend/demo/meta.json
  examples/component/legend/index.en.md
  examples/component/legend/index.zh.md
  examples/general/annotation/API.en.md
  examples/general/annotation/API.zh.md
  examples/general/annotation/index.en.md
  examples/general/annotation/index.zh.md
  gatsby-config.js
Labels: PR: partially-approved
