Repository antvis/G2Plot, pull requests merged in 2021-02, with the labels that each got.

#2291 feat(animation): 增加动画文档和 demo & 多图层图表支持分view动画
  __tests__/unit/plots/multi-view/index-spec.ts
  docs/api/options/animation.en.md
  docs/api/options/animation.zh.md
  docs/common/animate-option.en.md
  docs/common/animate-option.zh.md
  examples/dynamic-plots/animation/demo/animation-column.jsx
  examples/dynamic-plots/animation/demo/animation-line.jsx
  examples/dynamic-plots/animation/demo/animation-pie.jsx
  examples/dynamic-plots/animation/demo/easing-effects.ts
  examples/dynamic-plots/animation/demo/meta.json
  examples/dynamic-plots/animation/index.en.md
  examples/dynamic-plots/animation/index.zh.md
  src/plots/multi-view/adaptor.ts
  src/plots/multi-view/types.ts
Labels: PR: partially-approved

#2283 Feat box plot change data
  __tests__/unit/plots/box/change-data-spec.ts
  __tests__/unit/plots/box/outliers-spec.ts
  __tests__/unit/plots/box/utils-spec.ts
  src/plots/box/adaptor.ts
  src/plots/box/constant.ts
  src/plots/box/index.ts
  src/plots/box/utils.ts
Labels: PR: unreviewed

#2295 feat(sankey): add nodeWidth, nodePadding options
  __tests__/bugs/issue-2267-spec.ts
  __tests__/data/sankey-energy.ts
  __tests__/unit/plots/sankey/index-spec.ts
  src/plots/sankey/adaptor.ts
  src/plots/sankey/helper.ts
  src/plots/sankey/index.ts
  src/plots/sankey/types.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
Labels: PR: partially-approved

#2287 feat: 双轴图新增 slider
  __tests__/data/pv-uv.ts
  __tests__/unit/plots/dual-axes/slider-spec.ts
  __tests__/unit/utils/is-between-spec.ts
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
  examples/dual-axes/column-line/demo/meta.json
  examples/dual-axes/column-line/demo/slider-culumn-line.ts
  src/constant.ts
  src/plots/dual-axes/adaptor.ts
  src/plots/dual-axes/util/render-sider.ts
  src/utils/index.ts
  src/utils/number.ts
Labels: PR: unreviewed

#2302 chore: 2.3.11
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2307 feat: export default-options, you can use staticMethod to getDefaultOptions, like `Plot.getDefaultOptions()`
  __tests__/unit/plots/area/index-spec.ts
  __tests__/unit/plots/bar/index-spec.ts
  __tests__/unit/plots/column/index-spec.ts
  __tests__/unit/plots/gauge/index-spec.ts
  __tests__/unit/plots/gauge/shapes/index-spec.ts
  __tests__/unit/plots/gauge/utils-spec.ts
  __tests__/unit/plots/line/index-spec.ts
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  __tests__/unit/plots/tiny-area/index-spec.ts
  __tests__/unit/plots/tiny-column/index-spec.ts
  __tests__/unit/plots/tiny-line/index-spec.ts
  package.json
  src/plots/area/constants.ts
  src/plots/area/index.ts
  src/plots/bar/constants.ts
  src/plots/bar/index.ts
  src/plots/column/constants.ts
  src/plots/column/index.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/constant.ts
  src/plots/gauge/constants.ts
  src/plots/gauge/index.ts
  src/plots/gauge/utils.ts
  src/plots/line/constants.ts
  src/plots/line/index.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/constant.ts
  src/plots/progress/constants.ts
  src/plots/progress/index.ts
  src/plots/ring-progress/adaptor.ts
  src/plots/ring-progress/constants.ts
  src/plots/ring-progress/index.ts
  src/plots/tiny-area/constants.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/constants.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/constants.ts
  src/plots/tiny-line/index.ts
  src/types/statistic.ts
Labels: PR: partially-approved

#2306 fix(column): update scales when changeData (#2303)
  __tests__/bugs/issue-2303-spec.ts
  src/plots/area/adaptor.ts
  src/plots/area/index.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/column/adaptor.ts
  src/plots/column/index.ts
  src/plots/line/index.ts
  src/plots/tiny-area/adaptor.ts
  src/plots/tiny-area/index.ts
  src/plots/tiny-column/adaptor.ts
  src/plots/tiny-column/index.ts
  src/plots/tiny-line/adaptor.ts
  src/plots/tiny-line/index.ts
Labels: PR: unreviewed

#2311 docs: fix link 404
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#2314 docs(dual-axes): 双轴图补充meta使用示例
  docs/api/plots/dual-axes.en.md
  docs/api/plots/dual-axes.zh.md
Labels: PR: partially-approved

#2315 docs(interactions): 交互相关的 api 文档补充
  docs/api/options/interactions.en.md
  docs/api/options/interactions.zh.md
  docs/common/interactions.en.md
  docs/common/interactions.zh.md
Labels: PR: partially-approved

#2317 fix(bar): bar plot not transformData before changedata
  __tests__/bugs/bar-changedata-spec.ts
  __tests__/unit/plots/bar/change-data-spec.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/bar/utils.ts
Labels: PR: unreviewed

#2312 fix: pie tooltip
  __tests__/bugs/issue-2220-spec.ts
  __tests__/unit/plots/pie/data-spec.ts
  __tests__/unit/plots/pie/statistic-spec.ts
  __tests__/unit/plots/pie/tooltip-spec.ts
  src/plots/pie/adaptor.ts
Labels: PR: reviewed-approved

#2321 docs 0208
  docs/api/components/scrollbar.zh.md
  docs/api/options/interactions.en.md
  docs/api/options/interactions.zh.md
  docs/api/plots/column.en.md
  docs/common/theme.en.md
  examples/bar/basic/demo/meta.json
Labels: PR: partially-approved

#2323 feat: 雷达图新增 innerRadius、startAngle、endAngle
  __tests__/unit/plots/radar/coordinate-spec.ts
  docs/api/plots/radar.en.md
  docs/api/plots/radar.zh.md
  src/plots/radar/adaptor.ts
  src/plots/radar/types.ts
Labels: PR: reviewed-approved

#2328 docs: scrollbar style & lock editor version
  __tests__/unit/plots/column/scrollbar-spec.ts
  docs/api/components/scrollbar.en.md
  docs/api/components/scrollbar.zh.md
  docs/common/scrollbar.en.md
  docs/common/scrollbar.zh.md
  examples/general/theme/demo/custom-theme.ts
  examples/general/theme/demo/meta.json
  package.json
Labels: PR: reviewed-approved

#2334 feat(state-style): 若干图表支持 state 设置样式 & 增加文档
  __tests__/unit/plots/heatmap/state-spec.ts
  docs/api/plots/area.en.md
  docs/api/plots/area.zh.md
  docs/api/plots/bar.en.md
  docs/api/plots/bar.zh.md
  docs/api/plots/column.en.md
  docs/api/plots/column.zh.md
  docs/api/plots/heatmap.en.md
  docs/api/plots/heatmap.zh.md
  docs/api/plots/histogram.en.md
  docs/api/plots/histogram.zh.md
  docs/api/plots/line.en.md
  docs/api/plots/line.zh.md
  docs/api/plots/pie.en.md
  docs/api/plots/pie.zh.md
  docs/api/plots/rose.en.md
  docs/api/plots/rose.zh.md
  docs/api/plots/waterfall.en.md
  docs/api/plots/waterfall.zh.md
  docs/common/state-style.en.md
  docs/common/state-style.zh.md
  gatsby-config.js
  src/plots/area/adaptor.ts
  src/plots/column/adaptor.ts
  src/plots/heatmap/adaptor.ts
  src/plots/histogram/adaptor.ts
Labels: PR: partially-approved

#2336 feat(radial-bar): add radial bar label adaptor
  __tests__/unit/plots/radial-bar/label-spec.ts
  src/plots/radial-bar/adaptor.ts
Labels: PR: partially-approved

#2337 feat: treemap layout optimize
  __tests__/data/treemap.ts
  __tests__/unit/plots/sunburst/index-spec.ts
  __tests__/unit/plots/treemap/color-spec.ts
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  __tests__/unit/plots/treemap/lable-spec.ts
  __tests__/unit/plots/treemap/sort-spec.ts
  __tests__/unit/plots/treemap/tooltip-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  src/plots/treemap/adaptor.ts
  src/utils/hierarchy/treemap.ts
  src/utils/hierarchy/types.ts
Labels: PR: unreviewed

#2339 docs(heatmap): 添加热力新年 demo
  examples/case/customize/demo/desire-heatmap.ts
  examples/case/customize/demo/meta.json
Labels: PR: partially-approved

#2319 fix: gague,pie,ring-progress,liquid 等 changedata 触发钩子事件
  __tests__/bugs/issue-2260-spec.ts
  src/plots/gauge/index.ts
  src/plots/liquid/index.ts
  src/plots/pie/index.ts
  src/plots/ring-progress/index.ts
Labels: PR: unreviewed

#2342 chore: v2.3.12
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: partially-approved

#2344 feat(ring-progress): 将环形进度条的z-index进行调整,默认置顶 shape0
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/plots/progress/adaptor.ts
Labels: PR: reviewed-approved

#2294 feat: multiview 支持 multi-plots && 支持 association 🎉🎉🎉
  __tests__/unit/adaptor/geometries/interval-spec.ts
  __tests__/unit/plots/multi-view/interactions/association-spec.ts
  __tests__/unit/plots/multi-view/multi-plots-spec.ts
  __tests__/unit/plots/multi-view/tooltip-spec.ts
  __tests__/unit/plots/multi-view/utils-spec.ts
  __tests__/unit/utils/statistic-spec.ts
  __tests__/unit/utils/view-spec.ts
  docs/api/multi-view.en.md
  docs/api/multi-view.zh.md
  docs/api/options/interactions.en.md
  docs/api/options/interactions.zh.md
  examples/case/customize/demo/line.ts
  examples/case/customize/demo/meta.json
  examples/dynamic-plots/animation/demo/easing-effects.ts
  examples/plugin/association/demo/association-filter.ts
  examples/plugin/association/demo/association-highlight.ts
  examples/plugin/association/demo/association-pie.ts
  examples/plugin/association/demo/meta.json
  examples/plugin/association/index.en.md
  examples/plugin/association/index.zh.md
  examples/plugin/multi-view/demo/drinks.ts
  examples/plugin/multi-view/demo/series-columns.ts
  gatsby-config.js
  src/core/plot.ts
  src/plots/multi-view/adaptor.ts
  src/plots/multi-view/index.ts
  src/plots/multi-view/interactions/association.ts
  src/plots/multi-view/interactions/index.ts
  src/plots/multi-view/interactions/utils.ts
  src/plots/multi-view/types.ts
  src/plots/multi-view/utils.ts
  src/utils/geometry.ts
  src/utils/index.ts
  src/utils/view.ts
Labels: PR: reviewed-approved

#2345 feat(gauge): 仪表盘支持 annotations
  src/plots/gauge/adaptor.ts
Labels: PR: reviewed-approved

#2350 feat: 玫瑰图新增 startAngle、endAngle
  __tests__/unit/plots/rose/coordinate-spec.ts
  docs/api/plots/rose.en.md
  docs/api/plots/rose.zh.md
  src/plots/rose/adaptor.ts
  src/plots/rose/types.ts
Labels: PR: reviewed-approved

#2354 fix(sankey): shape order same with data, layout space
  __tests__/bugs/issue-2352-spec.ts
  __tests__/unit/plots/sankey/index-spec.ts
  src/plots/sankey/adaptor.ts
Labels: PR: unreviewed

#2351 chore: fix website build error
  gatsby-browser.js
  package.json
Labels: PR: unreviewed

#2361 docs(axis): 坐标轴文档
  docs/common/axis.en.md
  docs/common/axis.zh.md
Labels: PR: reviewed-approved

#2357 feat: sankey node depth configure
  __tests__/bugs/issue-2353-spec.ts
  docs/api/plots/sankey.en.md
  docs/api/plots/sankey.zh.md
  src/plots/sankey/adaptor.ts
  src/plots/sankey/types.ts
  src/utils/data.ts
  src/utils/transform/sankey.ts
Labels: PR: unreviewed

#2347 docs(slider): 缩略轴支持配置 handler 样式 & 增加 api 文档说明
  docs/api/options/events.zh.md
  docs/common/slider.en.md
  docs/common/slider.zh.md
Labels: PR: unreviewed
