Repository antvis/G2Plot, pull requests merged in 2021-06, with the labels that each got.

#2596 docs: add browser compatibility in FAQ
  .github/workflows/auto-inspection.yml
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
Labels: PR: unreviewed

#2598 docs(MetaOption)
  docs/api/options/meta.en.md
  docs/api/options/meta.zh.md
Labels: PR: unreviewed

#2606 fix: 使用 mock 数据
  examples/more-plots/word-cloud/demo/basic.ts
Labels: PR: reviewed-approved

#2593 feat: violin
  .github/workflows/auto-inspection.yml
  __tests__/data/violin.ts
  __tests__/unit/plots/violin/animation-spec.ts
  __tests__/unit/plots/violin/annotation-spec.ts
  __tests__/unit/plots/violin/axis-spec.ts
  __tests__/unit/plots/violin/box-spec.ts
  __tests__/unit/plots/violin/change-data-spec.ts
  __tests__/unit/plots/violin/index-spec.ts
  __tests__/unit/plots/violin/legend-spec.ts
  __tests__/unit/plots/violin/tooltip-spec.ts
  __tests__/unit/plots/violin/utils-spec.ts
  __tests__/unit/plots/violin/violin-shape-spec.ts
  __tests__/unit/utils/transform/quantile-spec.ts
  docs/api/plots/violin.en.md
  docs/api/plots/violin.zh.md
  docs/common/common-component.en.md
  docs/common/common-component.zh.md
  docs/common/component.en.md
  docs/common/component.zh.md
  examples/more-plots/violin/API.en.md
  examples/more-plots/violin/API.zh.md
  examples/more-plots/violin/demo/basic.ts
  examples/more-plots/violin/demo/group.ts
  examples/more-plots/violin/demo/meta.json
  examples/more-plots/violin/demo/shape.ts
  examples/more-plots/violin/demo/tooltip.ts
  examples/more-plots/violin/index.en.md
  examples/more-plots/violin/index.zh.md
  package.json
  src/adaptor/geometries/index.ts
  src/adaptor/geometries/violin.ts
  src/index.ts
  src/plots/violin/adaptor.ts
  src/plots/violin/constant.ts
  src/plots/violin/index.ts
  src/plots/violin/types.ts
  src/plots/violin/utils.ts
  src/utils/transform/quantile.ts
Labels: PR: reviewed-approved

#2607 docs: fix typo in the faq.zh.md
  docs/manual/faq.zh.md
Labels: PR: reviewed-approved

#2605 feat: locale 支持
  __tests__/unit/core/global-spec.ts
  __tests__/unit/core/locale-spec.ts
  __tests__/unit/utils/template-spec.ts
  jest.setup.js
  package.json
  src/core/global.ts
  src/core/locale.ts
  src/core/plot.ts
  src/index.ts
  src/locales/en_US.ts
  src/locales/zh_CN.ts
  src/plots/funnel/adaptor.ts
  src/plots/pie/adaptor.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/constant.ts
  src/types/common.ts
  src/types/index.ts
  src/types/locale.ts
  src/utils/template.ts
Labels: PR: reviewed-approved

#2609 chore: 添加 issue-template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/question.md
Labels: PR: unreviewed

#2610 Revert "chore: 添加 issue-template"
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/question.md
Labels: PR: unreviewed

#2608 refactor(drilldown): 矩阵树图下钻交互改造
  .github/workflows/build.yml
  __tests__/unit/interactions/drill-down-spec.ts
  __tests__/unit/plots/sunburst/drill-down-spec.ts
  __tests__/unit/plots/sunburst/tooltip-spec.ts
  __tests__/unit/plots/sunburst/treemap-spec.ts
  __tests__/unit/plots/treemap/interactions/drill-down-spec.ts
  __tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
  __tests__/unit/plots/treemap/utils-spec.ts
  __tests__/unit/utils/padding-spec.ts
  docs/api/plots/sunburst.en.md
  docs/api/plots/sunburst.zh.md
  docs/api/plots/treemap.en.md
  docs/api/plots/treemap.zh.md
  docs/common/drill-down.en.md
  docs/common/drill-down.zh.md
  examples/more-plots/sunburst/demo/basic.ts
  examples/more-plots/sunburst/demo/basic2.ts
  examples/more-plots/sunburst/demo/custom-tooltip-items.ts
  examples/more-plots/sunburst/demo/tooltip-fields.ts
  examples/more-plots/treemap/demo/drill-down.ts
  package.json
  src/interactions/actions/drill-down.ts
  src/interactions/drag-move.ts
  src/interactions/drill-down.ts
  src/plots/scatter/index.ts
  src/plots/scatter/interactions/index.ts
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/constant.ts
  src/plots/sunburst/index.ts
  src/plots/sunburst/interactions/index.ts
  src/plots/sunburst/types.ts
  src/plots/sunburst/utils.ts
  src/plots/treemap/adaptor.ts
  src/plots/treemap/constant.ts
  src/plots/treemap/index.ts
  src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
  src/plots/treemap/interactions/index.ts
  src/plots/treemap/interactions/treemap-drill-down.ts
  src/plots/treemap/interactions/util.ts
  src/plots/treemap/types.ts
  src/plots/treemap/utils.ts
  src/types/drill-down.ts
  src/utils/hierarchy/partition.ts
  src/utils/padding.ts
Labels: Interaction, PR: partially-approved, PR: unreviewed, WIP

#2615 docs: Radar seriesField字段修复为非必需
  docs/api/plots/radar.en.md
  docs/api/plots/radar.zh.md
Labels: PR: unreviewed

#2582 docs: 文档 & 公告
  docs/api/options/g2plot.en.md
  docs/api/options/g2plot.zh.md
  docs/api/plots/heatmap.zh.md
  docs/common/chart-options.en.md
  docs/common/chart-options.zh.md
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  docs/manual/plots/facet.en.md
  docs/manual/plots/facet.zh.md
  docs/manual/plots/violin.en.md
  docs/manual/plots/violin.zh.md
  examples/more-plots/stock/demo/large-data.ts
  examples/more-plots/stock/demo/meta.json
  examples/more-plots/sunburst/demo/meta.json
  examples/plugin/association/index.en.md
  examples/plugin/association/index.zh.md
  examples/plugin/facet/API.en.md
  examples/plugin/facet/API.zh.md
  examples/plugin/facet/demo/circle.ts
  examples/plugin/facet/demo/column.ts
  examples/plugin/facet/demo/list.ts
  examples/plugin/facet/demo/matrix.ts
  examples/plugin/facet/demo/meta.json
  examples/plugin/facet/demo/mirror.ts
  examples/plugin/facet/demo/rect.ts
  examples/plugin/facet/demo/tree-column.ts
  examples/plugin/facet/demo/tree.ts
  examples/plugin/facet/index.en.md
  examples/plugin/facet/index.zh.md
  gatsby-config.js
Labels: PR: unreviewed

#2617 chore: v2.3.22 & changelog
  CHANGELOG.md
  docs/api/components/statistic.en.md
  docs/api/components/statistic.zh.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#2621 fix: rename style to stockStyle
  __tests__/unit/plots/stock/style-spec.ts
  docs/api/plots/stock.en.md
  docs/api/plots/stock.zh.md
  examples/more-plots/stock/demo/custom-style.ts
  src/plots/stock/adaptor.ts
  src/plots/stock/types.ts
Labels: PR: partially-approved

#2625 fix(docs): 修复文档 demo 无限增大
  docs/common/crosshairs-text.en.md
  docs/common/crosshairs-text.zh.md
  examples/more-plots/stock/demo/slider.ts
  examples/more-plots/treemap/demo/drill-down.ts
Labels: PR: unreviewed

#2626 fix(violin): 修复小提琴图数据为空时，渲染直接抛出 error
  __tests__/unit/plots/violin/change-data-spec.ts
  src/plots/violin/adaptor.ts
Labels: PR: partially-approved

#2631 chore: update contributor-helper.yml
  .github/workflows/contributor-helper.yml
Labels: PR: unreviewed

#2634 refactor(funnel): 支持尖底漏斗图以及样式设置
  __tests__/unit/plots/funnel/index-spec.ts
  __tests__/unit/plots/funnel/style-spec.ts
  docs/api/plots/funnel.en.md
  docs/api/plots/funnel.zh.md
  docs/common/plot-cfg.en.md
  docs/common/plot-cfg.zh.md
  examples/more-plots/funnel/demo/meta.json
  examples/more-plots/funnel/demo/pyramid.ts
  examples/more-plots/funnel/demo/static-field.ts
  examples/plugin/multi-view/demo/composite-funnel.ts
  examples/plugin/multi-view/demo/meta.json
  src/locales/en_US.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/constant.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/dynamic-height.ts
  src/plots/funnel/index.ts
  src/plots/funnel/types.ts
  src/plots/mix/utils.ts
Labels: PR: reviewed-approved

#2633 fix(chord): 修复和弦图 state 设置不生效
  __tests__/unit/plots/chord/state-spec.ts
  src/plots/chord/index.ts
Labels: PR: reviewed-approved

#2637 feat(sunburst): 旭日图增加 ignoreParentValue 配置
  docs/api/plots/sunburst.en.md
  docs/api/plots/sunburst.zh.md
  examples/more-plots/sunburst/demo/tooltip-fields.ts
  src/plots/sunburst/types.ts
  src/utils/hierarchy/partition.ts
Labels: PR: reviewed-approved

#2632 fix(chord): 和弦图支持展示节点 tooltip & 修复动画效果不生效
  __tests__/unit/plots/chord/index-spec.ts
  __tests__/unit/plots/chord/tooltip-spec.ts
  __tests__/unit/utils/geometry-spec.ts
  examples/relation-plots/chord/demo/custom-tooltip.ts
  examples/relation-plots/chord/demo/meta.json
  src/index.ts
  src/plots/chord/adaptor.ts
  src/plots/chord/constant.ts
  src/plots/chord/types.ts
  src/utils/geometry.ts
  src/utils/index.ts
Labels: PR: reviewed-approved

#2635 chore: add contributors
  .all-contributorsrc
  .github/ISSUE_TEMPLATE.md
  .github/workflows/contributor-helper.yml
  README.md
  README.zh-CN.md
  package.json
  scripts/init-contributors.js
Labels: PR: reviewed-approved

#2642 fix: typo in legend-spec.ts
  __tests__/unit/plots/scatter/legend-spec.ts
Labels: PR: unreviewed

#2643 fix(chord): 修复单测问题
  __tests__/unit/plots/chord/state-spec.ts
Labels: PR: reviewed-approved

#2644 chore: v2.3.24 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved

#2639 fix(bullet): 修复轴组件添加max时，子弹图scale呈现不正确问题
  __tests__/bugs/issue-2636-spec.ts
  src/plots/bullet/adaptor.ts
Labels: PR: unreviewed

#2658 fix: funnel with empty data, #2616
  __tests__/bugs/issue-2616-spec.ts
  src/plots/funnel/geometries/common.ts
Labels: PR: partially-approved

#2649 fix(scatter): 散点图刷选交互之后的 scale 处理
  __tests__/unit/plots/scatter/data-spec.ts
  __tests__/unit/plots/scatter/size-spec.ts
  __tests__/unit/plots/scatter/style-spec.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/scatter/util.ts
Labels: PR: unreviewed

#2661 fix(#2651): when scatter data length = 1 and x is cat
  __tests__/bugs/issue-2651-spec.ts
  __tests__/unit/utils/get-meta-spec.ts
  src/plots/scatter/adaptor.ts
  src/plots/scatter/index.ts
  src/plots/scatter/util.ts
Labels: PR: partially-approved

#2655 Circle packing
  __tests__/data/circle-packing.ts
  __tests__/unit/plots/circle-packing/animation-spec.ts
  __tests__/unit/plots/circle-packing/index-spec.ts
  __tests__/unit/plots/circle-packing/tooltip-spec.ts
  docs/api/plots/circle-packing.en.md
  docs/api/plots/circle-packing.zh.md
  examples/more-plots/circle-packing/API.en.md
  examples/more-plots/circle-packing/API.zh.md
  examples/more-plots/circle-packing/demo/basic.ts
  examples/more-plots/circle-packing/demo/custom-padding.ts
  examples/more-plots/circle-packing/demo/label.ts
  examples/more-plots/circle-packing/demo/meta.json
  examples/more-plots/circle-packing/demo/nest.ts
  examples/more-plots/circle-packing/index.en.md
  examples/more-plots/circle-packing/index.zh.md
  package.json
  src/index.ts
  src/interactions/actions/drill-down.ts
  src/plots/_template/adaptor.ts
  src/plots/circle-packing/adaptor.ts
  src/plots/circle-packing/constant.ts
  src/plots/circle-packing/index.ts
  src/plots/circle-packing/interactions/index.ts
  src/plots/circle-packing/types.ts
  src/plots/circle-packing/utils.ts
  src/utils/hierarchy/pack.ts
Labels: PR: reviewed-approved

#2664 feat(drill-down): 优化下下钻的面包屑位置
  __tests__/unit/interactions/drill-down-spec.ts
  __tests__/unit/plots/circle-packing/index-spec.ts
  __tests__/unit/plots/treemap/interactions/drill-down-spec.ts
  examples/more-plots/circle-packing/demo/meta.json
  package.json
  src/interactions/actions/drill-down.ts
  src/plots/circle-packing/constant.ts
Labels: PR: unreviewed

#2665 chore: 2.3.25 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed
