Repository antvis/G2Plot, pull requests merged in 2022-03, with the labels that each got.

#3131 feat(consionBar): 转化分析图 + 水波图
  examples/case/statistical-scenario/demo/conversion-funnel.ts
  src/index.ts
  src/plots/liquid/index.ts
  src/plots/liquid/shapes/liquid.ts
Labels: PR: unreviewed, feature

#3142 docs: 周边工具增加 性能检测工具
  gatsby-config.js
Labels: documentation, PR: unreviewed

#3143 feat(funnel): 漏斗图增加关闭分面 title 的展示
  CHANGELOG.md
  docs/api/plots/funnel.en.md
  docs/api/plots/funnel.zh.md
  package.json
  src/index.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/geometries/facet.ts
  src/plots/funnel/types.ts
Labels: PR: unreviewed, feature

#3145 docs(multi-view): 增加异常检测折线图demo
  examples/plugin/multi-view/demo/anomaly-detection-line-chart.ts
  examples/plugin/multi-view/demo/meta.json
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#3146 chore: v2.4.10
  docs/manual/plots/funnel.en.md
  docs/manual/plots/funnel.zh.md
  gatsby-config.js
Labels: PR: unreviewed, ignore-for-release

#3149 feat(gauge): 仪表盘增加 tooltip 配置
  __tests__/unit/plots/gauge/tooltip-spec.ts
  docs/api/plots/gauge.en.md
  docs/api/plots/gauge.zh.md
  examples/progress-plots/gauge/demo/meta.json
  examples/progress-plots/gauge/demo/tooltip-gauge.ts
  src/plots/gauge/adaptor.ts
  src/plots/gauge/types.ts
Labels: PR: unreviewed, feature

#3153 chore: v2.4.11 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3155 feat(bidirectional-bar): 对称条形图支持主题配置
  __tests__/unit/plots/bidirectional-bar/index-spec.ts
  src/plots/bidirectional-bar/adaptor.ts
Labels: PR: unreviewed, feature

#3163 feat(mix): mix 图表支持 stock
  src/plots/mix/utils.ts
Labels: PR: unreviewed, feature

#3157 chore: fix typo in locale.json
  site/locale.json
Labels: PR: unreviewed, ignore-for-release

#3164 chore 2.4.13
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3168 feat(mix): mix 复合图表支持统一在顶层配置，增加 top、slider、annotations 等属性配置
  __tests__/unit/plots/multi-view/index-spec.ts
  docs/api/advanced-plots/mix.zh.md
  examples/plugin/multi-view/demo/customized-stock.jsx
  examples/plugin/multi-view/demo/meta.json
  examples/plugin/multi-view/demo/nobel-prize.ts
  src/plots/mix/adaptor.ts
  src/plots/mix/types.ts
  src/plots/mix/utils.ts
Labels: PR: unreviewed, feature
