Repository antvis/G2Plot, pull requests merged in 2022-11, with the labels that each got.

#3389 docs: fix typo
  docs/api/plot-api.zh.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved

#3375 fix(column): custom customItems invalid issue (#3367)
  __tests__/bugs/issue-3367-spec.ts
  src/plots/column/adaptor.ts
Labels: PR: unreviewed, bugfix

#3354 fix(funnel): 漏斗图转化率文本位置获取修改
  __tests__/unit/plots/funnel/compare-spec.ts
  src/plots/funnel/adaptor.ts
  src/plots/funnel/geometries/basic.ts
  src/plots/funnel/geometries/common.ts
  src/plots/funnel/geometries/compare.ts
  src/plots/funnel/index.ts
  src/plots/funnel/interactions/funnel-conversion-tag.ts
  src/plots/funnel/interactions/index.ts
  src/plots/funnel/types.ts
Labels: PR: unreviewed, bugfix

#3373 fix(type): fix appendPadding description typo
  src/types/common.ts
Labels: PR: reviewed-approved, bugfix

#3399 chore: remove all-contributor script
  .all-contributorsrc
  package.json
  scripts/init-contributors.js
Labels: PR: unreviewed, ignore-for-release

#3401 fix: site button
  .dumirc.ts
Labels: PR: unreviewed

#3404 chore: site
  .github/workflows/mirror.yml
  __tests__/unit/plots/gauge/shapes/index-spec.ts
Labels: PR: reviewed-approved, ignore-for-release

#3405 chore: 网站配置更新
  .dumirc.ts
  .github/workflows/release.yml
  .github/workflows/site-deploy.yml
Labels: PR: unreviewed, ignore-for-release
