Repository antvis/G2Plot, pull requests merged in 2022-04, with the labels that each got.

#3172 feat(coordinate): 支持 coordinate 坐标转换配置
  __tests__/bugs/bar-axis-label-spec.ts
  __tests__/unit/plots/area/change-data-spec.ts
  __tests__/unit/plots/word-cloud/legend-spec.ts
  docs/api/plots/area.en.md
  docs/api/plots/area.zh.md
  docs/api/plots/bar.en.md
  docs/api/plots/bar.zh.md
  docs/api/plots/column.en.md
  docs/api/plots/column.zh.md
  docs/common/coordinate.en.md
  docs/common/coordinate.zh.md
  examples/bar/basic/demo/coordinate.ts
  examples/bar/basic/demo/meta.json
  examples/column/basic/demo/coordinate.ts
  examples/column/basic/demo/meta.json
  examples/plugin/multi-view/demo/meta.json
  gatsby-config.js
  src/adaptor/common.ts
  src/plots/area/adaptor.ts
  src/plots/area/index.ts
  src/plots/area/types.ts
  src/plots/bar/adaptor.ts
  src/plots/bar/index.ts
  src/plots/column/adaptor.ts
  src/plots/column/index.ts
  src/plots/column/types.ts
  src/plots/mix/utils.ts
  src/plots/pie/adaptor.ts
  src/types/coordinate.ts
  src/utils/transform/percent.ts
Labels: PR: unreviewed, feature

#3174 chore: v2.4.15 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3175 chore(website): remove data-set & add bundle-analyser
  examples/case/statistical-scenario/demo/trend.jsx
  examples/more-plots/stock/demo/large-data.ts
  examples/plugin/facet/demo/tree-column.ts
  examples/plugin/facet/demo/tree.ts
  examples/plugin/multi-view/demo/drinks.ts
  gatsby-browser.js
  gatsby-config.js
  package.json
Labels: PR: unreviewed, ignore-for-release

#3176 docs(mix): 增加 mix demo 和文档说明
  docs/api/advanced-plots/mix.en.md
  docs/api/advanced-plots/mix.zh.md
  examples/plugin/multi-view/demo/meta.json
  examples/plugin/multi-view/demo/nest-pie.ts
Labels: documentation, PR: unreviewed

#3183 fix: 勘误-百分比条形图
  examples/bar/percent/demo/meta.json
Labels: PR: unreviewed, bugfix

#3191 chore: v2.4.16 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release
