Repository antvis/G2Plot, pull requests merged in 2022-06, with the labels that each got.

#3235 fix(pie): 修复饼图 title statistic 没有使用 meta formatter
  CHANGELOG.md
  __tests__/bugs/pie-statistic-spec.ts
  package.json
  src/index.ts
  src/plots/pie/adaptor.ts
Labels: PR: unreviewed, bugfix

#3227 docs(sankey): add demo for sankey
  examples/column/basic/demo/meta.json
  examples/column/scenario/demo/meta.json
  examples/component/legend/demo/meta.json
  examples/line/scenario/demo/meta.json
  examples/more-plots/circle-packing/demo/meta.json
  examples/plugin/multi-view/demo/meta.json
  examples/progress-plots/gauge/demo/meta.json
  examples/relation-plots/sankey/demo/meta.json
  examples/relation-plots/sankey/demo/node-sort-sankey.ts
Labels: documentation, PR: unreviewed

#3240 chore: specify @antv/util dependency
  package.json
Labels: PR: unreviewed, ignore-for-release

#3231 fix(bullet): 子弹图 添加单数值range/measures 、 多 target 数据修改兼容
  __tests__/unit/plots/bullet/data-spec.ts
  src/plots/bullet/utils.ts
Labels: PR: unreviewed, bugfix

#3241 fix(bullet): 修改子弹图单测
  __tests__/unit/plots/bullet/data-spec.ts
Labels: PR: unreviewed, bugfix

#3243 fix/bar changedata
  CHANGELOG.md
  __tests__/bugs/bar-changedata-spec.ts
  package.json
  src/index.ts
  src/plots/bar/index.ts
Labels: PR: unreviewed

#3253 docs(demo): add a new demo about how to handle element multiple selected
  examples/case/interactions/demo/element-selected.ts
  examples/case/interactions/demo/funnel-element-selected.ts
  examples/case/interactions/demo/meta.json
  examples/case/interactions/demo/pie-element-selected.ts
  examples/case/interactions/index.en.md
  examples/case/interactions/index.zh.md
Labels: PR: unreviewed

#3258 feat/interacion brush
  CHANGELOG.md
  __tests__/unit/interactions/brush-spec.ts
  __tests__/unit/plots/sankey/index-spec.ts
  examples/dynamic-plots/brush/demo/advanced-brush3.ts
  examples/dynamic-plots/brush/demo/meta.json
  examples/relation-plots/sankey/demo/meta.json
  package.json
  src/adaptor/brush.ts
  src/index.ts
  src/interactions/brush.ts
  src/types/interaction.ts
Labels: PR: unreviewed

#3162 feat(bar): 添加动态条形图
  examples/bar/basic/demo/dynamic.ts
  examples/bar/basic/demo/meta.json
Labels: feature

#3264 fix(test): g2plot label 延迟渲染 注释和增加延迟时间 到 test
  __tests__/unit/plots/sankey/index-spec.ts
  __tests__/unit/utils/transform/word-cloud-spec.ts
Labels: PR: unreviewed, bugfix

#3268 fix(progress): 迷你进度条重新修改
  __tests__/unit/plots/progress/index-spec.ts
  __tests__/unit/plots/progress/utils-spec.ts
  __tests__/unit/plots/ring-progress/index-spec.ts
  src/plots/progress/adaptor.ts
  src/plots/progress/utils.ts
Labels: PR: reviewed-approved, bugfix
