Repository antvis/G2Plot, pull requests merged in 2022-09, with the labels that each got.

#3346 fix: 锁 remark-mdx 版本修复启动报错
  package.json
Labels: PR: unreviewed, bugfix

#3349 fix(stock): avoid mutating stock data item
  __tests__/unit/plots/stock/data-spec.ts
  src/plots/stock/utils.ts
Labels: PR: reviewed-approved, bugfix

#3362 docs(changelog): 更正链接异常
  CHANGELOG.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved
