Repository antvis/G2Plot, pull requests merged in 2022-02, with the labels that each got.

#3104 chore: v2.4.8 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3108 chore: github actions 整理
  .github/release.yml
  .github/workflows/build.yml
  .github/workflows/conventional-labels.yml
  .github/workflows/npm-publish.yml
  .github/workflows/rebase.yml
  .github/workflows/release-notify.yml
  .github/workflows/release.yml
Labels: PR: unreviewed, ignore-for-release

#3125 feat: 基于 JSDoc 标准调整 types 类型定义
  src/types/button.ts
  src/types/common.ts
  src/types/drill-down.ts
  src/types/interaction.ts
  src/types/label.ts
  src/types/meta.ts
  src/types/pattern.ts
  src/types/state.ts
  src/types/statistic.ts
  src/types/tooltip.ts
Labels: PR: partially-approved, feature

#3126 feat: 基于 jsDoc 规范完善 plots 组件注释
  src/plots/area/types.ts
  src/plots/bar/types.ts
  src/plots/bidirectional-bar/types.ts
  src/plots/box/types.ts
  src/plots/bullet/types.ts
  src/plots/chord/types.ts
  src/plots/circle-packing/types.ts
  src/plots/column/types.ts
  src/plots/dual-axes/types.ts
  src/plots/facet/types.ts
  src/plots/funnel/types.ts
  src/plots/gauge/types.ts
  src/plots/heatmap/types.ts
  src/plots/histogram/types.ts
  src/plots/line/types.ts
  src/plots/liquid/types.ts
  src/plots/mix/types.ts
  src/plots/pie/types.ts
  src/plots/progress/types.ts
  src/plots/radar/types.ts
  src/plots/radial-bar/types.ts
  src/plots/ring-progress/types.ts
  src/plots/rose/types.ts
  src/plots/sankey/types.ts
  src/plots/scatter/types.ts
  src/plots/stock/types.ts
  src/plots/sunburst/types.ts
  src/plots/tiny-area/types.ts
  src/plots/tiny-column/types.ts
  src/plots/tiny-line/types.ts
  src/plots/treemap/types.ts
  src/plots/venn/types.ts
  src/plots/violin/types.ts
  src/plots/waterfall/types.ts
  src/plots/word-cloud/types.ts
Labels: PR: unreviewed, feature

#3119 fix(annotations): 修复addAnnotations在双轴图等具有分view图表失效的问题
  __tests__/bugs/issue-3084-spec.ts
  docs/api/plot-api.en.md
  docs/api/plot-api.zh.md
  src/core/plot.ts
Labels: PR: reviewed-approved, bugfix
