Repository antvis/G2Plot, pull requests merged in 2022-08, with the labels that each got.

#3307 📃 docs(fix title text field):
  docs/common/legend-cfg.zh.md
Labels: PR: reviewed-approved

#3313 fix(funnel): 当 next 为 0 时，应该显示 0% 而不是 -∞
  __tests__/bugs/issue-2124-spec.ts
  __tests__/unit/adaptor/conversion-tag-spec.ts
  __tests__/unit/utils/conversion-spec.ts
  src/utils/conversion.ts
Labels: PR: unreviewed, bugfix

#3317 fix(box): 箱型图 添加 annotation 配置
  src/plots/box/adaptor.ts
Labels: PR: reviewed-approved, bugfix

#3275 fix(animation): 动画添加回调， 可以给不同的 形状添加动画
  __tests__/unit/plots/facet/animation-spec.ts
  __tests__/unit/plots/line/animation-spec.ts
  __tests__/unit/plots/sankey/animation-spec.ts
  src/adaptor/common.ts
  src/plots/chord/adaptor.ts
  src/plots/facet/types.ts
  src/plots/facet/utils.ts
  src/plots/sankey/adaptor.ts
  src/plots/violin/adaptor.ts
  src/types/common.ts
  src/utils/index.ts
  src/utils/view.ts
Labels: PR: unreviewed, bugfix

#3246 feat(custom Shape): 添加 Shape 文档 以及 添加 三个 自定义 Shape demo
  docs/api/options/shape.en.md
  docs/api/options/shape.zh.md
  examples/plugin/custom-shape/API.en.md
  examples/plugin/custom-shape/API.zh.md
  examples/plugin/custom-shape/demo/bar-custom-shape.ts
  examples/plugin/custom-shape/demo/conversion-bar-shape.ts
  examples/plugin/custom-shape/demo/meta.json
  examples/plugin/custom-shape/demo/pie-custom-shape.ts
  examples/plugin/custom-shape/index.en.md
  examples/plugin/custom-shape/index.zh.md
  src/plots/pie/adaptor.ts
  src/plots/pie/types.ts
Labels: PR: unreviewed, feature

#3337 chore: v2.4.21 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release
