Repository antvis/G2Plot, pull requests merged in 2022-01, with the labels that each got.

#3065 docs: 增加 axis title api说明
  docs/common/axis.en.md
  docs/common/axis.zh.md
  examples/case/statistical-scenario/demo/meta.json
  examples/column/basic/demo/meta.json
  examples/column/grouped/demo/meta.json
Labels: PR: unreviewed

#3064 feat(scatter): 散点图气泡图添加 slider 缩略轴 scrollbar 滚动条 配置
  src/plots/scatter/adaptor.ts
Labels: PR: unreviewed

#3066 chore: v2.4.6 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3075 fix(liquid): 水波图允许关闭动画效果
  src/plots/liquid/adaptor.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
Labels: PR: unreviewed

#3074 feat(legend): 图例增加 radio 按钮实现正选 focus 功能
  __tests__/unit/plots/bar/legend-spec.ts
  __tests__/unit/plots/column/legend-spec.ts
  __tests__/unit/plots/pie/label-spec.ts
  docs/common/legend-cfg.en.md
  docs/common/legend-cfg.zh.md
  examples/component/legend/demo/legend-radio.ts
  examples/component/legend/demo/meta.json
  src/plots/area/constants.ts
  src/plots/bar/constants.ts
  src/plots/column/constants.ts
  src/plots/line/constants.ts
  src/plots/pie/contants.ts
  src/plots/rose/constant.ts
Labels: PR: unreviewed

#3077 chore: v2.4.7 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed

#3081 feat(sankey): 分别对 node 和 edge 添加 交互属性配置
  __tests__/unit/plots/sankey/interations-spec.ts
  docs/api/plots/sankey.en.md
  docs/api/plots/sankey.zh.md
  src/plots/sankey/adaptor.ts
  src/plots/sankey/types.ts
Labels: PR: reviewed-approved

#3090 ci: fix footer click
  .github/workflows/release-notify.yml
Labels: PR: unreviewed

#3089 fix(column): 修复百分比柱状图 总和为零时的 bug
  __tests__/bugs/issue-3085-spec.ts
  src/utils/transform/percent.ts
Labels: PR: reviewed-approved

#3092 docs(gauge): 增加仪表盘自定义 demo
  examples/progress-plots/gauge/demo/custom-indicator3.ts
  examples/progress-plots/gauge/demo/meta.json
Labels: PR: unreviewed

#3096 fix(dual-axes): 修复双轴图bottom统一的问题 #2930
  __tests__/bugs/issue-2930-spec.ts
  src/plots/dual-axes/util/render-sider.ts
Labels: PR: reviewed-approved, bugfix
