Repository antvis/G2Plot, pull requests merged in 2022-12, with the labels that each got.

#3411 feat(Liquid): Add shapeStyle config
  docs/api/plots/liquid.en.md
  docs/api/plots/liquid.zh.md
  examples/progress-plots/liquid/demo/custom.ts
  examples/progress-plots/liquid/demo/meta.json
  src/plots/liquid/adaptor.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
Labels: PR: unreviewed, feature

#3413 chore: 2.4.23 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3417 chore: update deploy action
  .github/workflows/deploy.yml
  jest.config.js
  package.json
  site/.dumi/global.ts
  site/CNAME
Labels: PR: unreviewed, ignore-for-release

#3419 fix: close issues
  site/docs/common/legend-cfg.en.md
  site/examples/dynamic-plots/basic/demo/dynamic-spline.ts
Labels: PR: unreviewed, bugfix

#3420 fix: pre-site 预发站点不跳转
  .github/workflows/deploy.yml
  site/.dumi/global.ts
  site/examples/line/scenario/demo/derived-measures-line.ts
  site/examples/line/scenario/demo/multiple-measures-line.ts
  site/examples/line/scenario/demo/series-multiple-measures-line.ts
Labels: PR: unreviewed, bugfix

#3421 feat: add site direct
  .github/workflows/deploy.yml
  package.json
  site/.dumi/global.ts
Labels: PR: unreviewed, feature

#3435 fix: several error demo in site
  site/examples/case/advanced/demo/associate-filter.ts
  site/examples/case/advanced/demo/associate-pie-tooltip.ts
  site/examples/case/interactions/demo/meta.json
  site/examples/dynamic-plots/brush/demo/advanced-brush1.ts
  site/examples/dynamic-plots/brush/demo/advanced-brush2.ts
Labels: PR: reviewed-approved, bugfix
