Repository antvis/G2Plot, pull requests merged in 2023-05, with the labels that each got.

#3541 chore: update version of @antv/component to 0.8.33 for dist build
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved, ignore-for-release

#3542 feat: export all G2
  __tests__/integration/main.ts
  package.json
  src/index.ts
  src/types/common.ts
Labels: PR: unreviewed

#3544 chore: update version of @antv/component to 0.8.34 for dist build
  CHANGELOG.md
  package.json
Labels: ignore-for-release

#3525 docs: Fix a few typos
  CONTRIBUTING.md
  site/docs/api/plot-api.en.md
  site/docs/api/plots/funnel.en.md
  site/docs/api/plots/violin.en.md
Labels: documentation, PR: unreviewed

#3545 chore: update version of @antv/component to 0.8.34 for dist build
  src/index.ts
Labels: ignore-for-release

#3564 chore: fix customized stock demo typo
  site/examples/plugin/multi-view/demo/customized-stock.jsx
Labels: ignore-for-release

#3514 docs: fix link
  site/docs/manual/upgrade.en.md
  site/docs/manual/upgrade.zh.md
Labels: documentation, PR: unreviewed
