Repository antvis/G2Plot, pull requests merged in 2023-02, with the labels that each got.

#3454 chore: fix homepage url
  site/.dumirc.ts
Labels: PR: reviewed-approved, ignore-for-release

#3451 docs: fix typo
  site/docs/common/tooltip.en.md
  site/docs/common/tooltip.zh.md
Labels: documentation, PR: reviewed-approved

#3455 fix(Liquid): should render wave only when percent > 0
  src/plots/liquid/adaptor.ts
  src/plots/liquid/shapes/liquid.ts
  src/plots/liquid/types.ts
Labels: PR: reviewed-approved, bugfix

#3458 chore: v2.4.24 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: reviewed-approved, ignore-for-release

#3460 fix: 修复 antv/scale 版本依赖错误
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, bugfix

#3471 Update dependency of @antv/g2
  .husky/commit-msg
  .husky/pre-commit
  __tests__/integration/snapshots/lineAnnotationLine-actual.png
  __tests__/integration/snapshots/lineAnnotationLine-diff.png
  __tests__/integration/snapshots/lineAnnotationRange-actual.png
  __tests__/integration/snapshots/lineAnnotationRange-diff.png
  __tests__/integration/snapshots/lineArea-actual.png
  __tests__/integration/snapshots/lineArea-diff.png
  __tests__/integration/snapshots/lineBasic-actual.png
  __tests__/integration/snapshots/lineBasic-diff.png
  __tests__/integration/snapshots/lineColorMapping-actual.png
  __tests__/integration/snapshots/lineColorMapping-diff.png
  __tests__/integration/snapshots/lineConditionRangeY-actual.png
  __tests__/integration/snapshots/lineConditionRangeY-diff.png
  __tests__/integration/snapshots/linePointShape-actual.png
  __tests__/integration/snapshots/linePointShape-diff.png
  __tests__/integration/snapshots/lineSeries-actual.png
  __tests__/integration/snapshots/lineSeries-diff.png
  __tests__/integration/snapshots/lineSlider-actual.png
  __tests__/integration/snapshots/lineSlider-diff.png
  jest.config.js
  jest.node.config.js
  package.json
  pnpm-lock.yaml
  src/plots/line/index.ts
Labels: PR: reviewed-approved

#3480 docs: fix typo
  site/docs/manual/getting-started.zh.md
Labels: documentation, PR: unreviewed
