Repository antvis/G2Plot, pull requests merged in 2023-03, with the labels that each got.

#3483 fix(Sankey): insufficient pass-in parameters for the callback function of edgeStyle
  __tests__/unit/plots/sankey/adaptor-spec.ts
  src/plots/sankey/adaptor.ts
Labels: PR: partially-approved, bugfix

#3485 chore: v2.4.26 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3488 chore: upgrade typescript to v4
  .eslintrc
  __tests__/unit/core/index-spec.ts
  __tests__/unit/plots/multi-view/multi-plots-spec.ts
  __tests__/unit/plots/scatter/regression-line-spec.ts
  __tests__/unit/plots/sunburst/treemap-spec.ts
  package.json
  src/plots/bidirectional-bar/adaptor.ts
  src/plots/sankey/layout.ts
  src/utils/hierarchy/partition.ts
Labels: PR: partially-approved, ignore-for-release

#3476 (feat) 回归散点图增加显示回归拟合函数相关配置，close #3474
  __tests__/unit/plots/scatter/regression-line-spec.ts
  __tests__/unit/plots/scatter/util-spec.ts
  site/docs/api/plots/scatter.en.md
  site/docs/api/plots/scatter.zh.md
  src/plots/scatter/adaptor.ts
  src/plots/scatter/types.ts
  src/plots/scatter/util.ts
Labels: PR: reviewed-approved

#3490 feat: 基于G2 Spec初始化V3
  .npmrc
  .prettierignore
  README.md
  __tests__/integration/main.ts
  __tests__/integration/plots/line-annotation-line.ts
  __tests__/integration/plots/line-annotation-range.ts
  __tests__/integration/plots/line-area.ts
  __tests__/integration/plots/line-basic.ts
  __tests__/integration/plots/line-color-mapping.ts
  __tests__/integration/plots/line-condition-rangeY.ts
  __tests__/integration/plots/line-point-shape.ts
  __tests__/integration/plots/line-scrollbar.ts
  __tests__/integration/plots/line-series.ts
  __tests__/integration/plots/line-slider.ts
  __tests__/integration/snapshot.spec.ts
  jest.config.js
  jest.node.config.js
  package.json
  pnpm-lock.yaml
  src/adaptor/annotation.ts
  src/adaptor/conditionRange.ts
  src/adaptor/mark.ts
  src/components/index.ts
  src/components/mark.ts
  src/core/plot.ts
  src/index.ts
  src/module.d.ts
  src/plots/line/adaptor.ts
  src/plots/line/index.ts
  src/plots/line/type.ts
  src/types/annotation.ts
  src/types/common.ts
  src/types/index.ts
  src/utils/flow.ts
  src/utils/helper.ts
  src/utils/index.ts
  src/utils/is-composite-plot.ts
  src/utils/scale.ts
  tsconfig.json
Labels: PR: unreviewed

#3493 feat: g2 version
  __tests__/integration/canvas.ts
  package.json
  src/types/common.ts
Labels: PR: reviewed-approved

#3496 feat: add column plot
  __tests__/integration/plots/column-basic.ts
  __tests__/integration/plots/index.ts
  src/index.ts
  src/plots/column/adaptor.ts
  src/plots/column/index.ts
  src/plots/column/type.ts
Labels: PR: unreviewed

#3495 feat(custom shape): support custom shape for area/waterfall/radial-bar/rose/sunburst plot
  __tests__/unit/plots/area/index-spec.ts
  __tests__/unit/plots/radial-bar/index-spec.ts
  __tests__/unit/plots/rose/index-spec.ts
  __tests__/unit/plots/sunburst/index-spec.ts
  __tests__/unit/plots/waterfall/index-spec.ts
  src/adaptor/geometries/area.ts
  src/plots/area/adaptor.ts
  src/plots/area/types.ts
  src/plots/radial-bar/adaptor.ts
  src/plots/radial-bar/types.ts
  src/plots/rose/adaptor.ts
  src/plots/rose/types.ts
  src/plots/sunburst/adaptor.ts
  src/plots/sunburst/types.ts
  src/plots/waterfall/adaptor.ts
  src/plots/waterfall/types.ts
Labels: PR: reviewed-approved, feature

#3494 fix(column): 修复柱状图拆分维度为空字符串时，错误显示了 xField 作为 title 的问题
  src/plots/column/adaptor.ts
Labels: PR: reviewed-approved, bugfix

#3497 chore: v2.4.27 & changelog
  CHANGELOG.md
  package.json
  src/index.ts
Labels: PR: unreviewed, ignore-for-release

#3500 fix: renderer error
  __tests__/integration/main.ts
  __tests__/integration/plots/column-basic.ts
  __tests__/integration/plots/line-annotation-line.ts
  __tests__/integration/plots/line-annotation-range.ts
  __tests__/integration/plots/line-area.ts
  __tests__/integration/plots/line-basic.ts
  __tests__/integration/plots/line-color-mapping.ts
  __tests__/integration/plots/line-condition-rangeY.ts
  __tests__/integration/plots/line-point-shape.ts
  __tests__/integration/plots/line-scrollbar.ts
  __tests__/integration/plots/line-series.ts
  __tests__/integration/plots/line-slider.ts
  package.json
  src/core/plot.ts
  src/utils/index.ts
Labels: PR: unreviewed

#3507 ci: add to match snapshot
  e2e/.env
  e2e/plots/line.spec.ts
  e2e/snapshots/column-basic-stable.png
  e2e/snapshots/line-annotation-line-stable.png
  e2e/snapshots/line-annotation-range-stable.png
  e2e/snapshots/line-area-stable.png
  e2e/snapshots/line-basic-stable.png
  e2e/snapshots/line-color-mapping-stable.png
  e2e/snapshots/line-condition-rangeY-stable.png
  e2e/snapshots/line-point-shape-stable.png
  e2e/snapshots/line-scrollbar-stable.png
  e2e/snapshots/line-series-stable.png
  e2e/snapshots/line-slider-stable.png
  e2e/utils/Index.ts
  e2e/utils/log-diff.ts
  e2e/utils/log.ts
  package.json
  playwright.config.ts
Labels: PR: unreviewed
